using System;

namespace DragonEngineLibrary
{
    public enum BattleCommandSetID : uint
    {
        invalid,         // constant 0x0
        Default,         // constant 0x1
        e_akiyama,       // constant 0x2
        e_amon,      // constant 0x3
        e_base,      // constant 0x4
        e_boss_cpr,      // constant 0x5
        e_boss_edo,      // constant 0x6
        e_boss_edo_a,        // constant 0x7
        e_boss_edo_b,        // constant 0x8
        e_box,       // constant 0x9
        e_clan_amon,         // constant 0xA
        e_cpr,       // constant 0xB
        e_drum,      // constant 0xC
        e_drum_base,         // constant 0xD
        e_fat,       // constant 0xE
        e_goro,      // constant 0xF
        e_grd,       // constant 0x10
        e_han,       // constant 0x11
        e_hirose,        // constant 0x12
        e_infighter,         // constant 0x13
        e_iwami,         // constant 0x14
        e_jak,       // constant 0x15
        e_jaka_wpe,      // constant 0x16
        e_jnk_wpb,       // constant 0x17
        e_jnk_wpd,       // constant 0x18
        e_junky,         // constant 0x19
        e_kakutou,       // constant 0x1A
        e_karate,        // constant 0x1B
        e_kbx,       // constant 0x1C
        e_kenka,         // constant 0x1D
        e_kiryu,         // constant 0x1E
        e_koshimizu,         // constant 0x1F
        e_koshimizu_b,       // constant 0x20
        e_lau,       // constant 0x21
        e_lea,       // constant 0x22
        e_majima,        // constant 0x23
        e_majima_wpb,        // constant 0x24
        e_masuzoe,       // constant 0x25
        e_matsunaga,         // constant 0x26
        e_mosa_base,         // constant 0x27
        e_mosa_cook,         // constant 0x28
        e_mosa_daigo,        // constant 0x29
        e_mosa_hung,         // constant 0x2A
        e_mosa_kanda,        // constant 0x2B
        e_mosa_karate,       // constant 0x2C
        e_mosa_kuze,         // constant 0x2D
        e_mosa_lee,      // constant 0x2E
        e_mosa_mask,         // constant 0x2F
        e_mosa_rikiya,       // constant 0x30
        e_mosa_sbs,      // constant 0x31
        e_mosa_sougou,       // constant 0x32
        e_mosa_wpe,      // constant 0x33
        e_mosa_wpy,      // constant 0x34
        e_mosa_wrestler,         // constant 0x35
        e_mosa_yahata,       // constant 0x36
        e_nagumo,        // constant 0x37
        e_nagumo_yop,        // constant 0x38
        e_pro_kozima,        // constant 0x39
        e_pro_nagata,        // constant 0x3A
        e_pro_naito,         // constant 0x3B
        e_pro_okada,         // constant 0x3C
        e_pro_tanahashi,         // constant 0x3D
        e_pro_tenzan,        // constant 0x3E
        e_pro_yano,      // constant 0x3F
        e_pwr,       // constant 0x40
        e_pwr_sync_f,        // constant 0x41
        e_rocket,        // constant 0x42
        e_saejima,       // constant 0x43
        e_sayama,        // constant 0x44
        e_sbc,       // constant 0x45
        e_someya,        // constant 0x46
        e_someya_e,      // constant 0x47
        e_someya_e_heat,         // constant 0x48
        e_someya_heat,       // constant 0x49
        e_sync_catch,        // constant 0x4A
        e_sync_mount,        // constant 0x4B
        e_sync_tackle,       // constant 0x4C
        e_tac,       // constant 0x4D
        e_tagashira,         // constant 0x4E
        e_usami,         // constant 0x4F
        e_wpa,       // constant 0x50
        e_wpb,       // constant 0x51
        e_wpb_dosu,      // constant 0x52
        e_wpc,       // constant 0x53
        e_wpd,       // constant 0x54
        e_wpe,       // constant 0x55
        e_wpg,       // constant 0x56
        e_wph,       // constant 0x57
        e_wpn,       // constant 0x58
        e_wpr,       // constant 0x59
        e_wpy,       // constant 0x5A
        e_yopparai,      // constant 0x5B
        e_zako2,         // constant 0x5C
        e_zako3,         // constant 0x5D
        p_kiryu_b,       // constant 0x5E
        p_kiryu_base,        // constant 0x5F
        p_kiryu_l,       // constant 0x60
        p_kiryu_l_sync_b,        // constant 0x61
        p_kiryu_l_sync_f,        // constant 0x62
        p_onomi_l,       // constant 0x63
        p_player_wpa,        // constant 0x64
        p_player_wpb,        // constant 0x65
        p_player_wpc,        // constant 0x66
        p_player_wpd,        // constant 0x67
        p_player_wpe,        // constant 0x68
        p_player_wpg,        // constant 0x69
        p_player_wph,        // constant 0x6A
        p_player_wpj,        // constant 0x6B
        p_player_wpm,        // constant 0x6C
        p_player_wpn,        // constant 0x6D
        p_player_wps,        // constant 0x6E
        p_player_wpy,        // constant 0x6F
        p_yagami_base,       // constant 0x70
        p_yagami_mai,        // constant 0x71
        p_yagami_sen,        // constant 0x72
        p_yagami_sync_b,         // constant 0x73
        p_yagami_sync_f,         // constant 0x74
        p_player_wpi,        // constant 0x75
        p_player_wpi_yari,       // constant 0x76
        p_player_wpt,        // constant 0x77
        p_player_wpq,        // constant 0x78
        p_player_wpr,        // constant 0x79
        p_player_wpx,        // constant 0x7A
        p_yagami_wpa,        // constant 0x7B
        p_yagami_wpb,        // constant 0x7C
        p_yagami_wpc,        // constant 0x7D
        p_yagami_wpd,        // constant 0x7E
        p_yagami_wpe,        // constant 0x7F
        p_yagami_wpg,        // constant 0x80
        p_yagami_wph,        // constant 0x81
        p_yagami_wpn,        // constant 0x82
        p_yagami_wpy,        // constant 0x83
        p_yagami_b,      // constant 0x84
        e_ninja_wpe,         // constant 0x85
        e_yoroi_wpi,         // constant 0x86
        p_majima_l,      // constant 0x87
        p_majima,        // constant 0x88
        p_yagami,        // constant 0x89
        e_tosenbo,       // constant 0x8A
        e_boss_kim_wpr,      // constant 0x8B
        e_boss_dashiuba,         // constant 0x8C
        e_kuroshozoku,       // constant 0x8D
        e_boss_kim,      // constant 0x8E
        e_boss_sai,      // constant 0x8F
        e_tiger,         // constant 0x90
        e_sync_ride,         // constant 0x91
        e_boss_murase,       // constant 0x92
        e_daigo,         // constant 0x93
        e_boss_murase_wpe,       // constant 0x94
        e_dorobou,       // constant 0x95
        e_boss_hayashi,      // constant 0x96
        e_yoroi_wpg,         // constant 0x97
        e_boss_gary,         // constant 0x98
        e_boss_ryuji,        // constant 0x99
        e_boss_hayashi_wpx,      // constant 0x9A
        e_boss_shindo_wpe,       // constant 0x9B
        e_boss_ryuji_wpe,        // constant 0x9C
        e_boss_kunieda_wpa,      // constant 0x9D
        e_shotgun,       // constant 0x9E
        e_boss_iibuchi,      // constant 0x9F
        e_mosa_wpt,      // constant 0xA0
        e_j_boss_ozaki,      // constant 0xA1
        e_j_boss_kengo_wpe,      // constant 0xA2
        e_j_boss_kengo,      // constant 0xA3
        e_j_boss_higashi,        // constant 0xA4
        e_j_boss_higashi_wpb,        // constant 0xA5
        e_wpt,       // constant 0xA6
        e_wpx,       // constant 0xA7
        e_mosa_wpx,      // constant 0xA8
        p_yagami_wpv,        // constant 0xA9
        e_j_boss_sakakiba,       // constant 0xAA
        e_j_boss_honda,      // constant 0xAB
        e_j_boss_kasai,      // constant 0xAC
        e_mosa_cook_wpb,         // constant 0xAD
        e_j_boss_koga,       // constant 0xAE
        e_mosa_wpa,      // constant 0xAF
        e_yoroi_wpl,         // constant 0xB0
        e_mosa_wpd,      // constant 0xB1
        e_pro_chono,         // constant 0xB2
        e_pro_muto,      // constant 0xB3
        e_pro_tenryu,        // constant 0xB4
        e_pro_choshu,        // constant 0xB5
        e_pro_fujinami,      // constant 0xB6
        e_clan_rocket,       // constant 0xB7
        e_j_boss_shioya,         // constant 0xB8
        e_j_boss_hamura,         // constant 0xB9
        e_j_boss_koga_wpk,       // constant 0xBA
        e_mammoth,       // constant 0xBB
        e_amon1,         // constant 0xBC
        e_amon2,         // constant 0xBD
        e_amon3,         // constant 0xBE
        e_clan_bomb,         // constant 0xBF
        e_clan_bomb_base,        // constant 0xC0
        p_majima_wpb,        // constant 0xC1
        p_yagami_wpi,        // constant 0xC2
        p_yagami_wpq,        // constant 0xC3
        p_yagami_wpt,        // constant 0xC4
        e_j_boss_kuroiwa,        // constant 0xC5
        e_mosa_kick,         // constant 0xC6
        e_j_boss_stick_wpb,      // constant 0xC7
        e_j_boss_mashiko,        // constant 0xC8
        e_npc_mafuyu,        // constant 0xC9
        e_kaito,         // constant 0xCA
        e_sugiura,       // constant 0xCB
        e_j_boss_stick,      // constant 0xCC
        e_j_boss_stick_wpe,      // constant 0xCD
        e_j_boss_stick_wpi,      // constant 0xCE
        e_j_boss_stick_wpj,      // constant 0xCF
        e_j_boss_stick_wpx,      // constant 0xD0
        e_j_boss_honda_sync,         // constant 0xD1
        p_yagami_wpf,        // constant 0xD2
        n_hamura,        // constant 0xD3
        n_matsukane,         // constant 0xD4
        p_yagami_wpx,        // constant 0xD5
        e_j_boss_kuroiwa_sync,       // constant 0xD6
        p_yagami_mount,      // constant 0xD7
        e_amon_wp,       // constant 0xD8
        e_amon_wpv,      // constant 0xD9
        e_swayman,       // constant 0xDA
        e_kaito_rpg,         // constant 0xDB
        e_rpg_boss_1,        // constant 0xDC
        e_rpg_zako_1,        // constant 0xDD
        e_rpg_zako_2,        // constant 0xDE
        e_rpg_zako_3,        // constant 0xDF
        e_sugiura_rpg,       // constant 0xE0
        e_support,       // constant 0xE1
        p_yagami_rpg,        // constant 0xE2
        rpg_jb_02,       // constant 0xE3
        rpg_jb_03,       // constant 0xE4
        rpg_jb_04,       // constant 0xE5
        rpg_jb_hls,      // constant 0xE6
        rpg_npca_base,       // constant 0xE7
        rpg_npcb_base,       // constant 0xE8
        rpg_npcc_base,       // constant 0xE9
        rpg_women_wpi,       // constant 0xEA
        rpg_wpa,         // constant 0xEB
        rpg_wpi,         // constant 0xEC
        test_rpg_ally_wpa,       // constant 0xED
        test_rpg_ally_wpc,       // constant 0xEE
        test_rpg_ally_wph,       // constant 0xEF
        test_rpg_boss,       // constant 0xF0
        test_rpg_enemy_base,         // constant 0xF1
        test_rpg_enemy_wpa,      // constant 0xF2
        test_rpg_enemy_wpc,      // constant 0xF3
        test_rpg_enemy_wph,      // constant 0xF4
        test_rpg_enemy01,        // constant 0xF5
        test_rpg_enemy02,        // constant 0xF6
        test_rpg_enemy03,        // constant 0xF7
        test_rpg_npc_01,         // constant 0xF8
        test_rpg_npc_02,         // constant 0xF9
        test_rpg_npc_03,         // constant 0xFA
        test_rpg_player,         // constant 0xFB
        test_rpg_player_base,        // constant 0xFC
        e_clean_robot,       // constant 0xFD
        rpg_ally_job_01,         // constant 0xFE
        rpg_ally_job_02,         // constant 0xFF
        rpg_ally_job_03,         // constant 0x100
        rpg_ally_job_04,         // constant 0x101
        rpg_ally_job_05,         // constant 0x102
        rpg_ally_job_06,         // constant 0x103
        rpg_ally_job_07,         // constant 0x104
        rpg_ally_job_08,         // constant 0x105
        rpg_ally_job_09,         // constant 0x106
        rpg_ally_job_10,         // constant 0x107
        rpg_ally_job_11,         // constant 0x108
        rpg_ally_job_12,         // constant 0x109
        rpg_ally_job_13,         // constant 0x10A
        rpg_ally_job_14,         // constant 0x10B
        rpg_ally_job_15,         // constant 0x10C
        rpg_ally_job_16,         // constant 0x10D
        rpg_ally_job_17,         // constant 0x10E
        rpg_ally_job_18,         // constant 0x10F
        rpg_ally_job_20,         // constant 0x110
        rpg_ally_job_21,         // constant 0x111
        rpg_ally_job_22,         // constant 0x112
        rpg_ally_job_23,         // constant 0x113
        rpg_ally_job_24,         // constant 0x114
        rpg_ally_job_25,         // constant 0x115
        rpg_ally_ksg,        // constant 0x116
        rpg_ally_npca_base,      // constant 0x117
        rpg_ally_npcb_base,      // constant 0x118
        rpg_ally_npcc_base,      // constant 0x119
        e_salaryman,         // constant 0x11A
        e_gomi_fukuro,       // constant 0x11B
        e_grappler,      // constant 0x11C
        e_slugger,       // constant 0x11D
        e_tepoudama,         // constant 0x11E
        e_reinou,        // constant 0x11F
        p_adachi_job_01,         // constant 0x120
        p_ayaka_job_01,      // constant 0x121
        p_kasuga_job_01,         // constant 0x122
        p_kasuga_job_02,         // constant 0x123
        p_kasuga_job_03,         // constant 0x124
        p_kasuga_job_04,         // constant 0x125
        p_man_job_01,        // constant 0x126
        p_man_job_02,        // constant 0x127
        p_man_job_03,        // constant 0x128
        p_man_job_04,        // constant 0x129
        p_man_job_05,        // constant 0x12A
        p_nanba_job_01,      // constant 0x12B
        p_saeko_job_01,      // constant 0x12C
        e_cleaner,       // constant 0x12D
        e_rapper,        // constant 0x12E
        e_thief,         // constant 0x12F
        e_tourima,       // constant 0x130
        e_sawashiro,         // constant 0x131
        e_sawashiro_b,       // constant 0x132
        e_sawashiro_x,       // constant 0x133
        e_chef,      // constant 0x134
        e_cmafia,        // constant 0x135
        e_drunk,         // constant 0x136
        e_homeless,      // constant 0x137
        e_musician,      // constant 0x138
        e_performer,         // constant 0x139
        e_shinkyu,       // constant 0x13A
        e_shokunin,      // constant 0x13B
        p_adachi,        // constant 0x13C
        rpg_test_skill,      // constant 0x13D
        p_chou_job_01,       // constant 0x13E
        p_dlc_job_01,        // constant 0x13F
        p_jyungi_job_01,         // constant 0x140
        p_man_job_06,        // constant 0x141
        p_man_job_07,        // constant 0x142
        p_man_job_08,        // constant 0x143
        p_woman_a_job_01,        // constant 0x144
        p_woman_job_01,      // constant 0x145
        p_woman_job_02,      // constant 0x146
        p_woman_job_03,      // constant 0x147
        p_woman_job_04,      // constant 0x148
        e_bannin,        // constant 0x149
        e_baseball_fan,      // constant 0x14A
        e_big_eater,         // constant 0x14B
        e_bouncer,       // constant 0x14C
        e_boxer,         // constant 0x14D
        e_doctor,        // constant 0x14E
        e_gambler,       // constant 0x14F
        e_gang,      // constant 0x150
        e_gang_leader,       // constant 0x151
        e_guardman,      // constant 0x152
        e_hacker,        // constant 0x153
        e_hecaton,       // constant 0x154
        e_hippie,        // constant 0x155
        e_hitman,        // constant 0x156
        e_host,      // constant 0x157
        e_kempo,         // constant 0x158
        e_lotion_man,        // constant 0x159
        e_otaku,         // constant 0x15A
        e_press,         // constant 0x15B
        e_pyro,      // constant 0x15C
        e_regent,        // constant 0x15D
        e_rosyutsu,      // constant 0x15E
        e_sandwich_man,      // constant 0x15F
        e_scout_man,         // constant 0x160
        e_skater,        // constant 0x161
        e_soldier,       // constant 0x162
        e_tribal,        // constant 0x163
        e_yakuza,        // constant 0x164
        e_yakuza_bat,        // constant 0x165
        e_yakuza_dosu,       // constant 0x166
        e_yakuza_handgun,        // constant 0x167
        e_yakuza_katana,         // constant 0x168
        e_yakuza_knife,      // constant 0x169
        e_yakuza_oumi,       // constant 0x16A
        e_yakuza_pistol,         // constant 0x16B
        e_yakuza_touzyo,         // constant 0x16C
        e_arashi,        // constant 0x16D
        e_ballplayer,        // constant 0x16E
        e_criminal,      // constant 0x16F
        e_dealer,        // constant 0x170
        e_fanatic,       // constant 0x171
        e_inventor,      // constant 0x172
        e_paripi,        // constant 0x173
        e_scissors,      // constant 0x174
        e_straw_doll,        // constant 0x175
        e_umibouzu,      // constant 0x176
        e_wp_master,         // constant 0x177
        e_zombie,        // constant 0x178
        e_matoba_e,      // constant 0x179
        e_boss_clean_robot,      // constant 0x17A
        e_boss_healer,       // constant 0x17B
        e_boss_matoba_e,         // constant 0x17C
        e_boss_sawashiro,        // constant 0x17D
        e_boss_sawashiro_b,      // constant 0x17E
        e_boss_sawashiro_x,      // constant 0x17F
        e_boss_tiger,        // constant 0x180
        e_boss_mabuchi_i,        // constant 0x181
        e_boss_sawashiro_e,      // constant 0x182
        e_bcj,       // constant 0x183
        e_bousou,        // constant 0x184
        e_boss_sawashiro_brt,        // constant 0x185
        e_boss_attacker,         // constant 0x186
        e_boss_tank,         // constant 0x187
        e_boss_ishioda,      // constant 0x188
        e_boss_kiryu_rush,       // constant 0x189
        e_boss_saejima,      // constant 0x18A
        e_boss_majima_b,         // constant 0x18B
        e_boss_kiryu_legend,         // constant 0x18C
        p_man_musician,      // constant 0x18D
        p_woman_nightqueen,      // constant 0x18E
        p_woman_idol,        // constant 0x18F
        e_boss_crane_truck,      // constant 0x190
        e_boss_power_shovel,         // constant 0x191
        e_boss_kiryu,        // constant 0x192
        e_boss_kiryu_crash,      // constant 0x193
        p_man_kaitaiya,      // constant 0x194
        p_woman_dealer,      // constant 0x195
        e_boss_mirror_face,      // constant 0x196
        e_boss_tendo,        // constant 0x197
        e_boss_arakawa,      // constant 0x198
        p_kasuga,        // constant 0x199
        e_boss_arakawa_y,        // constant 0x19A
        p_woman_martial,         // constant 0x19B
        e_sniper,        // constant 0x19C
        p_saeko,         // constant 0x19D
        e_boss_kuma,         // constant 0x19E
        e_otaku_b,       // constant 0x19F
        e_mazooji,       // constant 0x1A0
        e_fanatic_b,         // constant 0x1A1
    };
}
