using System;


namespace DragonEngineLibrary
{
    public enum BattleControlType : uint
    {
        invalid,         // constant 0x0
        player,      // constant 0x1
        zako,        // constant 0x2
        chinpira,        // constant 0x3
        gomi_fukuro,         // constant 0x4
        clean_robot,         // constant 0x5
        salaryman,       // constant 0x6
        ally_npca,       // constant 0x7
        ally_npcb,       // constant 0x8
        ally_npcc,       // constant 0x9
        ally_ksg,        // constant 0xA
        tepoudama,       // constant 0xB
        slugger,         // constant 0xC
        grappler,        // constant 0xD
        reinou,      // constant 0xE
        ally_kasuga,         // constant 0xF
        ally_ayaka,      // constant 0x10
        ally_nanba,      // constant 0x11
        ally_adachi,         // constant 0x12
        ally_saeko,      // constant 0x13
        npc_man,         // constant 0x14
        npc_woman,       // constant 0x15
        tourima,         // constant 0x16
        rapper,      // constant 0x17
        cleaner,         // constant 0x18
        thief,       // constant 0x19
        sawashiro,       // constant 0x1A
        sawashiro_b,         // constant 0x1B
        sawashiro_x,         // constant 0x1C
        performer,       // constant 0x1D
        homeless,        // constant 0x1E
        shokunin,        // constant 0x1F
        drunk,       // constant 0x20
        shinkyu,         // constant 0x21
        cmafia,      // constant 0x22
        chef,        // constant 0x23
        musician,        // constant 0x24
        kasuga,      // constant 0x25
        nanba,       // constant 0x26
        adachi,      // constant 0x27
        ayaka,       // constant 0x28
        saeko,       // constant 0x29
        chou,        // constant 0x2A
        jyungi,      // constant 0x2B
        woman_a,         // constant 0x2C
        big_eater,       // constant 0x2D
        hitman,      // constant 0x2E
        soldier,         // constant 0x2F
        bouncer,         // constant 0x30
        guardman,        // constant 0x31
        rosyutsu,        // constant 0x32
        doctor,      // constant 0x33
        hacker,      // constant 0x34
        pyro,        // constant 0x35
        boxer,       // constant 0x36
        press,       // constant 0x37
        skater,      // constant 0x38
        kempo,       // constant 0x39
        hippie,      // constant 0x3A
        gambler,         // constant 0x3B
        lotion_man,      // constant 0x3C
        sandwich_man,        // constant 0x3D
        hecaton,         // constant 0x3E
        bannin,      // constant 0x3F
        otaku,       // constant 0x40
        regent,      // constant 0x41
        baseball_fan,        // constant 0x42
        scout_man,       // constant 0x43
        tribal,      // constant 0x44
        host,        // constant 0x45
        gang,        // constant 0x46
        gang_leader,         // constant 0x47
        yakuza_yakuza,       // constant 0x48
        yakuza_katana,       // constant 0x49
        yakuza_pistol,       // constant 0x4A
        yakuza_handgun,      // constant 0x4B
        yakuza_dosu,         // constant 0x4C
        yakuza_knife,        // constant 0x4D
        yakuza_bat,      // constant 0x4E
        yakuza_yakuza_oumi,      // constant 0x4F
        yakuza_yakuza_touzyo,        // constant 0x50
        arashi,      // constant 0x51
        paripi,      // constant 0x52
        umibouzu,        // constant 0x53
        wp_master,       // constant 0x54
        inventor,        // constant 0x55
        zombie,      // constant 0x56
        scissors,        // constant 0x57
        straw_doll,      // constant 0x58
        fanatic,         // constant 0x59
        ballplayer,      // constant 0x5A
        criminal,        // constant 0x5B
        dealer,      // constant 0x5C
        yakuza_oumi,         // constant 0x5D
        yakuza_touzyo,       // constant 0x5E
        yakuza,      // constant 0x5F
        tiger,       // constant 0x60
        crane_truck,         // constant 0x61
        power_shovel,        // constant 0x62
        matoba_e,        // constant 0x63
        boss_sawashiro,      // constant 0x64
        boss_sawashiro_b,        // constant 0x65
        boss_sawashiro_x,        // constant 0x66
        boss_clean_robot,        // constant 0x67
        boss_tiger,      // constant 0x68
        boss_crane_truck,        // constant 0x69
        boss_power_shovel,       // constant 0x6A
        boss_matoba_e,       // constant 0x6B
        boss_healer,         // constant 0x6C
        boss_sawashiro_e,        // constant 0x6D
        boss_mabuchi_i,      // constant 0x6E
        bcj,         // constant 0x6F
        bousou,      // constant 0x70
        boss_sawashiro_brt,      // constant 0x71
        boss_attacker,       // constant 0x72
        boss_ishioda,        // constant 0x73
        boss_kiryu_rush,         // constant 0x74
        boss_saejima,        // constant 0x75
        boss_kiryu_legend,       // constant 0x76
        boss_majima_b,       // constant 0x77
        boss_tank,       // constant 0x78
        boss_kiryu,      // constant 0x79
        boss_kiryu_crash,        // constant 0x7A
        boss_mirror_face,        // constant 0x7B
        boss_tendo,      // constant 0x7C
        boss_arakawa,        // constant 0x7D
        boss_arakawa_y,      // constant 0x7E
        sniper,      // constant 0x7F
        boss_kuma,       // constant 0x80
        otaku_b,         // constant 0x81
        boss_jyungi,         // constant 0x82
        boss_nanba,      // constant 0x83
        mazooji,         // constant 0x84
        fanatic_b,       // constant 0x85
        boss_amon,       // constant 0x86
        num,         // constant 0x87
    };
}
