using System;


namespace DragonEngineLibrary
{
    public enum BattleRPGEnemyID : uint
    {
        invalid,         // constant 0x0
        chinpira_1,      // constant 0x1
        chinpira_2,      // constant 0x2
        chinpira_3,      // constant 0x3
        test_battle_boss,        // constant 0x4
        test_battle_zako,        // constant 0x5
        clean_robot,         // constant 0x6
        clean_robot_r_arm,       // constant 0x7
        clean_robot_l_arm,       // constant 0x8
        salaryman,       // constant 0x9
        yazawa_srm01,        // constant 0xA
        yazawa_srm02,        // constant 0xB
        yazawa_srm03,        // constant 0xC
        yazawa_yop01,        // constant 0xD
        yazawa_yop02,        // constant 0xE
        yazawa_yop03,        // constant 0xF
        yazawa_yop04,        // constant 0x10
        yazawa_hml01,        // constant 0x11
        yazawa_hml02,        // constant 0x12
        yazawa_hml03,        // constant 0x13
        yazawa_hml04,        // constant 0x14
        yazawa_hst01,        // constant 0x15
        yazawa_hst02,        // constant 0x16
        yazawa_hst03,        // constant 0x17
        yazawa_hst04,        // constant 0x18
        yazawa_cpr01,        // constant 0x19
        yazawa_cpr02,        // constant 0x1A
        yazawa_cpr03,        // constant 0x1B
        yazawa_cpr04,        // constant 0x1C
        yazawa_kto01,        // constant 0x1D
        yazawa_kto02,        // constant 0x1E
        yazawa_kto03,        // constant 0x1F
        yazawa_kto04,        // constant 0x20
        yazawa_gyg01,        // constant 0x21
        yazawa_gyg02,        // constant 0x22
        yazawa_gyg03,        // constant 0x23
        yazawa_gyg04,        // constant 0x24
        yazawa_trb01,        // constant 0x25
        yazawa_trb02,        // constant 0x26
        yazawa_trb03,        // constant 0x27
        yazawa_trb04,        // constant 0x28
        yazawa_tep01,        // constant 0x29
        yazawa_tep02,        // constant 0x2A
        yazawa_tep03,        // constant 0x2B
        yazawa_tep04,        // constant 0x2C
        yazawa_toj01,        // constant 0x2D
        yazawa_oum01,        // constant 0x2E
        yazawa_ykz01,        // constant 0x2F
        yazawa_ykz02,        // constant 0x30
        yazawa_ykz03,        // constant 0x31
        yazawa_ykz04,        // constant 0x32
        yazawa_ykz05,        // constant 0x33
        yazawa_shk01,        // constant 0x34
        yazawa_shk02,        // constant 0x35
        yazawa_shk03,        // constant 0x36
        yazawa_shk04,        // constant 0x37
        yazawa_nus01,        // constant 0x38
        yazawa_nus02,        // constant 0x39
        yazawa_nus03,        // constant 0x3A
        yazawa_nus04,        // constant 0x3B
        yazawa_cnm01,        // constant 0x3C
        yazawa_cnm02,        // constant 0x3D
        yazawa_cnm03,        // constant 0x3E
        yazawa_kpt01,        // constant 0x3F
        yazawa_kpt02,        // constant 0x40
        yazawa_kpt03,        // constant 0x41
        yazawa_kpt04,        // constant 0x42
        yazawa_ryr01,        // constant 0x43
        yazawa_ryr02,        // constant 0x44
        yazawa_ryr03,        // constant 0x45
        yazawa_ddg01,        // constant 0x46
        yazawa_ddg02,        // constant 0x47
        yazawa_ddg03,        // constant 0x48
        yazawa_ddg04,        // constant 0x49
        yazawa_trm01,        // constant 0x4A
        yazawa_trm02,        // constant 0x4B
        yazawa_trm03,        // constant 0x4C
        yazawa_trm04,        // constant 0x4D
        yazawa_trm05,        // constant 0x4E
        yazawa_ish01,        // constant 0x4F
        yazawa_ish02,        // constant 0x50
        yazawa_ish03,        // constant 0x51
        yazawa_msg01,        // constant 0x52
        yazawa_msg02,        // constant 0x53
        yazawa_msg03,        // constant 0x54
        yazawa_msg04,        // constant 0x55
        yazawa_tsk01,        // constant 0x56
        yazawa_tsk02,        // constant 0x57
        yazawa_tsk03,        // constant 0x58
        yazawa_tsk04,        // constant 0x59
        yazawa_htm01,        // constant 0x5A
        yazawa_htm02,        // constant 0x5B
        yazawa_htm03,        // constant 0x5C
        yazawa_htm04,        // constant 0x5D
        yazawa_gjn01,        // constant 0x5E
        yazawa_gjn02,        // constant 0x5F
        yazawa_gjn03,        // constant 0x60
        yazawa_gjn04,        // constant 0x61
        yazawa_yjb01,        // constant 0x62
        yazawa_yjb02,        // constant 0x63
        yazawa_yjb03,        // constant 0x64
        yazawa_yjb04,        // constant 0x65
        yazawa_hac01,        // constant 0x66
        yazawa_hac02,        // constant 0x67
        yazawa_hac03,        // constant 0x68
        yazawa_bin01,        // constant 0x69
        yazawa_bin02,        // constant 0x6A
        yazawa_bin03,        // constant 0x6B
        yazawa_shb01,        // constant 0x6C
        yazawa_shb02,        // constant 0x6D
        yazawa_shb03,        // constant 0x6E
        yazawa_rap01,        // constant 0x6F
        yazawa_rap02,        // constant 0x70
        yazawa_rap03,        // constant 0x71
        yazawa_rap04,        // constant 0x72
        yazawa_skm01,        // constant 0x73
        yazawa_skm02,        // constant 0x74
        yazawa_skm03,        // constant 0x75
        yazawa_skm04,        // constant 0x76
        yazawa_hkm01,        // constant 0x77
        yazawa_hkm02,        // constant 0x78
        yazawa_hkm03,        // constant 0x79
        yazawa_kah01,        // constant 0x7A
        yazawa_kah02,        // constant 0x7B
        yazawa_kah03,        // constant 0x7C
        yazawa_box01,        // constant 0x7D
        yazawa_box02,        // constant 0x7E
        yazawa_box03,        // constant 0x7F
        yazawa_box04,        // constant 0x80
        yazawa_kss01,        // constant 0x81
        yazawa_kss02,        // constant 0x82
        yazawa_kss03,        // constant 0x83
        yazawa_kss04,        // constant 0x84
        yazawa_rnr01,        // constant 0x85
        yazawa_rnr02,        // constant 0x86
        yazawa_rnr03,        // constant 0x87
        yazawa_gdm01,        // constant 0x88
        yazawa_gdm02,        // constant 0x89
        yazawa_gdm03,        // constant 0x8A
        yazawa_gdm04,        // constant 0x8B
        yazawa_ykf01,        // constant 0x8C
        yazawa_ykf02,        // constant 0x8D
        yazawa_ykf03,        // constant 0x8E
        yazawa_yks01,        // constant 0x8F
        yazawa_yks02,        // constant 0x90
        yazawa_yks03,        // constant 0x91
        yazawa_ssi01,        // constant 0x92
        yazawa_ssi02,        // constant 0x93
        yazawa_ssi03,        // constant 0x94
        yazawa_ssi04,        // constant 0x95
        yazawa_ksh01,        // constant 0x96
        yazawa_ksh02,        // constant 0x97
        yazawa_ksh03,        // constant 0x98
        yazawa_ksh04,        // constant 0x99
        yazawa_skt01,        // constant 0x9A
        yazawa_skt02,        // constant 0x9B
        yazawa_skt03,        // constant 0x9C
        yazawa_hip01,        // constant 0x9D
        yazawa_hip02,        // constant 0x9E
        yazawa_hip03,        // constant 0x9F
        yazawa_swm01,        // constant 0xA0
        yazawa_swm02,        // constant 0xA1
        yazawa_swm03,        // constant 0xA2
        yazawa_wtz01,        // constant 0xA3
        yazawa_wtz02,        // constant 0xA4
        yazawa_wtz03,        // constant 0xA5
        yazawa_htk01,        // constant 0xA6
        yazawa_htk02,        // constant 0xA7
        yazawa_htk03,        // constant 0xA8
        yazawa_rzt01,        // constant 0xA9
        yazawa_rzt02,        // constant 0xAA
        yazawa_rzt03,        // constant 0xAB
        yazawa_rzt04,        // constant 0xAC
        yazawa_dom01,        // constant 0xAD
        yazawa_dom02,        // constant 0xAE
        yazawa_rsm01,        // constant 0xAF
        yazawa_rsm02,        // constant 0xB0
        yazawa_rsm03,        // constant 0xB1
        yazawa_zom01,        // constant 0xB2
        yazawa_zom02,        // constant 0xB3
        yazawa_zom03,        // constant 0xB4
        yazawa_kae01,        // constant 0xB5
        yazawa_kae02,        // constant 0xB6
        yazawa_rsj01,        // constant 0xB7
        yazawa_rsj02,        // constant 0xB8
        yazawa_rsj03,        // constant 0xB9
        yazawa_nkt01,        // constant 0xBA
        yazawa_nkt02,        // constant 0xBB
        yazawa_nkt03,        // constant 0xBC
        yazawa_htj01,        // constant 0xBD
        yazawa_htj02,        // constant 0xBE
        yazawa_htj03,        // constant 0xBF
        yazawa_ars01,        // constant 0xC0
        yazawa_ars02,        // constant 0xC1
        yazawa_ars03,        // constant 0xC2
        yazawa_fzm01,        // constant 0xC3
        yazawa_fzm02,        // constant 0xC4
        yazawa_fzm03,        // constant 0xC5
        yazawa_bnn01,        // constant 0xC6
        yazawa_bnn02,        // constant 0xC7
        yazawa_bnn03,        // constant 0xC8
        yazawa_srg01,        // constant 0xC9
        yazawa_srg02,        // constant 0xCA
        yazawa_srg03,        // constant 0xCB
        yazawa_hmk01,        // constant 0xCC
        yazawa_hmk02,        // constant 0xCD
        yazawa_hmk03,        // constant 0xCE
        yazawa_prp01,        // constant 0xCF
        yazawa_prp02,        // constant 0xD0
        yazawa_prp03,        // constant 0xD1
        yazawa_otk01,        // constant 0xD2
        yazawa_otk02,        // constant 0xD3
        yazawa_otk03,        // constant 0xD4
        yazawa_hmc01,        // constant 0xD5
        yazawa_hmc02,        // constant 0xD6
        yazawa_hmc03,        // constant 0xD7
        yazawa_szz01,        // constant 0xD8
        yazawa_szz02,        // constant 0xD9
        yazawa_szz03,        // constant 0xDA
        yazawa_mmo01,        // constant 0xDB
        yazawa_mmo02,        // constant 0xDC
        yazawa_mmo03,        // constant 0xDD
        yazawa_wpm01,        // constant 0xDE
        yazawa_wpm02,        // constant 0xDF
        yazawa_wpm03,        // constant 0xE0
        yazawa_umb01,        // constant 0xE1
        yazawa_umb02,        // constant 0xE2
        yazawa_umb03,        // constant 0xE3
        yazawa_frm01,        // constant 0xE4
        yazawa_frm02,        // constant 0xE5
        yazawa_frm03,        // constant 0xE6
        yazawa_hgr01,        // constant 0xE7
        yazawa_hgr02,        // constant 0xE8
        yazawa_hgr03,        // constant 0xE9
        yazawa_wng01,        // constant 0xEA
        yazawa_wng02,        // constant 0xEB
        yazawa_wng03,        // constant 0xEC
        yazawa_niw01,        // constant 0xED
        yazawa_pws01,        // constant 0xEE
        yazawa_tig01,        // constant 0xEF
        yazawa_kum01,        // constant 0xF0
        yazawa_osj01,        // constant 0xF1
        yazawa_osj02,        // constant 0xF2
        yazawa_osj03,        // constant 0xF3
        yazawa_bik01,        // constant 0xF4
        sawashiro_test,      // constant 0xF5
        yazawa_toj02,        // constant 0xF6
        yazawa_toj03,        // constant 0xF7
        yazawa_toj04,        // constant 0xF8
        yazawa_toj05,        // constant 0xF9
        yazawa_toj06,        // constant 0xFA
        yazawa_toj07,        // constant 0xFB
        yazawa_oum02,        // constant 0xFC
        yazawa_oum03,        // constant 0xFD
        yazawa_oum04,        // constant 0xFE
        yazawa_oum05,        // constant 0xFF
        yazawa_oum06,        // constant 0x100
        yazawa_oum07,        // constant 0x101
        yazawa_ykz06,        // constant 0x102
        yazawa_ykz07,        // constant 0x103
        yazawa_ykz08,        // constant 0x104
        yazawa_ykz09,        // constant 0x105
        yazawa_ykz10,        // constant 0x106
        yazawa_ykz11,        // constant 0x107
        yazawa_ykz12,        // constant 0x108
        yazawa_c04_y010_boss_healer,         // constant 0x109
        yazawa_c04_y010_boss_tank,       // constant 0x10A
        yazawa_c04_y010_boss_attacker,       // constant 0x10B
        test_tiger,      // constant 0x10C
        yazawa_sawashiro01,      // constant 0x10D
        yazawa_sawashiro02,      // constant 0x10E
        matoba_e_test,       // constant 0x10F
        boss_healer_test,        // constant 0x110
        sawashiro_e_test,        // constant 0x111
        boss_mabuchi_test,       // constant 0x112
        test_bcj,        // constant 0x113
        yazawa_boss_name,        // constant 0x114
        yazawa_boss_sawashiro_c02,       // constant 0x115
        yazawa_boss_tei_c03,         // constant 0x116
        yazawa_boss_totsuka_c041,        // constant 0x117
        yazawa_boss_totsuka_c042,        // constant 0x118
        yazawa_boss_healer_c041,         // constant 0x119
        yazawa_boss_tank_c041,       // constant 0x11A
        yazawa_boss_attacker_c041,       // constant 0x11B
        yazawa_boss_healer_c042,         // constant 0x11C
        yazawa_boss_tank_c04,        // constant 0x11D
        yazawa_boss_attacker_c042,       // constant 0x11E
        yazawa_boss_tei_c05,         // constant 0x11F
        yazawa_boss_kantoku_c05,         // constant 0x120
        yazawa_boss_kantoku_c061,        // constant 0x121
        yazawa_boss_kantoku_c062,        // constant 0x122
        yazawa_boss_takabe,      // constant 0x123
        yazawa_boss_han,         // constant 0x124
        yazawa_boss_mabuchi_c08,         // constant 0x125
        yazawa_boss_totsuka_c09,         // constant 0x126
        yazawa_boss_ishioda_c091,        // constant 0x127
        yazawa_boss_ishioda_c092,        // constant 0x128
        yazawa_boss_nanba,       // constant 0x129
        yazawa_boss_tei_c10,         // constant 0x12A
        yazawa_boss_mafialeader,         // constant 0x12B
        yazawa_boss_tiger,       // constant 0x12C
        yazawa_boss_mabuchi_c10,         // constant 0x12D
        yazawa_boss_ishioda_c10,         // constant 0x12E
        yazawa_boss_matoba,      // constant 0x12F
        yazawa_boss_majima,      // constant 0x130
        yazawa_boss_saejima,         // constant 0x131
        yazawa_boss_sawashiro_c13,       // constant 0x132
        yazawa_boss_kiryu,       // constant 0x133
        yazawa_boss_ishioda_c14,         // constant 0x134
        yazawa_boss_mirror,      // constant 0x135
        yazawa_boss_tendo,       // constant 0x136
        yazawa_boss_aoki,        // constant 0x137
        yazawa_bou01,        // constant 0x138
        yazawa_bou02,        // constant 0x139
        yazawa_bou03,        // constant 0x13A
        yazawa_bou04,        // constant 0x13B
        sawashiro_brt_test,      // constant 0x13C
        yazawa_boss_kiryu_legend,        // constant 0x13D
        yazawa_boss_sawashiro_c02_b,         // constant 0x13E
        yazawa_boss_kiryu_rush,      // constant 0x13F
        yazawa_boss_kiryu_crash,         // constant 0x140
        yazawa_sub_rikishi,      // constant 0x141
        yazawa_sub_mazo,         // constant 0x142
        yazawa_boss_arakawa,         // constant 0x143
        yazawa_boss_arakawa_y,       // constant 0x144
        yazawa_sub_sniper,       // constant 0x145
        yazawa_boss_ushio_c01,       // constant 0x146
        yazawa_cpr01_main_1,         // constant 0x147
        yazawa_cpr01_main_2,         // constant 0x148
        yazawa_cpr01_main_3,         // constant 0x149
        yazawa_cpr01_main_4,         // constant 0x14A
        yazawa_shk01_main_1,         // constant 0x14B
        yazawa_cpr01_main_5,         // constant 0x14C
        yazawa_cpr01_main_6,         // constant 0x14D
        yazawa_ykz01_main_1,         // constant 0x14E
        yazawa_ykz01_main_2,         // constant 0x14F
        yazawa_ykz01_main_3,         // constant 0x150
        yazawa_ykz01_main_4,         // constant 0x151
        yazawa_ykz01_main_5,         // constant 0x152
        yazawa_ykz01_main_6,         // constant 0x153
        yazawa_ykz01_main_7,         // constant 0x154
        yazawa_ykz01_main_8,         // constant 0x155
        yazawa_ykz01_main_9,         // constant 0x156
        yazawa_ykz01_main_10,        // constant 0x157
        yazawa_ykz01_main_11,        // constant 0x158
        yazawa_ykz01_main_12,        // constant 0x159
        yazawa_ykz01_main_13,        // constant 0x15A
        yazawa_ykz01_main_14,        // constant 0x15B
        yazawa_ykz01_main_15,        // constant 0x15C
        yazawa_cpr02_main_1,         // constant 0x15D
        yazawa_hml02_main_1,         // constant 0x15E
        yazawa_cpr01_main_7,         // constant 0x15F
        yazawa_cpr01_main_8,         // constant 0x160
        yazawa_cpr01_main_9,         // constant 0x161
        yazawa_cpr01_main_10,        // constant 0x162
        yazawa_wtz01_main_1,         // constant 0x163
        yazawa_wtz01_main_2,         // constant 0x164
        yazawa_wtz01_main_3,         // constant 0x165
        yazawa_wtz01_main_4,         // constant 0x166
        yazawa_nus01_main_1,         // constant 0x167
        yazawa_nus01_main_2,         // constant 0x168
        yazawa_nus01_main_3,         // constant 0x169
        yazawa_gyg01_main_1,         // constant 0x16A
        yazawa_gyg01_main_2,         // constant 0x16B
        yazawa_gyg01_main_3,         // constant 0x16C
        yazawa_gdm01_main_1,         // constant 0x16D
        yazawa_gdm01_main_2,         // constant 0x16E
        yazawa_gdm01_main_3,         // constant 0x16F
        yazawa_gdm01_main_4,         // constant 0x170
        yazawa_cpr02_main_2,         // constant 0x171
        yazawa_cpr01_main_11,        // constant 0x172
        yazawa_cpr01_main_12,        // constant 0x173
        yazawa_cpr01_main_13,        // constant 0x174
        yazawa_cpr01_main_14,        // constant 0x175
        yazawa_cnm01_main_1,         // constant 0x176
        yazawa_cnm01_main_2,         // constant 0x177
        yazawa_cnm01_main_3,         // constant 0x178
        yazawa_cnm01_main_4,         // constant 0x179
        yazawa_cpr02_main_3,         // constant 0x17A
        yazawa_cnm01_main_5,         // constant 0x17B
        yazawa_cnm01_main_6,         // constant 0x17C
        yazawa_skm02_main_1,         // constant 0x17D
        yazawa_wtz01_main_5,         // constant 0x17E
        yazawa_wtz01_main_6,         // constant 0x17F
        yazawa_kto02_main_1,         // constant 0x180
        yazawa_cpr02_main_4,         // constant 0x181
        yazawa_wtz01_main_7,         // constant 0x182
        yazawa_wtz01_main_8,         // constant 0x183
        yazawa_wtz01_main_9,         // constant 0x184
        yazawa_srg01_main_1,         // constant 0x185
        yazawa_srg01_main_2,         // constant 0x186
        yazawa_srg01_main_3,         // constant 0x187
        yazawa_srg01_main_4,         // constant 0x188
        yazawa_srg01_main_5,         // constant 0x189
        yazawa_cpr02_main_5,         // constant 0x18A
        yazawa_cpr02_main_6,         // constant 0x18B
        yazawa_cpr02_main_7,         // constant 0x18C
        yazawa_cpr02_main_8,         // constant 0x18D
        yazawa_cpr02_main_9,         // constant 0x18E
        yazawa_cpr02_main_10,        // constant 0x18F
        yazawa_cpr02_main_11,        // constant 0x190
        yazawa_cpr02_main_12,        // constant 0x191
        chinpira_1_main_1,       // constant 0x192
        chinpira_1_main_2,       // constant 0x193
        chinpira_1_main_3,       // constant 0x194
        chinpira_1_main_4,       // constant 0x195
        chinpira_1_main_5,       // constant 0x196
        chinpira_1_main_6,       // constant 0x197
        chinpira_1_main_7,       // constant 0x198
        chinpira_1_main_8,       // constant 0x199
        chinpira_1_main_9,       // constant 0x19A
        chinpira_1_main_10,      // constant 0x19B
        chinpira_1_main_11,      // constant 0x19C
        chinpira_1_main_12,      // constant 0x19D
        chinpira_1_main_13,      // constant 0x19E
        chinpira_1_main_14,      // constant 0x19F
        chinpira_1_main_15,      // constant 0x1A0
        chinpira_1_main_16,      // constant 0x1A1
        chinpira_1_main_17,      // constant 0x1A2
        chinpira_1_main_18,      // constant 0x1A3
        chinpira_1_main_19,      // constant 0x1A4
        chinpira_1_main_20,      // constant 0x1A5
        chinpira_1_main_21,      // constant 0x1A6
        chinpira_1_main_22,      // constant 0x1A7
        chinpira_1_main_23,      // constant 0x1A8
        chinpira_1_main_24,      // constant 0x1A9
        chinpira_1_main_25,      // constant 0x1AA
        chinpira_1_main_26,      // constant 0x1AB
        chinpira_1_main_27,      // constant 0x1AC
        chinpira_1_main_28,      // constant 0x1AD
        chinpira_1_main_29,      // constant 0x1AE
        chinpira_1_main_30,      // constant 0x1AF
        chinpira_1_main_31,      // constant 0x1B0
        chinpira_1_main_32,      // constant 0x1B1
        chinpira_1_main_33,      // constant 0x1B2
        yazawa_pws01_main_1,         // constant 0x1B3
        chinpira_1_main_34,      // constant 0x1B4
        chinpira_1_main_35,      // constant 0x1B5
        chinpira_1_main_36,      // constant 0x1B6
        chinpira_1_main_37,      // constant 0x1B7
        chinpira_1_main_38,      // constant 0x1B8
        chinpira_1_main_39,      // constant 0x1B9
        chinpira_1_main_40,      // constant 0x1BA
        chinpira_1_main_41,      // constant 0x1BB
        chinpira_1_main_42,      // constant 0x1BC
        chinpira_1_main_43,      // constant 0x1BD
        chinpira_1_main_44,      // constant 0x1BE
        chinpira_1_main_45,      // constant 0x1BF
        chinpira_1_main_46,      // constant 0x1C0
        chinpira_1_main_47,      // constant 0x1C1
        chinpira_1_main_48,      // constant 0x1C2
        chinpira_1_main_49,      // constant 0x1C3
        chinpira_1_main_50,      // constant 0x1C4
        chinpira_1_main_51,      // constant 0x1C5
        chinpira_1_main_52,      // constant 0x1C6
        chinpira_1_main_53,      // constant 0x1C7
        chinpira_1_main_54,      // constant 0x1C8
        chinpira_1_main_55,      // constant 0x1C9
        chinpira_1_main_56,      // constant 0x1CA
        chinpira_1_main_57,      // constant 0x1CB
        chinpira_1_main_58,      // constant 0x1CC
        chinpira_1_main_59,      // constant 0x1CD
        chinpira_1_main_60,      // constant 0x1CE
        chinpira_1_main_61,      // constant 0x1CF
        chinpira_1_main_62,      // constant 0x1D0
        chinpira_1_main_63,      // constant 0x1D1
        chinpira_1_main_64,      // constant 0x1D2
        chinpira_1_main_65,      // constant 0x1D3
        chinpira_1_main_66,      // constant 0x1D4
        chinpira_1_main_67,      // constant 0x1D5
        chinpira_1_main_68,      // constant 0x1D6
        chinpira_1_main_69,      // constant 0x1D7
        chinpira_1_main_70,      // constant 0x1D8
        chinpira_1_main_71,      // constant 0x1D9
        chinpira_1_main_72,      // constant 0x1DA
        chinpira_1_main_73,      // constant 0x1DB
        chinpira_1_main_74,      // constant 0x1DC
        chinpira_1_main_75,      // constant 0x1DD
        chinpira_1_main_76,      // constant 0x1DE
        chinpira_1_main_77,      // constant 0x1DF
        chinpira_1_main_78,      // constant 0x1E0
        chinpira_1_main_79,      // constant 0x1E1
        chinpira_1_main_80,      // constant 0x1E2
        chinpira_1_main_81,      // constant 0x1E3
        chinpira_1_main_82,      // constant 0x1E4
        chinpira_1_main_83,      // constant 0x1E5
        chinpira_1_main_84,      // constant 0x1E6
        chinpira_1_main_85,      // constant 0x1E7
        chinpira_1_main_86,      // constant 0x1E8
        chinpira_1_main_87,      // constant 0x1E9
        chinpira_1_main_88,      // constant 0x1EA
        chinpira_1_main_89,      // constant 0x1EB
        chinpira_1_main_90,      // constant 0x1EC
        chinpira_1_main_91,      // constant 0x1ED
        chinpira_1_main_92,      // constant 0x1EE
        chinpira_1_main_93,      // constant 0x1EF
        chinpira_1_main_94,      // constant 0x1F0
        chinpira_1_main_95,      // constant 0x1F1
        chinpira_1_main_96,      // constant 0x1F2
        chinpira_1_main_97,      // constant 0x1F3
        chinpira_1_main_98,      // constant 0x1F4
        chinpira_1_main_99,      // constant 0x1F5
        yazawa_sub_a02_karate,       // constant 0x1F6
        yazawa_sub_a02_karate_mtr,       // constant 0x1F7
        yazawa_sub_a02_dad,      // constant 0x1F8
        yazawa_sub_a04_jimon,        // constant 0x1F9
        yazawa_sub_a04_kareshi,      // constant 0x1FA
        yazawa_sub_a05_bier,         // constant 0x1FB
        yazawa_sub_a06_fan,      // constant 0x1FC
        yazawa_sub_a06_fan2,         // constant 0x1FD
        yazawa_sub_a06_kantoku,      // constant 0x1FE
        yazawa_sub_a06_coach,        // constant 0x1FF
        yazawa_sub_a07_yankee,       // constant 0x200
        yazawa_sub_a07_thief,        // constant 0x201
        yazawa_sub_a08_yakuza,       // constant 0x202
        yazawa_sub_a08_gondawara,        // constant 0x203
        yazawa_sub_a08_yakuza_omt,       // constant 0x204
        yazawa_sub_a09_mazo,         // constant 0x205
        yazawa_sub_a09_gira,         // constant 0x206
        yazawa_sub_a09_niya,         // constant 0x207
        yazawa_sub_a09_ora,      // constant 0x208
        yazawa_sub_a11_i,        // constant 0x209
        yazawa_sub_a11_tsuzuki,      // constant 0x20A
        yazawa_sub_a12_jiei,         // constant 0x20B
        yazawa_sub_a16_red,      // constant 0x20C
        yazawa_sub_a16_blue,         // constant 0x20D
        yazawa_sub_a16_green,        // constant 0x20E
        yazawa_sub_a19_nise,         // constant 0x20F
        yazawa_sub_a21_yakuza,       // constant 0x210
        yazawa_sub_a22_chef,         // constant 0x211
        yazawa_sub_a22_badchef,      // constant 0x212
        yazawa_sub_a24_gomi,         // constant 0x213
        yazawa_sub_a34_yumbo,        // constant 0x214
        yazawa_sub_a35_metsuki,      // constant 0x215
        yazawa_sub_a36_yamikin,      // constant 0x216
        yazawa_sub_a39_sumo,         // constant 0x217
        yazawa_sub_a39_mili,         // constant 0x218
        yazawa_sub_a39_student,      // constant 0x219
        yazawa_sub_a67_hiroo,        // constant 0x21A
        yazawa_sub_a71_salary,       // constant 0x21B
        yazawa_sub_a71_stock,        // constant 0x21C
        yazawa_sub_a99_hakase,       // constant 0x21D
        yazawa_sub_jiei,         // constant 0x21E
        yazawa_osj01_r_arm,      // constant 0x21F
        yazawa_osj01_l_arm,      // constant 0x220
        yazawa_osj02_r_arm,      // constant 0x221
        yazawa_osj02_l_arm,      // constant 0x222
        yazawa_osj03_r_arm,      // constant 0x223
        yazawa_osj03_l_arm,      // constant 0x224
        yazawa_shk01_main,       // constant 0x225
        yazawa_shk02_main,       // constant 0x226
        yazawa_shk03_main,       // constant 0x227
        yazawa_shk04_main,       // constant 0x228
        sawashiro_x,         // constant 0x229
        sawashiro_brt,       // constant 0x22A
        yazawa_boss_amon,        // constant 0x22B
        yazawa_boss_majima_ghost,        // constant 0x22C
        yazawa_boss_amon_rush,       // constant 0x22D
        yazawa_boss_amon_crash,      // constant 0x22E
        yazawa_boss_amon_legend,         // constant 0x22F
    };
}
