using System;

namespace DragonEngineLibrary
{
    public enum CharacterVoicerID : uint
    {

        invalid,         // constant 0x0
        kiryu,       // constant 0x1
        yagami,      // constant 0x2
        kasuga,      // constant 0x3
        amon,        // constant 0x4
        test_zako01,         // constant 0x5
        leather,         // constant 0x6
        sneaker,         // constant 0x7
        highheel,        // constant 0x8
        loafer,      // constant 0x9
        boots,       // constant 0xA
        waraji,      // constant 0xB
        no_shoes,        // constant 0xC
        spike,       // constant 0xD
        barefoot,        // constant 0xE
        car_sedan01,         // constant 0xF
        car_sedan02,         // constant 0x10
        car_bus01,       // constant 0x11
        car_truck01,         // constant 0x12
        shop_cmn,        // constant 0x13
        cil_cmn,         // constant 0x14
        auth_telop,      // constant 0x15
        knt_m_young_mild,        // constant 0x16
        osk_m_young_mild,        // constant 0x17
        knt_m_young_nrm,         // constant 0x18
        knt_m_young_vita,        // constant 0x19
        knt_m_uncle,         // constant 0x1A
        osk_m_uncle,         // constant 0x1B
        knt_m_old,       // constant 0x1C
        knt_m_child,         // constant 0x1D
        knt_m_chinpira_weak,         // constant 0x1E
        osk_m_chinpira_weak,         // constant 0x1F
        knt_m_chinpira_nrm,      // constant 0x20
        knt_m_chinpira_tough,        // constant 0x21
        knt_m_yakuza_nrm,        // constant 0x22
        osk_m_yakuza_nrm,        // constant 0x23
        knt_m_yakuza_warlike,        // constant 0x24
        knt_m_yakuza_inteli,         // constant 0x25
        knt_m_big_nrm,       // constant 0x26
        knt_m_big_tough,         // constant 0x27
        westan_m_nrm,        // constant 0x28
        eastan_m_nrm,        // constant 0x29
        knt_f_young_mild,        // constant 0x2A
        osk_f_young_mild,        // constant 0x2B
        knt_f_young_nrm,         // constant 0x2C
        osk_f_young_nrm,         // constant 0x2D
        knt_f_young_vita,        // constant 0x2E
        osk_f_young_vita,        // constant 0x2F
        knt_f_sexy_20s,      // constant 0x30
        knt_f_sexy_30s,      // constant 0x31
        osk_f_sexy_20s,      // constant 0x32
        knt_f_obasan,        // constant 0x33
        knt_f_old,       // constant 0x34
        knt_f_child,         // constant 0x35
        osk_m_young_nrm,         // constant 0x36
        osk_m_chinpira_nrm,      // constant 0x37
        osk_m_yakuza_warlike,        // constant 0x38
        osk_m_big_nrm,       // constant 0x39
        osk_m_big_tough,         // constant 0x3A
        westan_m_2nrm,       // constant 0x3B
        chn_m_yakuza_nrm,        // constant 0x3C
        cat_cmn,         // constant 0x3D
        auth_gaya_m,         // constant 0x3E
        auth_gaya_f,         // constant 0x3F
        mj_kindai_staff,         // constant 0x40
        mj_rarabai_staff,        // constant 0x41
        mj_rarabai_weak,         // constant 0x42
        mj_rarabai_mid,      // constant 0x43
        mj_kindai_mid,       // constant 0x44
        mj_kindai_strong,        // constant 0x45
        mj_kindai_pl_01,         // constant 0x46
        mj_kindai_pl_02,         // constant 0x47
        mj_kindai_pl_03,         // constant 0x48
        mj_kindai_pl_04,         // constant 0x49
        mj_kindai_pl_05,         // constant 0x4A
        mj_kindai_pl_06,         // constant 0x4B
        mj_kindai_pl_07,         // constant 0x4C
        mj_kindai_pl_08,         // constant 0x4D
        mj_kindai_pl_09,         // constant 0x4E
        darts_rival02,       // constant 0x4F
        darts_rival03,       // constant 0x50
        segacrew_01,         // constant 0x51
        segacrew_02,         // constant 0x52
        karaokestaff,        // constant 0x53
        cabacrew,        // constant 0x54
        cat01,       // constant 0x55
        cat02,       // constant 0x56
        cat03,       // constant 0x57
        cat04,       // constant 0x58
        cat05,       // constant 0x59
        kamurotaxi01,        // constant 0x5A
        kamurotaxi02,        // constant 0x5B
        shop_westan01,       // constant 0x5C
        shop_eastan01,       // constant 0x5D
        male_stopper,        // constant 0x5E
        ebisuya,         // constant 0x5F
        donkicrew,       // constant 0x60
        convenience01,       // constant 0x61
        sushigincrew,        // constant 0x62
        mng_dealer,      // constant 0x63
        mng_shinpan,         // constant 0x64
        ichidou,         // constant 0x65
        mng_rival01,         // constant 0x66
        mng_rival02,         // constant 0x67
        mng_rival03,         // constant 0x68
        mng_rival05,         // constant 0x69
        mng_rival06,         // constant 0x6A
        mng_rival09,         // constant 0x6B
        mng_rival10,         // constant 0x6C
        mng_rival13,         // constant 0x6D
        mng_rival15,         // constant 0x6E
        mng_rival17,         // constant 0x6F
        mng_rival20,         // constant 0x70
        darts_rival21,       // constant 0x71
        darts_rival24,       // constant 0x72
        sawashiro,       // constant 0x73
        adachi,      // constant 0x74
        nanba,       // constant 0x75
        han,         // constant 0x76
        chou,        // constant 0x77
        masumi,      // constant 0x78
        masumi_young,        // constant 0x79
        masato,      // constant 0x7A
        honjou,      // constant 0x7B
        yasumura,        // constant 0x7C
        toranosuke,      // constant 0x7D
        kankyaku1,       // constant 0x7E
        kankyaku2,       // constant 0x7F
        youko,       // constant 0x80
        toshio,      // constant 0x81
        ushio,       // constant 0x82
        takeo,       // constant 0x83
        michiyo,         // constant 0x84
        itakura,         // constant 0x85
        tabakoya_old,        // constant 0x86
        hiratuka,        // constant 0x87
        concierge,       // constant 0x88
        kyaba_woman1,        // constant 0x89
        kyaba_woman2,        // constant 0x8A
        kyaba_boy,       // constant 0x8B
        yumeno,      // constant 0x8C
        locker_man1,         // constant 0x8D
        locker_man2,         // constant 0x8E
        jirou,       // constant 0x8F
        soap_girl1,      // constant 0x90
        soap_girl2,      // constant 0x91
        nonomura_ykz,        // constant 0x92
        nonomura_oyabun,         // constant 0x93
        oden_girl,       // constant 0x94
        kukkyou_man,         // constant 0x95
        kowamote_man,        // constant 0x96
        police_young,        // constant 0x97
        mitokougyou_ykz,         // constant 0x98
        gyuudon,         // constant 0x99
        saibankan,       // constant 0x9A
        kanie,       // constant 0x9B
        keimukan,        // constant 0x9C
        biyoushi,        // constant 0x9D
        hakamairi_ykz1,      // constant 0x9E
        hakamairi_ykz2,      // constant 0x9F
        souji,       // constant 0xA0
        tabakoya,        // constant 0xA1
        arakawa_ykz,         // constant 0xA2
        arakawakobun1,       // constant 0xA3
        arakawakobun2,       // constant 0xA4
        arakawakobun3,       // constant 0xA5
        oumi_ykz3,       // constant 0xA6
        oumi_ykz4,       // constant 0xA7
        kakuseiki,       // constant 0xA8
        oumi_oyabun1,        // constant 0xA9
        oumi_oyabun2,        // constant 0xAA
        ibori,       // constant 0xAB
        kyuushokusha,        // constant 0xAC
        komijuru_kanbu,      // constant 0xAD
        syuukin_tei,         // constant 0xAE
        syupurehikoru,       // constant 0xAF
        shokuin_woman,       // constant 0xB0
        womanliefe_girl,         // constant 0xB1
        snack_mama,      // constant 0xB2
        sonchou,         // constant 0xB3
        chon_girl1,      // constant 0xB4
        chon_girl3,      // constant 0xB5
        chon_girl4,      // constant 0xB6
        chon_girl2,      // constant 0xB7
        syuukin_teshita,         // constant 0xB8
        hamako,      // constant 0xB9
        homeless_fat,        // constant 0xBA
        matuo,       // constant 0xBB
        homeless_thin,       // constant 0xBC
        yankee1,         // constant 0xBD
        yankee2,         // constant 0xBE
        kume,        // constant 0xBF
        gunsyu1,         // constant 0xC0
        gunsyu2,         // constant 0xC1
        gunsyu3,         // constant 0xC2
        gunsyu4,         // constant 0xC3
        gunsyu5,         // constant 0xC4
        ebihara,         // constant 0xC5
        jinnai,      // constant 0xC6
        syouta,      // constant 0xC7
        syouta_chichi,       // constant 0xC8
        sinjinkarate,        // constant 0xC9
        monkasei1,       // constant 0xCA
        monkasei2,       // constant 0xCB
        monkasei3,       // constant 0xCC
        shihandai,       // constant 0xCD
        bussou,      // constant 0xCE
        kiyowa_man,      // constant 0xCF
        ikareru_fujin,       // constant 0xD0
        tada,        // constant 0xD1
        boushi_man,      // constant 0xD2
        megane_man,      // constant 0xD3
        hige_man,        // constant 0xD4
        shirakawa,       // constant 0xD5
        terakado,        // constant 0xD6
        kuroi,       // constant 0xD7
        now_girl,        // constant 0xD8
        now_friend,      // constant 0xD9
        ikesukanai,      // constant 0xDA
        yarukinai,       // constant 0xDB
        kedaruge,        // constant 0xDC
        shirakawa_kare,      // constant 0xDD
        youkiless,       // constant 0xDE
        uwasa_girl,      // constant 0xDF
        itamae_man,      // constant 0xE0
        miha_girl,       // constant 0xE1
        obie_girl,       // constant 0xE2
        saitou,      // constant 0xE3
        ziei,        // constant 0xE4
        girl_himei,      // constant 0xE5
        umeko,       // constant 0xE6
        kimuchiuri,      // constant 0xE7
        red_salary,      // constant 0xE8
        rikujo_man,      // constant 0xE9
        kyouko,      // constant 0xEA
        announce,        // constant 0xEB
        ekiin,       // constant 0xEC
        kyouko_senpai,       // constant 0xED
        boy_koukou,      // constant 0xEE
        hissi_rouba,         // constant 0xEF
        shigesan,        // constant 0xF0
        oogara_ykz,      // constant 0xF1
        sitappa_ykz,         // constant 0xF2
        hironaka,        // constant 0xF3
        tuukou_woman,        // constant 0xF4
        kondou,      // constant 0xF5
        gomi,        // constant 0xF6
        catherine,       // constant 0xF7
        yasuda,      // constant 0xF8
        bira_man,        // constant 0xF9
        noraneko,        // constant 0xFA
        charlotte,       // constant 0xFB
        kisaku_sagyo,        // constant 0xFC
        bete_sagyo,      // constant 0xFD
        daru_sagyo,      // constant 0xFE
        itaike_boy,      // constant 0xFF
        boy_mother,      // constant 0x100
        kurara,      // constant 0x101
        koufun_man,      // constant 0x102
        couple_g,        // constant 0x103
        couple_b,        // constant 0x104
        kansin_roujin,       // constant 0x105
        tension_girl,        // constant 0x106
        kowamote_ykz,        // constant 0x107
        ooshima,         // constant 0x108
        poppo_tenin,         // constant 0x109
        hobosan_jou,         // constant 0x10A
        susumu_chan,         // constant 0x10B
        awate_ykz,       // constant 0x10C
        gondawara_ykz,       // constant 0x10D
        i_llusion,       // constant 0x10E
        komarigaotenin,      // constant 0x10F
        karamare,        // constant 0x110
        hanryu_joyuu,        // constant 0x111
        syorou_girl,         // constant 0x112
        tsuzuki,         // constant 0x113
        kaede,       // constant 0x114
        syokudoutenin,       // constant 0x115
        kuchiwaru,       // constant 0x116
        ninsouwaru,      // constant 0x117
        mimawari_keikan,         // constant 0x118
        garawaru,        // constant 0x119
        awano,       // constant 0x11A
        fukuya_tenin,        // constant 0x11B
        awano_grandma,       // constant 0x11C
        miha_jk,         // constant 0x11D
        reisei_jk,       // constant 0x11E
        nise_michio,         // constant 0x11F
        kenbutsu_girl,       // constant 0x120
        michiofunboy1,       // constant 0x121
        metsuki_chinpira,        // constant 0x122
        hinnasi_chinpira,        // constant 0x123
        koufun_michio,       // constant 0x124
        toorigakari_girl,        // constant 0x125
        toorigakari_boy,         // constant 0x126
        rouzin_metsuki,      // constant 0x127
        michiofungirl,       // constant 0x128
        michiofunboy2,       // constant 0x129
        megumi,      // constant 0x12A
        syorou_rouzin,       // constant 0x12B
        metukiwaru_bokin,        // constant 0x12C
        gyarufuu_make,       // constant 0x12D
        tyara_boy,       // constant 0x12E
        jouhin_madam,        // constant 0x12F
        ositoyaka_madam,         // constant 0x130
        seiryo_kasyu,        // constant 0x131
        insyoku_tentyou,         // constant 0x132
        kozure_mama,         // constant 0x133
        kosokoso,        // constant 0x134
        hisohiso,        // constant 0x135
        mukiryoku_boy,       // constant 0x136
        akarui_jk,       // constant 0x137
        mazime_boy,      // constant 0x138
        yasasisou_girl,      // constant 0x139
        koufun_fun,      // constant 0x13A
        nekkyou_fun,         // constant 0x13B
        sozii,       // constant 0x13C
        okitahakase,         // constant 0x13D
        osouzimaru,      // constant 0x13E
        hadasi_baachan,      // constant 0x13F
        fish_toraneko,       // constant 0x140
        gamecenter_staff,        // constant 0x141
        Default,         // constant 0x142
        katana,      // constant 0x143
        gun,         // constant 0x144
        zako,        // constant 0x145
        sude,        // constant 0x146
        testchair,       // constant 0x147
        testbin,         // constant 0x148
        testdesk,        // constant 0x149
        breakbin,        // constant 0x14A
        bigkanban,       // constant 0x14B
        steelkanban,         // constant 0x14C
        bicycle,         // constant 0x14D
        shelf,       // constant 0x14E
        breakshelf,      // constant 0x14F
        crashshelf,      // constant 0x150
        glass,       // constant 0x151
        testdoor,        // constant 0x152
        testautodoor,        // constant 0x153
        dosu,        // constant 0x154
        cardboard,       // constant 0x155
        bike,        // constant 0x156
        garbage,         // constant 0x157
        plant,       // constant 0x158
        pylon,       // constant 0x159
        glass_cracks,        // constant 0x15A
        woodkomono,      // constant 0x15B
        tablestone,      // constant 0x15C
        metalkomono,         // constant 0x15D
        haizaraglass,        // constant 0x15E
        alpsdoor,        // constant 0x15F
        metal_harddoor,      // constant 0x160
        paper,       // constant 0x161
        can,         // constant 0x162
        sofa,        // constant 0x163
        cardbordshelf,       // constant 0x164
        metalchair,      // constant 0x165
        silent,      // constant 0x166
        metal,       // constant 0x167
        clangrenade,         // constant 0x168
        clandosu,        // constant 0x169
        clangun,         // constant 0x16A
        wooddoor,        // constant 0x16B
        doubledoor,      // constant 0x16C
        slidedoor,       // constant 0x16D
        hammer,      // constant 0x16E
        woodgareki,      // constant 0x16F
        stonegareki,         // constant 0x170
        bokuto,      // constant 0x171
        drumkan,         // constant 0x172
        drumexp,         // constant 0x173
        bathdoor,        // constant 0x174
        bomb,        // constant 0x175
        vendhing,        // constant 0x176
        hirosedoor,      // constant 0x177
        sesoujy,         // constant 0x178
        kiyomidoor,      // constant 0x179
        morenodoor,      // constant 0x17A
        serenadoor,      // constant 0x17B
        suigundoor,      // constant 0x17C
        semulticopter,       // constant 0x17D
        fusuma,      // constant 0x17E
        woodbat,         // constant 0x17F
        metalbat,        // constant 0x180
        pipe,        // constant 0x181
        rpg,         // constant 0x182
        ev,      // constant 0x183
        oldev,       // constant 0x184
        soccer,      // constant 0x185
        siren,       // constant 0x186
        shelfkan,        // constant 0x187
        flour,       // constant 0x188
        metalslidedoor,      // constant 0x189
        buranko,         // constant 0x18A
        chopstick,       // constant 0x18B
        hardball,        // constant 0x18C
        dish,        // constant 0x18D
        meet,        // constant 0x18E
        turimeet,        // constant 0x18F
        rope,        // constant 0x190
        metalpot,        // constant 0x191
        metaldoubledoor,         // constant 0x192
        zousendoor,      // constant 0x193
        machinegun,      // constant 0x194
        zousendouble,        // constant 0x195
        zousenheavy,         // constant 0x196
        amondrone,       // constant 0x197
        amonrumba,       // constant 0x198
        imssn_bomb,      // constant 0x199
        fuzokuswg,       // constant 0x19A
        propan,      // constant 0x19B
        karistick,       // constant 0x19C
        spray,       // constant 0x19D
        tonfa,       // constant 0x19E
        meriken,         // constant 0x19F
        yari,        // constant 0x1A0
        shoukaki,        // constant 0x1A1
        kien,        // constant 0x1A2
        sword_seiryuto,      // constant 0x1A3
        sword_fire,      // constant 0x1A4
        sword_thunder,       // constant 0x1A5
        sword_wind,      // constant 0x1A6
        sword_yoto,      // constant 0x1A7
        sword_photon,        // constant 0x1A8
        daiken,      // constant 0x1A9
        bowl,        // constant 0x1AA
        slaper,      // constant 0x1AB
        gmk_spear,       // constant 0x1AC
        shotgun,         // constant 0x1AD
        vhc_trailer,         // constant 0x1AE
        vhc_houseboat,       // constant 0x1AF
        haichi_gatling,      // constant 0x1B0
        lighter,         // constant 0x1B1
        stungun,         // constant 0x1B2
        clan_base,       // constant 0x1B3
        metal_barricade,         // constant 0x1B4
        garagara,        // constant 0x1B5
        arm_slaper,      // constant 0x1B6
        arm_hammer,      // constant 0x1B7
        arm_woodbat,         // constant 0x1B8
        arm_metalbat,        // constant 0x1B9
        arm_pipe,        // constant 0x1BA
        arm_karistick,       // constant 0x1BB
        arm_tonfa,       // constant 0x1BC
        arm_meriken,         // constant 0x1BD
        arm_yari,        // constant 0x1BE
        arm_stungun,         // constant 0x1BF
        arm_swd_yoto,        // constant 0x1C0
        arm_swd_thunder,         // constant 0x1C1
        arm_swd_wind,        // constant 0x1C2
        arm_swd_photon,      // constant 0x1C3
        arm_swd_fire,        // constant 0x1C4
        arm_swd_seiryuto,        // constant 0x1C5
        arm_swd_daiken,      // constant 0x1C6
        arm_swd_bokuto,      // constant 0x1C7
        arm_swd_katana,      // constant 0x1C8
        arm_swd_kien,        // constant 0x1C9
        arm_swd_dosu,        // constant 0x1CA
        arm_gun_default,         // constant 0x1CB
        arm_gun_machinegun,      // constant 0x1CC
        arm_gun_shotgun,         // constant 0x1CD
        arm_gun_rpg,         // constant 0x1CE
        arm_gun_bomb,        // constant 0x1CF
        obj_metalkomono,         // constant 0x1D0
        obj_tablestone,      // constant 0x1D1
        obj_haizaraglass,        // constant 0x1D2
        obj_woodkomono,      // constant 0x1D3
        obj_chopstick,       // constant 0x1D4
        obj_buranko,         // constant 0x1D5
        obj_fuzokuswg,       // constant 0x1D6
        obj_rope,        // constant 0x1D7
        obj_bicycle,         // constant 0x1D8
        obj_bowl,        // constant 0x1D9
        obj_soccer,      // constant 0x1DA
        obj_hardball,        // constant 0x1DB
        obj_desk,        // constant 0x1DC
        obj_sofa,        // constant 0x1DD
        obj_woodgareki,      // constant 0x1DE
        obj_stonegareki,         // constant 0x1DF
        obj_chair,       // constant 0x1E0
        obj_default,         // constant 0x1E1
        obj_paper,       // constant 0x1E2
        obj_bigkanban,       // constant 0x1E3
        obj_steelkanban,         // constant 0x1E4
        obj_metal_barricade,         // constant 0x1E5
        obj_metalchair,      // constant 0x1E6
        obj_shelf,       // constant 0x1E7
        obj_shelfkan,        // constant 0x1E8
        obj_breakshelf,      // constant 0x1E9
        obj_crashshelf,      // constant 0x1EA
        obj_cardbordshelf,       // constant 0x1EB
        obj_glass,       // constant 0x1EC
        obj_glass_cracks,        // constant 0x1ED
        obj_cardboard,       // constant 0x1EE
        obj_can,         // constant 0x1EF
        obj_bike,        // constant 0x1F0
        obj_drumkan,         // constant 0x1F1
        obj_propan,      // constant 0x1F2
        obj_drumexp,         // constant 0x1F3
        obj_garbage,         // constant 0x1F4
        obj_plant,       // constant 0x1F5
        obj_pylon,       // constant 0x1F6
        obj_bin,         // constant 0x1F7
        obj_lighter,         // constant 0x1F8
        obj_spray,       // constant 0x1F9
        obj_shoukaki,        // constant 0x1FA
        obj_dish,        // constant 0x1FB
        obj_metalpot,        // constant 0x1FC
        obj_testtone,        // constant 0x1FD
        obj_meet,        // constant 0x1FE
        obj_turimeet,        // constant 0x1FF
        obj_silent,      // constant 0x200
        obj_flour,       // constant 0x201
        obj_breakbin,        // constant 0x202
        door_sp_moreno,      // constant 0x203
        door_sp_suigun,      // constant 0x204
        door_sp_kiyomi,      // constant 0x205
        door_sp_zousen,      // constant 0x206
        door_bath,       // constant 0x207
        door_wood,       // constant 0x208
        door_double,         // constant 0x209
        door_metaldouble,        // constant 0x20A
        door_sp_zousendouble,        // constant 0x20B
        door_sp_zousenheavy,         // constant 0x20C
        door_sp_alps,        // constant 0x20D
        door_sp_serena,      // constant 0x20E
        door_metal_hard,         // constant 0x20F
        door_autodoor,       // constant 0x210
        door_slidedoor,      // constant 0x211
        door_fusuma,         // constant 0x212
        door_sp_hirose,      // constant 0x213
        door_metalslide,         // constant 0x214
        door_oldev,      // constant 0x215
        door_ev,         // constant 0x216
        door_default,        // constant 0x217
        etc_timer_bomb,      // constant 0x218
        arm_nunchaku,        // constant 0x219
        arm_stunbaton,       // constant 0x21A
        arm_gun_laser,       // constant 0x21B
        arm_woodbat_fire,        // constant 0x21C
        arm_stunmassager,        // constant 0x21D
        obj_bigkanban_chase,         // constant 0x21E
        obj_curingnet,       // constant 0x21F
        obj_zabuton,         // constant 0x220
        gmk_fallofawall,         // constant 0x221
        akane,       // constant 0x222
        denwa_chinpira,      // constant 0x223
        rikishi,         // constant 0x224
        kanako,      // constant 0x225
        sniper_ppoi,         // constant 0x226
        gakuseifuku_boy,         // constant 0x227
        shibuya,         // constant 0x228
        megumi_haha,         // constant 0x229
        megumi_titi,         // constant 0x22A
        yakikinfuu,      // constant 0x22B
        tinpirappoi,         // constant 0x22C
        gorotsukippoi,       // constant 0x22D
        kangoshi,        // constant 0x22E
        noboru,      // constant 0x22F
        tatiwaru_yanki,      // constant 0x230
        sportstensyu,        // constant 0x231
        glove_manzoku,       // constant 0x232
        tamae,       // constant 0x233
        glove_dorobou,       // constant 0x234
        butsukarare_hinto,       // constant 0x235
        kansin_hinto,        // constant 0x236
        onomichi_doll,       // constant 0x237
        doujima,         // constant 0x238
        kashiwagi,       // constant 0x239
        shimano,         // constant 0x23A
        majima,      // constant 0x23B
        gaya01,      // constant 0x23C
        gaya02,      // constant 0x23D
        gaya03,      // constant 0x23E
        michino,         // constant 0x23F
        ayami,       // constant 0x240
        ayami_chichi,        // constant 0x241
        ayami_haha,      // constant 0x242
        iyami_joushi,        // constant 0x243
        kisaku_danseikyaku,      // constant 0x244
        tanjun_danseikyaku,      // constant 0x245
        yasasisou_joseikyaku,        // constant 0x246
        fuwafuwa_joseikyaku,         // constant 0x247
        yakuzafuu_otoko,         // constant 0x248
        tyuukamam_tenin,         // constant 0x249
        taiyakiya_tenin,         // constant 0x24A
        sexy_bunny,      // constant 0x24B
        horinouchi,      // constant 0x24C
        police_musen,        // constant 0x24D
        nonomiya,        // constant 0x24E
        coffee_tenin,        // constant 0x24F
        totsuka,         // constant 0x250
        nanoha,      // constant 0x251
        hidamari_uketsuke,       // constant 0x252
        hidamari_celeb_old,      // constant 0x253
        hidamari_souji,      // constant 0x254
        hidamari_oldwomanwoman,      // constant 0x255
        hidamari_kaigoshi,       // constant 0x256
        hidamari_doctor,         // constant 0x257
        hidamari_keibin1,        // constant 0x258
        ryuhei,      // constant 0x259
        seiryukai_wakagashira,       // constant 0x25A
        mabuchi,         // constant 0x25B
        saeko,       // constant 0x25C
        white_kukkyou,       // constant 0x25D
        white_gunsyu1,       // constant 0x25E
        white_gunsyu2,       // constant 0x25F
        white_gunsyu3,       // constant 0x260
        white_gunsyu4,       // constant 0x261
        white_gunsyu5,       // constant 0x262
        nonomiya_shiriai1,       // constant 0x263
        nonomiya_shiriai2,       // constant 0x264
        ryubou_men,      // constant 0x265
        rinrin_boy,      // constant 0x266
        rinrin_hostess1,         // constant 0x267
        rinrin_hostess2,         // constant 0x268
        rinrin_hostess3,         // constant 0x269
        boueki_nioroshileader,       // constant 0x26A
        boueki_kanshileader,         // constant 0x26B
        boueki_kantoku,      // constant 0x26C
        boueki_eigyou1,      // constant 0x26D
        boueki_eigyou2,      // constant 0x26E
        boueki_eigyou3,      // constant 0x26F
        fuuzoku_juumin1,         // constant 0x270
        fuuzoku_juumin2,         // constant 0x271
        fuuzoku_juumin3,         // constant 0x272
        fuuzoku_gaya1,       // constant 0x273
        fuuzoku_gaya2,       // constant 0x274
        fuuzoku_gaya3,       // constant 0x275
        fuuzoku_gaya4,       // constant 0x276
        ryubou_nioroshi1,        // constant 0x277
        ryubou_nioroshi2,        // constant 0x278
        ryubou_nioroshi3,        // constant 0x279
        mabuchi_teshita,         // constant 0x27A
        water_police,        // constant 0x27B
        hanayama,        // constant 0x27C
        anzai,       // constant 0x27D
        kudo,        // constant 0x27E
        kantoku_yakyu,       // constant 0x27F
        kochi_yakyu,         // constant 0x280
        majime_kisha,        // constant 0x281
        ohei_kisha,      // constant 0x282
        kiyowa_kisha,        // constant 0x283
        oshitsuyo_kisha,         // constant 0x284
        kageki_fuan,         // constant 0x285
        koedeka_fuan,        // constant 0x286
        yoki_kyaba,      // constant 0x287
        akarui_kyaba,        // constant 0x288
        yuta_chuka,      // constant 0x289
        tokuro_chuka,        // constant 0x28A
        mao_chuka,       // constant 0x28B
        senpai_ryori,        // constant 0x28C
        garawaru_ryori,      // constant 0x28D
        ohei_ryori,      // constant 0x28E
        charai_ryori,        // constant 0x28F
        hiro_baito,      // constant 0x290
        shomonai,        // constant 0x291
        okubyo_otoko,        // constant 0x292
        ikioi_kisha,         // constant 0x293
        mazo_ojisan,         // constant 0x294
        yumiko_sm,       // constant 0x295
        shiho_sm,        // constant 0x296
        atsugesho_sm,        // constant 0x297
        kinpatsu_sm,         // constant 0x298
        nanba_wan_sm,        // constant 0x299
        tencho_sm,       // constant 0x29A
        mazo_haha,       // constant 0x29B
        oratsuita_otoko,         // constant 0x29C
        giratsuita_otoko,        // constant 0x29D
        niyatsuita_otoko,        // constant 0x29E
        homeless_kan,        // constant 0x29F
        juumin_macho,        // constant 0x2A0
        juumin_oldwoman,         // constant 0x2A1
        juumin_child,        // constant 0x2A2
        yankee_hige,         // constant 0x2A3
        yankee_ronge,        // constant 0x2A4
        yankee_kinpatu,      // constant 0x2A5
        yasagure_chinpira1,      // constant 0x2A6
        yasagure_chinpira2,      // constant 0x2A7
        yasagure_chinpira3,      // constant 0x2A8
        kimuchi_kyaku,       // constant 0x2A9
        sujihakase,      // constant 0x2AA
        henshitsusha,        // constant 0x2AB
        bukkomitaka,         // constant 0x2AC
        ikari,       // constant 0x2AD
        hayakawa,        // constant 0x2AE
        gaikoku_otoko,       // constant 0x2AF
        erito_sarari,        // constant 0x2B0
        erito_shoken,        // constant 0x2B1
        knt_m_young_anemia,      // constant 0x2B2
        knt_m_uncle_nrm,         // constant 0x2B3
        knt_m_uncle_anemia,      // constant 0x2B4
        osk_m_yakuza_inteli,         // constant 0x2B5
        chn_m_nrm,       // constant 0x2B6
        chn_m_chinpira_weak,         // constant 0x2B7
        chn_m_chinpira_nrm,      // constant 0x2B8
        chn_m_yakuza_kata,       // constant 0x2B9
        chn_m_yakuza_tough,      // constant 0x2BA
        chn_m_old,       // constant 0x2BB
        korean_m_uncle,      // constant 0x2BC
        korean_m_30s,        // constant 0x2BD
        knt_m_hmls_old1,         // constant 0x2BE
        knt_m_hmls_old2,         // constant 0x2BF
        knt_m_hmls_uncle1,       // constant 0x2C0
        knt_m_hmls_uncle2,       // constant 0x2C1
        westan_m_tough,      // constant 0x2C2
        knt_m_grappler,      // constant 0x2C3
        knt_m_mad,       // constant 0x2C4
        knt_m_arakure,       // constant 0x2C5
        knt_m_hentai,        // constant 0x2C6
        knt_m_cool,      // constant 0x2C7
        knt_m_polite,        // constant 0x2C8
        knt_f_hmls_old,      // constant 0x2C9
        knt_f_hmls_obasan,       // constant 0x2CA
        chn_f_obasan,        // constant 0x2CB
        chn_f_old,       // constant 0x2CC
        chn_f_young_nrm,         // constant 0x2CD
        korean_f_old,        // constant 0x2CE
        korean_f_obasan,         // constant 0x2CF
        hidamari_oldwoman,       // constant 0x2D0
        takabe,      // constant 0x2D1
        ryubou_smart,        // constant 0x2D2
        ryubou_arakure,      // constant 0x2D3
        tetsu,       // constant 0x2D4
        sonhi,       // constant 0x2D5
        komijuru_omen,       // constant 0x2D6
        poke_tenninn,        // constant 0x2D7
        shihainin_mg,        // constant 0x2D8
        sugasuga_mg,         // constant 0x2D9
        manzoku_mg,      // constant 0x2DA
        syupurehikoru2,      // constant 0x2DB
        syupurehikoru3,      // constant 0x2DC
        ogasawara,       // constant 0x2DD
        hisho_woman,         // constant 0x2DE
        totsuka_buka,        // constant 0x2DF
        machi_himei,         // constant 0x2E0
        bleach_gaya1,        // constant 0x2E1
        bleach_gaya2,        // constant 0x2E2
        bleach_gaya3,        // constant 0x2E3
        bleach_oumi,         // constant 0x2E4
        ishioda,         // constant 0x2E5
        omoni_tenin,         // constant 0x2E6
        chn_m_nrm_kata,      // constant 0x2E7
        knt_m_mad_cook,      // constant 0x2E8
        knt_m_mad_st_ripper,         // constant 0x2E9
        knt_m_mad_docter,        // constant 0x2EA
        knt_m_mad_hacker,        // constant 0x2EB
        knt_m_mad_firebug,       // constant 0x2EC
        knt_m_mad_bag_man,       // constant 0x2ED
        homeless_ran,        // constant 0x2EE
        tendou,      // constant 0x2EF
        souri,       // constant 0x2F0
        announcer_woman,         // constant 0x2F1
        ogikubo,         // constant 0x2F2
        massmedia,       // constant 0x2F3
        reporter1,       // constant 0x2F4
        reporter2,       // constant 0x2F5
        securitypolice,      // constant 0x2F6
        couple_woman,        // constant 0x2F7
        couple_man,      // constant 0x2F8
        suzumori,        // constant 0x2F9
        parking_oumi1,       // constant 0x2FA
        parking_oumi2,       // constant 0x2FB
        bukimi_oumi,         // constant 0x2FC
        keigopolice,         // constant 0x2FD
        junpei_pk,       // constant 0x2FE
        kiyoshi_pk,      // constant 0x2FF
        toshio_pk,       // constant 0x300
        tomoji_pk,       // constant 0x301
        heian_keibi1,        // constant 0x302
        heian_ykz1,      // constant 0x303
        heian_ykz2,      // constant 0x304
        heian_ykz3,      // constant 0x305
        heian_ykz4,      // constant 0x306
        dcart_pokecir,       // constant 0x307
        dcart_yakuza,        // constant 0x308
        dcart_bikegang,      // constant 0x309
        dcart_bizman,        // constant 0x30A
        dcart_wrestler,      // constant 0x30B
        dcart_sumoist,       // constant 0x30C
        dcart_bunny,         // constant 0x30D
        dcart_old_woman,         // constant 0x30E
        kanbe,       // constant 0x30F
        matoba,      // constant 0x310
        sougi_woman1,        // constant 0x311
        sougi_woman2,        // constant 0x312
        sougi_man1,      // constant 0x313
        sougi_man2,      // constant 0x314
        sougi_man3,      // constant 0x315
        oumi_tuiseki,        // constant 0x316
        sanguras_ykz,        // constant 0x317
        ikatsui_ykz,         // constant 0x318
        yakuza_call,         // constant 0x319
        souten_yobikomi,         // constant 0x31A
        ogata,       // constant 0x31B
        oumi_keikai,         // constant 0x31C
        saejima,         // constant 0x31D
        daigo,       // constant 0x31E
        gaya_demukae,        // constant 0x31F
        gaya_hantai1,        // constant 0x320
        gaya_hantai2,        // constant 0x321
        gaya_hantai3,        // constant 0x322
        gaya_hantai4,        // constant 0x323
        watase,      // constant 0x324
        oumi_sentou,         // constant 0x325
        oumi_nekutai,        // constant 0x326
        oumi_dosu,       // constant 0x327
        soshiki_kanbu1,      // constant 0x328
        soshiki_kanbu2,      // constant 0x329
        soshiki_kanbu3,      // constant 0x32A
        chousyu_woman,       // constant 0x32B
        chousyu_tonari,      // constant 0x32C
        commentator,         // constant 0x32D
        shikai,      // constant 0x32E
        narrator,        // constant 0x32F
        sawashiro_buka,      // constant 0x330
        sawashiro_shounen,       // constant 0x331
        ikumi,       // constant 0x332
        sawashiro_seinen,        // constant 0x333
        tougenkyou_tenin,        // constant 0x334
        chn_m_chinpira_big,      // constant 0x335
        kor_m_yakuza_nrm,        // constant 0x336
        kor_m_yakuza_tough,      // constant 0x337
        kor_m_chinpira_big,      // constant 0x338
        kor_f_30s01,         // constant 0x339
        kor_f_30s02,         // constant 0x33A
        mj_baron,        // constant 0x33B
        mj_president,        // constant 0x33C
        mj_wife,         // constant 0x33D
        mgr_m_yng_vita,      // constant 0x33E
        mgr_m_yng_inteli,        // constant 0x33F
        mgr_m_uncle,         // constant 0x340
        mgr_m_yakuza,        // constant 0x341
        mgr_m_old,       // constant 0x342
        mgr_f_yng_vita,      // constant 0x343
        mgr_f_yng_sexy,      // constant 0x344
        mgr_f_yng_mild,      // constant 0x345
        mgr_f_obasan,        // constant 0x346
        mgr_f_old,       // constant 0x347
        masaki_pk,       // constant 0x348
        aichan,      // constant 0x349
        naoki,       // constant 0x34A
        hamanoumi,       // constant 0x34B
        suguru,      // constant 0x34C
        jin,         // constant 0x34D
        matsuko,         // constant 0x34E
        akira,       // constant 0x34F
        poke_fighter,        // constant 0x350
        wdr_knt_m_young_mild,        // constant 0x351
        wdr_osk_m_young_mild,        // constant 0x352
        wdr_knt_m_young_nrm,         // constant 0x353
        wdr_osk_m_young_nrm,         // constant 0x354
        wdr_knt_m_young_vita,        // constant 0x355
        wdr_knt_m_uncle,         // constant 0x356
        wdr_osk_m_uncle,         // constant 0x357
        wdr_knt_m_chinpira_weak,         // constant 0x358
        wdr_osk_m_chinpira_weak,         // constant 0x359
        wdr_knt_m_chinpira_nrm,      // constant 0x35A
        wdr_osk_m_chinpira_nrm,      // constant 0x35B
        wdr_knt_m_chinpira_tough,        // constant 0x35C
        wdr_knt_m_yakuza_nrm,        // constant 0x35D
        wdr_osk_m_yakuza_nrm,        // constant 0x35E
        wdr_knt_m_yakuza_warlike,        // constant 0x35F
        wdr_osk_m_yakuza_warlike,        // constant 0x360
        wdr_knt_m_yakuza_inteli,         // constant 0x361
        wdr_knt_m_big_nrm,       // constant 0x362
        wdr_osk_m_big_nrm,       // constant 0x363
        wdr_knt_m_big_tough,         // constant 0x364
        wdr_osk_m_big_tough,         // constant 0x365
        wdr_chn_m_chinpira_weak,         // constant 0x366
        wdr_chn_m_chinpira_nrm,      // constant 0x367
        wdr_chn_m_yakuza_nrm,        // constant 0x368
        wdr_chn_m_yakuza_tough,      // constant 0x369
        wdr_chn_m_big_tough,         // constant 0x36A
        wdr_knt_f_young_mild,        // constant 0x36B
        wdr_osk_f_young_mild,        // constant 0x36C
        wdr_knt_f_young_nrm,         // constant 0x36D
        wdr_osk_f_young_nrm,         // constant 0x36E
        wdr_knt_f_young_vita,        // constant 0x36F
        wdr_osk_f_young_vita,        // constant 0x370
        wdr_knt_f_sexy_20s,      // constant 0x371
        wdr_knt_f_sexy_30s,      // constant 0x372
        wdr_osk_f_sexy_20s,      // constant 0x373
        wdr_knt_f_obasan,        // constant 0x374
        wdr_m_hls01,         // constant 0x375
        wdr_m_hls02,         // constant 0x376
        wdr_m_hls03,         // constant 0x377
        wdr_m_hls04,         // constant 0x378
        wdr_kor_m_30s01,         // constant 0x379
        wdr_kor_m_30s02,         // constant 0x37A
        wdr_kor_m_uncle,         // constant 0x37B
        wdr_kor_f_30s01,         // constant 0x37C
        wdr_kor_f_30s02,         // constant 0x37D
        boss_yankee,         // constant 0x37E
        kiyowa_megane,       // constant 0x37F
        kyaba_boy2,      // constant 0x380
        oumi_yuudou,         // constant 0x381
        oumi_annai,      // constant 0x382
        gaya_chousyu1,       // constant 0x383
        gaya_chousyu2,       // constant 0x384
        gaya_chousyu3,       // constant 0x385
        gaya_homeless1,      // constant 0x386
        gaya_homeless2,      // constant 0x387
        gaya_homeless3,      // constant 0x388
        gaya_homeless4,      // constant 0x389
        massmedia1,      // constant 0x38A
        kasuga_baby,         // constant 0x38B
        girl_kumiin,         // constant 0x38C
        girl_shitappa,       // constant 0x38D
        syuukin_teshita1,        // constant 0x38E
        syuukin_teshita2,        // constant 0x38F
        ishioda_buka1,       // constant 0x390
        ishioda_buka2,       // constant 0x391
        reporter3,       // constant 0x392
        reporter4,       // constant 0x393
        reporter5,       // constant 0x394
        keigopolice1,        // constant 0x395
        keigopolice2,        // constant 0x396
        gaya_oomisoka1,      // constant 0x397
        gaya_oomisoka2,      // constant 0x398
        white_demolady1,         // constant 0x399
        white_demolady2,         // constant 0x39A
        oumi_taore,      // constant 0x39B
        ryuou,       // constant 0x39C
        Operator,        // constant 0x39D
        sniper,      // constant 0x39E
        master,      // constant 0x39F
        aoki_kouho,      // constant 0x3A0
        uguisu,      // constant 0x3A1
        atenshi,         // constant 0x3A2
        date,        // constant 0x3A3
        kisha,       // constant 0x3A4
        aoki_unten,      // constant 0x3A5
        keiji_elite,         // constant 0x3A6
        keiji_young,         // constant 0x3A7
        tuukounin,       // constant 0x3A8
        shikai_minji,        // constant 0x3A9
        yakuza_kurofuku,         // constant 0x3AA
        seiryu_ykz1,         // constant 0x3AB
        seiryu_ykz2,         // constant 0x3AC
        seiryu_aida,         // constant 0x3AD
        seiryu_kasayama,         // constant 0x3AE
        seiryu_kikukawa,         // constant 0x3AF
        arm_bag,         // constant 0x3B0
        etc_houseboat,       // constant 0x3B1
        masato_young,        // constant 0x3B2
        kansyu,      // constant 0x3B3
        gary,        // constant 0x3B4
        dh_chirashi,         // constant 0x3B5
        dh_denwa,        // constant 0x3B6
        dh_hosuto,       // constant 0x3B7
        tome,        // constant 0x3B8
        kokekokko,       // constant 0x3B9
        tsugumi,         // constant 0x3BA
        tsugumi_chichi,      // constant 0x3BB
        jiageya_kojo,        // constant 0x3BC
        yuki,        // constant 0x3BD
        dcart_mob01,         // constant 0x3BE
        dcart_mob02,         // constant 0x3BF
        dcart_mob03,         // constant 0x3C0
        lau,         // constant 0x3C1
        mgr_m_yng_nrm,       // constant 0x3C2
        mgr_m_kor_nrm_kata,      // constant 0x3C3
        mgr_f_yng_nrm,       // constant 0x3C4
        sklwdr_crasher01,        // constant 0x3C5
        sklwdr_crasher02,        // constant 0x3C6
        sklwdr_crasher03,        // constant 0x3C7
        sklwdr_crasher04,        // constant 0x3C8
        sklwdr_liveman01,        // constant 0x3C9
        sklwdr_liveman02,        // constant 0x3CA
        sklwdr_liveman03,        // constant 0x3CB
        sklwdr_riot_police,      // constant 0x3CC
        sklwdr_fanatic01,        // constant 0x3CD
        sklwdr_fanatic02,        // constant 0x3CE
        sklwdr_idlefan01,        // constant 0x3CF
        sklwdr_idlefan02,        // constant 0x3D0
        sklwdr_idlefan03,        // constant 0x3D1
        koyuki,      // constant 0x3D2
        holder_m_yng_nrm,        // constant 0x3D3
        holder_m_yng_biz,        // constant 0x3D4
        holder_m_yng_big,        // constant 0x3D5
        holder_m_mdl_caster,         // constant 0x3D6
        holder_m_yng_cool,       // constant 0x3D7
        holder_m_mdl_big,        // constant 0x3D8
        holder_m_mdl_ykz,        // constant 0x3D9
        holder_m_yng_hagetaka,       // constant 0x3DA
        holder_m_yng_big_ykz,        // constant 0x3DB
        holder_m_mdl_afro,       // constant 0x3DC
        holder_m_mdl_celeb,      // constant 0x3DD
        holder_f_yng_nrm,        // constant 0x3DE
        holder_f_mdl_celeb,      // constant 0x3DF
        holder_f_west_kata,      // constant 0x3E0
        holder_f_old_monster,        // constant 0x3E1
        chn_f_nrm_kata,      // constant 0x3E2
        iroha,       // constant 0x3E3
        ryutsu_tenninn,      // constant 0x3E4
        eri,         // constant 0x3E5
        kagaribi,        // constant 0x3E6
        oumi_junkai1,        // constant 0x3E7
        oumi_junkai2,        // constant 0x3E8
        adachi_mf,       // constant 0x3E9
        takashi,         // constant 0x3EA
        kosuke,      // constant 0x3EB
        hasegawa,        // constant 0x3EC
        gooddandy,       // constant 0x3ED
        futaba,      // constant 0x3EE
        atsushi,         // constant 0x3EF
        atsushi_bro,         // constant 0x3F0
        ktrgawa,         // constant 0x3F1
        yamashita,       // constant 0x3F2
        jin_zantou,      // constant 0x3F3
        hls_yowai,       // constant 0x3F4
        hls_komono,      // constant 0x3F5
        hls_asamashii,       // constant 0x3F6
        hls_sekoi,       // constant 0x3F7
        hls_hisshi,      // constant 0x3F8
        hls_kurouto,         // constant 0x3F9
        cm_girl,         // constant 0x3FA
        cab_rb01,        // constant 0x3FB
        cab_rb02,        // constant 0x3FC
        cab_rinrin01,        // constant 0x3FD
        cab_rinrin02,        // constant 0x3FE
        oyajigari,       // constant 0x3FF
        obj_pole,        // constant 0x400
        housho,      // constant 0x401
        misono,      // constant 0x402
        saiki,       // constant 0x403
        nakanowtr,       // constant 0x404
        mishima,         // constant 0x405
        tiger01,         // constant 0x406
        arm_money,       // constant 0x407
        arm_cake,        // constant 0x408
        arm_bin,         // constant 0x409
        arm_rose,        // constant 0x40A
        arm_gun_dynamite,        // constant 0x40B
        arm_bowl,        // constant 0x40C
        arm_shield,      // constant 0x40D
        arm_card,        // constant 0x40E
        jyk_pws,         // constant 0x40F
        jyk_crn,         // constant 0x410
        arm_whip,        // constant 0x411
        robo_nrm,        // constant 0x412
        chinatsu,        // constant 0x413
        nanba_enem,      // constant 0x414
        han_enem,        // constant 0x415
        arm_gun_bowgun,      // constant 0x416
        cat01_inside,        // constant 0x417
        cat02_inside,        // constant 0x418
        cat03_inside,        // constant 0x419
        cat04_inside,        // constant 0x41A
        cat05_inside,        // constant 0x41B
        door_metal_outside,      // constant 0x41C
    };
}
