using System;
using System.Collections.Generic;

namespace DragonEngineLibrary
{
    public enum CharacterBoneType : uint
    {
        invalid,         // constant 0x0
        ck,      // constant 0x1
        cm,      // constant 0x2
        cn,      // constant 0x3
        co,      // constant 0x4
        cp,      // constant 0x5
        cw,      // constant 0x6
        cx,      // constant 0x7
        ca,      // constant 0x8
        octopus,         // constant 0x9
        mouse,       // constant 0xA
        suzume,      // constant 0xB
        kamome,      // constant 0xC
        cat_auth,        // constant 0xD
        cat,         // constant 0xE
        karasu,      // constant 0xF
        kawahagi,        // constant 0x10
        maguro,      // constant 0x11
        anago,       // constant 0x12
        karei,       // constant 0x13
        jellyfish,       // constant 0x14
        hato,        // constant 0x15
        haze,        // constant 0x16
        takaashigani,        // constant 0x17
        siirakansu,      // constant 0x18
        ika,         // constant 0x19
        onikasago,       // constant 0x1A
        ebi,         // constant 0x1B
        madai,       // constant 0x1C
        ryuguu,      // constant 0x1D
        same,        // constant 0x1E
        salmon,      // constant 0x1F
        harisen,         // constant 0x20
        dog,         // constant 0x21
        sirasu,      // constant 0x22
        torafugu,        // constant 0x23
        d00,         // constant 0x24
        d01,         // constant 0x25
        d02,         // constant 0x26
        d03,         // constant 0x27
        d05,         // constant 0x28
        d06,         // constant 0x29
        d07,         // constant 0x2A
        d08,         // constant 0x2B
        d09,         // constant 0x2C
        d10,         // constant 0x2D
        d11,         // constant 0x2E
        d12,         // constant 0x2F
        d13,         // constant 0x30
        d14,         // constant 0x31
        d15,         // constant 0x32
        d17,         // constant 0x33
        d18,         // constant 0x34
        d19,         // constant 0x35
        d20,         // constant 0x36
        d23,         // constant 0x37
        d24,         // constant 0x38
        d26,         // constant 0x39
        d32,         // constant 0x3A
        d37,         // constant 0x3B
        d38,         // constant 0x3C
        d46,         // constant 0x3D
        d47,         // constant 0x3E
        megalodon,       // constant 0x3F
        kimono,      // constant 0x40
        longcoat,        // constant 0x41
        longcoat2,       // constant 0x42
        tiger,       // constant 0x43
        arowana,         // constant 0x44
        kingyo,      // constant 0x45
        kuidaore,        // constant 0x46
        yagami,      // constant 0x47
        judge_cw,        // constant 0x48
        majimatowel,         // constant 0x49
        caba,        // constant 0x4A
        kimono_judge,        // constant 0x4B
        glasses_judge,       // constant 0x4C
        raincoat,        // constant 0x4D
        longhair,        // constant 0x4E
        nishikigoi,      // constant 0x4F
        koi,         // constant 0x50
        kame,        // constant 0x51
        longhair_fix,        // constant 0x52
        JK_skirt,        // constant 0x53
        LOD4,        // constant 0x54
        bear,        // constant 0x55
        horse,       // constant 0x56
        crayfish,        // constant 0x57
        cleanrobot,      // constant 0x58
        niwatori,        // constant 0x59
        chimpanzee,      // constant 0x5A
        cd,      // constant 0x5B
        excavator,       // constant 0x5C
        kamurop,         // constant 0x5D
        cranetruck,      // constant 0x5E
        dragon,      // constant 0x5F
        dragon_small,        // constant 0x60
        dragon_big,      // constant 0x61
        num,         // constant 0x62
    };
}
