using System;

namespace DragonEngineLibrary
{
    public enum CharacterNPCListID : uint
    {
        invalid,         // constant 0x0
        k_m_young_suit,      // constant 0x1
        k_m_student,         // constant 0x2
        k_m_yakuza,      // constant 0x3
        k_m_chinpira,        // constant 0x4
        k_f_young_suit,      // constant 0x5
        k_m_middle_suit,         // constant 0x6
        k_m_old_suit,        // constant 0x7
        k_m_host,        // constant 0x8
        k_f_middle_suit,         // constant 0x9
        k_f_student,         // constant 0xA
        k_e_chinpira,        // constant 0xB
        k_e_china_yakuza,        // constant 0xC
        k_e_host,        // constant 0xD
        k_e_yakuza,      // constant 0xE
        k_m_mob_young,       // constant 0xF
        k_m_mob_midle,       // constant 0x10
        k_f_mob_young,       // constant 0x11
        k_f_mob_midle,       // constant 0x12
        k_m_suit,        // constant 0x13
        k_m_barker,      // constant 0x14
        k_m_drunk,       // constant 0x15
        k_m_homeless,        // constant 0x16
        k_m_worker,      // constant 0x17
        k_m_casual,      // constant 0x18
        k_f_suit,        // constant 0x19
        k_f_caba,        // constant 0x1A
        k_f_ol,      // constant 0x1B
        k_f_casual,      // constant 0x1C
        cat,         // constant 0x1D
        k_e_yakuza_nml,      // constant 0x1E
        k_e_yakuza_fat,      // constant 0x1F
        k_e_yakuza_mus,      // constant 0x20
        k_e_chinpira_nml,        // constant 0x21
        k_e_chinpira_fat,        // constant 0x22
        k_e_chinpira_mus,        // constant 0x23
        k_e_teamer_nml,      // constant 0x24
        k_e_teamer_fat,      // constant 0x25
        k_e_teamer_mus,      // constant 0x26
        f_hact_caba,         // constant 0x27
        o_m_suit,        // constant 0x28
        o_m_drunk,       // constant 0x29
        o_m_shipyard,        // constant 0x2A
        o_m_worker,      // constant 0x2B
        o_m_casual,      // constant 0x2C
        o_m_student,         // constant 0x2D
        o_f_suit,        // constant 0x2E
        o_f_ol,      // constant 0x2F
        o_f_casual,      // constant 0x30
        o_f_student,         // constant 0x31
        k_e_yakuza_saio_nml,         // constant 0x32
        k_e_yakuza_saio_fat,         // constant 0x33
        k_e_yakuza_saio_mus,         // constant 0x34
        o_e_yakuza_nml,      // constant 0x35
        o_e_yakuza_fat,      // constant 0x36
        o_e_yakuza_mus,      // constant 0x37
        o_e_narazumono_nml,      // constant 0x38
        o_e_narazumono_fat,      // constant 0x39
        o_e_narazumono_mus,      // constant 0x3A
        o_e_waru_nml,        // constant 0x3B
        o_e_waru_fat,        // constant 0x3C
        o_e_waru_mus,        // constant 0x3D
        k_e_tojo_nml,        // constant 0x3E
        k_e_tojo_fat,        // constant 0x3F
        k_e_tojo_mus,        // constant 0x40
        k_e_jin_nml,         // constant 0x41
        k_e_jin_fat,         // constant 0x42
        k_e_jin_mus,         // constant 0x43
        o_e_yomei_nml,       // constant 0x44
        o_e_yomei_fat,       // constant 0x45
        o_e_yomei_mus,       // constant 0x46
        k_mob_driver,        // constant 0x47
        o_mob_driver,        // constant 0x48
        k_mob_indoor,        // constant 0x49
        o_mob_indoor,        // constant 0x4A
        k_mob_batting_center,        // constant 0x4B
        k_mob_office,        // constant 0x4C
        k_mob_m_indoor_nobag,        // constant 0x4D
        k_mob_f_indoor_nobag,        // constant 0x4E
        o_mob_m_indoor_nobag,        // constant 0x4F
        o_mob_f_indoor_nobag,        // constant 0x50
        apple_hostess,       // constant 0x51
        k_mob_m_visitor,         // constant 0x52
        k_mob_m_businessman,         // constant 0x53
        k_mob_f_businessman,         // constant 0x54
        k_m_kouji,       // constant 0x55
        o_e_yomei_black,         // constant 0x56
        k_f_young_casual,        // constant 0x57
        police,      // constant 0x58
        tojo,        // constant 0x59
        tojo_mo,         // constant 0x5A
        tgj_mob,         // constant 0x5B
        s_m_suit,        // constant 0x5C
        s_m_barker,      // constant 0x5D
        s_m_drunk,       // constant 0x5E
        s_m_homeless,        // constant 0x5F
        s_m_worker,      // constant 0x60
        s_m_casual,      // constant 0x61
        s_m_student,         // constant 0x62
        s_m_tissue,      // constant 0x63
        s_f_ol,      // constant 0x64
        s_f_caba,        // constant 0x65
        s_f_casual,      // constant 0x66
        s_f_student,         // constant 0x67
        s_f_tissue,      // constant 0x68
        s_mob_indoor,        // constant 0x69
        s_e_yakuza_nml,      // constant 0x6A
        s_e_yakuza_fat,      // constant 0x6B
        s_e_yakuza_mus,      // constant 0x6C
        s_e_chinpira_nml,        // constant 0x6D
        s_e_chinpira_fat,        // constant 0x6E
        s_e_chinpira_mus,        // constant 0x6F
        s_e_teamer_nml,      // constant 0x70
        s_e_teamer_fat,      // constant 0x71
        s_e_teamer_mus,      // constant 0x72
        e_gold_nml,      // constant 0x73
        e_gold_fat,      // constant 0x74
        e_gold_mus,      // constant 0x75
        j_e_matsugane_nml,       // constant 0x76
        j_e_matsugane_fat,       // constant 0x77
        j_e_matsugane_mus,       // constant 0x78
        j_e_kyoreikai_nml,       // constant 0x79
        j_e_kyoreikai_fat,       // constant 0x7A
        j_e_kyoreikai_mus,       // constant 0x7B
        k_m_young_suit_nobag,        // constant 0x7C
        k_m_middle_suit_nobag,       // constant 0x7D
        k_f_young_suit_nobag,        // constant 0x7E
        k_f_mob_midle_nobag,         // constant 0x7F
        k_f_young_casual_nobag,      // constant 0x80
        s_m_suit_nobag,      // constant 0x81
        s_f_ol_nobag,        // constant 0x82
        s_f_caba_nobag,      // constant 0x83
        sai_public,      // constant 0x84
        k_m_casual_sit,      // constant 0x85
        k_f_casual_sit,      // constant 0x86
        s_m_casual_sit,      // constant 0x87
        s_f_casual_sit,      // constant 0x88
        j_m_sk35_mathcomi,       // constant 0x89
        j_f_sk35_mathcomi,       // constant 0x8A
        j_m_sk35_fan,        // constant 0x8B
        j_f_sk35_fan,        // constant 0x8C
        fishing_pond_fish,       // constant 0x8D
        y_m_businessman,         // constant 0x8E
        y_m_public,      // constant 0x8F
        y_w_businessman,         // constant 0x90
        y_w_public,      // constant 0x91
        y_m_biz_01,      // constant 0x92
        y_m_biz_02,      // constant 0x93
        y_m_biz_03,      // constant 0x94
        y_m_drk_01,      // constant 0x95
        y_m_drk_02,      // constant 0x96
        y_m_drk_03,      // constant 0x97
        y_m_hol_01,      // constant 0x98
        y_m_hol_02,      // constant 0x99
        y_m_hol_03,      // constant 0x9A
        y_m_hol_04,      // constant 0x9B
        y_m_hol_05,      // constant 0x9C
        y_m_hos_01,      // constant 0x9D
        y_m_hos_02,      // constant 0x9E
        y_m_hos_03,      // constant 0x9F
        y_m_hos_04,      // constant 0xA0
        y_m_chp_01,      // constant 0xA1
        y_m_chp_02,      // constant 0xA2
        y_m_chp_03,      // constant 0xA3
        y_m_fig_01,      // constant 0xA4
        y_m_fig_02,      // constant 0xA5
        y_m_fig_03,      // constant 0xA6
        y_m_fig_04,      // constant 0xA7
        y_m_gag_01,      // constant 0xA8
        y_m_gag_02,      // constant 0xA9
        y_m_gag_03,      // constant 0xAA
        y_m_gag_04,      // constant 0xAB
        y_m_gag_05,      // constant 0xAC
        y_m_trb_01,      // constant 0xAD
        y_m_trb_02,      // constant 0xAE
        y_m_trb_03,      // constant 0xAF
        y_m_trb_04,      // constant 0xB0
        y_m_gun_01,      // constant 0xB1
        y_m_gun_02,      // constant 0xB2
        y_m_gun_03,      // constant 0xB3
        y_m_gun_04,      // constant 0xB4
        y_m_toj_01,      // constant 0xB5
        y_m_omi_01,      // constant 0xB6
        y_m_ykz_01,      // constant 0xB7
        y_m_ykz_02,      // constant 0xB8
        y_m_ykz_03,      // constant 0xB9
        y_m_ykz_04,      // constant 0xBA
        y_m_ykz_05,      // constant 0xBB
        y_m_wrk_01,      // constant 0xBC
        y_m_wrk_02,      // constant 0xBD
        y_m_wrk_03,      // constant 0xBE
        y_m_rbb_01,      // constant 0xBF
        y_m_rbb_02,      // constant 0xC0
        y_m_rbb_03,      // constant 0xC1
        y_m_chn_01,      // constant 0xC2
        y_m_chn_02,      // constant 0xC3
        y_m_chn_03,      // constant 0xC4
        y_m_kun_01,      // constant 0xC5
        y_m_kun_02,      // constant 0xC6
        y_m_kun_03,      // constant 0xC7
        y_m_kun_04,      // constant 0xC8
        y_m_cok_01,      // constant 0xC9
        y_m_cok_02,      // constant 0xCA
        y_m_cok_03,      // constant 0xCB
        y_m_jug_01,      // constant 0xCC
        y_m_jug_02,      // constant 0xCD
        y_m_jug_03,      // constant 0xCE
        y_m_jug_04,      // constant 0xCF
        y_m_phk_01,      // constant 0xD0
        y_m_phk_02,      // constant 0xD1
        y_m_phk_03,      // constant 0xD2
        y_m_phk_04,      // constant 0xD3
        y_m_phk_05,      // constant 0xD4
        y_m_doc_01,      // constant 0xD5
        y_m_doc_02,      // constant 0xD6
        y_m_doc_03,      // constant 0xD7
        y_m_acp_01,      // constant 0xD8
        y_m_acp_02,      // constant 0xD9
        y_m_acp_03,      // constant 0xDA
        y_m_acp_04,      // constant 0xDB
        y_m_fod_01,      // constant 0xDC
        y_m_fod_02,      // constant 0xDD
        y_m_fod_03,      // constant 0xDE
        y_m_hit_01,      // constant 0xDF
        y_m_hit_02,      // constant 0xE0
        y_m_hit_03,      // constant 0xE1
        y_m_amy_01,      // constant 0xE2
        y_m_amy_02,      // constant 0xE3
        y_m_amy_03,      // constant 0xE4
        y_m_amy_04,      // constant 0xE5
        y_m_bou_01,      // constant 0xE6
        y_m_bou_02,      // constant 0xE7
        y_m_bou_03,      // constant 0xE8
        y_m_bou_04,      // constant 0xE9
        y_m_frg_01,      // constant 0xEA
        y_m_frg_02,      // constant 0xEB
        y_m_frg_03,      // constant 0xEC
        y_m_frg_04,      // constant 0xED
        y_m_hac_01,      // constant 0xEE
        y_m_hac_02,      // constant 0xEF
        y_m_hac_03,      // constant 0xF0
        y_m_hac_04,      // constant 0xF1
        y_m_sel_01,      // constant 0xF2
        y_m_sel_02,      // constant 0xF3
        y_m_sel_03,      // constant 0xF4
        y_m_con_01,      // constant 0xF5
        y_m_con_02,      // constant 0xF6
        y_m_con_03,      // constant 0xF7
        y_m_con_04,      // constant 0xF8
        y_m_rap_01,      // constant 0xF9
        y_m_rap_02,      // constant 0xFA
        y_m_rap_03,      // constant 0xFB
        y_m_rap_04,      // constant 0xFC
        y_m_sct_01,      // constant 0xFD
        y_m_sct_02,      // constant 0xFE
        y_m_sct_03,      // constant 0xFF
        y_m_sct_04,      // constant 0x100
        y_m_sct_05,      // constant 0x101
        y_m_ars_01,      // constant 0x102
        y_m_ars_02,      // constant 0x103
        y_m_ars_03,      // constant 0x104
        y_m_thg_01,      // constant 0x105
        y_m_thg_02,      // constant 0x106
        y_m_thg_03,      // constant 0x107
        y_m_bxe_01,      // constant 0x108
        y_m_bxe_02,      // constant 0x109
        y_m_bxe_03,      // constant 0x10A
        y_m_zea_01,      // constant 0x10B
        y_m_zea_02,      // constant 0x10C
        y_m_zea_03,      // constant 0x10D
        y_m_zea_04,      // constant 0x10E
        y_m_zea_05,      // constant 0x10F
        y_m_psy_01,      // constant 0x110
        y_m_psy_02,      // constant 0x111
        y_m_gad_01,      // constant 0x112
        y_m_gad_02,      // constant 0x113
        y_m_gad_03,      // constant 0x114
        y_m_bbf_01,      // constant 0x115
        y_m_bbf_02,      // constant 0x116
        y_m_bbf_03,      // constant 0x117
        y_m_bbp_01,      // constant 0x118
        y_m_bbp_02,      // constant 0x119
        y_m_bbp_03,      // constant 0x11A
        y_m_cln_01,      // constant 0x11B
        y_m_cln_02,      // constant 0x11C
        y_m_cln_03,      // constant 0x11D
        y_m_cln_04,      // constant 0x11E
        y_m_rep_01,      // constant 0x11F
        y_m_rep_02,      // constant 0x120
        y_m_rep_03,      // constant 0x121
        y_m_rep_04,      // constant 0x122
        y_m_skt_01,      // constant 0x123
        y_m_skt_02,      // constant 0x124
        y_m_skt_03,      // constant 0x125
        y_m_hpp_01,      // constant 0x126
        y_m_hpp_02,      // constant 0x127
        y_m_hpp_03,      // constant 0x128
        y_m_snw_01,      // constant 0x129
        y_m_snw_02,      // constant 0x12A
        y_m_snw_03,      // constant 0x12B
        y_m_wri_01,      // constant 0x12C
        y_m_wri_02,      // constant 0x12D
        y_m_wri_03,      // constant 0x12E
        y_m_hkc_01,      // constant 0x12F
        y_m_hkc_02,      // constant 0x130
        y_m_hkc_03,      // constant 0x131
        y_m_reg_01,      // constant 0x132
        y_m_reg_02,      // constant 0x133
        y_m_reg_03,      // constant 0x134
        y_m_reg_04,      // constant 0x135
        y_m_dol_01,      // constant 0x136
        y_m_dol_02,      // constant 0x137
        y_m_sli_01,      // constant 0x138
        y_m_sli_02,      // constant 0x139
        y_m_sli_03,      // constant 0x13A
        y_m_zom_01,      // constant 0x13B
        y_m_zom_02,      // constant 0x13C
        y_m_zom_03,      // constant 0x13D
        y_m_exp_01,      // constant 0x13E
        y_m_exp_02,      // constant 0x13F
        y_m_exp_03,      // constant 0x140
        y_m_cat_01,      // constant 0x141
        y_m_cat_02,      // constant 0x142
        y_m_cat_03,      // constant 0x143
        y_m_pig_01,      // constant 0x144
        y_m_pig_02,      // constant 0x145
        y_m_pig_03,      // constant 0x146
        y_m_pig_04,      // constant 0x147
        y_m_brd_01,      // constant 0x148
        y_m_van_01,      // constant 0x149
        y_m_van_02,      // constant 0x14A
        y_m_van_03,      // constant 0x14B
        y_m_brt_01,      // constant 0x14C
        y_m_brt_02,      // constant 0x14D
        y_m_brt_03,      // constant 0x14E
        y_m_dem_01,      // constant 0x14F
        y_m_dem_02,      // constant 0x150
        y_m_dem_03,      // constant 0x151
        y_m_smk_01,      // constant 0x152
        y_m_smk_02,      // constant 0x153
        y_m_smk_03,      // constant 0x154
        y_m_tro_01,      // constant 0x155
        y_m_tro_02,      // constant 0x156
        y_m_tro_03,      // constant 0x157
        y_m_tro_04,      // constant 0x158
        y_m_inv_01,      // constant 0x159
        y_m_inv_02,      // constant 0x15A
        y_m_inv_03,      // constant 0x15B
        y_m_prp_01,      // constant 0x15C
        y_m_prp_02,      // constant 0x15D
        y_m_prp_03,      // constant 0x15E
        y_m_nrd_01,      // constant 0x15F
        y_m_nrd_02,      // constant 0x160
        y_m_nrd_03,      // constant 0x161
        y_m_mas_01,      // constant 0x162
        y_m_mas_02,      // constant 0x163
        y_m_mas_03,      // constant 0x164
        y_m_cut_01,      // constant 0x165
        y_m_cut_02,      // constant 0x166
        y_m_cut_03,      // constant 0x167
        y_m_gbg_01,      // constant 0x168
        y_m_gbg_02,      // constant 0x169
        y_m_gbg_03,      // constant 0x16A
        y_m_spr_01,      // constant 0x16B
        y_m_spr_02,      // constant 0x16C
        y_m_spr_03,      // constant 0x16D
        y_m_buz_01,      // constant 0x16E
        y_m_buz_02,      // constant 0x16F
        y_m_buz_03,      // constant 0x170
        y_m_ltb_01,      // constant 0x171
        y_m_ltb_02,      // constant 0x172
        y_m_ltb_03,      // constant 0x173
        y_m_swg_01,      // constant 0x174
        y_m_swg_02,      // constant 0x175
        y_m_swg_03,      // constant 0x176
        y_m_str_01,      // constant 0x177
        y_m_str_02,      // constant 0x178
        y_m_str_03,      // constant 0x179
        y_m_drk_04,      // constant 0x17A
        y_m_chp_04,      // constant 0x17B
        y_m_wrk_04,      // constant 0x17C
        y_m_rbb_04,      // constant 0x17D
        y_m_fod_04,      // constant 0x17E
        y_m_hit_04,      // constant 0x17F
        y_m_bxe_04,      // constant 0x180
        y_m_psy_03,      // constant 0x181
        y_m_gad_04,      // constant 0x182
        k_m_external_sit,        // constant 0x183
        s_m_external_sit,        // constant 0x184
        y_m_external_sit,        // constant 0x185
        k_f_external_sit,        // constant 0x186
        s_f_external_sit,        // constant 0x187
        y_f_external_sit,        // constant 0x188
        y_m_young_suit,      // constant 0x189
        y_m_young_suit_nobag,        // constant 0x18A
        y_m_middle_suit,         // constant 0x18B
        y_m_middle_suit_nobag,       // constant 0x18C
        y_m_student,         // constant 0x18D
        y_m_casual,      // constant 0x18E
        y_f_young_suit,      // constant 0x18F
        y_f_young_suit_nobag,        // constant 0x190
        y_f_middle_suit,         // constant 0x191
        y_f_student,         // constant 0x192
        y_f_casual,      // constant 0x193
        y_f_young_casual,        // constant 0x194
        y_f_young_casual_nobag,      // constant 0x195
        y_f_ol,      // constant 0x196
        y_m_mob_young,       // constant 0x197
        y_m_mob_midle,       // constant 0x198
        y_f_mob_young,       // constant 0x199
        y_f_mob_midle,       // constant 0x19A
        y_f_mob_midle_nobag,         // constant 0x19B
        y_chinese,       // constant 0x19C
        y_korean,        // constant 0x19D
        y_homeless,      // constant 0x19E
        y_mob_driver,        // constant 0x19F
        y_mob_indoor,        // constant 0x1A0
        y_m_chinese,         // constant 0x1A1
        y_f_chinese,         // constant 0x1A2
        y_m_korean,      // constant 0x1A3
        y_f_korean,      // constant 0x1A4
        y_m_ltb_01A,         // constant 0x1A5
        y_m_ltb_02A,         // constant 0x1A6
        y_m_ltb_03A,         // constant 0x1A7
        s_f_suit,        // constant 0x1A8
        s_f_young_casual,        // constant 0x1A9
        s_f_young_suit,      // constant 0x1AA
        s_m_mob_young,       // constant 0x1AB
        y_f_suit,        // constant 0x1AC
        y_m_homeless,        // constant 0x1AD
        y_m_suit,        // constant 0x1AE
        y_m_exp_01A,         // constant 0x1AF
        y_m_exp_02A,         // constant 0x1B0
        y_m_exp_03A,         // constant 0x1B1
        y_m_hac_01A,         // constant 0x1B2
        y_m_hac_02A,         // constant 0x1B3
        y_m_hac_03A,         // constant 0x1B4
        y_m_barker,      // constant 0x1B5
        y_wz,        // constant 0x1B6
        s_oumi,      // constant 0x1B7
        y_sanretsu,      // constant 0x1B8
    };
}
