using System;

namespace DragonEngineLibrary
{
    public enum EffectEventCharaID : uint
    {
        invalid,		 // constant 0x0
        H23540_SP_KICK_L_LV1,		 // constant 0x1
        H23540_SP_KICK_L_LV2,		 // constant 0x2
        H23540_SP_KICK_L_LV3,		 // constant 0x3
        H23550_SP_KICK_R_LV1,		 // constant 0x4
        H23550_SP_KICK_R_LV2,		 // constant 0x5
        H23550_SP_KICK_R_LV3,		 // constant 0x6
        H23560_SP_PUNCH_L_LV1,		 // constant 0x7
        H23560_SP_PUNCH_L_LV2,		 // constant 0x8
        H23560_SP_PUNCH_L_LV3,		 // constant 0x9
        H23570_SP_PUNCH_R_LV1,		 // constant 0xA
        H23570_SP_PUNCH_R_LV2,		 // constant 0xB
        H23570_SP_PUNCH_R_LV3,		 // constant 0xC
        H23620_SP_KICK_F_LV1,		 // constant 0xD
        H23620_SP_KICK_F_LV2,		 // constant 0xE
        H23620_SP_KICK_F_LV3,		 // constant 0xF
        H23630_SP_KICK_DWN_R_LV1,		 // constant 0x10
        H23630_SP_KICK_DWN_R_LV2,		 // constant 0x11
        H23630_SP_KICK_DWN_R_LV3,		 // constant 0x12
        H23640_SP_UPPER_F_LV1,		 // constant 0x13
        H23640_SP_UPPER_F_LV2,		 // constant 0x14
        H23640_SP_UPPER_F_LV3,		 // constant 0x15
        H23650_SP_PUNCH_F_LV1,		 // constant 0x16
        H23650_SP_PUNCH_F_LV2,		 // constant 0x17
        H23650_SP_PUNCH_F_LV3,		 // constant 0x18
        OgrefHeatAuraKr00,		 // constant 0x19
        OgrefHeatAuraKr01,		 // constant 0x1A
        OgrefHeatAuraKr02,		 // constant 0x1B
        OgrefHeatAuraNpc_ed,		 // constant 0x1C
        OgrefHeatAuraNpc_lp,		 // constant 0x1D
        OgrefHeatAuraNpc_st,		 // constant 0x1E
        OgrefHeatChargeKr_ed,		 // constant 0x1F
        OgrefHeatChargeKr_lp,		 // constant 0x20
        OgrefHeatChargeKr_st,		 // constant 0x21
        OgrefHeatChargeKr02,		 // constant 0x22
        OgrefHeatChargeKr03,		 // constant 0x23
        OgrefHeatAuraBossN00,		 // constant 0x24
        OgrefHeatAuraBossN01,		 // constant 0x25
        OgrefHeatAuraBossN02,		 // constant 0x26
        OgreF_ClanBattleDyingVanish,		 // constant 0x27
        OgreF_ClanBattleGuard,		 // constant 0x28
        OgreF_ClanBattleHit,		 // constant 0x29
        OgreF_ClanBattleKumichoAuraE,		 // constant 0x2A
        OgreF_ClanBattleKumichoAuraP,		 // constant 0x2B
        OgreF_ClanBattleSklAllRange,		 // constant 0x2C
        OgreF_ClanBattleSklFrontArc,		 // constant 0x2D
        OgreF_ClanBattleSklFrontLong,		 // constant 0x2E
        OgreF_ClanBattleSklFrontShrt,		 // constant 0x2F
        OgreF_CabaGood,		 // constant 0x30
        OgreF_CabaVeryGood,		 // constant 0x31
        OgrefHvyChg_lp,		 // constant 0x32
        OgreF_ClanBattleCozyCrash,		 // constant 0x33
        OgreF_ClanBattleIyashi,		 // constant 0x34
        OgreF_ClanBattleMuscle,		 // constant 0x35
        OgreF_ClanBattleShinIyashi,		 // constant 0x36
        OgrefHvyChg_ed,		 // constant 0x37
        OgrefHvyChg_st,		 // constant 0x38
        OgreF_Btl12_070Smoke,		 // constant 0x39
        OgreF_ClnBtlSklRngEnemy,		 // constant 0x3A
        OgreF_ClnBtlSklRngForward,		 // constant 0x3B
        OgreF_ClnBtlSklRngFriend,		 // constant 0x3C
        OgreF_ClnBtlSklRngNarLong,		 // constant 0x3D
        OgreF_ClnBtlSklRngRound,		 // constant 0x3E
        OgreF_ClnBtlSklRngSelf,		 // constant 0x3F
        OgreF_ClnBtlSklRngWidShort,		 // constant 0x40
        OgreF_ClanBattleGoutai,		 // constant 0x41
        OgreF_ClanBattleMuteki,		 // constant 0x42
        OgreF_ClanBattleSuperArmor,		 // constant 0x43
        OgreF_ClanBattleHitE,		 // constant 0x44
        OgrefHeatKaraokeSt,		 // constant 0x45
        H23551_SP_KICK_R_01_LV1,		 // constant 0x46
        H23551_SP_KICK_R_01_LV2,		 // constant 0x47
        H23551_SP_KICK_R_01_LV3,		 // constant 0x48
        Lexus2_Chg_lv1_ok,		 // constant 0x49
        Lexus2_Chg_lv2_doing,		 // constant 0x4A
        Lexus2_Chg_lv2_ok,		 // constant 0x4B
        Lexus2_Chg_lv3_doing,		 // constant 0x4C
        Lexus2_Chg_lv3_keeping,		 // constant 0x4D
        Lexus2_Chg_lv3_ok,		 // constant 0x4E
        Lexus2_DmgFire,		 // constant 0x4F
        Lexus2_DmgElec,		 // constant 0x50
        Lexus2_Chg_doing,		 // constant 0x51
        JudgeHeatAuraYgmEnb_ed,		 // constant 0x52
        JudgeHeatAuraYgmEnb_lp,		 // constant 0x53
        JudgeHeatAuraYgmEnb_st,		 // constant 0x54
        JudgeHeatAuraYgmIsn_ed,		 // constant 0x55
        JudgeHeatAuraYgmIsn_lp,		 // constant 0x56
        JudgeHeatAuraYgmIsn_st,		 // constant 0x57
        JudgeHeatChargeYgmEnb_st,		 // constant 0x58
        JudgeHeatChargeYgmIsn_st,		 // constant 0x59
        JudgePsclSwitchYgmEnb_st,		 // constant 0x5A
        JudgePsclSwitchYgmIsn_st,		 // constant 0x5B
        JudgeBattleEffectPreset,		 // constant 0x5C
        JudgeGaikouYgm_st,		 // constant 0x5D
        JudgeNaikouYgm_st,		 // constant 0x5E
        lexus2_island_yen10000_M,		 // constant 0x5F
        lexus2_island_yen10000_S,		 // constant 0x60
        lexus2_island_yen10000_H,		 // constant 0x61
        Lexus2_Chg_keeping,		 // constant 0x62
        Lexus2_Chg_keep_start,		 // constant 0x63
        Lexus2_Chg_OK_S,		 // constant 0x64
        Lexus2_Chg_OK_T,		 // constant 0x65
        Lexus2_Chg_start,		 // constant 0x66
        JudgePsclSwitchYgmEnb_Nst,		 // constant 0x67
        JudgePsclSwitchYgmIsn_Nst,		 // constant 0x68
        Lexus2_renkeguard_ok,		 // constant 0x69
        Shadow_target_blue_loop,		 // constant 0x6A
        Shadow_target_blue_start,		 // constant 0x6B
        Shadow_target_red_loop,		 // constant 0x6C
        Shadow_target_red_start,		 // constant 0x6D
        Shadow_target_yellow_loop,		 // constant 0x6E
        Shadow_target_yellow_start,		 // constant 0x6F
        JudgeSgrkMgEnemyA,		 // constant 0x70
        JudgeSgrkMgGiftA,		 // constant 0x71
        JudgeSgrkMgTaxiA,		 // constant 0x72
        JudgeSgrkMgYgmA,		 // constant 0x73
        chase_drinkAura,		 // constant 0x74
        lexus2_migawariishi,		 // constant 0x75
        Lexus2_Dmgthumbing,		 // constant 0x76
        Lexus2_ClanSkillChargedAuraE,		 // constant 0x77
        Lexus2_ClanSkillChargedAuraP,		 // constant 0x78
        Lexus2_ClanSkillMuteki,		 // constant 0x79
        Lexus2_ClanSkillSpeedUp,		 // constant 0x7A
        JudgeSgrkMgYgmGOvr,		 // constant 0x7B
        JudgeSgrkMgYgmGoal,		 // constant 0x7C
        Lexus2_Caba_Highlight,		 // constant 0x7D
        chase_accelAura,		 // constant 0x7E
        Lx2_Aura_kouchi_lp,		 // constant 0x7F
        Shadow_target_blue_eye,		 // constant 0x80
        Shadow_target_red_eye,		 // constant 0x81
        Shadow_target_yellow_eye,		 // constant 0x82
        JudgeSgrkMgEnemyGOvr,		 // constant 0x83
        JudgeSgrkMgYgmEnb,		 // constant 0x84
        JudgeSgrkMgYgmIsn,		 // constant 0x85
        JudgeSgrkMgYgmWarp,		 // constant 0x86
        JudgeSgrkMgEnemyBori,		 // constant 0x87
        JudgeSgrkMgEnemyHng,		 // constant 0x88
        JudgeSgrkMgEnemyMna,		 // constant 0x89
        JudgeSgrkMgEnemyNin,		 // constant 0x8A
        JudgeSgrkMgEnemyTigr,		 // constant 0x8B
        JudgeSgrkStgTypeA,		 // constant 0x8C
        JudgeSgrkStgTypeB,		 // constant 0x8D
        JudgeSgrkStgTypeC,		 // constant 0x8E
        JudgeBossAuraMur_ed,		 // constant 0x8F
        JudgeBossAuraMur_lp,		 // constant 0x90
        JudgeBossAuraMur_st,		 // constant 0x91
        JudgeBossAuraHig_ed,		 // constant 0x92
        JudgeBossAuraHig_lp,		 // constant 0x93
        JudgeBossAuraHig_st,		 // constant 0x94
        JudgeBossAuraKng_ed,		 // constant 0x95
        JudgeBossAuraKng_lp,		 // constant 0x96
        JudgeBossAuraKng_st,		 // constant 0x97
        JudgeBossAuraOza_ed,		 // constant 0x98
        JudgeBossAuraOza_lp,		 // constant 0x99
        JudgeBossAuraOza_st,		 // constant 0x9A
        JudgeBossAuraSio_ed,		 // constant 0x9B
        JudgeBossAuraSio_lp,		 // constant 0x9C
        JudgeBossAuraSio_st,		 // constant 0x9D
        JudgeBossAuraHam_ed,		 // constant 0x9E
        JudgeBossAuraHam_lp,		 // constant 0x9F
        JudgeBossAuraHam_st,		 // constant 0xA0
        JudgeBossAuraHon_ed,		 // constant 0xA1
        JudgeBossAuraHon_lp,		 // constant 0xA2
        JudgeBossAuraHon_st,		 // constant 0xA3
        JudgeBossAuraKas_ed,		 // constant 0xA4
        JudgeBossAuraKas_lp,		 // constant 0xA5
        JudgeBossAuraKas_st,		 // constant 0xA6
        JudgeBossAuraKog_ed,		 // constant 0xA7
        JudgeBossAuraKog_lp,		 // constant 0xA8
        JudgeBossAuraKog_st,		 // constant 0xA9
        JudgeBossAuraKur_ed,		 // constant 0xAA
        JudgeBossAuraKur_lp,		 // constant 0xAB
        JudgeBossAuraKur_st,		 // constant 0xAC
        JudgeBossAuraMas_ed,		 // constant 0xAD
        JudgeBossAuraMas_lp,		 // constant 0xAE
        JudgeBossAuraMas_st,		 // constant 0xAF
        JudgeBossAuraSak_ed,		 // constant 0xB0
        JudgeBossAuraSak_lp,		 // constant 0xB1
        JudgeBossAuraSak_st,		 // constant 0xB2
        JudgeBossAuraStk_ed,		 // constant 0xB3
        JudgeBossAuraStk_lp,		 // constant 0xB4
        JudgeBossAuraStk_st,		 // constant 0xB5
        JudgeBossAuraTnf_ed,		 // constant 0xB6
        JudgeBossAuraTnf_lp,		 // constant 0xB7
        JudgeBossAuraTnf_st,		 // constant 0xB8
        JudgeBossAuraHnti_lp,		 // constant 0xB9
        JudgeSideAuraHentai_ed,		 // constant 0xBA
        JudgeSideAuraHentai_lp,		 // constant 0xBB
        JudgeSideAuraHentai_st,		 // constant 0xBC
        JudgeSgrkStgKamuroA,		 // constant 0xBD
        JudgeSgrkMgEnemyBlack,		 // constant 0xBE
        JudgeSgrkMgEnemyGold,		 // constant 0xBF
        judgehactmaipreset,		 // constant 0xC0
        judgehactsenpreset,		 // constant 0xC1
        ogref_clanbattlesuperarmor,		 // constant 0xC2
        shadow_target_01,		 // constant 0xC3
        JudgeSgrkMgTigGOvr,		 // constant 0xC4
        JudgeGirlFndGood,		 // constant 0xC5
        JudgeGirlFndVeryGood,		 // constant 0xC6
        JudgeGirlFndBad,		 // constant 0xC7
        JudgeSgrkFaceBad,		 // constant 0xC8
        JudgeSgrkFaceGood,		 // constant 0xC9
        JudgeSgrkFaceNormal,		 // constant 0xCA
        JudgeSenyakuTypeA_st,		 // constant 0xCB
        JudgeSgrkMgYgmFever,		 // constant 0xCC
        judge_dmgelec,		 // constant 0xCD
        lexus2_dmgelec,		 // constant 0xCE
        JudgeEnemyBibiri_lp,		 // constant 0xCF
        JudgeEnemyIkari_lp,		 // constant 0xD0
        mahuyu_cheerAura,		 // constant 0xD1
        JudgeFatalChara_lp,		 // constant 0xD2
        JudgeChargeYgmIsn,		 // constant 0xD3
        JudgeSgrkStgTogiElct,		 // constant 0xD4
        JudgeSgrkStgTogiFire,		 // constant 0xD5
        JudgeSgrkStgTogiNml,		 // constant 0xD6
        JudgeSgrkStgAjiagai,		 // constant 0xD7
        JudgeSgrkStgBassen,		 // constant 0xD8
        JudgeSgrkStgDroneVS,		 // constant 0xD9
        JudgeSgrkStgGekijomae,		 // constant 0xDA
        JudgeSgrkStgMTower,		 // constant 0xDB
        JudgeSgrkStgQueenluge,		 // constant 0xDC
        JudgeSgrkStgRarabai,		 // constant 0xDD
        JudgeSgrkStgShowa,		 // constant 0xDE
        JudgeSgrkStgSmileburger,		 // constant 0xDF
        JudgeSgrkStgTikachusha,		 // constant 0xE0
        JudgeAmonBattleBlue,		 // constant 0xE1
        JudgeAmonBattleRed,		 // constant 0xE2
        JudgeSenyakuTypeA_ed,		 // constant 0xE3
        JudgeSenyakuTypeB_ed,		 // constant 0xE4
        JudgeSenyakuTypeB_st,		 // constant 0xE5
        JudgeSenyakuTypeC_ed,		 // constant 0xE6
        JudgeSenyakuTypeC_st,		 // constant 0xE7
        JudgeSenyakuTypeD_ed,		 // constant 0xE8
        JudgeSenyakuTypeD_st,		 // constant 0xE9
        JudgeSenyakuTypeE_ed,		 // constant 0xEA
        JudgeSenyakuTypeE_st,		 // constant 0xEB
        JudgeBossHonFistLight_lp,		 // constant 0xEC
        JudgeSenyakuTypeC2_loop,		 // constant 0xED
        JudgeChargeSTYgmIsn,		 // constant 0xEE
        JudgeSgrkFaceBadBTL,		 // constant 0xEF
        JudgeSgrkFaceBadFver,		 // constant 0xF0
        JudgeSgrkFaceGoodBTL,		 // constant 0xF1
        JudgeSgrkFaceGoodFver,		 // constant 0xF2
        JudgeSgrkFaceNormalBTL,		 // constant 0xF3
        JudgeSgrkFaceNormalFver,		 // constant 0xF4
        YZ_enemy_select_lp,		 // constant 0xF5
        YZ_enemy_select_st,		 // constant 0xF6
        YZ_player_active_st,		 // constant 0xF7
        YZ_enemy_mark_to_P,		 // constant 0xF8
        YZ_frend_coop_st,		 // constant 0xF9
        YZ_player_mark_from_E,		 // constant 0xFA
        YZ_enemy_sli_loop,		 // constant 0xFB
        YZ_DmgFire,		 // constant 0xFC
        YZ_enemy_sli_BTLst,		 // constant 0xFD
        YZ_MG_meigaza_sheepappear,		 // constant 0xFE
        YZ_dmgelec,		 // constant 0xFF
        YZ_Cure_Lv01,		 // constant 0x100
        YZ_Heal_LV2,		 // constant 0x101
        YZ_Heal_LV3,		 // constant 0x102
        YZ_Heal_LV1,		 // constant 0x103
        YZ_Chara_Cange01,		 // constant 0x104
        M_NAN_BTL_TUE_skl_fire01_LV1,		 // constant 0x105
        M_NAN_BTL_TUE_skl_fire01_LV2,		 // constant 0x106
        M_NAN_BTL_TUE_skl_stink01_LV1,		 // constant 0x107
        M_NAN_BTL_TUE_skl_stink01_LV2,		 // constant 0x108
        YZ_Attack_DOWN_st,		 // constant 0x109
        YZ_Attack_UP_lp,		 // constant 0x10A
        YZ_Attack_UP_st,		 // constant 0x10B
        YZ_MGZ_E_sleep01_lp,		 // constant 0x10C
        YZ_Attack_DOWN_lp,		 // constant 0x10D
        YZ_DmgFire_one,		 // constant 0x10E
        YZ_Defense_DOWN_lp,		 // constant 0x10F
        YZ_Defense_DOWN_st,		 // constant 0x110
        YZ_Defense_UP_lp,		 // constant 0x111
        YZ_Defense_UP_st,		 // constant 0x112
        YZ_enemy_vanish,		 // constant 0x113
        YZ_Dexterity_DOWN_lp,		 // constant 0x114
        YZ_Dexterity_DOWN_st,		 // constant 0x115
        YZ_Dexterity_UP_lp,		 // constant 0x116
        YZ_Dexterity_UP_st,		 // constant 0x117
        YZ_Speed_DOWN_lp,		 // constant 0x118
        YZ_Speed_DOWN_st,		 // constant 0x119
        YZ_Speed_UP_lp,		 // constant 0x11A
        YZ_Speed_UP_st,		 // constant 0x11B
        YZ_DRcar_Barrier,		 // constant 0x11C
        YZ_MGZ_bird_cymbal,		 // constant 0x11D
        YZ_Homeless_cure,		 // constant 0x11E
        YZ_Homeless_dash,		 // constant 0x11F
        YZ_MGZ_E_sleep_lush_lp,		 // constant 0x120
        P_ICH_BTL_WPD_skl_hvy_LV1,		 // constant 0x121
        P_ICH_BTL_WPD_skl_hvy_LV2,		 // constant 0x122
        p_ich_btl_wpd_ath_wid_01,		 // constant 0x123
        p_ich_btl_wpd_ath_wid_02,		 // constant 0x124
        YZ_Homeless_zombie,		 // constant 0x125
        YZ_enemy_vanish_lp,		 // constant 0x126
        YZ_Chara_rim_test,		 // constant 0x127
        YZ_MGZ_P_sleep_hit,		 // constant 0x128
        M_NAN_BTL_TUE_skl_hato01_LV1,		 // constant 0x129
        M_NAN_BTL_TUE_skl_hato01_LV2,		 // constant 0x12A
        YZ_Rim_Red01,		 // constant 0x12B
        YZ_Rim_Red02,		 // constant 0x12C
        YZ_Rim_Red03,		 // constant 0x12D
        YZ_MGZ_E_dmg_hit,		 // constant 0x12E
        M_NAN_BTL_TUE_skl_stink01_LV3,		 // constant 0x12F
        YZ_Accuracy_DOWN_st,		 // constant 0x130
        YZ_Accuracy_UP_st,		 // constant 0x131
        YZ_Dodge_DOWN_st,		 // constant 0x132
        YZ_Dodge_UP_st,		 // constant 0x133
        YZ_DmgBleed,		 // constant 0x134
        YZ_DmgBleed_one,		 // constant 0x135
        YZ_DmgElec_one,		 // constant 0x136
        YZ_Heal_DOWN_st,		 // constant 0x137
        YZ_Heal_UP_st,		 // constant 0x138
        YZ_Dmg_bibiri,		 // constant 0x139
        YZ_Dmg_brainwashing,		 // constant 0x13A
        YZ_Dmg_charm,		 // constant 0x13B
        YZ_Dmg_hetari,		 // constant 0x13C
        YZ_Dmg_ikari,		 // constant 0x13D
        YZ_Dmg_noroi,		 // constant 0x13E
        YZ_Dmg_piyo,		 // constant 0x13F
        YZ_Dmg_sleep,		 // constant 0x140
        YZ_Dmg_drunk01,		 // constant 0x141
        YZ_Dmg_drunk02,		 // constant 0x142
        YZ_Dmg_drunk03,		 // constant 0x143
        YZ_DmgCold,		 // constant 0x144
        YZ_DmgCold_one,		 // constant 0x145
        YZ_DmgPoison,		 // constant 0x146
        YZ_DmgPoison_one,		 // constant 0x147
        yz_enemy_active_st,		 // constant 0x148
        YZ_Rim_skill01,		 // constant 0x149
        M_NAN_BTL_TUE_skl_hato01_LV2_hit,		 // constant 0x14A
        M_NAN_BTL_TUE_skl_hato01_LV1_hit,		 // constant 0x14B
        YZ_MGZ_E_sleep02_lp,		 // constant 0x14C
        YZ_MGZ_E_sleep03_lp,		 // constant 0x14D
        YZ_MGZ_E_sleep04_lp,		 // constant 0x14E
        adachi_job01_nml_atk,		 // constant 0x14F
        adachi_job01_nml_atk_down,		 // constant 0x150
        adachi_job01_skill_01,		 // constant 0x151
        adachi_job01_skill_02,		 // constant 0x152
        adachi_job01_skill_03,		 // constant 0x153
        adachi_job01_skill_04,		 // constant 0x154
        adachi_job01_skill_05,		 // constant 0x155
        adachi_job01_skill_07,		 // constant 0x156
        adachi_job01_skill_08,		 // constant 0x157
        adachi_job01_skill_09,		 // constant 0x158
        adachi_job01_skill_10,		 // constant 0x159
        adachi_job01_skill_11,		 // constant 0x15A
        adachi_job01_skill_12,		 // constant 0x15B
        adachi_job01_skill_13,		 // constant 0x15C
        adachi_job01_skill_14,		 // constant 0x15D
        adachi_job01_skill_counter,		 // constant 0x15E
        adachi_skill_01,		 // constant 0x15F
        adachi_skill_02,		 // constant 0x160
        adachi_skill_03,		 // constant 0x161
        adachi_skill_04,		 // constant 0x162
        adachi_skill_05,		 // constant 0x163
        adachi_skill_06,		 // constant 0x164
        arashi_atk_a,		 // constant 0x165
        arashi_furimawashi,		 // constant 0x166
        arashi_kiai,		 // constant 0x167
        arashi_kuzushi,		 // constant 0x168
        ayaka_01,		 // constant 0x169
        ayaka_02,		 // constant 0x16A
        ayaka_03,		 // constant 0x16B
        ayaka_04,		 // constant 0x16C
        ayaka_05,		 // constant 0x16D
        ayaka_06,		 // constant 0x16E
        ayaka_job01_nml_atk,		 // constant 0x16F
        ayaka_job01_nml_atk_down,		 // constant 0x170
        ayako_job01_skill_01,		 // constant 0x171
        ayako_job01_skill_02,		 // constant 0x172
        ayako_job01_skill_03,		 // constant 0x173
        ayako_job01_skill_04,		 // constant 0x174
        ayako_job01_skill_05,		 // constant 0x175
        ayako_job01_skill_06,		 // constant 0x176
        ayako_job01_skill_07,		 // constant 0x177
        ayako_job01_skill_08,		 // constant 0x178
        ayako_job01_skill_09,		 // constant 0x179
        ayako_job01_skill_10,		 // constant 0x17A
        ayako_job01_skill_11,		 // constant 0x17B
        ayako_job01_skill_12,		 // constant 0x17C
        ayako_job01_skill_13,		 // constant 0x17D
        ballplayer_atk_a,		 // constant 0x17E
        ballplayer_knock,		 // constant 0x17F
        ballplayer_throw,		 // constant 0x180
        bannin_atk_a,		 // constant 0x181
        bannin_atk_b,		 // constant 0x182
        baseball_fan_atk_a,		 // constant 0x183
        baseball_fan_call,		 // constant 0x184
        baseball_fan_yaji,		 // constant 0x185
        bcj_atk_a,		 // constant 0x186
        bcj_atk_b,		 // constant 0x187
        bcj_atk_c,		 // constant 0x188
        big_eater_atk_a,		 // constant 0x189
        big_eater_atk_b,		 // constant 0x18A
        big_eater_charm,		 // constant 0x18B
        boss_attacker_atk_charge,		 // constant 0x18C
        boss_attacker_skl_kiai,		 // constant 0x18D
        boss_clean_robot_atk_a,		 // constant 0x18E
        boss_crane_truck_atk_a,		 // constant 0x18F
        boss_healer_hide,		 // constant 0x190
        boss_ishioda_atk_a,		 // constant 0x191
        boss_ishioda_counter,		 // constant 0x192
        boss_ishioda_rev_a,		 // constant 0x193
        boss_ishioda_rev_b,		 // constant 0x194
        boss_ishioda_rev_shot,		 // constant 0x195
        boss_ishioda_shot_a,		 // constant 0x196
        boss_ishioda_standby,		 // constant 0x197
        boss_kiryu_legend_atk_a,		 // constant 0x198
        boss_kiryu_legend_atk_b,		 // constant 0x199
        boss_kiryu_legend_atk_c,		 // constant 0x19A
        boss_kiryu_legend_atk_d,		 // constant 0x19B
        boss_kiryu_legend_skl_counter,		 // constant 0x19C
        boss_kiryu_rush_atk_a,		 // constant 0x19D
        boss_kiryu_rush_atk_b,		 // constant 0x19E
        boss_kiryu_rush_atk_c,		 // constant 0x19F
        boss_mabuchi_i_atk_a,		 // constant 0x1A0
        boss_mabuchi_i_atk_b,		 // constant 0x1A1
        boss_mabuchi_i_atk_c,		 // constant 0x1A2
        boss_mabuchi_i_atk_d,		 // constant 0x1A3
        boss_mabuchi_i_atk_e,		 // constant 0x1A4
        boss_majima_b_atk_a,		 // constant 0x1A5
        boss_majima_b_atk_b,		 // constant 0x1A6
        boss_majima_b_atk_c,		 // constant 0x1A7
        boss_majima_b_atk_d,		 // constant 0x1A8
        boss_majima_b_atk_e,		 // constant 0x1A9
        boss_majima_b_skl_buf,		 // constant 0x1AA
        boss_matoba_e_atk_a,		 // constant 0x1AB
        boss_matoba_e_atk_b,		 // constant 0x1AC
        boss_matoba_e_atk_c,		 // constant 0x1AD
        boss_power_shovel_arm_atk_a,		 // constant 0x1AE
        boss_power_shovel_arm_atk_b,		 // constant 0x1AF
        boss_power_shovel_arm_atk_c,		 // constant 0x1B0
        boss_power_shovel_arm_atk_d,		 // constant 0x1B1
        boss_power_shovel_arm_atk_e,		 // constant 0x1B2
        boss_power_shovel_grd_atk_a,		 // constant 0x1B3
        boss_power_shovel_grd_atk_b,		 // constant 0x1B4
        boss_power_shovel_grd_atk_c,		 // constant 0x1B5
        boss_power_shovel_grd_atk_d,		 // constant 0x1B6
        boss_saejima_atk_a,		 // constant 0x1B7
        boss_saejima_atk_b,		 // constant 0x1B8
        boss_saejima_atk_c,		 // constant 0x1B9
        boss_saejima_atk_d,		 // constant 0x1BA
        boss_sawashiro_atk_a,		 // constant 0x1BB
        boss_sawashiro_atk_b,		 // constant 0x1BC
        boss_sawashiro_brt_atk_a,		 // constant 0x1BD
        boss_sawashiro_brt_atk_b,		 // constant 0x1BE
        boss_sawashiro_brt_counter,		 // constant 0x1BF
        boss_sawashiro_b_atk_a,		 // constant 0x1C0
        boss_sawashiro_b_atk_b,		 // constant 0x1C1
        boss_sawashiro_e_atk_a,		 // constant 0x1C2
        boss_sawashiro_e_atk_b,		 // constant 0x1C3
        boss_sawashiro_x_atk_a,		 // constant 0x1C4
        boss_sawashiro_x_atk_b,		 // constant 0x1C5
        boss_sawashiro_x_counter,		 // constant 0x1C6
        boss_sawashiro_x_heal,		 // constant 0x1C7
        boss_tank_object_atk,		 // constant 0x1C8
        boss_tiger_atk_a,		 // constant 0x1C9
        boss_tiger_atk_b,		 // constant 0x1CA
        bouncer_atk_a,		 // constant 0x1CB
        bouncer_counter,		 // constant 0x1CC
        bouncer_counter_shot,		 // constant 0x1CD
        bousou_atk_a,		 // constant 0x1CE
        bousou_atk_b,		 // constant 0x1CF
        bousou_atk_c,		 // constant 0x1D0
        bousou_atk_d,		 // constant 0x1D1
        boxer_atk_a,		 // constant 0x1D2
        boxer_chop,		 // constant 0x1D3
        boxer_heal,		 // constant 0x1D4
        boxer_provoke,		 // constant 0x1D5
        chef_atk,		 // constant 0x1D6
        chef_buff,		 // constant 0x1D7
        chef_fire,		 // constant 0x1D8
        chef_heal,		 // constant 0x1D9
        chef_tired,		 // constant 0x1DA
        chinpira_atk_a,		 // constant 0x1DB
        chinpira_call,		 // constant 0x1DC
        chinpira_debuff,		 // constant 0x1DD
        chinpira_revenge,		 // constant 0x1DE
        chou_job01_nml_atk,		 // constant 0x1DF
        chou_job01_nml_atk_down,		 // constant 0x1E0
        chou_job01_skill_01,		 // constant 0x1E1
        chou_job01_skill_02,		 // constant 0x1E2
        chou_job01_skill_03,		 // constant 0x1E3
        chou_job01_skill_04,		 // constant 0x1E4
        chou_job01_skill_05,		 // constant 0x1E5
        chou_job01_skill_06,		 // constant 0x1E6
        chou_job01_skill_07,		 // constant 0x1E7
        chou_job01_skill_08,		 // constant 0x1E8
        chou_job01_skill_09,		 // constant 0x1E9
        chou_job01_skill_10,		 // constant 0x1EA
        chou_job01_skill_11,		 // constant 0x1EB
        chou_job01_skill_12,		 // constant 0x1EC
        cho_skill_01,		 // constant 0x1ED
        cho_skill_02,		 // constant 0x1EE
        cho_skill_03,		 // constant 0x1EF
        cho_skill_04,		 // constant 0x1F0
        cho_skill_05,		 // constant 0x1F1
        cho_skill_06,		 // constant 0x1F2
        cleaner_atk_a,		 // constant 0x1F3
        cleaner_atk_bee,		 // constant 0x1F4
        cleaner_atk_fire,		 // constant 0x1F5
        cleaner_atk_hammer,		 // constant 0x1F6
        cleaner_atk_roll,		 // constant 0x1F7
        cleaner_buff_clear,		 // constant 0x1F8
        cleaner_debuff_clear,		 // constant 0x1F9
        cmafia_atk,		 // constant 0x1FA
        cmafia_buff,		 // constant 0x1FB
        cmafia_call,		 // constant 0x1FC
        criminal_atk_a,		 // constant 0x1FD
        criminal_choke,		 // constant 0x1FE
        criminal_death,		 // constant 0x1FF
        criminal_shout,		 // constant 0x200
        dealer_atk_a,		 // constant 0x201
        dealer_powder,		 // constant 0x202
        doctor_atk_a,		 // constant 0x203
        doctor_def_buff,		 // constant 0x204
        drunk_atk,		 // constant 0x205
        drunk_fukai,		 // constant 0x206
        drunk_hedoro,		 // constant 0x207
        drunk_tanuki,		 // constant 0x208
        enemy_run_away,		 // constant 0x209
        fanatic_atk_a,		 // constant 0x20A
        fanatic_call,		 // constant 0x20B
        fanatic_curse,		 // constant 0x20C
        fanatic_jashin,		 // constant 0x20D
        fanatic_revive,		 // constant 0x20E
        fanatic_shout,		 // constant 0x20F
        gambler_atk_a,		 // constant 0x210
        gambler_death,		 // constant 0x211
        gambler_mimiyori,		 // constant 0x212
        gang_atk_a,		 // constant 0x213
        gang_atk_b,		 // constant 0x214
        gang_leader_atk_a,		 // constant 0x215
        gang_leader_rapid,		 // constant 0x216
        gang_leader_reload,		 // constant 0x217
        gang_leader_shot,		 // constant 0x218
        gang_leader_sleep,		 // constant 0x219
        gang_leader_souten,		 // constant 0x21A
        gomi_atk_akushu,		 // constant 0x21B
        gomi_atk_hip,		 // constant 0x21C
        gomi_dance,		 // constant 0x21D
        gomi_heal,		 // constant 0x21E
        gomi_otakara_fail,		 // constant 0x21F
        gomi_otakara_koku,		 // constant 0x220
        gomi_otakara_shot,		 // constant 0x221
        gomi_otakara_zeni,		 // constant 0x222
        gomi_watch,		 // constant 0x223
        grappler_atk_a,		 // constant 0x224
        grappler_atk_b,		 // constant 0x225
        grappler_atk_chop,		 // constant 0x226
        grappler_atk_dive,		 // constant 0x227
        grappler_choke,		 // constant 0x228
        grappler_cry,		 // constant 0x229
        guardman_atk_a,		 // constant 0x22A
        guardman_atk_buff,		 // constant 0x22B
        guardman_def_down,		 // constant 0x22C
        guardman_provoke,		 // constant 0x22D
        guest_01_skill_01,		 // constant 0x22E
        guest_01_skill_02,		 // constant 0x22F
        guest_01_skill_03,		 // constant 0x230
        guest_01_skill_04,		 // constant 0x231
        guest_01_skill_05,		 // constant 0x232
        guest_01_skill_06,		 // constant 0x233
        guest_job01_skill_01,		 // constant 0x234
        guest_job01_skill_02,		 // constant 0x235
        guest_job01_skill_03,		 // constant 0x236
        guest_job01_skill_04,		 // constant 0x237
        guest_job01_skill_05,		 // constant 0x238
        guest_job01_skill_06,		 // constant 0x239
        guest_job01_skill_07,		 // constant 0x23A
        guest_job01_skill_08,		 // constant 0x23B
        guest_job01_skill_09,		 // constant 0x23C
        guest_job01_skill_10,		 // constant 0x23D
        guest_job01_skill_11,		 // constant 0x23E
        guest_job01_skill_12,		 // constant 0x23F
        hacker_atk_a,		 // constant 0x240
        hacker_atk_b,		 // constant 0x241
        hacker_fear,		 // constant 0x242
        han_job01_nml_atk,		 // constant 0x243
        han_job01_nml_atk_down,		 // constant 0x244
        han_job01_skill_01,		 // constant 0x245
        han_job01_skill_02,		 // constant 0x246
        han_job01_skill_03,		 // constant 0x247
        han_job01_skill_04,		 // constant 0x248
        han_job01_skill_05,		 // constant 0x249
        han_job01_skill_06,		 // constant 0x24A
        han_job01_skill_06_en,		 // constant 0x24B
        han_job01_skill_07,		 // constant 0x24C
        han_job01_skill_08,		 // constant 0x24D
        han_job01_skill_09,		 // constant 0x24E
        han_job01_skill_10,		 // constant 0x24F
        han_job01_skill_11,		 // constant 0x250
        han_job01_skill_12,		 // constant 0x251
        han_skill_01,		 // constant 0x252
        han_skill_02,		 // constant 0x253
        han_skill_03,		 // constant 0x254
        han_skill_04,		 // constant 0x255
        han_skill_05,		 // constant 0x256
        han_skill_06,		 // constant 0x257
        hecaton_atk_a,		 // constant 0x258
        hecaton_buildup,		 // constant 0x259
        hecaton_pose_1,		 // constant 0x25A
        hecaton_pose_2,		 // constant 0x25B
        hippie_atk_a,		 // constant 0x25C
        hippie_heal,		 // constant 0x25D
        hippie_smoke,		 // constant 0x25E
        hippie_song,		 // constant 0x25F
        hitman_atk_a,		 // constant 0x260
        hitman_paralyze,		 // constant 0x261
        hitman_stealth,		 // constant 0x262
        homeless_atk,		 // constant 0x263
        homeless_danbo,		 // constant 0x264
        homeless_dogeza,		 // constant 0x265
        homeless_fire,		 // constant 0x266
        homeless_sleep,		 // constant 0x267
        homeless_stink,		 // constant 0x268
        homeless_yasou,		 // constant 0x269
        host_atk_a,		 // constant 0x26A
        host_heal_1,		 // constant 0x26B
        host_heal_2,		 // constant 0x26C
        host_sleep,		 // constant 0x26D
        inventor_atk_a,		 // constant 0x26E
        inventor_barrier,		 // constant 0x26F
        inventor_shot,		 // constant 0x270
        job_bodyguard_skill_01,		 // constant 0x271
        job_bodyguard_skill_02,		 // constant 0x272
        job_bodyguard_skill_03,		 // constant 0x273
        job_bodyguard_skill_04,		 // constant 0x274
        job_bodyguard_skill_05,		 // constant 0x275
        job_bodyguard_skill_06,		 // constant 0x276
        job_bodyguard_skill_07,		 // constant 0x277
        job_bodyguard_skill_08,		 // constant 0x278
        job_bodyguard_skill_09,		 // constant 0x279
        job_bodyguard_skill_10,		 // constant 0x27A
        job_caba_skill_01,		 // constant 0x27B
        job_caba_skill_02,		 // constant 0x27C
        job_caba_skill_03,		 // constant 0x27D
        job_caba_skill_04,		 // constant 0x27E
        job_caba_skill_05,		 // constant 0x27F
        job_caba_skill_06,		 // constant 0x280
        job_caba_skill_07,		 // constant 0x281
        job_caba_skill_08,		 // constant 0x282
        job_caba_skill_09,		 // constant 0x283
        job_caba_skill_10,		 // constant 0x284
        job_caba_skill_11,		 // constant 0x285
        job_caba_skill_12,		 // constant 0x286
        job_chef_skill_01,		 // constant 0x287
        job_chef_skill_02,		 // constant 0x288
        job_chef_skill_03,		 // constant 0x289
        job_chef_skill_04,		 // constant 0x28A
        job_chef_skill_05,		 // constant 0x28B
        job_chef_skill_06,		 // constant 0x28C
        job_chef_skill_07,		 // constant 0x28D
        job_chef_skill_08,		 // constant 0x28E
        job_chef_skill_09,		 // constant 0x28F
        job_chef_skill_10,		 // constant 0x290
        job_chef_skill_11,		 // constant 0x291
        job_chef_skill_12,		 // constant 0x292
        job_dancer_skill_01,		 // constant 0x293
        job_dancer_skill_02,		 // constant 0x294
        job_dancer_skill_03,		 // constant 0x295
        job_dancer_skill_04,		 // constant 0x296
        job_dancer_skill_05,		 // constant 0x297
        job_dancer_skill_06,		 // constant 0x298
        job_dancer_skill_07,		 // constant 0x299
        job_dancer_skill_08,		 // constant 0x29A
        job_dancer_skill_09,		 // constant 0x29B
        job_dancer_skill_10,		 // constant 0x29C
        job_dancer_skill_11,		 // constant 0x29D
        job_dancer_skill_12,		 // constant 0x29E
        job_dealer_skill_01,		 // constant 0x29F
        job_dealer_skill_02,		 // constant 0x2A0
        job_dealer_skill_03,		 // constant 0x2A1
        job_dealer_skill_04,		 // constant 0x2A2
        job_dealer_skill_04_a,		 // constant 0x2A3
        job_dealer_skill_04_b,		 // constant 0x2A4
        job_dealer_skill_04_c,		 // constant 0x2A5
        job_dealer_skill_05,		 // constant 0x2A6
        job_dealer_skill_06,		 // constant 0x2A7
        job_dealer_skill_07,		 // constant 0x2A8
        job_dealer_skill_08,		 // constant 0x2A9
        job_dealer_skill_09,		 // constant 0x2AA
        job_dealer_skill_10,		 // constant 0x2AB
        job_devil_skill_01,		 // constant 0x2AC
        job_devil_skill_02,		 // constant 0x2AD
        job_devil_skill_03,		 // constant 0x2AE
        job_devil_skill_04,		 // constant 0x2AF
        job_devil_skill_05,		 // constant 0x2B0
        job_devil_skill_06,		 // constant 0x2B1
        job_devil_skill_07,		 // constant 0x2B2
        job_devil_skill_08,		 // constant 0x2B3
        job_devil_skill_09,		 // constant 0x2B4
        job_devil_skill_10,		 // constant 0x2B5
        job_fortuneteller_skill_01,		 // constant 0x2B6
        job_fortuneteller_skill_02,		 // constant 0x2B7
        job_fortuneteller_skill_03,		 // constant 0x2B8
        job_fortuneteller_skill_04,		 // constant 0x2B9
        job_fortuneteller_skill_05,		 // constant 0x2BA
        job_fortuneteller_skill_06,		 // constant 0x2BB
        job_fortuneteller_skill_07,		 // constant 0x2BC
        job_fortuneteller_skill_08,		 // constant 0x2BD
        job_fortuneteller_skill_09,		 // constant 0x2BE
        job_fortuneteller_skill_10,		 // constant 0x2BF
        job_host_skill_01,		 // constant 0x2C0
        job_host_skill_02,		 // constant 0x2C1
        job_host_skill_03,		 // constant 0x2C2
        job_host_skill_04,		 // constant 0x2C3
        job_host_skill_05,		 // constant 0x2C4
        job_host_skill_06,		 // constant 0x2C5
        job_host_skill_07,		 // constant 0x2C6
        job_host_skill_08,		 // constant 0x2C7
        job_host_skill_09,		 // constant 0x2C8
        job_host_skill_10,		 // constant 0x2C9
        job_host_skill_11,		 // constant 0x2CA
        job_host_skill_12,		 // constant 0x2CB
        job_idol_skill_01,		 // constant 0x2CC
        job_idol_skill_02,		 // constant 0x2CD
        job_idol_skill_03,		 // constant 0x2CE
        job_idol_skill_04,		 // constant 0x2CF
        job_idol_skill_05,		 // constant 0x2D0
        job_idol_skill_06,		 // constant 0x2D1
        job_idol_skill_07,		 // constant 0x2D2
        job_idol_skill_08,		 // constant 0x2D3
        job_idol_skill_09,		 // constant 0x2D4
        job_idol_skill_10,		 // constant 0x2D5
        job_nightqueen_skill_01,		 // constant 0x2D6
        job_nightqueen_skill_02,		 // constant 0x2D7
        job_nightqueen_skill_03,		 // constant 0x2D8
        job_nightqueen_skill_04,		 // constant 0x2D9
        job_nightqueen_skill_05,		 // constant 0x2DA
        job_nightqueen_skill_06,		 // constant 0x2DB
        job_nightqueen_skill_07,		 // constant 0x2DC
        job_nightqueen_skill_08,		 // constant 0x2DD
        job_nightqueen_skill_09,		 // constant 0x2DE
        job_nightqueen_skill_10,		 // constant 0x2DF
        job_riot_skill_01,		 // constant 0x2E0
        job_riot_skill_02,		 // constant 0x2E1
        job_riot_skill_03,		 // constant 0x2E2
        job_riot_skill_04,		 // constant 0x2E3
        job_riot_skill_05,		 // constant 0x2E4
        job_riot_skill_06,		 // constant 0x2E5
        job_riot_skill_07,		 // constant 0x2E6
        job_riot_skill_08,		 // constant 0x2E7
        job_riot_skill_09,		 // constant 0x2E8
        job_riot_skill_10,		 // constant 0x2E9
        job_streetmusicians_skill_01,		 // constant 0x2EA
        job_streetmusicians_skill_02,		 // constant 0x2EB
        job_streetmusicians_skill_03,		 // constant 0x2EC
        job_streetmusicians_skill_04,		 // constant 0x2ED
        job_streetmusicians_skill_04_lv1,		 // constant 0x2EE
        job_streetmusicians_skill_04_lv2,		 // constant 0x2EF
        job_streetmusicians_skill_04_lv3,		 // constant 0x2F0
        job_streetmusicians_skill_05,		 // constant 0x2F1
        job_streetmusicians_skill_06,		 // constant 0x2F2
        job_streetmusicians_skill_07,		 // constant 0x2F3
        job_streetmusicians_skill_08,		 // constant 0x2F4
        job_streetmusicians_skill_09,		 // constant 0x2F5
        job_streetmusicians_skill_12,		 // constant 0x2F6
        job_streetmusicians_skill_absorb_mp,		 // constant 0x2F7
        job_streetmusicians_skill_counter,		 // constant 0x2F8
        job_wreckingyard_skill_01,		 // constant 0x2F9
        job_wreckingyard_skill_02,		 // constant 0x2FA
        job_wreckingyard_skill_03,		 // constant 0x2FB
        job_wreckingyard_skill_04,		 // constant 0x2FC
        job_wreckingyard_skill_05,		 // constant 0x2FD
        job_wreckingyard_skill_06,		 // constant 0x2FE
        job_wreckingyard_skill_07,		 // constant 0x2FF
        job_wreckingyard_skill_08,		 // constant 0x300
        job_wreckingyard_skill_09,		 // constant 0x301
        job_wreckingyard_skill_10,		 // constant 0x302
        job_wreckingyard_skill_11,		 // constant 0x303
        kasuga_job01_nml_atk,		 // constant 0x304
        kasuga_job01_nml_atk_down,		 // constant 0x305
        kasuga_job01_nml_atk_wep_A,		 // constant 0x306
        kasuga_job01_nml_atk_wep_C,		 // constant 0x307
        kasuga_job01_nml_atk_wep_H,		 // constant 0x308
        kasuga_job02_skill_01,		 // constant 0x309
        kasuga_job02_skill_02,		 // constant 0x30A
        kasuga_job02_skill_03,		 // constant 0x30B
        kasuga_job02_skill_04,		 // constant 0x30C
        kasuga_job02_skill_05,		 // constant 0x30D
        kasuga_job02_skill_06,		 // constant 0x30E
        kasuga_job02_skill_07,		 // constant 0x30F
        kasuga_job02_skill_08,		 // constant 0x310
        kasuga_job02_skill_09,		 // constant 0x311
        kasuga_job02_skill_10,		 // constant 0x312
        kasuga_job02_skill_11,		 // constant 0x313
        kasuga_job02_skill_12,		 // constant 0x314
        kasuga_job03_nml_atk,		 // constant 0x315
        kasuga_job03_nml_atk_down,		 // constant 0x316
        kasuga_job04_skill_01,		 // constant 0x317
        kasuga_job04_skill_02,		 // constant 0x318
        kasuga_job04_skill_03,		 // constant 0x319
        kasuga_job04_skill_04,		 // constant 0x31A
        kasuga_job04_skill_05,		 // constant 0x31B
        kasuga_job04_skill_06,		 // constant 0x31C
        kasuga_job04_skill_07,		 // constant 0x31D
        kasuga_job04_skill_08,		 // constant 0x31E
        kasuga_job04_skill_09,		 // constant 0x31F
        kasuga_job04_skill_10,		 // constant 0x320
        kasuga_job04_skill_11,		 // constant 0x321
        kasuga_job04_skill_12,		 // constant 0x322
        kasuga_skill_baisyu,		 // constant 0x323
        kasuga_skill_binta1,		 // constant 0x324
        kasuga_skill_binta2,		 // constant 0x325
        kasuga_skill_binta3,		 // constant 0x326
        kasuga_skill_kyoukatsu,		 // constant 0x327
        kasuga_skill_laser,		 // constant 0x328
        kasuga_skill_settoku,		 // constant 0x329
        kempo_atk_a,		 // constant 0x32A
        kempo_atk_b,		 // constant 0x32B
        kempo_buff_act,		 // constant 0x32C
        kempo_buff_atk,		 // constant 0x32D
        kempo_range_kick,		 // constant 0x32E
        lotion_man_atk_a,		 // constant 0x32F
        lotion_man_atk_b,		 // constant 0x330
        lotion_man_atk_miss,		 // constant 0x331
        lotion_man_matplay,		 // constant 0x332
        lotion_man_rocket,		 // constant 0x333
        man_job01_nml_atk,		 // constant 0x334
        man_job01_nml_atk_down,		 // constant 0x335
        man_job02_nml_atk,		 // constant 0x336
        man_job02_nml_atk_down,		 // constant 0x337
        man_job03_nml_atk,		 // constant 0x338
        man_job03_nml_atk_down,		 // constant 0x339
        man_job04_nml_atk,		 // constant 0x33A
        man_job04_nml_atk_down,		 // constant 0x33B
        man_job05_nml_atk,		 // constant 0x33C
        man_job05_nml_atk_down,		 // constant 0x33D
        man_job06_nml_atk,		 // constant 0x33E
        man_job06_nml_atk_down,		 // constant 0x33F
        man_job07_nml_atk,		 // constant 0x340
        man_job07_nml_atk_down,		 // constant 0x341
        man_job08_nml_atk,		 // constant 0x342
        man_job08_nml_atk_down,		 // constant 0x343
        musician_atk,		 // constant 0x344
        musician_death,		 // constant 0x345
        musician_heal,		 // constant 0x346
        musician_shout,		 // constant 0x347
        nanba_job01_nml_atk,		 // constant 0x348
        nanba_job01_nml_atk_down,		 // constant 0x349
        nanba_job01_skill_01,		 // constant 0x34A
        nanba_job01_skill_02,		 // constant 0x34B
        nanba_job01_skill_03,		 // constant 0x34C
        nanba_job01_skill_04,		 // constant 0x34D
        nanba_job01_skill_05,		 // constant 0x34E
        nanba_job01_skill_06,		 // constant 0x34F
        nanba_job01_skill_07,		 // constant 0x350
        nanba_job01_skill_08,		 // constant 0x351
        nanba_job01_skill_09,		 // constant 0x352
        nanba_job01_skill_10,		 // constant 0x353
        nanba_job01_skill_11,		 // constant 0x354
        nanba_job01_skill_12,		 // constant 0x355
        nanba_skill_heal1,		 // constant 0x356
        nanba_skill_heal2,		 // constant 0x357
        nanba_skill_recover,		 // constant 0x358
        nanba_skill_self_heal1,		 // constant 0x359
        nanba_skill_self_heal2,		 // constant 0x35A
        nanba_skill_self_heal3,		 // constant 0x35B
        otaku_atk_a,		 // constant 0x35C
        otaku_atk_b,		 // constant 0x35D
        otaku_enegy,		 // constant 0x35E
        otaku_lazer,		 // constant 0x35F
        otaku_mounting,		 // constant 0x360
        paripi_atk_a,		 // constant 0x361
        paripi_debuff_acc,		 // constant 0x362
        paripi_debuff_agi,		 // constant 0x363
        paripi_debuff_def,		 // constant 0x364
        paripi_mp_drain,		 // constant 0x365
        performer_atk,		 // constant 0x366
        performer_helfire,		 // constant 0x367
        performer_komikaru,		 // constant 0x368
        performer_look,		 // constant 0x369
        performer_saimin,		 // constant 0x36A
        press_atk_a,		 // constant 0x36B
        press_dokidoki,		 // constant 0x36C
        press_lowangle,		 // constant 0x36D
        press_shitsumon,		 // constant 0x36E
        pyro_no_atk,		 // constant 0x36F
        pyro_throw,		 // constant 0x370
        rapper_all_heal,		 // constant 0x371
        rapper_atk_a,		 // constant 0x372
        rapper_debuff_fear,		 // constant 0x373
        rapper_debuff_mp,		 // constant 0x374
        rapper_debuff_skill,		 // constant 0x375
        regent_atk_a,		 // constant 0x376
        regent_dance,		 // constant 0x377
        regent_hair,		 // constant 0x378
        reinou_atk_a,		 // constant 0x379
        reinou_charm,		 // constant 0x37A
        reinou_clr_debuff,		 // constant 0x37B
        reinou_dwn_atk,		 // constant 0x37C
        reinou_up_atk,		 // constant 0x37D
        reinou_up_spd,		 // constant 0x37E
        rosyutsu_atk_a,		 // constant 0x37F
        rosyutsu_dance,		 // constant 0x380
        rosyutsu_hvnsgate,		 // constant 0x381
        rosyutsu_kaichin,		 // constant 0x382
        rosyutsu_showtime,		 // constant 0x383
        saeko_job01_nml_atk,		 // constant 0x384
        saeko_job01_nml_atk_down,		 // constant 0x385
        saeko_job01_skill_01,		 // constant 0x386
        saeko_job01_skill_02,		 // constant 0x387
        saeko_job01_skill_03,		 // constant 0x388
        saeko_job01_skill_04,		 // constant 0x389
        saeko_job01_skill_05,		 // constant 0x38A
        saeko_job01_skill_06,		 // constant 0x38B
        saeko_job01_skill_07,		 // constant 0x38C
        saeko_job01_skill_08,		 // constant 0x38D
        saeko_job01_skill_09,		 // constant 0x38E
        saeko_job01_skill_10,		 // constant 0x38F
        saeko_job01_skill_11,		 // constant 0x390
        saeko_job01_skill_12,		 // constant 0x391
        saeko_skill_01,		 // constant 0x392
        saeko_skill_02,		 // constant 0x393
        saeko_skill_03,		 // constant 0x394
        saeko_skill_04,		 // constant 0x395
        saeko_skill_05,		 // constant 0x396
        saeko_skill_06,		 // constant 0x397
        saeko_skill_06_a,		 // constant 0x398
        saeko_skill_06_b,		 // constant 0x399
        saeko_skill_06_c,		 // constant 0x39A
        saeko_skill_06_d,		 // constant 0x39B
        saeko_skill_07,		 // constant 0x39C
        salaryman_atk_a,		 // constant 0x39D
        salaryman_atk_b,		 // constant 0x39E
        salaryman_call,		 // constant 0x39F
        sandwich_man_atk_a,		 // constant 0x3A0
        sandwich_man_guard,		 // constant 0x3A1
        sandwich_man_kanban,		 // constant 0x3A2
        scissors_atk_a,		 // constant 0x3A3
        scissors_buff,		 // constant 0x3A4
        scissors_debuff,		 // constant 0x3A5
        scissors_spin,		 // constant 0x3A6
        scout_man_atk_a,		 // constant 0x3A7
        scout_man_call,		 // constant 0x3A8
        scout_man_kudoki,		 // constant 0x3A9
        scout_man_look,		 // constant 0x3AA
        scout_man_miryou,		 // constant 0x3AB
        shinkyu_atk,		 // constant 0x3AC
        shinkyu_hari,		 // constant 0x3AD
        shinkyu_heal,		 // constant 0x3AE
        shokunin_atk,		 // constant 0x3AF
        shokunin_bomb,		 // constant 0x3B0
        shokunin_furimawashi,		 // constant 0x3B1
        shokunin_jibaku,		 // constant 0x3B2
        shokunin_jinarashi,		 // constant 0x3B3
        shokunin_kaiten,		 // constant 0x3B4
        shokunin_kiai,		 // constant 0x3B5
        shokunin_kiai2,		 // constant 0x3B6
        skater_atk_a,		 // constant 0x3B7
        skater_heal,		 // constant 0x3B8
        skater_trick,		 // constant 0x3B9
        skill_base,		 // constant 0x3BA
        slugger_atk_a,		 // constant 0x3BB
        slugger_cry_a,		 // constant 0x3BC
        slugger_cry_b,		 // constant 0x3BD
        slugger_heal,		 // constant 0x3BE
        slugger_swing,		 // constant 0x3BF
        slugger_swing_fail,		 // constant 0x3C0
        slugger_yokoku,		 // constant 0x3C1
        soldier_atk_a,		 // constant 0x3C2
        soldier_atk_b,		 // constant 0x3C3
        soldier_cqc,		 // constant 0x3C4
        soldier_granede,		 // constant 0x3C5
        soldier_lazer,		 // constant 0x3C6
        soldier_rapid,		 // constant 0x3C7
        straw_doll_atk_a,		 // constant 0x3C8
        straw_doll_curse,		 // constant 0x3C9
        straw_doll_death,		 // constant 0x3CA
        straw_doll_revive,		 // constant 0x3CB
        tepoudama_atk_a,		 // constant 0x3CC
        tepoudama_atk_b,		 // constant 0x3CD
        tepoudama_atk_c,		 // constant 0x3CE
        tepoudama_atk_d,		 // constant 0x3CF
        tepoudama_buff,		 // constant 0x3D0
        thief_atk_a,		 // constant 0x3D1
        thief_enmaku,		 // constant 0x3D2
        thief_steal,		 // constant 0x3D3
        tourima_atk_a,		 // constant 0x3D4
        tourima_atk_b,		 // constant 0x3D5
        tourima_atk_crit,		 // constant 0x3D6
        tourima_atk_kaiten,		 // constant 0x3D7
        tourima_buff_atk,		 // constant 0x3D8
        tourima_buff_poison,		 // constant 0x3D9
        tourima_odoshi,		 // constant 0x3DA
        tribal_atk_a,		 // constant 0x3DB
        tribal_atk_b,		 // constant 0x3DC
        tribal_counter,		 // constant 0x3DD
        umibouzu_atk_a,		 // constant 0x3DE
        umibouzu_debuf,		 // constant 0x3DF
        woman_job01_nml_atk,		 // constant 0x3E0
        woman_job01_nml_atk_down,		 // constant 0x3E1
        woman_job02_nml_atk,		 // constant 0x3E2
        woman_job02_nml_atk_down,		 // constant 0x3E3
        woman_job03_nml_atk,		 // constant 0x3E4
        woman_job03_nml_atk_down,		 // constant 0x3E5
        woman_job04_nml_atk,		 // constant 0x3E6
        woman_job04_nml_atk_down,		 // constant 0x3E7
        wp_master_atk_a,		 // constant 0x3E8
        wp_master_heavy,		 // constant 0x3E9
        wp_master_renda,		 // constant 0x3EA
        wp_master_shotgun,		 // constant 0x3EB
        wp_master_slap,		 // constant 0x3EC
        wp_master_stun,		 // constant 0x3ED
        yakuza_atk_a,		 // constant 0x3EE
        yakuza_bat_atk_a,		 // constant 0x3EF
        yakuza_bat_atk_b,		 // constant 0x3F0
        yakuza_call,		 // constant 0x3F1
        yakuza_dosu_atk_a,		 // constant 0x3F2
        yakuza_dosu_atk_b,		 // constant 0x3F3
        yakuza_handgun_atk_a,		 // constant 0x3F4
        yakuza_handgun_atk_b,		 // constant 0x3F5
        yakuza_katana_atk_a,		 // constant 0x3F6
        yakuza_katana_atk_b,		 // constant 0x3F7
        yakuza_knife_atk_a,		 // constant 0x3F8
        yakuza_knife_atk_b,		 // constant 0x3F9
        yakuza_mai,		 // constant 0x3FA
        yakuza_oumi_atk_a,		 // constant 0x3FB
        yakuza_oumi_atk_b,		 // constant 0x3FC
        yakuza_pistol_atk_a,		 // constant 0x3FD
        yakuza_pistol_atk_b,		 // constant 0x3FE
        yakuza_slash,		 // constant 0x3FF
        yakuza_sleep,		 // constant 0x400
        yakuza_touzyo_atk_a,		 // constant 0x401
        yakuza_touzyo_atk_b,		 // constant 0x402
        zombie_atk_a,		 // constant 0x403
        zombie_touch,		 // constant 0x404
        boss_tank_object_lock,		 // constant 0x405
        YZ_DRcar_Burnt,		 // constant 0x406
        p_ich_btl_wpd_ath_wid_01_LV1,		 // constant 0x407
        p_ich_btl_wpd_ath_wid_01_LV2,		 // constant 0x408
        YZ_Chara_eyelight01,		 // constant 0x409
        baseball_fan_fire,		 // constant 0x40A
        boss_arakawa_atk_a,		 // constant 0x40B
        boss_arakawa_pvk_a,		 // constant 0x40C
        boss_arakawa_pvk_b,		 // constant 0x40D
        boss_arakawa_skl_counter,		 // constant 0x40E
        boss_arakawa_y_atk_a,		 // constant 0x40F
        boss_arakawa_y_atk_b,		 // constant 0x410
        boss_arakawa_y_pvk_a,		 // constant 0x411
        boss_healer_call,		 // constant 0x412
        boss_kiryu_atk_a,		 // constant 0x413
        boss_kiryu_atk_b,		 // constant 0x414
        boss_kiryu_atk_c,		 // constant 0x415
        boss_kiryu_atk_d,		 // constant 0x416
        boss_kiryu_atk_e,		 // constant 0x417
        boss_kiryu_atk_f,		 // constant 0x418
        boss_kiryu_crash_atk_a,		 // constant 0x419
        boss_kiryu_crash_atk_b,		 // constant 0x41A
        boss_mirror_face_atk_a,		 // constant 0x41B
        boss_mirror_face_atk_b,		 // constant 0x41C
        boss_mirror_face_skl_kansatsu,		 // constant 0x41D
        boss_sawashiro_b_yokoku,		 // constant 0x41E
        boss_tank_object_atk_miss,		 // constant 0x41F
        boss_tendo_atk_a,		 // constant 0x420
        drunk_tanuki_atk,		 // constant 0x421
        grappler_charge,		 // constant 0x422
        job_caba_skill_06_c,		 // constant 0x423
        job_caba_skill_08_a,		 // constant 0x424
        job_caba_skill_08_b,		 // constant 0x425
        job_caba_skill_08_d,		 // constant 0x426
        job_dealer_skill_05_a,		 // constant 0x427
        job_dealer_skill_05_b,		 // constant 0x428
        job_dealer_skill_05_c,		 // constant 0x429
        job_dealer_skill_05_d,		 // constant 0x42A
        kasuga_skill_kizuna,		 // constant 0x42B
        lotion_man_atk_c,		 // constant 0x42C
        sniper_atk_a,		 // constant 0x42D
        yz_heal_down,		 // constant 0x42E
        YZ_subAwanoBubble,		 // constant 0x42F
        YZ_BTL_ENM_lotion,		 // constant 0x430
        YZ_BTL_ENM_ParipiMirrorball,		 // constant 0x431
        YZ_BTL_ENM_ChinAtsu_anger,		 // constant 0x432
        YZ_BTL_ENM_wara_CandleFire,		 // constant 0x433
        YZ_BTL_ENM_wara_CandleFire_b,		 // constant 0x434
        YZ_BTL_ENM_wara_CandleFire_c,		 // constant 0x435
        adachi_job01_skill_counter_act,		 // constant 0x436
        ballplayer_throw2,		 // constant 0x437
        ballplayer_throw3,		 // constant 0x438
        baseball_fan_yaji2,		 // constant 0x439
        big_eater_fire,		 // constant 0x43A
        boss_healer_heal,		 // constant 0x43B
        boss_kiryu_legend_skl_counter_act,		 // constant 0x43C
        boss_mabuchi_i_kamae,		 // constant 0x43D
        boss_mabuchi_i_kamae_en,		 // constant 0x43E
        boss_sawashiro_brt_counter_act,		 // constant 0x43F
        boss_sawashiro_x_counter_act,		 // constant 0x440
        boss_sawashiro_x_counter_act2,		 // constant 0x441
        boss_sawashiro_x_counter_act3,		 // constant 0x442
        boss_takabe_heal,		 // constant 0x443
        boss_tendo_atk_3ren,		 // constant 0x444
        boss_tendo_atk_3ren_l,		 // constant 0x445
        boss_tendo_atk_3ren_r,		 // constant 0x446
        boss_tendo_atk_ago,		 // constant 0x447
        boss_tendo_atk_akuma,		 // constant 0x448
        boss_tendo_atk_kami,		 // constant 0x449
        boss_tendo_charge_ago,		 // constant 0x44A
        boss_tendo_charge_akuma,		 // constant 0x44B
        boss_tendo_charge_kami,		 // constant 0x44C
        bouncer_rapid,		 // constant 0x44D
        bouncer_spguard,		 // constant 0x44E
        boxer_atk_crit,		 // constant 0x44F
        chef_fire_2,		 // constant 0x450
        chef_fire_3,		 // constant 0x451
        cleaner_atk_splash,		 // constant 0x452
        cmafia_buff_para,		 // constant 0x453
        criminal_stun,		 // constant 0x454
        dealer_powder_hap,		 // constant 0x455
        dealer_powder_vio,		 // constant 0x456
        dealer_stungun,		 // constant 0x457
        dealer_stungun_b,		 // constant 0x458
        dealer_stungun_c,		 // constant 0x459
        doctor_def_buff_skl,		 // constant 0x45A
        doctor_def_buff_spd,		 // constant 0x45B
        doctor_def_debuff_skl,		 // constant 0x45C
        fanatic_bastar,		 // constant 0x45D
        gang_leader_bigshot,		 // constant 0x45E
        gang_leader_shot_b,		 // constant 0x45F
        guardman_atk_buff2,		 // constant 0x460
        hacker_drone,		 // constant 0x461
        hacker_eromov,		 // constant 0x462
        hacker_expomov,		 // constant 0x463
        hecaton_pose_3,		 // constant 0x464
        hippie_heal2,		 // constant 0x465
        hippie_heal3,		 // constant 0x466
        hitman_critical,		 // constant 0x467
        hitman_spshot,		 // constant 0x468
        host_heal_3,		 // constant 0x469
        host_sleep_2,		 // constant 0x46A
        inventor_shot_elect,		 // constant 0x46B
        inventor_shot_ice,		 // constant 0x46C
        job_dealer_skill_09_buf_cri,		 // constant 0x46D
        job_dealer_skill_09_dam,		 // constant 0x46E
        job_dealer_skill_09_dam_ally,		 // constant 0x46F
        job_dealer_skill_09_escape,		 // constant 0x470
        job_dealer_skill_09_miss,		 // constant 0x471
        job_dealer_skill_09_sleep,		 // constant 0x472
        job_streetmusicians_skill_counter_act,		 // constant 0x473
        kasuga_job01_nml_atk2,		 // constant 0x474
        kasuga_job01_nml_atk3,		 // constant 0x475
        kasuga_skill_kizuna_adachi,		 // constant 0x476
        kasuga_skill_kizuna_chou,		 // constant 0x477
        kasuga_skill_kizuna_eri,		 // constant 0x478
        kasuga_skill_kizuna_han,		 // constant 0x479
        kasuga_skill_kizuna_nanba,		 // constant 0x47A
        kasuga_skill_kizuna_saeko,		 // constant 0x47B
        lotion_man_moisture,		 // constant 0x47C
        musician_resusc,		 // constant 0x47D
        musician_sleep,		 // constant 0x47E
        performer_komikaru_2,		 // constant 0x47F
        press_flash,		 // constant 0x480
        pyro_throw_bom,		 // constant 0x481
        pyro_throw_charge,		 // constant 0x482
        pyro_throw_fail,		 // constant 0x483
        pyro_throw_ice,		 // constant 0x484
        rapper_call,		 // constant 0x485
        sandwich_man_reflect,		 // constant 0x486
        shinkyu_haricold,		 // constant 0x487
        shinkyu_healfull,		 // constant 0x488
        shinkyu_healphys,		 // constant 0x489
        slugger_sa,		 // constant 0x48A
        straw_doll_deathall,		 // constant 0x48B
        tepoudama_buff_2,		 // constant 0x48C
        thief_steal_atk,		 // constant 0x48D
        umibouzu_fishatk,		 // constant 0x48E
        wp_master_fire,		 // constant 0x48F
        zombie_touch_death,		 // constant 0x490
        zombie_touch_poison,		 // constant 0x491
        YZ_BTL_ENM_PsyKing_Plasm,		 // constant 0x492
        YZ_BTL_ItemSend,		 // constant 0x493
        YZ_BTL_Counter,		 // constant 0x494
        YZ_BTL_Charge,		 // constant 0x495
        YZ_BTL_CardboardBox,		 // constant 0x496
        YZ_BTL_Clench,		 // constant 0x497
        adachi_skill_kizuna,		 // constant 0x498
        boss_kiryu_crash_style,		 // constant 0x499
        boss_kiryu_legend_style,		 // constant 0x49A
        boss_kiryu_rush_style,		 // constant 0x49B
        boss_kum_atk_a,		 // constant 0x49C
        boss_kum_atk_b,		 // constant 0x49D
        boss_saejima_pvk,		 // constant 0x49E
        boss_sawashiro_b_pvk,		 // constant 0x49F
        boss_tendo_atk_mai,		 // constant 0x4A0
        boss_tendo_charge_mai,		 // constant 0x4A1
        boxer_atk_b,		 // constant 0x4A2
        cho_skill_kizuna,		 // constant 0x4A3
        drunk_hedoro_act,		 // constant 0x4A4
        grappler_charge_act,		 // constant 0x4A5
        grappler_charge_fail,		 // constant 0x4A6
        guest_01_skill_kizuna,		 // constant 0x4A7
        guest_job01_nml_atk,		 // constant 0x4A8
        guest_job01_nml_atk_down,		 // constant 0x4A9
        han_skill_kizuna,		 // constant 0x4AA
        hitman_stealth_en,		 // constant 0x4AB
        nanba_skill_kizuna,		 // constant 0x4AC
        pyro_throw_bom_charge,		 // constant 0x4AD
        pyro_throw_bom_fail,		 // constant 0x4AE
        pyro_throw_ice_charge,		 // constant 0x4AF
        pyro_throw_ice_fail,		 // constant 0x4B0
        saeko_skill_kizuna,		 // constant 0x4B1
        YZ_Dmg_piyo_one,		 // constant 0x4B2
        YZ_Dmg_sleep_one,		 // constant 0x4B3
        YZ_Dmg_charm_one,		 // constant 0x4B4
        YZ_Dmg_hetari_one,		 // constant 0x4B5
        YZ_Magic_LV1,		 // constant 0x4B6
        YZ_Magic_LV2,		 // constant 0x4B7
        YZ_Magic_LV3,		 // constant 0x4B8
        YZ_BTL_Change,		 // constant 0x4B9
        YZ_BTL_Clear,		 // constant 0x4BA
        YZ_BTL_Return,		 // constant 0x4BB
        YZ_MGZ_E_sleep01_lush_lp,		 // constant 0x4BC
        YZ_MGZ_E_sleep02_lush_lp,		 // constant 0x4BD
        YZ_MGZ_E_sleep03_lush_lp,		 // constant 0x4BE
        YZ_MGZ_E_sleep04_lush_lp,		 // constant 0x4BF
        YZ_BTL_Cange2,		 // constant 0x4C0
        YZ_BTL_Return2,		 // constant 0x4C1
        YZ_Dmg_bibiri_one,		 // constant 0x4C2
        YZ_Dmg_brainwashing_one,		 // constant 0x4C3
        yz_dmg_drunk01_one,		 // constant 0x4C4
        YZ_Dmg_ikari_one,		 // constant 0x4C5
        YZ_HM_Recovery_LV1,		 // constant 0x4C6
        YZ_HM_Recovery_LV2,		 // constant 0x4C7
        YZ_HM_Recovery_LV3,		 // constant 0x4C8
        YZ_BTL_AbnmlClear,		 // constant 0x4C9
        YZ_Rim_skill03,		 // constant 0x4CA
        YZ_item_01,		 // constant 0x4CB
        YZ_item_02,		 // constant 0x4CC
        YZ_item_03,		 // constant 0x4CD
        YZ_item_04,		 // constant 0x4CE
        YZ_item_05,		 // constant 0x4CF
        YZ_item_06,		 // constant 0x4D0
        YZ_Chara_eyelight02,		 // constant 0x4D1
        YZ_Rim01_kiyu,		 // constant 0x4D2
        job_caba_skill_08_c,		 // constant 0x4D3
        YZ_Rim01_kiryu,		 // constant 0x4D4
        YZ_BTL_Defense_lp,		 // constant 0x4D5
        drunk_hedoro_lp,		 // constant 0x4D6
        YZ_Chara_eyelight01_InventorA,		 // constant 0x4D7
        YZ_Chara_eyelight01_InventorB,		 // constant 0x4D8
        YZ_Chara_eyelight01_InventorC,		 // constant 0x4D9
        YZ_BTL_MPSend,		 // constant 0x4DA
        boss_tank_object_lock_lp,		 // constant 0x4DB
        YZ_BTL_ENM_army,		 // constant 0x4DC
        YZ_BTL_ENM_seamaster,		 // constant 0x4DD
        YZ_BTL_ENM_tiger,		 // constant 0x4DE
        hacker_drone_HIT01,		 // constant 0x4DF
        YZ_BTL_OSJ_Flashing,		 // constant 0x4E0
        YZ_BTL_OSJ_Green,		 // constant 0x4E1
        YZ_BTL_OSJ_Red,		 // constant 0x4E2
        boss_mirror_face_atk_c,		 // constant 0x4E3
        boss_mirror_face_atk_d,		 // constant 0x4E4
        adachi_job01_skill_counter_end,		 // constant 0x4E5
        boss_arakawa_call,		 // constant 0x4E6
        boss_clean_robot_atk_daikaiten,		 // constant 0x4E7
        boss_clean_robot_atk_elec,		 // constant 0x4E8
        boss_clean_robot_atk_water,		 // constant 0x4E9
        boss_han_job01_nml_atk,		 // constant 0x4EA
        boss_han_job01_nml_atk_down,		 // constant 0x4EB
        boss_han_job01_skill_04,		 // constant 0x4EC
        boss_han_job01_skill_04_a,		 // constant 0x4ED
        boss_han_job01_skill_04_b,		 // constant 0x4EE
        boss_han_job01_skill_10,		 // constant 0x4EF
        boss_han_skill_02,		 // constant 0x4F0
        boss_han_skill_04,		 // constant 0x4F1
        boss_han_skill_05,		 // constant 0x4F2
        boss_majima_b_skl_avatar,		 // constant 0x4F3
        boss_nanba_job01_nml_atk,		 // constant 0x4F4
        boss_nanba_job01_nml_atk_down,		 // constant 0x4F5
        boss_nanba_job01_skill_02,		 // constant 0x4F6
        boss_nanba_job01_skill_04,		 // constant 0x4F7
        boss_nanba_job01_skill_05,		 // constant 0x4F8
        boss_nanba_job01_skill_10,		 // constant 0x4F9
        boss_nanba_skill_heal2,		 // constant 0x4FA
        boss_saejima_hact,		 // constant 0x4FB
        boss_sawashiro_brt_hact,		 // constant 0x4FC
        boss_tiger_atk_c,		 // constant 0x4FD
        boss_tiger_atk_d,		 // constant 0x4FE
        boss_tiger_atk_e,		 // constant 0x4FF
        bouncer_pvk,		 // constant 0x500
        chinpira_debuff_tei,		 // constant 0x501
        chinpira_revenge_act,		 // constant 0x502
        chinpira_revenge_end,		 // constant 0x503
        chou_job01_skill_12_lv0,		 // constant 0x504
        chou_job01_skill_12_lv1,		 // constant 0x505
        chou_job01_skill_12_lv2,		 // constant 0x506
        chou_job01_skill_12_lv3,		 // constant 0x507
        drunk_tanuki_end,		 // constant 0x508
        gang_call,		 // constant 0x509
        han_job01_skill_04_a,		 // constant 0x50A
        han_job01_skill_04_b,		 // constant 0x50B
        homeless_danbo_end,		 // constant 0x50C
        inventor_barrier_end,		 // constant 0x50D
        job_caba_skill_10_failed,		 // constant 0x50E
        job_caba_skill_10_success,		 // constant 0x50F
        job_dealer_skill_01_card10,		 // constant 0x510
        job_dealer_skill_01_card2,		 // constant 0x511
        job_dealer_skill_01_card5,		 // constant 0x512
        job_dealer_skill_01_cardA,		 // constant 0x513
        job_dealer_skill_01_cardJoker,		 // constant 0x514
        job_dealer_skill_07_a,		 // constant 0x515
        job_dealer_skill_07_b,		 // constant 0x516
        job_dealer_skill_07_c,		 // constant 0x517
        job_dealer_skill_07_d,		 // constant 0x518
        job_dealer_skill_07_e,		 // constant 0x519
        job_dealer_skill_07_f,		 // constant 0x51A
        job_dealer_skill_08_a,		 // constant 0x51B
        job_dealer_skill_08_b,		 // constant 0x51C
        job_dealer_skill_08_c,		 // constant 0x51D
        job_dealer_skill_08_d,		 // constant 0x51E
        job_dealer_skill_08_e,		 // constant 0x51F
        job_dealer_skill_08_f,		 // constant 0x520
        job_fortuneteller_skill_06_fuu,		 // constant 0x521
        job_fortuneteller_skill_06_sen,		 // constant 0x522
        job_fortuneteller_skill_10_a,		 // constant 0x523
        job_fortuneteller_skill_10_b,		 // constant 0x524
        job_fortuneteller_skill_10_c,		 // constant 0x525
        job_fortuneteller_skill_10_d,		 // constant 0x526
        job_fortuneteller_skill_10_e,		 // constant 0x527
        job_idol_skill_11,		 // constant 0x528
        job_nightqueen_skill_08_a,		 // constant 0x529
        job_nightqueen_skill_08_b,		 // constant 0x52A
        job_streetmusicians_skill_01_V1,		 // constant 0x52B
        job_streetmusicians_skill_01_V2,		 // constant 0x52C
        job_streetmusicians_skill_01_V3,		 // constant 0x52D
        job_wreckingyard_skill_01_atk,		 // constant 0x52E
        job_wreckingyard_skill_02_atk,		 // constant 0x52F
        kasuga_job03_nml_range_atk,		 // constant 0x530
        man_job_devil_nml_atk,		 // constant 0x531
        man_job_devil_nml_atk_down,		 // constant 0x532
        otaku_b_atk_a,		 // constant 0x533
        otaku_b_atk_b,		 // constant 0x534
        otaku_b_enegy,		 // constant 0x535
        otaku_b_lazer,		 // constant 0x536
        otaku_b_mounting,		 // constant 0x537
        pyro_atk,		 // constant 0x538
        sandwich_man_guard_end,		 // constant 0x539
        slugger_sa_end,		 // constant 0x53A
        tourima_atk_stun,		 // constant 0x53B
        woman_job02_nml_atk_down_ref_spatk,		 // constant 0x53C
        woman_job02_nml_atk_ref_spatk,		 // constant 0x53D
        YZ_BTL_MPSend2,		 // constant 0x53E
        YZ_BTL_Guard,		 // constant 0x53F
        YZ_machine_active_st,		 // constant 0x540
        YZ_Rim_Mac01,		 // constant 0x541
        YZ_Rim_Tig01,		 // constant 0x542
        YZ_tiger_active_st,		 // constant 0x543
        YZ_DmgBleed2,		 // constant 0x544
        YZ_DmgBleedA,		 // constant 0x545
        YZ_DmgBleed_A,		 // constant 0x546
        YZ_dmgelecA,		 // constant 0x547
        yz_dmgfireA,		 // constant 0x548
        yz_dmg_bibiriA,		 // constant 0x549
        YZ_dmgelecM,		 // constant 0x54A
        YZ_boss_juki_hit,		 // constant 0x54B
        M_TYO_BTL_WPE_skl_renki01_lp,		 // constant 0x54C
        YZ_boss_juki_damage,		 // constant 0x54D
        YZ_Rim_Mac02,		 // constant 0x54E
        E_ISI_BTL_SUD_nirami_lp,		 // constant 0x54F
        job_host_skill_11_success,		 // constant 0x550
        job_host_skill_12_success,		 // constant 0x551
        YZ_item_07,		 // constant 0x552
        YZ_item_08,		 // constant 0x553
        YZ_bom_elec,		 // constant 0x554
        YZ_bom_fire,		 // constant 0x555
        YZ_bom_ice,		 // constant 0x556
        YZ_Rim01_majima,		 // constant 0x557
        YZ_Rim01_saejima,		 // constant 0x558
        YZ_Rim01_tendo,		 // constant 0x559
        YZ_rim_anklet,		 // constant 0x55A
        M_STM_BTL_GTR_skl_call_lp,		 // constant 0x55B
        boss_sawashiro_yokoku_lp,		 // constant 0x55C
        YZ_BTL_ENM_ChinAtsu_confusion,		 // constant 0x55D
        A_TIG_BTL_aura_lp,		 // constant 0x55E
        E_TND_BTL_SUD_ryu_mai_lp,		 // constant 0x55F
        E_TND_BTL_SUD_ryu_uroko_lp,		 // constant 0x560
        boss_kiryu_lp,		 // constant 0x561
        boss_kiryu_rush_counter,		 // constant 0x562
        E_OSJ_ADD_pose_rise_battery,		 // constant 0x563
        boss_mabuchi_lp,		 // constant 0x564
        YZ_rim_anklet_elec,		 // constant 0x565
        YZ_rim_anklet_fire,		 // constant 0x566
        YZ_rim_anklet_ice,		 // constant 0x567
        YZ_Dmg_ikari_machine1,		 // constant 0x568
        YZ_Dmg_ikari_machine2,		 // constant 0x569
        boss_kiryu_lp2,		 // constant 0x56A
        boss_arakawa_pvk_a_en,		 // constant 0x56B
        boss_arakawa_pvk_c,		 // constant 0x56C
        boss_arakawa_skl_rerise,		 // constant 0x56D
        boss_arakawa_skl_rev1,		 // constant 0x56E
        boss_arakawa_skl_rev2,		 // constant 0x56F
        boss_saejima_lp,		 // constant 0x570
    }
}
