using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DragonEngineLibrary
{
    public enum GameVarID : uint
    {
        invalid = 0,
        is_battle = 1,
        daynight = 2,
        stage = 3,
        main_timeline = 4,
        main_timeline_clock = 5,
        sound_game_mode = 6,
        human_freeze = 7,
        taikenban_timeline = 8,
        taikenban_timeline_clock = 9,
        is_force_battle_of_scene = 10,
        scene_id = 11,
        scene_status = 12,
        is_player_dead = 13,
        is_sp_hit_playing = 14,
        is_cinematic = 15,
        is_continue_screen = 16,
        is_chase = 17,
        is_caption_playing = 18,
        smartphone_use_block = 19,
        is_talk = 20,
        is_cinematic_connecting = 21,
        is_hact = 22,
        is_load_pos_set_player_block = 23,
        is_minigame = 24,
        is_block_minigame_abort = 25,
        player_item_buff = 26,
        is_player_item_buff = 27,
        is_player_drunk = 28,
        is_play_full_screen_movie = 29,
        is_ignore_invisible_talk = 30,
        is_auth_skip = 31,
        is_scene_fading = 32,
        is_tww_now = 33,
        is_player_hold_baby = 34,
        is_photo_mode = 35,
        is_pause = 36,
        is_eating_at_shop = 37,
        is_buying_at_vending = 38,
        is_hide_map = 39,
        is_hide_minimap = 40,
        is_shopping_at_shop = 41,
        is_drama_free_talk = 42,
        is_trouble_mission_talk = 43,
        is_auth_connect = 44,
        is_stalker_hold_baby = 45,
        is_chapter_title_playing = 46,
        is_btl_finish_auth_enc = 47,
        is_trouble_mission_drama_talk = 48,
        is_drama_hact = 49,
        is_stalking = 50,
        is_encount_battle = 51,
        karaoke_music_kind = 52,
        karaoke_difficulty = 53,
        karaoke_player = 54,
        karaoke_partner = 55,
        karaoke_singer = 56,
        karaoke_is_second = 57,
        karaoke_is_cheer = 58,
        is_police_alert = 59,
        can_pocket_in_weapon = 60,
        can_kaigeki = 61,
        is_drama_talk = 62,
        video_call_now = 63,
        is_flying_drone = 64,
        is_move_onedari = 65,
        is_talktype_voice = 66,
        is_talktype_text = 67,
        is_talktype_def = 68,
        is_sound_talktype_def = 69,
        is_sound_talktype_voice = 70,
        is_sound_talktype_text = 71,
        is_sound_talktype_hact = 72,
        is_sound_talktype_auth = 73,
        option_show_mini_map = 74,
        video_call_calling = 75,
        is_unlocking = 76,
        using_smapho_camera = 77,
        disable_weapon_selector = 78,
        disable_weapon_selector_down = 79,
        is_exclusion_other_drama_talk = 80,
        is_bouncer_mission = 81,
        talk_voice_sync = 82,
        not_erase_encounter = 83,
        is_shooting_mode = 84,
        is_allow_minigame_save = 85,
        is_verification_2d = 86,
        is_verification_3d = 87,
        is_video_call_connecting = 88,
        is_video_call_talking = 89,
        is_sugoroku_now = 90,
        is_drone_menu = 91,
        is_drone_race_now = 92,
        is_drone_no_notification = 93,
        is_picking_now = 94,
        is_sound_talktype_voice_advbgm_on = 95,
        is_disable_verification_ope = 96,
        is_hide_player_gauge = 97,
        is_disable_encount_boss_talk = 98,
        is_pause_except_smartphone = 99,
        is_shooting_photo = 100,
        is_verification_talk = 101,
        is_sound_talktype_f = 102,
        is_battle_fade_end = 103,
        is_player_exist = 104,
        is_remove_player = 105,
        is_disable_always_costume_change = 106,
        is_scene_start_fade_without_play = 107,
        is_sujimon_zukan_displaying = 108,
        is_sound_talktype_party = 109,
        is_ui_loading = 110,
        is_loading_image_displaying = 111,
        is_disp_cinema_frame = 112
    }
}
