using System;

namespace DragonEngineLibrary
{
    public enum MapIconID
    {

        player,      // constant 0x1
        enemy,       // constant 0x2
        npc,         // constant 0x3
        mob,         // constant 0x4
        goal,        // constant 0x5
        boss,        // constant 0x6
        key_npc,         // constant 0x7
        store,       // constant 0x8
        restaurant,      // constant 0x9
        playspot,        // constant 0xA
        taxy,        // constant 0xB
        mission,         // constant 0xC
        vending,         // constant 0xD
        street_name,         // constant 0xE
        im_npc,      // constant 0xF
        user_goal,       // constant 0x10
        substory,        // constant 0x11
        dlc_present,         // constant 0x12
        object_access,       // constant 0x13
        prohibit,        // constant 0x14
        manhole,         // constant 0x15
        safety_box_lock,         // constant 0x16
        safety_box_open,         // constant 0x17
        entrance,        // constant 0x18
        search_pin,      // constant 0x19
        police,      // constant 0x1A
        player_drone,        // constant 0x1B
        locked_door,         // constant 0x1C
        ajito,       // constant 0x1D
        important_place,         // constant 0x1E
        side_case,       // constant 0x1F
        Friend,      // constant 0x20
        girl_friend,         // constant 0x21
        important_person,        // constant 0x22
        enemy_searching,         // constant 0x23
        boss_encount,        // constant 0x24
        area_goal,       // constant 0x25
        area_alert,      // constant 0x26
        judge_locked_door,       // constant 0x27
        substory_boot,       // constant 0x28
        stalker,         // constant 0x29
        enemy_drone,         // constant 0x2A
        park,        // constant 0x2B
        area_goal_side,      // constant 0x2C
        unlock_work_npc,         // constant 0x2D
        unlock_work_key,         // constant 0x2E
        friend_search,       // constant 0x2F
        sugoroku_arrow0,         // constant 0x30
        sugoroku_arrow_blue,         // constant 0x31
        sugoroku_arrow_red,      // constant 0x32
        sugoroku_arrow_yellow,       // constant 0x33
        sugoroku_arrow_purple,       // constant 0x34
        sugoroku_move_on,        // constant 0x35
        sugoroku_heal,       // constant 0x36
        sugoroku_gift,       // constant 0x37
        sugoroku_taxi,       // constant 0x38
        sugoroku_dice_add,       // constant 0x39
        sugoroku_move_back,      // constant 0x3A
        sugoroku_battle,         // constant 0x3B
        sugoroku_u_turn,         // constant 0x3C
        sugoroku_dice_min,       // constant 0x3D
        sugoroku_bank,       // constant 0x3E
        sugoroku_door,       // constant 0x3F
        sugoroku_random,         // constant 0x40
        sugoroku_start_goal,         // constant 0x41
        sugoroku_arrow,      // constant 0x42
        sugoroku_normal,         // constant 0x43
        sugoroku_arrow_gray,         // constant 0x44
        sugoroku_battle_gate,        // constant 0x45
        sugoroku_start,      // constant 0x46
        sugoroku_goal,       // constant 0x47
        sugoroku_koronyan,       // constant 0x48
        sugoroku_king_koronyan,      // constant 0x49
        sugoroku_kuronyan,       // constant 0x4A
        encount_boss_kasai,      // constant 0x4B
        sugoroku_goal_popup,         // constant 0x4C
        encount_boss_koga,       // constant 0x4D
        encount_boss_sakakiba,       // constant 0x4E
        encount_boss_hinda,      // constant 0x4F
        goal_side,       // constant 0x50
        sugoroku_player,         // constant 0x51
        qr_code,         // constant 0x52
        dungeon_shop,        // constant 0x53
        dungeon_up,      // constant 0x54
        dungeon_down,        // constant 0x55
        dungeon_treasure_on,         // constant 0x56
        dungeon_treasure_off,        // constant 0x57
        dungeon_key,         // constant 0x58
        dungeon_save,        // constant 0x59
        dungeon_recover,         // constant 0x5A
        homeless_player,         // constant 0x5B
        homeless_enemy,      // constant 0x5C
        homeless_truck,      // constant 0x5D
        homeless_goal,       // constant 0x5E
        homeless_lucky_npc,      // constant 0x5F
        homeless_item,       // constant 0x60
        homeless_can,        // constant 0x61
        homeless_cans,       // constant 0x62
        quest,       // constant 0x63
        quest_reception,         // constant 0x64
        homeless_tutorial_goal,      // constant 0x65
        planter,         // constant 0x66
        store_equip,         // constant 0x67
        sujimon,         // constant 0x68
        ladder,      // constant 0x69
        dungeon_up_stairs,       // constant 0x6A
        dungeon_down_stairs,         // constant 0x6B
        btl_spot,        // constant 0x6C
        gold_safety_box,         // constant 0x6D
        silver_safety_box,       // constant 0x6E
        item_box,		 // constant 0x6F
    }
}
