using System;

namespace DragonEngineLibrary
{
    public enum RPGSkillID
    {

        invalid,         // constant 0x0
        EX_ALLY_runaway_success,         // constant 0x1
        EX_ALLY_runaway_failed,      // constant 0x2
        EX_ITEM_ally_single,         // constant 0x3
        EX_ITEM_ally_all,        // constant 0x4
        EX_ITEM_enemy_single,        // constant 0x5
        EX_ITEM_enemy_all,       // constant 0x6
        JOB01_nml_atk_a,         // constant 0x7
        JOB01_nml_atk_a_down,        // constant 0x8
        JOB01_nml_atk_a_wep_A,       // constant 0x9
        JOB01_nml_atk_a_wep_C,       // constant 0xA
        JOB01_nml_atk_a_wep_H,       // constant 0xB
        JOB01_nml_atk_b,         // constant 0xC
        JOB01_nml_atk_b_wep_A,       // constant 0xD
        JOB01_nml_atk_b_wep_C,       // constant 0xE
        JOB01_nml_atk_b_wep_H,       // constant 0xF
        JOB01_nml_atk_c,         // constant 0x10
        JOB01_nml_atk_c_wep_A,       // constant 0x11
        JOB01_nml_atk_c_wep_C,       // constant 0x12
        JOB01_nml_atk_c_wep_H,       // constant 0x13
        JOB01_skill_01,      // constant 0x14
        JOB01_skill_02,      // constant 0x15
        JOB06_nml_atk_a,         // constant 0x16
        JOB06_nml_atk_a_down,        // constant 0x17
        JOB06_nml_atk_b,         // constant 0x18
        JOB06_nml_atk_c,         // constant 0x19
        JOB06_skill_01,      // constant 0x1A
        JOB06_skill_02,      // constant 0x1B
        JOB07_nml_atk_a,         // constant 0x1C
        JOB07_nml_atk_a_down,        // constant 0x1D
        JOB07_nml_atk_b,         // constant 0x1E
        JOB07_nml_atk_c,         // constant 0x1F
        JOB07_skill_01,      // constant 0x20
        JOB07_skill_02,      // constant 0x21
        JOB11_nml_atk_a,         // constant 0x22
        JOB11_nml_atk_a_down,        // constant 0x23
        JOB11_nml_atk_b,         // constant 0x24
        JOB11_nml_atk_c,         // constant 0x25
        JOB11_skill_01,      // constant 0x26
        JOB11_skill_02,      // constant 0x27
        test_01,         // constant 0x28
        test_02,         // constant 0x29
        test_03,         // constant 0x2A
        test_04,         // constant 0x2B
        test_05,         // constant 0x2C
        test_06,         // constant 0x2D
        test_07,         // constant 0x2E
        test_08,         // constant 0x2F
        test_09,         // constant 0x30
        test_10,         // constant 0x31
        test_11,         // constant 0x32
        test_12,         // constant 0x33
        test_13,         // constant 0x34
        test_14,         // constant 0x35
        test_15,         // constant 0x36
        test_16,         // constant 0x37
        test_17,         // constant 0x38
        test_18,         // constant 0x39
        test_19,         // constant 0x3A
        test_20,         // constant 0x3B
        test_21,         // constant 0x3C
        test_22,         // constant 0x3D
        test_23,         // constant 0x3E
        test_24,         // constant 0x3F
        test_25,         // constant 0x40
        test_26,         // constant 0x41
        test_27,         // constant 0x42
        test_28,         // constant 0x43
        test_29,         // constant 0x44
        test_30,         // constant 0x45
        test_31,         // constant 0x46
        test_32,         // constant 0x47
        test_33,         // constant 0x48
        test_34,         // constant 0x49
        test_35,         // constant 0x4A
        test_36,         // constant 0x4B
        test_37,         // constant 0x4C
        test_38,         // constant 0x4D
        test_39,         // constant 0x4E
        test_40,         // constant 0x4F
        test_41,         // constant 0x50
        test_42,         // constant 0x51
        test_43,         // constant 0x52
        test_44,         // constant 0x53
        test_45,         // constant 0x54
        test_46,         // constant 0x55
        test_47,         // constant 0x56
        test_48,         // constant 0x57
        test_49,         // constant 0x58
        test_50,         // constant 0x59
        test_51,         // constant 0x5A
        test_hact_replace_player,        // constant 0x5B
        test_hact_replace_player1,       // constant 0x5C
        test_hact_replace_player2,       // constant 0x5D
        test_hact_replace_player3,       // constant 0x5E
        test_52,         // constant 0x5F
        test_53,         // constant 0x60
        test_54,         // constant 0x61
        test_55,         // constant 0x62
        test_56,         // constant 0x63
        test_57,         // constant 0x64
        test_58,         // constant 0x65
        test_59,         // constant 0x66
        test_60,         // constant 0x67
        test_61,         // constant 0x68
        test_62,         // constant 0x69
        test_63,         // constant 0x6A
        DH_001,      // constant 0x6B
        DH_002,      // constant 0x6C
        DH_003,      // constant 0x6D
        DH_004,      // constant 0x6E
        DH_005,      // constant 0x6F
        DH_006,      // constant 0x70
        DH_007,      // constant 0x71
        DH_008,      // constant 0x72
        DH_009,      // constant 0x73
        DH_010,      // constant 0x74
        DH_011,      // constant 0x75
        DH_012,      // constant 0x76
        DH_013,      // constant 0x77
        DH_014,      // constant 0x78
        DH_015,      // constant 0x79
        DH_016,      // constant 0x7A
        DH_017,      // constant 0x7B
        DH_018,      // constant 0x7C
        test_64,         // constant 0x7D
        test_65,         // constant 0x7E
        test_66,         // constant 0x7F
        test_67,         // constant 0x80
        salaryman_atk_a,         // constant 0x81
        salaryman_atk_b,         // constant 0x82
        salaryman_call,      // constant 0x83
        tepoudama_atk_a,         // constant 0x84
        tepoudama_atk_b,         // constant 0x85
        tepoudama_atk_c,         // constant 0x86
        tepoudama_atk_d,         // constant 0x87
        tepoudama_buff,      // constant 0x88
        slugger_atk_a,       // constant 0x89
        slugger_yokoku,      // constant 0x8A
        slugger_cry_a,       // constant 0x8B
        slugger_cry_b,       // constant 0x8C
        slugger_heal,        // constant 0x8D
        slugger_swing,       // constant 0x8E
        slugger_swing_fail,      // constant 0x8F
        grappler_atk_a,      // constant 0x90
        grappler_atk_b,      // constant 0x91
        grappler_atk_chop,       // constant 0x92
        grappler_atk_dive,       // constant 0x93
        grappler_cry,        // constant 0x94
        grappler_choke,      // constant 0x95
        grappler_choke_fail,         // constant 0x96
        reinou_atk_a,        // constant 0x97
        reinou_buff,         // constant 0x98
        reinou_debuff,       // constant 0x99
        gomi_atk_a,      // constant 0x9A
        gomi_atk_b,      // constant 0x9B
        gomi_otakara_koku,       // constant 0x9C
        gomi_otakara_shot,       // constant 0x9D
        gomi_otakara_zeni,       // constant 0x9E
        gomi_otakara_fail,       // constant 0x9F
        gomi_dance,      // constant 0xA0
        gomi_heal,       // constant 0xA1
        gomi_watch,      // constant 0xA2
        kasuga_job01_nml_atk,        // constant 0xA3
        kasuga_job01_nml_atk_down,       // constant 0xA4
        kasuga_job01_nml_atk_wep_A,      // constant 0xA5
        kasuga_job01_nml_atk_wep_C,      // constant 0xA6
        kasuga_job01_nml_atk_wep_H,      // constant 0xA7
        kasuga_job03_nml_atk,        // constant 0xA8
        kasuga_job03_nml_atk_down,       // constant 0xA9
        nanba_job01_nml_atk,         // constant 0xAA
        nanba_job01_nml_atk_down,        // constant 0xAB
        adachi_job01_nml_atk,        // constant 0xAC
        adachi_job01_nml_atk_down,       // constant 0xAD
        ayaka_job01_nml_atk,         // constant 0xAE
        ayaka_job01_nml_atk_down,        // constant 0xAF
        saeko_job01_nml_atk,         // constant 0xB0
        saeko_job01_nml_atk_down,        // constant 0xB1
        chinpira_atk_a,      // constant 0xB2
        chinpira_atk_b,      // constant 0xB3
        kasuga_skill_01,         // constant 0xB4
        kasuga_skill_02,         // constant 0xB5
        kasuga_skill_03,         // constant 0xB6
        kasuga_skill_04,         // constant 0xB7
        kasuga_skill_05,         // constant 0xB8
        kasuga_skill_06,         // constant 0xB9
        kasuga_skill_07,         // constant 0xBA
        nanba_skill_01,      // constant 0xBB
        nanba_skill_02,      // constant 0xBC
        nanba_skill_03,      // constant 0xBD
        nanba_skill_04,      // constant 0xBE
        nanba_skill_05,      // constant 0xBF
        nanba_skill_06,      // constant 0xC0
        adachi_skill_01,         // constant 0xC1
        adachi_skill_02,         // constant 0xC2
        adachi_skill_03,         // constant 0xC3
        adachi_skill_04,         // constant 0xC4
        adachi_skill_05,         // constant 0xC5
        adachi_skill_06,         // constant 0xC6
        kasuga_job04_skill_01,       // constant 0xC7
        kasuga_job04_skill_02,       // constant 0xC8
        kasuga_job04_skill_03,       // constant 0xC9
        kasuga_job04_skill_04,       // constant 0xCA
        kasuga_job04_skill_05,       // constant 0xCB
        kasuga_job04_skill_06,       // constant 0xCC
        kasuga_job04_skill_07,       // constant 0xCD
        kasuga_job04_skill_08,       // constant 0xCE
        kasuga_job04_skill_09,       // constant 0xCF
        kasuga_job04_skill_10,       // constant 0xD0
        kasuga_job04_skill_11,       // constant 0xD1
        kasuga_job04_skill_12,       // constant 0xD2
        han_skill_01,        // constant 0xD3
        han_skill_02,        // constant 0xD4
        han_skill_03,        // constant 0xD5
        han_skill_04,        // constant 0xD6
        han_skill_05,        // constant 0xD7
        han_skill_06,        // constant 0xD8
        cho_skill_01,        // constant 0xD9
        cho_skill_02,        // constant 0xDA
        cho_skill_03,        // constant 0xDB
        cho_skill_04,        // constant 0xDC
        cho_skill_05,        // constant 0xDD
        cho_skill_06,        // constant 0xDE
        women01_skill_01,        // constant 0xDF
        women01_skill_02,        // constant 0xE0
        women01_skill_03,        // constant 0xE1
        women01_skill_04,        // constant 0xE2
        women01_skill_05,        // constant 0xE3
        women01_skill_06,        // constant 0xE4
        women02_skill_01,        // constant 0xE5
        women02_skill_02,        // constant 0xE6
        women02_skill_03,        // constant 0xE7
        women02_skill_04,        // constant 0xE8
        women02_skill_05,        // constant 0xE9
        women02_skill_06,        // constant 0xEA
        kari_skill_01,       // constant 0xEB
        kari_skill_02,       // constant 0xEC
        kari_skill_03,       // constant 0xED
        kari_skill_04,       // constant 0xEE
        kari_skill_05,       // constant 0xEF
        kari_skill_06,       // constant 0xF0
        kasuga_job02_skill_01,       // constant 0xF1
        kasuga_job02_skill_02,       // constant 0xF2
        kasuga_job02_skill_03,       // constant 0xF3
        kasuga_job02_skill_04,       // constant 0xF4
        kasuga_job02_skill_05,       // constant 0xF5
        kasuga_job02_skill_06,       // constant 0xF6
        kasuga_job02_skill_07,       // constant 0xF7
        kasuga_job02_skill_08,       // constant 0xF8
        kasuga_job02_skill_09,       // constant 0xF9
        kasuga_job02_skill_10,       // constant 0xFA
        kasuga_job02_skill_11,       // constant 0xFB
        kasuga_job02_skill_12,       // constant 0xFC
        nanba_job01_skill_01,        // constant 0xFD
        nanba_job01_skill_02,        // constant 0xFE
        nanba_job01_skill_03,        // constant 0xFF
        nanba_job01_skill_04,        // constant 0x100
        nanba_job01_skill_05,        // constant 0x101
        nanba_job01_skill_06,        // constant 0x102
        nanba_job01_skill_07,        // constant 0x103
        nanba_job01_skill_08,        // constant 0x104
        nanba_job01_skill_09,        // constant 0x105
        nanba_job01_skill_10,        // constant 0x106
        nanba_job01_skill_11,        // constant 0x107
        nanba_job01_skill_12,        // constant 0x108
        adachi_job01_skill_01,       // constant 0x109
        adachi_job01_skill_02,       // constant 0x10A
        adachi_job01_skill_03,       // constant 0x10B
        adachi_job01_skill_04,       // constant 0x10C
        adachi_job01_skill_05,       // constant 0x10D
        adachi_job01_skill_06,       // constant 0x10E
        adachi_job01_skill_07,       // constant 0x10F
        adachi_job01_skill_08,       // constant 0x110
        adachi_job01_skill_09,       // constant 0x111
        adachi_job01_skill_10,       // constant 0x112
        adachi_job01_skill_11,       // constant 0x113
        adachi_job01_skill_12,       // constant 0x114
        adachi_job01_skill_13,       // constant 0x115
        adachi_job01_skill_14,       // constant 0x116
        adachi_job01_skill_15,       // constant 0x117
        adachi_job01_skill_16,       // constant 0x118
        adachi_job01_skill_17,       // constant 0x119
        adachi_job01_skill_18,       // constant 0x11A
        saeko_skill_01,      // constant 0x11B
        saeko_skill_02,      // constant 0x11C
        saeko_skill_03,      // constant 0x11D
        saeko_skill_04,      // constant 0x11E
        saeko_skill_05,      // constant 0x11F
        saeko_skill_06,      // constant 0x120
        ayaka_01,        // constant 0x121
        ayaka_02,        // constant 0x122
        ayaka_03,        // constant 0x123
        ayaka_04,        // constant 0x124
        ayaka_05,        // constant 0x125
        ayaka_06,        // constant 0x126
        han_job01_skill_01,      // constant 0x127
        han_job01_skill_02,      // constant 0x128
        han_job01_skill_03,      // constant 0x129
        han_job01_skill_04,      // constant 0x12A
        han_job01_skill_05,      // constant 0x12B
        han_job01_skill_06,      // constant 0x12C
        han_job01_skill_07,      // constant 0x12D
        han_job01_skill_08,      // constant 0x12E
        han_job01_skill_09,      // constant 0x12F
        han_job01_skill_10,      // constant 0x130
        han_job01_skill_11,      // constant 0x131
        han_job01_skill_12,      // constant 0x132
        saeko_job01_skill_01,        // constant 0x133
        saeko_job01_skill_02,        // constant 0x134
        saeko_job01_skill_03,        // constant 0x135
        saeko_job01_skill_04,        // constant 0x136
        saeko_job01_skill_05,        // constant 0x137
        saeko_job01_skill_06,        // constant 0x138
        saeko_job01_skill_07,        // constant 0x139
        saeko_job01_skill_08,        // constant 0x13A
        saeko_job01_skill_09,        // constant 0x13B
        saeko_job01_skill_10,        // constant 0x13C
        saeko_job01_skill_11,        // constant 0x13D
        saeko_job01_skill_12,        // constant 0x13E
        ayako_job01_skill_01,        // constant 0x13F
        ayako_job01_skill_02,        // constant 0x140
        ayako_job01_skill_03,        // constant 0x141
        ayako_job01_skill_04,        // constant 0x142
        ayako_job01_skill_05,        // constant 0x143
        ayako_job01_skill_06,        // constant 0x144
        ayako_job01_skill_07,        // constant 0x145
        ayako_job01_skill_08,        // constant 0x146
        ayako_job01_skill_09,        // constant 0x147
        ayako_job01_skill_10,        // constant 0x148
        ayako_job01_skill_11,        // constant 0x149
        ayako_job01_skill_12,        // constant 0x14A
        ayako_job01_skill_13,        // constant 0x14B
        job_bodyguard_skill_01,      // constant 0x14C
        job_bodyguard_skill_02,      // constant 0x14D
        job_bodyguard_skill_03,      // constant 0x14E
        job_bodyguard_skill_04,      // constant 0x14F
        job_bodyguard_skill_05,      // constant 0x150
        job_bodyguard_skill_06,      // constant 0x151
        job_bodyguard_skill_07,      // constant 0x152
        job_bodyguard_skill_08,      // constant 0x153
        job_bodyguard_skill_09,      // constant 0x154
        job_bodyguard_skill_10,      // constant 0x155
        job_host_skill_01,       // constant 0x156
        job_host_skill_02,       // constant 0x157
        job_host_skill_03,       // constant 0x158
        job_host_skill_04,       // constant 0x159
        job_host_skill_05,       // constant 0x15A
        job_host_skill_06,       // constant 0x15B
        job_host_skill_07,       // constant 0x15C
        job_host_skill_08,       // constant 0x15D
        job_host_skill_09,       // constant 0x15E
        job_host_skill_10,       // constant 0x15F
        job_host_skill_11,       // constant 0x160
        job_host_skill_12,       // constant 0x161
        job_wreckingyard_skill_01,       // constant 0x162
        job_wreckingyard_skill_02,       // constant 0x163
        job_wreckingyard_skill_03,       // constant 0x164
        job_wreckingyard_skill_04,       // constant 0x165
        job_wreckingyard_skill_05,       // constant 0x166
        job_wreckingyard_skill_06,       // constant 0x167
        job_wreckingyard_skill_07,       // constant 0x168
        job_wreckingyard_skill_08,       // constant 0x169
        job_wreckingyard_skill_09,       // constant 0x16A
        job_wreckingyard_skill_10,       // constant 0x16B
        job_streetmusicians_skill_01,        // constant 0x16C
        job_streetmusicians_skill_02,        // constant 0x16D
        job_streetmusicians_skill_03,        // constant 0x16E
        job_streetmusicians_skill_04,        // constant 0x16F
        job_streetmusicians_skill_05,        // constant 0x170
        job_streetmusicians_skill_06,        // constant 0x171
        job_streetmusicians_skill_07,        // constant 0x172
        job_streetmusicians_skill_08,        // constant 0x173
        job_streetmusicians_skill_09,        // constant 0x174
        job_streetmusicians_skill_10,        // constant 0x175
        job_streetmusicians_skill_11,        // constant 0x176
        job_streetmusicians_skill_12,        // constant 0x177
        job_devil_skill_01,      // constant 0x178
        job_devil_skill_02,      // constant 0x179
        job_devil_skill_03,      // constant 0x17A
        job_devil_skill_04,      // constant 0x17B
        job_devil_skill_05,      // constant 0x17C
        job_devil_skill_06,      // constant 0x17D
        job_devil_skill_07,      // constant 0x17E
        job_devil_skill_08,      // constant 0x17F
        job_devil_skill_09,      // constant 0x180
        job_devil_skill_10,      // constant 0x181
        job_sweeper_skill_01,        // constant 0x182
        job_sweeper_skill_02,        // constant 0x183
        job_sweeper_skill_03,        // constant 0x184
        job_sweeper_skill_04,        // constant 0x185
        job_sweeper_skill_05,        // constant 0x186
        job_sweeper_skill_06,        // constant 0x187
        job_sweeper_skill_07,        // constant 0x188
        job_sweeper_skill_08,        // constant 0x189
        job_sweeper_skill_09,        // constant 0x18A
        job_sweeper_skill_10,        // constant 0x18B
        job_sweeper_skill_11,        // constant 0x18C
        job_sweeper_skill_12,        // constant 0x18D
        job_riot_skill_01,       // constant 0x18E
        job_riot_skill_02,       // constant 0x18F
        job_riot_skill_03,       // constant 0x190
        job_riot_skill_04,       // constant 0x191
        job_riot_skill_05,       // constant 0x192
        job_riot_skill_06,       // constant 0x193
        job_riot_skill_07,       // constant 0x194
        job_riot_skill_08,       // constant 0x195
        job_riot_skill_09,       // constant 0x196
        job_riot_skill_10,       // constant 0x197
        job_messiah_skill_01,        // constant 0x198
        tourima_atk_a,       // constant 0x199
        tourima_atk_b,       // constant 0x19A
        tourima_buff_poison,         // constant 0x19B
        tourima_buff_atk,        // constant 0x19C
        tourima_atk_crit,        // constant 0x19D
        tourima_atk_kaiten,      // constant 0x19E
        rapper_atk_a,        // constant 0x19F
        rapper_buff,         // constant 0x1A0
        rapper_debuff_mp,        // constant 0x1A1
        rapper_debuff_skill,         // constant 0x1A2
        rapper_debuff_fear,      // constant 0x1A3
        cleaner_atk_a,       // constant 0x1A4
        cleaner_debuff_clear,        // constant 0x1A5
        cleaner_buff_clear,      // constant 0x1A6
        cleaner_atk_bee,         // constant 0x1A7
        cleaner_atk_fire,        // constant 0x1A8
        cleaner_atk_hammer,      // constant 0x1A9
        cleaner_atk_roll,        // constant 0x1AA
        thief_atk_a,         // constant 0x1AB
        thief_enmaku,        // constant 0x1AC
        thief_steal,         // constant 0x1AD
        job_messiah_skill_02,        // constant 0x1AE
        job_messiah_skill_03,        // constant 0x1AF
        job_messiah_skill_04,        // constant 0x1B0
        job_messiah_skill_05,        // constant 0x1B1
        job_messiah_skill_06,        // constant 0x1B2
        job_messiah_skill_07,        // constant 0x1B3
        job_messiah_skill_08,        // constant 0x1B4
        job_messiah_skill_09,        // constant 0x1B5
        job_messiah_skill_10,        // constant 0x1B6
        test_68,         // constant 0x1B7
        job_idol_skill_01,       // constant 0x1B8
        job_idol_skill_02,       // constant 0x1B9
        job_idol_skill_03,       // constant 0x1BA
        job_idol_skill_04,       // constant 0x1BB
        job_idol_skill_05,       // constant 0x1BC
        job_idol_skill_06,       // constant 0x1BD
        job_idol_skill_07,       // constant 0x1BE
        job_idol_skill_08,       // constant 0x1BF
        job_idol_skill_09,       // constant 0x1C0
        job_idol_skill_10,       // constant 0x1C1
        job_dealer_skill_01,         // constant 0x1C2
        job_dealer_skill_02,         // constant 0x1C3
        job_dealer_skill_03,         // constant 0x1C4
        job_dealer_skill_04,         // constant 0x1C5
        job_dealer_skill_05,         // constant 0x1C6
        job_dealer_skill_06,         // constant 0x1C7
        job_dealer_skill_07,         // constant 0x1C8
        job_dealer_skill_08,         // constant 0x1C9
        job_dealer_skill_09,         // constant 0x1CA
        job_dealer_skill_10,         // constant 0x1CB
        job_nightqueen_skill_01,         // constant 0x1CC
        job_nightqueen_skill_02,         // constant 0x1CD
        job_nightqueen_skill_03,         // constant 0x1CE
        job_nightqueen_skill_04,         // constant 0x1CF
        job_nightqueen_skill_05,         // constant 0x1D0
        job_nightqueen_skill_06,         // constant 0x1D1
        job_nightqueen_skill_07,         // constant 0x1D2
        job_nightqueen_skill_08,         // constant 0x1D3
        job_nightqueen_skill_09,         // constant 0x1D4
        job_nightqueen_skill_10,         // constant 0x1D5
        sawashiro_atk_a,         // constant 0x1D6
        sawashiro_atk_b,         // constant 0x1D7
        sawashiro_b_atk_a,       // constant 0x1D8
        sawashiro_b_atk_b,       // constant 0x1D9
        sawashiro_x_atk_a,       // constant 0x1DA
        sawashiro_x_heal,        // constant 0x1DB
        sawashiro_x_counter,         // constant 0x1DC
        performer_atk,       // constant 0x1DD
        performer_helfire,       // constant 0x1DE
        performer_komikaru,      // constant 0x1DF
        performer_saimin,        // constant 0x1E0
        performer_look,      // constant 0x1E1
        drunk_atk,       // constant 0x1E2
        drunk_fukai,         // constant 0x1E3
        drunk_hedoro,        // constant 0x1E4
        drunk_tanuki,        // constant 0x1E5
        shokunin_atk,        // constant 0x1E6
        shokunin_oroshi,         // constant 0x1E7
        shokunin_kiai,       // constant 0x1E8
        shokunin_bomb,       // constant 0x1E9
        shokunin_jibaku,         // constant 0x1EA
        homeless_atk,        // constant 0x1EB
        homeless_yasou,      // constant 0x1EC
        homeless_fire,       // constant 0x1ED
        homeless_dogeza,         // constant 0x1EE
        homeless_stink,      // constant 0x1EF
        homeless_sleep,      // constant 0x1F0
        homeless_danbo,      // constant 0x1F1
        musician_atk,        // constant 0x1F2
        musician_death,      // constant 0x1F3
        musician_heal,       // constant 0x1F4
        musician_shout,      // constant 0x1F5
        chef_atk,        // constant 0x1F6
        chef_buff,       // constant 0x1F7
        chef_heal,       // constant 0x1F8
        chef_tired,      // constant 0x1F9
        cmafia_atk,      // constant 0x1FA
        cmafia_buff,         // constant 0x1FB
        cmafia_call,         // constant 0x1FC
        shinkyu_atk,         // constant 0x1FD
        shinkyu_hari,        // constant 0x1FE
        shinkyu_heal,        // constant 0x1FF
        reinou_up_atk,       // constant 0x200
        reinou_up_spd,       // constant 0x201
        reinou_clr_debuff,       // constant 0x202
        reinou_dwn_atk,      // constant 0x203
        reinou_charm,        // constant 0x204
        chef_fire,       // constant 0x205
        itm_use_enemy_single,        // constant 0x206
        itm_use_enemy_all,       // constant 0x207
        itm_heal,        // constant 0x208
        itm_heal_except_self,        // constant 0x209
        itm_revive,      // constant 0x20A
        itm_revive_all,      // constant 0x20B
        itm_heal_all,        // constant 0x20C
        itm_use_ally_all,        // constant 0x20D
        itm_use_ally_single_except_self,         // constant 0x20E
        itm_heat_enemy,      // constant 0x20F
        itm_grenade_nml,         // constant 0x210
        itm_heal_drink,      // constant 0x211
        itm_heal_food,       // constant 0x212
        tourima_odoshi,      // constant 0x213
        saeko_skill_06_a,        // constant 0x214
        saeko_skill_06_b,        // constant 0x215
        saeko_skill_06_c,        // constant 0x216
        saeko_skill_06_d,        // constant 0x217
        DH_011_a,        // constant 0x218
        DH_011_b,        // constant 0x219
        guest_01_skill_01,       // constant 0x21A
        guest_01_skill_02,       // constant 0x21B
        guest_01_skill_03,       // constant 0x21C
        guest_01_skill_04,       // constant 0x21D
        guest_01_skill_05,       // constant 0x21E
        guest_01_skill_06,       // constant 0x21F
        guest_job01_skill_01,        // constant 0x220
        guest_job01_skill_02,        // constant 0x221
        guest_job01_skill_03,        // constant 0x222
        guest_job01_skill_04,        // constant 0x223
        guest_job01_skill_05,        // constant 0x224
        guest_job01_skill_06,        // constant 0x225
        guest_job01_skill_07,        // constant 0x226
        guest_job01_skill_08,        // constant 0x227
        guest_job01_skill_09,        // constant 0x228
        guest_job01_skill_10,        // constant 0x229
        guest_job01_skill_11,        // constant 0x22A
        guest_job01_skill_12,        // constant 0x22B
        job_dancer_skill_01,         // constant 0x22C
        job_dancer_skill_02,         // constant 0x22D
        job_dancer_skill_03,         // constant 0x22E
        job_dancer_skill_04,         // constant 0x22F
        job_dancer_skill_05,         // constant 0x230
        job_dancer_skill_06,         // constant 0x231
        job_dancer_skill_07,         // constant 0x232
        job_dancer_skill_08,         // constant 0x233
        job_dancer_skill_09,         // constant 0x234
        job_dancer_skill_10,         // constant 0x235
        job_dancer_skill_11,         // constant 0x236
        job_dancer_skill_12,         // constant 0x237
        job_chef_skill_01,       // constant 0x238
        job_chef_skill_02,       // constant 0x239
        job_chef_skill_03,       // constant 0x23A
        job_chef_skill_04,       // constant 0x23B
        job_chef_skill_05,       // constant 0x23C
        job_chef_skill_06,       // constant 0x23D
        job_chef_skill_07,       // constant 0x23E
        job_chef_skill_08,       // constant 0x23F
        job_chef_skill_09,       // constant 0x240
        job_chef_skill_10,       // constant 0x241
        job_chef_skill_11,       // constant 0x242
        job_chef_skill_12,       // constant 0x243
        job_fortuneteller_skill_01,      // constant 0x244
        job_fortuneteller_skill_02,      // constant 0x245
        job_fortuneteller_skill_03,      // constant 0x246
        job_fortuneteller_skill_04,      // constant 0x247
        job_fortuneteller_skill_05,      // constant 0x248
        job_fortuneteller_skill_06,      // constant 0x249
        job_fortuneteller_skill_07,      // constant 0x24A
        job_fortuneteller_skill_08,      // constant 0x24B
        job_fortuneteller_skill_09,      // constant 0x24C
        job_fortuneteller_skill_10,      // constant 0x24D
        job_caba_skill_01,       // constant 0x24E
        job_caba_skill_02,       // constant 0x24F
        job_caba_skill_03,       // constant 0x250
        job_caba_skill_04,       // constant 0x251
        job_caba_skill_05,       // constant 0x252
        job_caba_skill_06,       // constant 0x253
        job_caba_skill_07,       // constant 0x254
        job_caba_skill_08,       // constant 0x255
        job_caba_skill_09,       // constant 0x256
        job_caba_skill_10,       // constant 0x257
        job_caba_skill_11,       // constant 0x258
        job_caba_skill_12,       // constant 0x259
        man_job01_nml_atk,       // constant 0x25A
        man_job01_nml_atk_down,      // constant 0x25B
        man_job02_nml_atk,       // constant 0x25C
        man_job02_nml_atk_down,      // constant 0x25D
        man_job03_nml_atk,       // constant 0x25E
        man_job03_nml_atk_down,      // constant 0x25F
        man_job04_nml_atk,       // constant 0x260
        man_job04_nml_atk_down,      // constant 0x261
        man_job05_nml_atk,       // constant 0x262
        man_job05_nml_atk_down,      // constant 0x263
        man_job06_nml_atk,       // constant 0x264
        man_job06_nml_atk_down,      // constant 0x265
        man_job07_nml_atk,       // constant 0x266
        man_job07_nml_atk_down,      // constant 0x267
        man_job08_nml_atk,       // constant 0x268
        man_job08_nml_atk_down,      // constant 0x269
        woman_job01_nml_atk,         // constant 0x26A
        woman_job01_nml_atk_down,        // constant 0x26B
        woman_job02_nml_atk,         // constant 0x26C
        woman_job02_nml_atk_down,        // constant 0x26D
        woman_job03_nml_atk,         // constant 0x26E
        woman_job03_nml_atk_down,        // constant 0x26F
        woman_job04_nml_atk,         // constant 0x270
        woman_job04_nml_atk_down,        // constant 0x271
        big_eater_atk_a,         // constant 0x272
        big_eater_atk_b,         // constant 0x273
        big_eater_charm,         // constant 0x274
        hitman_atk_a,        // constant 0x275
        hitman_paralyze,         // constant 0x276
        hitman_stealth,      // constant 0x277
        soldier_atk_a,       // constant 0x278
        soldier_atk_b,       // constant 0x279
        soldier_cqc,         // constant 0x27A
        soldier_rapid,       // constant 0x27B
        soldier_lazer,       // constant 0x27C
        soldier_granede,         // constant 0x27D
        bouncer_atk_a,       // constant 0x27E
        bouncer_guard,       // constant 0x27F
        bouncer_counter,         // constant 0x280
        bouncer_counter_shot,        // constant 0x281
        guardman_atk_a,      // constant 0x282
        guardman_provoke,        // constant 0x283
        guardman_atk_buff,       // constant 0x284
        guardman_def_down,       // constant 0x285
        rosyutsu_atk_a,      // constant 0x286
        rosyutsu_dance,      // constant 0x287
        rosyutsu_kaichin,        // constant 0x288
        rosyutsu_hvnsgate,       // constant 0x289
        rosyutsu_showtime,       // constant 0x28A
        doctor_atk_a,        // constant 0x28B
        doctor_def_buff,         // constant 0x28C
        hacker_atk_a,        // constant 0x28D
        hacker_atk_b,        // constant 0x28E
        hacker_fear,         // constant 0x28F
        pyro_no_atk,         // constant 0x290
        pyro_throw,      // constant 0x291
        boxer_atk_a,         // constant 0x292
        boxer_provoke,       // constant 0x293
        boxer_chop,      // constant 0x294
        boxer_heal,      // constant 0x295
        press_atk_a,         // constant 0x296
        press_dokidoki,      // constant 0x297
        press_shitsumon,         // constant 0x298
        press_lowangle,      // constant 0x299
        skater_atk_a,        // constant 0x29A
        skater_trick,        // constant 0x29B
        skater_heal,         // constant 0x29C
        chou_job01_skill_01,         // constant 0x29D
        chou_job01_skill_02,         // constant 0x29E
        chou_job01_skill_03,         // constant 0x29F
        chou_job01_skill_04,         // constant 0x2A0
        chou_job01_skill_05,         // constant 0x2A1
        chou_job01_skill_06,         // constant 0x2A2
        chou_job01_skill_07,         // constant 0x2A3
        chou_job01_skill_08,         // constant 0x2A4
        chou_job01_skill_09,         // constant 0x2A5
        chou_job01_skill_10,         // constant 0x2A6
        chou_job01_skill_11,         // constant 0x2A7
        chou_job01_skill_12,         // constant 0x2A8
        kempo_atk_a,         // constant 0x2A9
        kempo_atk_b,         // constant 0x2AA
        kempo_range_kick,        // constant 0x2AB
        kempo_buff_atk,      // constant 0x2AC
        kempo_buff_act,      // constant 0x2AD
        hippie_atk_a,        // constant 0x2AE
        hippie_heal,         // constant 0x2AF
        hippie_song,         // constant 0x2B0
        hippie_smoke,        // constant 0x2B1
        gambler_atk_a,       // constant 0x2B2
        gambler_death,       // constant 0x2B3
        gambler_mimiyori,        // constant 0x2B4
        lotion_man_atk_a,        // constant 0x2B5
        lotion_man_atk_b,        // constant 0x2B6
        lotion_man_atk_miss,         // constant 0x2B7
        lotion_man_rocket,       // constant 0x2B8
        lotion_man_matplay,      // constant 0x2B9
        sandwich_man_atk_a,      // constant 0x2BA
        sandwich_man_kanban,         // constant 0x2BB
        sandwich_man_guard,      // constant 0x2BC
        hecaton_atk_a,       // constant 0x2BD
        hecaton_buildup,         // constant 0x2BE
        hecaton_pose_1,      // constant 0x2BF
        hecaton_pose_2,      // constant 0x2C0
        bannin_atk_a,        // constant 0x2C1
        bannin_atk_b,        // constant 0x2C2
        otaku_atk_a,         // constant 0x2C3
        otaku_atk_b,         // constant 0x2C4
        otaku_enegy,         // constant 0x2C5
        otaku_lazer,         // constant 0x2C6
        otaku_mounting,      // constant 0x2C7
        regent_atk_a,        // constant 0x2C8
        regent_hair,         // constant 0x2C9
        regent_dance,        // constant 0x2CA
        baseball_fan_atk_a,      // constant 0x2CB
        baseball_fan_yaji,       // constant 0x2CC
        baseball_fan_call,       // constant 0x2CD
        scout_man_atk_a,         // constant 0x2CE
        scout_man_look,      // constant 0x2CF
        scout_man_kudoki,        // constant 0x2D0
        scout_man_miryou,        // constant 0x2D1
        scout_man_call,      // constant 0x2D2
        tribal_atk_a,        // constant 0x2D3
        tribal_atk_b,        // constant 0x2D4
        tribal_counter,      // constant 0x2D5
        host_atk_a,      // constant 0x2D6
        host_heal_1,         // constant 0x2D7
        host_heal_2,         // constant 0x2D8
        host_sleep,      // constant 0x2D9
        arashi_atk_a,        // constant 0x2DA
        arashi_kuzushi,      // constant 0x2DB
        paripi_atk_a,        // constant 0x2DC
        paripi_debuff_acc,       // constant 0x2DD
        paripi_debuff_def,       // constant 0x2DE
        paripi_debuff_agi,       // constant 0x2DF
        paripi_mp_drain,         // constant 0x2E0
        umibouzu_atk_a,      // constant 0x2E1
        umibouzu_debuf,      // constant 0x2E2
        wp_master_atk_a,         // constant 0x2E3
        wp_master_shotgun,       // constant 0x2E4
        wp_master_heavy,         // constant 0x2E5
        wp_master_renda,         // constant 0x2E6
        wp_master_slap,      // constant 0x2E7
        wp_master_stun,      // constant 0x2E8
        inventor_atk_a,      // constant 0x2E9
        inventor_shot,       // constant 0x2EA
        inventor_barrier,        // constant 0x2EB
        zombie_atk_a,        // constant 0x2EC
        zombietouch,         // constant 0x2ED
        scissors_atk_a,      // constant 0x2EE
        scissors_spin,       // constant 0x2EF
        scissors_debuff,         // constant 0x2F0
        scissors_buff,       // constant 0x2F1
        straw_doll_atk_a,        // constant 0x2F2
        straw_doll_curse,        // constant 0x2F3
        straw_doll_death,        // constant 0x2F4
        straw_doll_revive,       // constant 0x2F5
        fanatic_atk_a,       // constant 0x2F6
        fanatic_shout,       // constant 0x2F7
        fanatic_call,        // constant 0x2F8
        fanatic_curse,       // constant 0x2F9
        fanatic_jashin,      // constant 0x2FA
        fanatic_revive,      // constant 0x2FB
        ballplayer_atk_a,        // constant 0x2FC
        ballplayer_throw,        // constant 0x2FD
        ballplayer_knock,        // constant 0x2FE
        criminal_atk_a,      // constant 0x2FF
        criminal_shout,      // constant 0x300
        criminal_death,      // constant 0x301
        criminal_choke,      // constant 0x302
        zombie_touch,        // constant 0x303
        dealer_atk_a,        // constant 0x304
        dealer_powder,       // constant 0x305
        gang_atk_a,      // constant 0x306
        gang_atk_b,      // constant 0x307
        gang_leader_atk_a,       // constant 0x308
        gang_leader_shot,        // constant 0x309
        gang_leader_rapid,       // constant 0x30A
        gang_leader_souten,      // constant 0x30B
        gang_leader_reload,      // constant 0x30C
        gang_leader_sleep,       // constant 0x30D
        yakuza_atk_a,        // constant 0x30E
        yakuza_atk_b,        // constant 0x30F
        yakuza_katana_atk_a,         // constant 0x310
        yakuza_katana_atk_b,         // constant 0x311
        yakuza_pistol_atk_a,         // constant 0x312
        yakuza_pistol_atk_b,         // constant 0x313
        yakuza_handgun_atk_a,        // constant 0x314
        yakuza_handgun_atk_b,        // constant 0x315
        yakuza_dosu_atk_a,       // constant 0x316
        yakuza_dosu_atk_b,       // constant 0x317
        yakuza_knife_atk_a,      // constant 0x318
        yakuza_knife_atk_b,      // constant 0x319
        yakuza_bat_atk_a,        // constant 0x31A
        yakuza_bat_atk_b,        // constant 0x31B
        yakuza_oumi_atk_a,       // constant 0x31C
        yakuza_oumi_atk_b,       // constant 0x31D
        yakuza_touzyo_atk_a,         // constant 0x31E
        yakuza_touzyo_atk_b,         // constant 0x31F
        yakuza_call,         // constant 0x320
        yakuza_sleep,        // constant 0x321
        yakuza_slash,        // constant 0x322
        yakuza_mai,      // constant 0x323
        chinpira_call,       // constant 0x324
        chinpira_debuff,         // constant 0x325
        chinpira_revenge,        // constant 0x326
        rapper_all_heal,         // constant 0x327
        shokunin_kaiten,         // constant 0x328
        shokunin_jinarashi,      // constant 0x329
        gomi_atk_hip,        // constant 0x32A
        gomi_atk_akushu,         // constant 0x32B
        base_ability_hp_up_100,      // constant 0x32C
        base_ability_mp_up_100,      // constant 0x32D
        base_ability_atk_up_50,      // constant 0x32E
        base_ability_def_up_50,      // constant 0x32F
        base_ability_spatk_up_50,        // constant 0x330
        base_ability_heal_up_50,         // constant 0x331
        base_ability_agi_up_50,      // constant 0x332
        base_ability_dex_up_50,      // constant 0x333
        base_ability_hp_up_ratio_10,         // constant 0x334
        saeko_skill_07,      // constant 0x335
        job_wreckingyard_skill_11,       // constant 0x336
        enemy_run_away,      // constant 0x337
        tiger_atk_a,         // constant 0x338
        tiger_atk_b,         // constant 0x339
        matoba_e_atk_a,      // constant 0x33A
        matoba_e_atk_b,      // constant 0x33B
        matoba_e_atk_c,      // constant 0x33C
        boss_sawashiro_atk_a,        // constant 0x33D
        boss_sawashiro_atk_b,        // constant 0x33E
        boss_sawashiro_b_atk_a,      // constant 0x33F
        boss_sawashiro_b_atk_b,      // constant 0x340
        boss_sawashiro_x_atk_a,      // constant 0x341
        boss_sawashiro_x_heal,       // constant 0x342
        boss_sawashiro_x_counter,        // constant 0x343
        boss_tiger_atk_a,        // constant 0x344
        boss_tiger_atk_b,        // constant 0x345
        boss_matoba_e_atk_a,         // constant 0x346
        boss_matoba_e_atk_b,         // constant 0x347
        boss_matoba_e_atk_c,         // constant 0x348
        boss_sawashiro_e_atk_a,      // constant 0x349
        boss_sawashiro_e_atk_b,      // constant 0x34A
        boss_mabuchi_i_atk_a,        // constant 0x34B
        boss_mabuchi_i_atk_b,        // constant 0x34C
        boss_mabuchi_i_atk_c,        // constant 0x34D
        boss_mabuchi_i_atk_d,        // constant 0x34E
        boss_mabuchi_i_atk_e,        // constant 0x34F
        bcj_atk_a,       // constant 0x350
        bcj_atk_b,       // constant 0x351
        bcj_atk_c,       // constant 0x352
        job_action_find_item,        // constant 0x353
        job_action_honey_hunt,       // constant 0x354
        job_action_pioneer,      // constant 0x355
        ABILITY_hp_up_100,       // constant 0x356
        job_dealer_skill_04_a,       // constant 0x357
        job_dealer_skill_04_b,       // constant 0x358
        job_dealer_skill_04_c,       // constant 0x359
        han_job01_skill_06_en,       // constant 0x35A
        boss_healer_hide,        // constant 0x35B
        bousou_atk_a,        // constant 0x35C
        bousou_atk_b,        // constant 0x35D
        bousou_atk_c,        // constant 0x35E
        bousou_atk_d,        // constant 0x35F
        boss_sawashiro_brt_atk_a,        // constant 0x360
        boss_sawashiro_brt_atk_b,        // constant 0x361
        boss_sawashiro_brt_counter,      // constant 0x362
        boss_sawashiro_x_atk_b,      // constant 0x363
        itm_buff_attack_s_drink,         // constant 0x364
        itm_buff_attack_s_restaurant,        // constant 0x365
        itm_buff_attack_l_drink,         // constant 0x366
        itm_buff_attack_l_restaurant,        // constant 0x367
        itm_buff_defense_s_drink,        // constant 0x368
        itm_buff_defense_s_restaurant,       // constant 0x369
        itm_buff_defense_l_drink,        // constant 0x36A
        itm_buff_defense_l_restaurant,       // constant 0x36B
        itm_buff_dodge_s_drink,      // constant 0x36C
        itm_buff_dodge_s_restaurant,         // constant 0x36D
        itm_buff_dodge_l_drink,      // constant 0x36E
        itm_buff_dodge_l_restaurant,         // constant 0x36F
        itm_buff_money_drink,        // constant 0x370
        itm_buff_exp_drink,      // constant 0x371
        itm_buff_drop_s_food,        // constant 0x372
        itm_buff_drop_s_restaurant,      // constant 0x373
        itm_buff_drop_l_restaurant,      // constant 0x374
        itm_heal_yakedo,         // constant 0x375
        itm_heal_kaze,       // constant 0x376
        itm_heal_shibire,        // constant 0x377
        itm_heal_doku,       // constant 0x378
        itm_heal_syukketsu,      // constant 0x379
        itm_heal_physical,       // constant 0x37A
        itm_heal_mental,         // constant 0x37B
        itm_heal_allcondition,       // constant 0x37C
        itm_revive_hphalf,       // constant 0x37D
        itm_status_hp,       // constant 0x37E
        itm_status_mp,       // constant 0x37F
        itm_status_kougeki,      // constant 0x380
        itm_status_kougekikiwami,        // constant 0x381
        itm_status_bougyo,       // constant 0x382
        itm_status_syunpatsu,        // constant 0x383
        itm_status_kiyousa,      // constant 0x384
        itm_status_heal,         // constant 0x385
        itm_status_all,      // constant 0x386
        itm_ningen_jonetsu,      // constant 0x387
        itm_ningen_mental,       // constant 0x388
        itm_ningen_doryo,        // constant 0x389
        itm_ningen_youki,        // constant 0x38A
        itm_ningen_tisei,        // constant 0x38B
        itm_ningen_osyare,       // constant 0x38C
        itm_ningen_all,      // constant 0x38D
        itm_jobexp_kasugasude,       // constant 0x38E
        itm_jobexp_kasugabat,        // constant 0x38F
        itm_jobexp_homeless,         // constant 0x390
        itm_jobexp_police,       // constant 0x391
        itm_jobexp_hitman,       // constant 0x392
        itm_jobexp_mafia,        // constant 0x393
        itm_jobexp_chimama,      // constant 0x394
        itm_jobexp_ol,       // constant 0x395
        itm_jobexp_yojinbou,         // constant 0x396
        itm_jobexp_host,         // constant 0x397
        itm_jobexp_kaitai,       // constant 0x398
        itm_jobexp_musician,         // constant 0x399
        itm_jobexp_kidotai,      // constant 0x39A
        itm_jobexp_dancer,       // constant 0x39B
        itm_jobexp_uranai,       // constant 0x39C
        itm_jobexp_idol,         // constant 0x39D
        itm_jobexp_dealer,       // constant 0x39E
        itm_jobexp_caba,         // constant 0x39F
        itm_jobexp_devil,        // constant 0x3A0
        itm_jobexp_kasugasude01,         // constant 0x3A1
        itm_jobexp_kasugabat01,      // constant 0x3A2
        itm_jobexp_homeless01,       // constant 0x3A3
        itm_jobexp_police01,         // constant 0x3A4
        itm_jobexp_hitman01,         // constant 0x3A5
        itm_jobexp_mafia01,      // constant 0x3A6
        itm_jobexp_chimama01,        // constant 0x3A7
        itm_jobexp_ol01,         // constant 0x3A8
        itm_jobexp_yojinbou01,       // constant 0x3A9
        itm_jobexp_host01,       // constant 0x3AA
        itm_jobexp_kaitai01,         // constant 0x3AB
        itm_jobexp_musician01,       // constant 0x3AC
        itm_jobexp_kidotai01,        // constant 0x3AD
        itm_jobexp_dancer01,         // constant 0x3AE
        itm_jobexp_uranai01,         // constant 0x3AF
        itm_jobexp_idol01,       // constant 0x3B0
        itm_jobexp_dealer01,         // constant 0x3B1
        itm_jobexp_caba01,       // constant 0x3B2
        itm_jobexp_devil01,      // constant 0x3B3
        equip_add_badcondition,      // constant 0x3B4
        equip_add_debuff,        // constant 0x3B5
        equip_criticalmiss,      // constant 0x3B6
        equip_hitplus,       // constant 0x3B7
        equip_normalattack2range,        // constant 0x3B8
        equip_magicattack_weak,      // constant 0x3B9
        equip_magicattack_critical,      // constant 0x3BA
        equip_throw_damage,      // constant 0x3BB
        equip_physicalattack_critical,       // constant 0x3BC
        equip_physicalattack_damage,         // constant 0x3BD
        equip_heal_critical,         // constant 0x3BE
        equip_myweapon_damege,       // constant 0x3BF
        equip_waitshort,         // constant 0x3C0
        equip_add_debuff_hit,        // constant 0x3C1
        equip_debuff_hitprob,        // constant 0x3C2
        equip_invalid_attribute,         // constant 0x3C3
        equip_invalid_defense,       // constant 0x3C4
        equip_add_noheal_syukketsu,      // constant 0x3C5
        equip_physicalattack_weakdamage,         // constant 0x3C6
        equip_guitarsong_critical,       // constant 0x3C7
        equip_guitarsong_bufflong,       // constant 0x3C8
        equip_equipjob_multihit_damage,      // constant 0x3C9
        equip_fireelectricwater_damage,      // constant 0x3CA
        equip_healplus,      // constant 0x3CB
        equip_reviveplus,        // constant 0x3CC
        equip_equipjob_healplus,         // constant 0x3CD
        equip_normalattack_magic,        // constant 0x3CE
        equip_equipjob_fireelectricwater_damage,         // constant 0x3CF
        equip_criticaldamage,        // constant 0x3D0
        equip_equipjob_probplus,         // constant 0x3D1
        equip_normalattack_drain,        // constant 0x3D2
        equip_normalattack_fireelectricwater,        // constant 0x3D3
        equip_money,         // constant 0x3D4
        equip_stealprob,         // constant 0x3D5
        equip_idol_badcondition,         // constant 0x3D6
        equip_voltageprob,       // constant 0x3D7
        equip_defensecommand_damage,         // constant 0x3D8
        equip_normalattack_heal,         // constant 0x3D9
        equip_invalid_badcondition_one,      // constant 0x3DA
        equip_invalid_badcondition_mental,       // constant 0x3DB
        equip_invalid_badcondition_allhalf,      // constant 0x3DC
        equip_invalid_badcondition_all,      // constant 0x3DD
        equip_charaexp,      // constant 0x3DE
        equip_mphalf_charaexp,       // constant 0x3DF
        equip_jobexp_kasugasude,         // constant 0x3E0
        equip_jobexp_kasugabat,      // constant 0x3E1
        equip_jobexp_homeless,       // constant 0x3E2
        equip_jobexp_police,         // constant 0x3E3
        equip_jobexp_hitman,         // constant 0x3E4
        equip_jobexp_mafia,      // constant 0x3E5
        equip_jobexp_chimama,        // constant 0x3E6
        equip_jobexp_ol,         // constant 0x3E7
        equip_jobexp_yojinbou,       // constant 0x3E8
        equip_jobexp_host,       // constant 0x3E9
        equip_jobexp_kaitai,         // constant 0x3EA
        equip_jobexp_musician,       // constant 0x3EB
        equip_jobexp_kidotai,        // constant 0x3EC
        equip_jobexp_dancer,         // constant 0x3ED
        equip_jobexp_uranai,         // constant 0x3EE
        equip_jobexp_idol,       // constant 0x3EF
        equip_jobexp_dealer,         // constant 0x3F0
        equip_jobexp_caba,       // constant 0x3F1
        equip_jobexp_devil,      // constant 0x3F2
        equip_criticalprob_s,        // constant 0x3F3
        equip_criticalprob_l,        // constant 0x3F4
        equip_mpregene,      // constant 0x3F5
        equip_reraise,       // constant 0x3F6
        equip_invalid_encount,       // constant 0x3F7
        itm_jobexp_cook,         // constant 0x3F8
        itm_jobexp_nightqueen,       // constant 0x3F9
        itm_skillunlock_kasugasude01,        // constant 0x3FA
        itm_skillunlock_kasugabat01,         // constant 0x3FB
        itm_skillunlock_homeless01,      // constant 0x3FC
        itm_skillunlock_police01,        // constant 0x3FD
        itm_skillunlock_hitman01,        // constant 0x3FE
        itm_skillunlock_mafia01,         // constant 0x3FF
        itm_skillunlock_chimama01,       // constant 0x400
        itm_skillunlock_ol01,        // constant 0x401
        itm_skillunlock_yojinbou01,      // constant 0x402
        itm_skillunlock_host01,      // constant 0x403
        itm_skillunlock_kaitai01,        // constant 0x404
        itm_skillunlock_musician01,      // constant 0x405
        itm_skillunlock_kidotai01,       // constant 0x406
        itm_skillunlock_dancer01,        // constant 0x407
        itm_skillunlock_cook01,      // constant 0x408
        itm_skillunlock_uranai01,        // constant 0x409
        itm_skillunlock_idol01,      // constant 0x40A
        itm_skillunlock_dealer01,        // constant 0x40B
        itm_skillunlock_caba01,      // constant 0x40C
        itm_skillunlock_nightqueen01,        // constant 0x40D
        itm_skillunlock_devil01,         // constant 0x40E
        equip_jobexp_cook,       // constant 0x40F
        equip_jobexp_nightqueen,         // constant 0x410
        shokunin_kiai2,      // constant 0x411
        shokunin_furimawashi,        // constant 0x412
        arashi_kiai,         // constant 0x413
        arashi_furimawashi,      // constant 0x414
        boss_attacker_skl_kiai,      // constant 0x415
        boss_attacker_atk_charge,        // constant 0x416
        boss_ishioda_atk_a,      // constant 0x417
        boss_ishioda_shot_a,         // constant 0x418
        boss_ishioda_rev_shot,       // constant 0x419
        boss_ishioda_rev_a,      // constant 0x41A
        boss_ishioda_rev_b,      // constant 0x41B
        boss_ishioda_standby,        // constant 0x41C
        boss_ishioda_counter,        // constant 0x41D
        boss_kiryu_rush_atk_a,       // constant 0x41E
        boss_kiryu_rush_atk_b,       // constant 0x41F
        boss_kiryu_rush_atk_c,       // constant 0x420
        boss_saejima_atk_a,      // constant 0x421
        boss_saejima_atk_b,      // constant 0x422
        boss_saejima_atk_c,      // constant 0x423
        boss_saejima_atk_d,      // constant 0x424
        boss_kiryu_legend_atk_a,         // constant 0x425
        boss_kiryu_legend_atk_b,         // constant 0x426
        boss_kiryu_legend_atk_c,         // constant 0x427
        boss_kiryu_legend_atk_d,         // constant 0x428
        boss_kiryu_legend_skl_counter,       // constant 0x429
        boss_majima_b_atk_a,         // constant 0x42A
        boss_majima_b_atk_b,         // constant 0x42B
        boss_majima_b_atk_c,         // constant 0x42C
        boss_majima_b_atk_d,         // constant 0x42D
        boss_majima_b_atk_e,         // constant 0x42E
        boss_majima_b_skl_buf,       // constant 0x42F
        chou_job01_nml_atk,      // constant 0x430
        chou_job01_nml_atk_down,         // constant 0x431
        boss_clean_robot_atk_a,      // constant 0x432
        itm_heal_ratio,      // constant 0x433
        job_streetmusicians_skill_04_lv1,        // constant 0x434
        job_streetmusicians_skill_04_lv2,        // constant 0x435
        job_streetmusicians_skill_04_lv3,        // constant 0x436
        kasuga_skill_baisyu,         // constant 0x437
        kasuga_skill_settoku,        // constant 0x438
        kasuga_skill_kyoukatsu,      // constant 0x439
        kasuga_skill_binta1,         // constant 0x43A
        kasuga_skill_binta2,         // constant 0x43B
        kasuga_skill_binta3,         // constant 0x43C
        kasuga_skill_laser,      // constant 0x43D
        nanba_skill_self_heal1,      // constant 0x43E
        nanba_skill_self_heal2,      // constant 0x43F
        nanba_skill_self_heal3,      // constant 0x440
        nanba_skill_heal1,       // constant 0x441
        nanba_skill_heal2,       // constant 0x442
        nanba_skill_recover,         // constant 0x443
        adachi_job01_skill_counter,      // constant 0x444
        job_streetmusicians_skill_counter,       // constant 0x445
        job_streetmusicians_skill_absorb_mp,         // constant 0x446
        boss_tank_object_atk,        // constant 0x447
        han_job01_nml_atk,       // constant 0x448
        han_job01_nml_atk_down,      // constant 0x449
        boss_crane_truck_atk_a,      // constant 0x44A
        boss_power_shovel_grd_atk_a,         // constant 0x44B
        boss_power_shovel_grd_atk_b,         // constant 0x44C
        boss_power_shovel_grd_atk_c,         // constant 0x44D
        boss_power_shovel_grd_atk_d,         // constant 0x44E
        boss_power_shovel_arm_atk_a,         // constant 0x44F
        boss_power_shovel_arm_atk_b,         // constant 0x450
        boss_power_shovel_arm_atk_c,         // constant 0x451
        boss_power_shovel_arm_atk_d,         // constant 0x452
        boss_power_shovel_arm_atk_e,         // constant 0x453
        boss_tank_object_lock,       // constant 0x454
        itm_heal_drunk,      // constant 0x455
        itm_heal_by_alcohol,         // constant 0x456
        boss_kiryu_crash_atk_a,      // constant 0x457
        boss_kiryu_crash_atk_b,      // constant 0x458
        boss_kiryu_atk_a,        // constant 0x459
        boss_kiryu_atk_b,        // constant 0x45A
        boss_kiryu_atk_c,        // constant 0x45B
        boss_kiryu_atk_d,        // constant 0x45C
        boss_kiryu_atk_e,        // constant 0x45D
        boss_kiryu_atk_f,        // constant 0x45E
        kasuga_skill_hact,       // constant 0x45F
        boss_sawashiro_b_yokoku,         // constant 0x460
        boss_mirror_face_atk_a,      // constant 0x461
        boss_mirror_face_atk_b,      // constant 0x462
        boss_mirror_face_skl_kansatsu,       // constant 0x463
        itm_revive_hp_half,      // constant 0x464
        itm_revive_hp_max,       // constant 0x465
        itm_revive_all_hp_half,      // constant 0x466
        itm_revive_all_hp_max,       // constant 0x467
        boss_tendo_atk_a,        // constant 0x468
        grappler_charge,         // constant 0x469
        job_dealer_skill_05_a,       // constant 0x46A
        job_dealer_skill_05_b,       // constant 0x46B
        job_dealer_skill_05_c,       // constant 0x46C
        job_dealer_skill_05_d,       // constant 0x46D
        boss_arakawa_atk_a,      // constant 0x46E
        boss_arakawa_pvk_a,      // constant 0x46F
        boss_arakawa_pvk_b,      // constant 0x470
        boss_arakawa_skl_counter,        // constant 0x471
        boss_arakawa_y_atk_a,        // constant 0x472
        boss_arakawa_y_atk_b,        // constant 0x473
        boss_arakawa_y_pvk_a,        // constant 0x474
        lotion_man_atk_c,        // constant 0x475
        job_caba_skill_08_a,         // constant 0x476
        job_caba_skill_08_b,         // constant 0x477
        job_caba_skill_06_c,         // constant 0x478
        job_caba_skill_08_d,         // constant 0x479
        itm_buff_attack_m_restaurant,        // constant 0x47A
        itm_buff_defense_m_restaurant,       // constant 0x47B
        itm_buff_dodge_m_restaurant,         // constant 0x47C
        sniper_atk_a,        // constant 0x47D
        itm_jobexp_martial,      // constant 0x47E
        itm_skillunlock_martial01,       // constant 0x47F
        kasuga_skill_kizuna,         // constant 0x480
        boss_tank_object_atk_miss,       // constant 0x481
        baseball_fan_fire,       // constant 0x482
        drunk_tanuki_atk,        // constant 0x483
        boss_healer_call,        // constant 0x484
        kasuga_job01_nml_atk2,       // constant 0x485
        kasuga_job01_nml_atk3,       // constant 0x486
        kasuga_skill_kizuna_nanba,       // constant 0x487
        kasuga_skill_kizuna_adachi,      // constant 0x488
        kasuga_skill_kizuna_han,         // constant 0x489
        kasuga_skill_kizuna_chou,        // constant 0x48A
        kasuga_skill_kizuna_saeko,       // constant 0x48B
        kasuga_skill_kizuna_eri,         // constant 0x48C
        boss_mabuchi_i_kamae,        // constant 0x48D
        boss_mabuchi_i_kamae_en,         // constant 0x48E
        boss_healer_heal,        // constant 0x48F
        tepoudama_buff_2,        // constant 0x490
        slugger_sa,      // constant 0x491
        rapper_call,         // constant 0x492
        cleaner_atk_splash,      // constant 0x493
        thief_steal_atk,         // constant 0x494
        performer_komikaru_2,        // constant 0x495
        musician_sleep,      // constant 0x496
        musician_resusc,         // constant 0x497
        chef_fire_2,         // constant 0x498
        chef_fire_3,         // constant 0x499
        cmafia_buff_para,        // constant 0x49A
        shinkyu_haricold,        // constant 0x49B
        shinkyu_healfull,        // constant 0x49C
        shinkyu_healphys,        // constant 0x49D
        big_eater_fire,      // constant 0x49E
        hitman_spshot,       // constant 0x49F
        hitman_critical,         // constant 0x4A0
        bouncer_rapid,       // constant 0x4A1
        bouncer_spguard,         // constant 0x4A2
        guardman_atk_buff2,      // constant 0x4A3
        doctor_def_buff_spd,         // constant 0x4A4
        doctor_def_buff_skl,         // constant 0x4A5
        doctor_def_debuff_skl,       // constant 0x4A6
        hacker_expomov,      // constant 0x4A7
        hacker_eromov,       // constant 0x4A8
        hacker_drone,        // constant 0x4A9
        pyro_throw_ice,      // constant 0x4AA
        pyro_throw_bom,      // constant 0x4AB
        boxer_atk_crit,      // constant 0x4AC
        press_flash,         // constant 0x4AD
        hippie_heal2,        // constant 0x4AE
        hippie_heal3,        // constant 0x4AF
        lotion_man_moisture,         // constant 0x4B0
        sandwich_man_reflect,        // constant 0x4B1
        hecaton_pose_3,      // constant 0x4B2
        baseball_fan_yaji2,      // constant 0x4B3
        host_heal_3,         // constant 0x4B4
        host_sleep_2,        // constant 0x4B5
        umibouzu_fishatk,        // constant 0x4B6
        wp_master_fire,      // constant 0x4B7
        inventor_shot_ice,       // constant 0x4B8
        inventor_shot_elect,         // constant 0x4B9
        zombie_touch_poison,         // constant 0x4BA
        zombie_touch_death,      // constant 0x4BB
        straw_doll_deathall,         // constant 0x4BC
        fanatic_bastar,      // constant 0x4BD
        ballplayer_throw2,       // constant 0x4BE
        ballplayer_throw3,       // constant 0x4BF
        criminal_stun,       // constant 0x4C0
        dealer_powder_vio,       // constant 0x4C1
        dealer_powder_hap,       // constant 0x4C2
        dealer_stungun,      // constant 0x4C3
        dealer_stungun_b,        // constant 0x4C4
        dealer_stungun_c,        // constant 0x4C5
        gang_leader_shot_b,      // constant 0x4C6
        gang_leader_bigshot,         // constant 0x4C7
        boss_sawashiro_x_counter_act,        // constant 0x4C8
        boss_sawashiro_x_counter_act2,       // constant 0x4C9
        boss_sawashiro_x_counter_act3,       // constant 0x4CA
        boss_sawashiro_brt_counter_act,      // constant 0x4CB
        boss_kiryu_legend_skl_counter_act,       // constant 0x4CC
        boss_takabe_heal,        // constant 0x4CD
        adachi_job01_skill_counter_act,      // constant 0x4CE
        job_streetmusicians_skill_counter_act,       // constant 0x4CF
        job_dealer_skill_09_miss,        // constant 0x4D0
        job_dealer_skill_09_sleep,       // constant 0x4D1
        job_dealer_skill_09_buf_cri,         // constant 0x4D2
        job_dealer_skill_09_dam,         // constant 0x4D3
        job_dealer_skill_09_dam_ally,        // constant 0x4D4
        job_dealer_skill_09_escape,      // constant 0x4D5
        boss_tendo_charge_akuma,         // constant 0x4D6
        boss_tendo_atk_akuma,        // constant 0x4D7
        pyro_throw_charge,       // constant 0x4D8
        pyro_throw_fail,         // constant 0x4D9
        boss_tendo_charge_ago,       // constant 0x4DA
        boss_tendo_atk_ago,      // constant 0x4DB
        boss_tendo_charge_kami,      // constant 0x4DC
        boss_tendo_atk_kami,         // constant 0x4DD
        boss_tendo_atk_3ren,         // constant 0x4DE
        boss_tendo_atk_3ren_l,       // constant 0x4DF
        boss_tendo_atk_3ren_r,       // constant 0x4E0
        boss_saejima_pvk,        // constant 0x4E1
        nanba_skill_kizuna,      // constant 0x4E2
        adachi_skill_kizuna,         // constant 0x4E3
        han_skill_kizuna,        // constant 0x4E4
        cho_skill_kizuna,        // constant 0x4E5
        saeko_skill_kizuna,      // constant 0x4E6
        guest_01_skill_kizuna,       // constant 0x4E7
        drunk_hedoro_act,        // constant 0x4E8
        guest_job01_nml_atk,         // constant 0x4E9
        guest_job01_nml_atk_down,        // constant 0x4EA
        grappler_charge_fail,        // constant 0x4EB
        grappler_charge_act,         // constant 0x4EC
        equip_weapon_kasuga_003,         // constant 0x4ED
        equip_weapon_kasuga_005,         // constant 0x4EE
        equip_weapon_kasuga_006,         // constant 0x4EF
        equip_weapon_nanba_006,      // constant 0x4F0
        equip_weapon_adachi_005,         // constant 0x4F1
        equip_weapon_adachi_012,         // constant 0x4F2
        equip_weapon_saeko_007,      // constant 0x4F3
        equip_weapon_saeko_010,      // constant 0x4F4
        equip_weapon_hanjungi_004,       // constant 0x4F5
        equip_weapon_chou_001,       // constant 0x4F6
        equip_weapon_ol_001,         // constant 0x4F7
        equip_weapon_ol_005,         // constant 0x4F8
        equip_weapon_ol_011,         // constant 0x4F9
        equip_weapon_bodyguard_001,      // constant 0x4FA
        equip_weapon_bodyguard_010,      // constant 0x4FB
        equip_weapon_bodyguard_013,      // constant 0x4FC
        equip_weapon_bodyguard_016,      // constant 0x4FD
        equip_weapon_host_003,       // constant 0x4FE
        equip_weapon_host_007,       // constant 0x4FF
        equip_weapon_host_016,       // constant 0x500
        equip_wreckingyard_002,      // constant 0x501
        equip_wreckingyard_003,      // constant 0x502
        equip_wreckingyard_009,      // constant 0x503
        equip_wreckingyard_012,      // constant 0x504
        equip_wreckingyard_015,      // constant 0x505
        equip_streetmusicians_005,       // constant 0x506
        equip_chef_006,      // constant 0x507
        equip_fortuneteller_002,         // constant 0x508
        equip_idol_004,      // constant 0x509
        equip_idol_007,      // constant 0x50A
        equip_idol_009,      // constant 0x50B
        equip_dealer_005,        // constant 0x50C
        equip_nightqueen_002,        // constant 0x50D
        equip_nightqueen_005,        // constant 0x50E
        boss_kum_atk_a,      // constant 0x50F
        boss_kum_atk_b,      // constant 0x510
        itm_heal_MP,         // constant 0x511
        equip_sub_story_finder,      // constant 0x512
        boss_sawashiro_b_pvk,        // constant 0x513
        pyro_throw_ice_charge,       // constant 0x514
        pyro_throw_ice_fail,         // constant 0x515
        pyro_throw_bom_charge,       // constant 0x516
        pyro_throw_bom_fail,         // constant 0x517
        itm_gun,         // constant 0x518
        itm_rocketlauncher,      // constant 0x519
        boss_kiryu_rush_style,       // constant 0x51A
        boss_kiryu_legend_style,         // constant 0x51B
        boss_kiryu_crash_style,      // constant 0x51C
        equip_body_armor_028,        // constant 0x51D
        boss_tendo_charge_mai,       // constant 0x51E
        boss_tendo_atk_mai,      // constant 0x51F
        equip_wreckingyard_016,      // constant 0x520
        boxer_atk_b,         // constant 0x521
        hitman_stealth_en,       // constant 0x522
        boss_majima_b_skl_avatar,        // constant 0x523
        gang_call,       // constant 0x524
        itm_buff_money_restaurant,       // constant 0x525
        itm_buff_exp_restaurant,         // constant 0x526
        job_fortuneteller_skill_06_fuu,      // constant 0x527
        job_fortuneteller_skill_06_sen,      // constant 0x528
        itm_kimuchi_legend,      // constant 0x529
        bouncer_pvk,         // constant 0x52A
        itm_throw_blow,      // constant 0x52B
        itm_throw_slash,         // constant 0x52C
        tgs_kasuga_skill_binta2,         // constant 0x52D
        tgs_kasuga_job02_skill_01,       // constant 0x52E
        tgs_kasuga_job02_skill_03,       // constant 0x52F
        tgs_kasuga_job02_skill_04,       // constant 0x530
        tgs_kasuga_job02_skill_05,       // constant 0x531
        tgs_kasuga_job02_skill_10,       // constant 0x532
        tgs_kasuga_job04_skill_02,       // constant 0x533
        tgs_kasuga_job04_skill_03,       // constant 0x534
        tgs_kasuga_job04_skill_05,       // constant 0x535
        tgs_nanba_skill_self_heal1,      // constant 0x536
        tgs_nanba_job01_skill_02,        // constant 0x537
        tgs_nanba_job01_skill_03,        // constant 0x538
        tgs_nanba_job01_skill_04,        // constant 0x539
        tgs_nanba_job01_skill_08,        // constant 0x53A
        tgs_adachi_skill_01,         // constant 0x53B
        tgs_adachi_skill_02,         // constant 0x53C
        tgs_adachi_skill_04,         // constant 0x53D
        tgs_adachi_job01_skill_01,       // constant 0x53E
        tgs_adachi_job01_skill_02,       // constant 0x53F
        tgs_adachi_job01_skill_03,       // constant 0x540
        tgs_adachi_job01_skill_09,       // constant 0x541
        tgs_job_bodyguard_skill_02,      // constant 0x542
        tgs_job_bodyguard_skill_03,      // constant 0x543
        tgs_job_bodyguard_skill_05,      // constant 0x544
        tgs_job_host_skill_01,       // constant 0x545
        tgs_job_host_skill_03,       // constant 0x546
        tgs_job_host_skill_04,       // constant 0x547
        tgs_job_dancer_skill_01,         // constant 0x548
        tgs_job_dancer_skill_02,         // constant 0x549
        tgs_job_dancer_skill_06,         // constant 0x54A
        sandwich_man_guard_end,      // constant 0x54B
        homeless_danbo_end,      // constant 0x54C
        drunk_tanuki_end,        // constant 0x54D
        tourima_atk_stun,        // constant 0x54E
        chinpira_revenge_act,        // constant 0x54F
        chinpira_revenge_end,        // constant 0x550
        itm_throw_shochu,        // constant 0x551
        itm_throw_liquidnitrogen,        // constant 0x552
        itm_throw_lightningbomb,         // constant 0x553
        itm_throw_alcohol,       // constant 0x554
        itm_throw_sleep,         // constant 0x555
        itm_throw_fear,      // constant 0x556
        itm_throw_charm,         // constant 0x557
        itm_throw_brainwashing,      // constant 0x558
        itm_throw_anger,         // constant 0x559
        itm_throw_shock,         // constant 0x55A
        adachi_job01_skill_counter_end,      // constant 0x55B
        job_caba_skill_08_c,         // constant 0x55C
        tgs_job_bodyguard_skill_07,      // constant 0x55D
        itm_heal_HP,         // constant 0x55E
        itm_heal_HP_lv2,         // constant 0x55F
        itm_heal_HP_lv3,         // constant 0x560
        itm_heal_MP_lv2,         // constant 0x561
        itm_heal_MP_lv3,         // constant 0x562
        itm_heal_lv2,        // constant 0x563
        itm_heal_lv3,        // constant 0x564
        itm_heal_HP_by_alcohol,      // constant 0x565
        itm_heal_HP_by_alcohol_lv2,      // constant 0x566
        itm_heal_HP_by_alcohol_lv3,      // constant 0x567
        itm_heal_MP_by_alcohol,      // constant 0x568
        itm_heal_MP_by_alcohol_lv2,      // constant 0x569
        itm_heal_MP_by_alcohol_lv3,      // constant 0x56A
        job_streetmusicians_skill_01_V1,         // constant 0x56B
        job_streetmusicians_skill_01_V2,         // constant 0x56C
        job_streetmusicians_skill_01_V3,         // constant 0x56D
        ABILITY_hp_up_10,        // constant 0x56E
        ABILITY_hp_up_20,        // constant 0x56F
        ABILITY_hp_up_30,        // constant 0x570
        ABILITY_hp_up_40,        // constant 0x571
        ABILITY_hp_up_50,        // constant 0x572
        ABILITY_mp_up_10,        // constant 0x573
        ABILITY_mp_up_20,        // constant 0x574
        ABILITY_mp_up_30,        // constant 0x575
        ABILITY_mp_up_40,        // constant 0x576
        ABILITY_mp_up_50,        // constant 0x577
        ABILITY_atk_up_10,       // constant 0x578
        ABILITY_atk_up_20,       // constant 0x579
        ABILITY_atk_up_30,       // constant 0x57A
        ABILITY_atk_up_40,       // constant 0x57B
        ABILITY_atk_up_50,       // constant 0x57C
        ABILITY_def_up_10,       // constant 0x57D
        ABILITY_def_up_20,       // constant 0x57E
        ABILITY_def_up_30,       // constant 0x57F
        ABILITY_def_up_40,       // constant 0x580
        ABILITY_def_up_50,       // constant 0x581
        ABILITY_spatk_up_10,         // constant 0x582
        ABILITY_spatk_up_20,         // constant 0x583
        ABILITY_spatk_up_30,         // constant 0x584
        ABILITY_spatk_up_40,         // constant 0x585
        ABILITY_spatk_up_50,         // constant 0x586
        ABILITY_heal_up_10,      // constant 0x587
        ABILITY_heal_up_20,      // constant 0x588
        ABILITY_heal_up_30,      // constant 0x589
        ABILITY_heal_up_40,      // constant 0x58A
        ABILITY_heal_up_50,      // constant 0x58B
        ABILITY_agi_up_10,       // constant 0x58C
        ABILITY_agi_up_20,       // constant 0x58D
        ABILITY_agi_up_30,       // constant 0x58E
        ABILITY_agi_up_40,       // constant 0x58F
        ABILITY_agi_up_50,       // constant 0x590
        ABILITY_dex_up_10,       // constant 0x591
        ABILITY_dex_up_20,       // constant 0x592
        ABILITY_dex_up_30,       // constant 0x593
        ABILITY_dex_up_40,       // constant 0x594
        ABILITY_dex_up_50,       // constant 0x595
        base_ability_mp_up_10,       // constant 0x596
        job_wreckingyard_skill_01_atk,       // constant 0x597
        job_wreckingyard_skill_02_atk,       // constant 0x598
        job_dealer_skill_01_card2,       // constant 0x599
        job_dealer_skill_01_card5,       // constant 0x59A
        job_dealer_skill_01_card10,      // constant 0x59B
        job_dealer_skill_01_cardA,       // constant 0x59C
        job_dealer_skill_01_cardJoker,       // constant 0x59D
        itm_smoke_bomb,      // constant 0x59E
        DH_001_lv2,      // constant 0x59F
        DH_002_lv2,      // constant 0x5A0
        DH_003_lv2,      // constant 0x5A1
        DH_004_lv2,      // constant 0x5A2
        DH_005_lv2,      // constant 0x5A3
        DH_006_lv2,      // constant 0x5A4
        DH_007_lv2,      // constant 0x5A5
        DH_008_lv2,      // constant 0x5A6
        DH_009_lv2,      // constant 0x5A7
        DH_010_lv2,      // constant 0x5A8
        DH_011_lv2,      // constant 0x5A9
        DH_011_a_lv2,        // constant 0x5AA
        DH_011_b_lv2,        // constant 0x5AB
        DH_012_lv2,      // constant 0x5AC
        DH_013_lv2,      // constant 0x5AD
        DH_014_lv2,      // constant 0x5AE
        DH_015_lv2,      // constant 0x5AF
        DH_016_lv2,      // constant 0x5B0
        DH_017_lv2,      // constant 0x5B1
        DH_018_lv2,      // constant 0x5B2
        slugger_sa_end,      // constant 0x5B3
        ABILITY_hp_up_5,         // constant 0x5B4
        ABILITY_hp_up_15,        // constant 0x5B5
        ABILITY_mp_up_5,         // constant 0x5B6
        ABILITY_mp_up_15,        // constant 0x5B7
        ABILITY_atk_up_5,        // constant 0x5B8
        ABILITY_atk_up_15,       // constant 0x5B9
        ABILITY_def_up_5,        // constant 0x5BA
        ABILITY_def_up_15,       // constant 0x5BB
        ABILITY_spatk_up_5,      // constant 0x5BC
        ABILITY_spatk_up_15,         // constant 0x5BD
        ABILITY_heal_up_5,       // constant 0x5BE
        ABILITY_heal_up_15,      // constant 0x5BF
        ABILITY_agi_up_5,        // constant 0x5C0
        ABILITY_agi_up_15,       // constant 0x5C1
        ABILITY_dex_up_5,        // constant 0x5C2
        ABILITY_dex_up_15,       // constant 0x5C3
        job_dealer_skill_07_a,       // constant 0x5C4
        job_dealer_skill_07_b,       // constant 0x5C5
        job_dealer_skill_07_c,       // constant 0x5C6
        job_dealer_skill_07_d,       // constant 0x5C7
        job_dealer_skill_07_e,       // constant 0x5C8
        job_dealer_skill_07_f,       // constant 0x5C9
        job_dealer_skill_08_a,       // constant 0x5CA
        job_dealer_skill_08_b,       // constant 0x5CB
        job_dealer_skill_08_c,       // constant 0x5CC
        job_dealer_skill_08_d,       // constant 0x5CD
        job_dealer_skill_08_e,       // constant 0x5CE
        job_dealer_skill_08_f,       // constant 0x5CF
        job_fortuneteller_skill_10_a,        // constant 0x5D0
        job_fortuneteller_skill_10_b,        // constant 0x5D1
        job_fortuneteller_skill_10_c,        // constant 0x5D2
        job_fortuneteller_skill_10_d,        // constant 0x5D3
        job_fortuneteller_skill_10_e,        // constant 0x5D4
        job_nightqueen_skill_08_a,       // constant 0x5D5
        job_nightqueen_skill_08_b,       // constant 0x5D6
        han_job01_skill_04_a,        // constant 0x5D7
        han_job01_skill_04_b,        // constant 0x5D8
        boss_tiger_atk_c,        // constant 0x5D9
        boss_tiger_atk_d,        // constant 0x5DA
        boss_tiger_atk_e,        // constant 0x5DB
        inventor_barrier_end,        // constant 0x5DC
        boss_mirror_face_atk_c,      // constant 0x5DD
        boss_mirror_face_atk_d,      // constant 0x5DE
        boss_arakawa_call,       // constant 0x5DF
        boss_sawashiro_brt_hact,         // constant 0x5E0
        chou_job01_skill_12_lv0,         // constant 0x5E1
        chou_job01_skill_12_lv1,         // constant 0x5E2
        chou_job01_skill_12_lv2,         // constant 0x5E3
        chou_job01_skill_12_lv3,         // constant 0x5E4
        man_job_devil_nml_atk,       // constant 0x5E5
        man_job_devil_nml_atk_down,      // constant 0x5E6
        boss_saejima_hact,       // constant 0x5E7
        woman_job02_nml_atk_ref_spatk,       // constant 0x5E8
        woman_job02_nml_atk_down_ref_spatk,      // constant 0x5E9
        kasuga_job03_nml_range_atk,      // constant 0x5EA
        otaku_b_atk_a,       // constant 0x5EB
        otaku_b_atk_b,       // constant 0x5EC
        otaku_b_enegy,       // constant 0x5ED
        otaku_b_lazer,       // constant 0x5EE
        otaku_b_mounting,        // constant 0x5EF
        boss_han_job01_nml_atk,      // constant 0x5F0
        boss_han_job01_nml_atk_down,         // constant 0x5F1
        boss_han_skill_05,       // constant 0x5F2
        boss_han_skill_02,       // constant 0x5F3
        boss_han_job01_skill_04,         // constant 0x5F4
        boss_han_job01_skill_04_a,       // constant 0x5F5
        boss_han_job01_skill_04_b,       // constant 0x5F6
        boss_han_skill_04,       // constant 0x5F7
        boss_han_job01_skill_10,         // constant 0x5F8
        boss_nanba_job01_nml_atk,        // constant 0x5F9
        boss_nanba_job01_nml_atk_down,       // constant 0x5FA
        boss_nanba_job01_skill_02,       // constant 0x5FB
        boss_nanba_job01_skill_10,       // constant 0x5FC
        boss_nanba_skill_heal2,      // constant 0x5FD
        boss_nanba_job01_skill_04,       // constant 0x5FE
        boss_nanba_job01_skill_05,       // constant 0x5FF
        boss_clean_robot_atk_daikaiten,      // constant 0x600
        boss_clean_robot_atk_elec,       // constant 0x601
        boss_clean_robot_atk_water,      // constant 0x602
        job_idol_skill_11,       // constant 0x603
        pyro_atk,        // constant 0x604
        chinpira_debuff_tei,         // constant 0x605
        job_caba_skill_10_success,       // constant 0x606
        job_caba_skill_10_failed,        // constant 0x607
        job_streetmusicians_skill_counter_end,       // constant 0x608
        DH_019,      // constant 0x609
        DH_019_lv2,      // constant 0x60A
        equip_jobexp_all,        // constant 0x60B
        equip_weapon_absorb_mp_01,       // constant 0x60C
        chou_job01_skill_10_act,         // constant 0x60D
        boss_crane_truck_atk_b,      // constant 0x60E
        cleaner_atk_roll_act,        // constant 0x60F
        cleaner_atk_roll_fail,       // constant 0x610
        cleaner_atk_splash_act,      // constant 0x611
        boss_crane_truck_atk_b_act,      // constant 0x612
        tgs_kasuga_skill_settoku,        // constant 0x613
        tgs_kasuga_skill_kyoukatsu,      // constant 0x614
        tgs_kasuga_skill_laser,      // constant 0x615
        tgs_kasuga_skill_binta1,         // constant 0x616
        tgs_kasuga_skill_baisyu,         // constant 0x617
        tgs_kasuga_skill_binta3,         // constant 0x618
        tgs_kasuga_job02_skill_11,       // constant 0x619
        tgs_nanba_skill_heal1,       // constant 0x61A
        tgs_nanba_skill_self_heal2,      // constant 0x61B
        tgs_nanba_skill_recover,         // constant 0x61C
        tgs_nanba_skill_heal2,       // constant 0x61D
        tgs_nanba_skill_self_heal3,      // constant 0x61E
        tgs_nanba_skill_kizuna,      // constant 0x61F
        tgs_adachi_skill_03,         // constant 0x620
        tgs_adachi_skill_kizuna,         // constant 0x621
        tgs_saeko_skill_01,      // constant 0x622
        tgs_saeko_skill_03,      // constant 0x623
        tgs_saeko_skill_02,      // constant 0x624
        tgs_saeko_skill_05,      // constant 0x625
        tgs_saeko_skill_04,      // constant 0x626
        tgs_saeko_skill_06,      // constant 0x627
        tgs_saeko_skill_kizuna,      // constant 0x628
        tgs_kasuga_job02_skill_06,       // constant 0x629
        tgs_kasuga_job02_skill_09,       // constant 0x62A
        tgs_kasuga_job02_skill_08,       // constant 0x62B
        tgs_kasuga_job02_skill_02,       // constant 0x62C
        tgs_kasuga_job04_skill_01,       // constant 0x62D
        tgs_kasuga_job04_skill_04,       // constant 0x62E
        tgs_kasuga_job04_skill_11,       // constant 0x62F
        tgs_kasuga_job04_skill_12,       // constant 0x630
        tgs_kasuga_job04_skill_07,       // constant 0x631
        tgs_kasuga_job04_skill_09,       // constant 0x632
        tgs_kasuga_job04_skill_10,       // constant 0x633
        tgs_kasuga_job04_skill_08,       // constant 0x634
        tgs_kasuga_job04_skill_06,       // constant 0x635
        tgs_nanba_job01_skill_07,        // constant 0x636
        tgs_nanba_job01_skill_12,        // constant 0x637
        tgs_nanba_job01_skill_01,        // constant 0x638
        tgs_nanba_job01_skill_10,        // constant 0x639
        tgs_nanba_job01_skill_05,        // constant 0x63A
        tgs_nanba_job01_skill_11,        // constant 0x63B
        tgs_nanba_job01_skill_06,        // constant 0x63C
        tgs_nanba_job01_skill_09,        // constant 0x63D
        tgs_adachi_job01_skill_counter,      // constant 0x63E
        tgs_adachi_job01_skill_counter_act,      // constant 0x63F
        tgs_adachi_job01_skill_counter_end,      // constant 0x640
        tgs_adachi_job01_skill_12,       // constant 0x641
        tgs_adachi_job01_skill_14,       // constant 0x642
        tgs_adachi_job01_skill_07,       // constant 0x643
        tgs_adachi_job01_skill_11,       // constant 0x644
        tgs_adachi_job01_skill_04,       // constant 0x645
        tgs_adachi_job01_skill_05,       // constant 0x646
        tgs_adachi_job01_skill_10,       // constant 0x647
        tgs_adachi_job01_skill_13,       // constant 0x648
        tgs_saeko_job01_skill_01,        // constant 0x649
        tgs_saeko_job01_skill_02,        // constant 0x64A
        tgs_saeko_job01_skill_08,        // constant 0x64B
        tgs_saeko_job01_skill_11,        // constant 0x64C
        tgs_saeko_job01_skill_03,        // constant 0x64D
        tgs_saeko_job01_skill_04,        // constant 0x64E
        tgs_saeko_job01_skill_06,        // constant 0x64F
        tgs_saeko_job01_skill_05,        // constant 0x650
        tgs_saeko_job01_skill_09,        // constant 0x651
        tgs_saeko_job01_skill_10,        // constant 0x652
        tgs_saeko_job01_skill_07,        // constant 0x653
        tgs_saeko_job01_skill_12,        // constant 0x654
        tgs_job_bodyguard_skill_01,      // constant 0x655
        tgs_job_bodyguard_skill_04,      // constant 0x656
        tgs_job_bodyguard_skill_10,      // constant 0x657
        tgs_job_bodyguard_skill_09,      // constant 0x658
        tgs_job_bodyguard_skill_08,      // constant 0x659
        tgs_job_bodyguard_skill_06,      // constant 0x65A
        tgs_job_host_skill_08,       // constant 0x65B
        tgs_job_host_skill_11,       // constant 0x65C
        tgs_job_host_skill_05,       // constant 0x65D
        tgs_job_host_skill_07,       // constant 0x65E
        tgs_job_host_skill_06,       // constant 0x65F
        tgs_job_host_skill_12,       // constant 0x660
        tgs_job_host_skill_10,       // constant 0x661
        tgs_job_host_skill_09,       // constant 0x662
        tgs_job_host_skill_02,       // constant 0x663
        tgs_job_dancer_skill_05,         // constant 0x664
        tgs_job_dancer_skill_08,         // constant 0x665
        tgs_job_dancer_skill_03,         // constant 0x666
        tgs_job_dancer_skill_04,         // constant 0x667
        tgs_job_dancer_skill_07,         // constant 0x668
        tgs_job_dancer_skill_09,         // constant 0x669
        tgs_job_dancer_skill_11,         // constant 0x66A
        tgs_job_dancer_skill_10,         // constant 0x66B
        tgs_job_dancer_skill_12,         // constant 0x66C
        tgs_job_idol_skill_01,       // constant 0x66D
        tgs_job_idol_skill_02,       // constant 0x66E
        tgs_job_idol_skill_07,       // constant 0x66F
        tgs_job_idol_skill_11,       // constant 0x670
        tgs_job_idol_skill_08,       // constant 0x671
        tgs_job_idol_skill_05,       // constant 0x672
        tgs_job_idol_skill_06,       // constant 0x673
        tgs_job_idol_skill_03,       // constant 0x674
        tgs_job_idol_skill_09,       // constant 0x675
        tgs_job_idol_skill_04,       // constant 0x676
        tgs_job_idol_skill_10,       // constant 0x677
        boss_mabuchi_i_grd,      // constant 0x678
        boss_mabuchi_i_grd_act,      // constant 0x679
        boss_mabuchi_i_grd_en,       // constant 0x67A
        adachi_job01_skill_04_suc,       // constant 0x67B
        adachi_job01_skill_04_fail,      // constant 0x67C
        equip_healplus_02,       // constant 0x67D
        equip_fireelectricwater_damage_02,       // constant 0x67E
        equip_equipjob_healplus_02,      // constant 0x67F
        equip_reviveplus_02,         // constant 0x680
        equip_normalattack_magic_02,         // constant 0x681
        boss_arakawa_pvk_c,      // constant 0x682
        boss_arakawa_skl_rev1,       // constant 0x683
        boss_arakawa_skl_rev2,       // constant 0x684
        boss_arakawa_skl_rerise,         // constant 0x685
        shokunin_bomb_throw,         // constant 0x686
        boss_ishioda_hact_01,        // constant 0x687
        boss_ishioda_hact_02,        // constant 0x688
        equip_weapon_saeko_017,      // constant 0x689
        equip_weapon_idol_014,       // constant 0x68A
        boss_kiryu_rush_counter,         // constant 0x68B
        boss_kiryu_rush_counter_en,      // constant 0x68C
        boss_kiryu_rush_swy_atk_l,       // constant 0x68D
        boss_kiryu_rush_swy_atk_r,       // constant 0x68E
        equip_weapon_fortuneteller_006,      // constant 0x68F
        equip_daiju,         // constant 0x690
        job_devil_skill_06_success,      // constant 0x691
        job_devil_skill_06_failed,       // constant 0x692
        equip_bougohuku,         // constant 0x693
        equip_sarashi01,         // constant 0x694
        equip_sarashi02,         // constant 0x695
        equip_sarashi03,         // constant 0x696
        equip_sarashi04,         // constant 0x697
        equip_belt01,        // constant 0x698
        equip_belt02,        // constant 0x699
        equip_belt03,        // constant 0x69A
        equip_belt04,        // constant 0x69B
        itm_heal_HP_target_all,      // constant 0x69C
        itm_heal_HP_lv2_target_all,      // constant 0x69D
        itm_heal_HP_lv3_target_all,      // constant 0x69E
        itm_heal_target_all,         // constant 0x69F
        itm_heal_lv2_target_all,         // constant 0x6A0
        itm_heal_lv3_target_all,         // constant 0x6A1
        kasuga_job04_skill_12_success,       // constant 0x6A2
        kasuga_job04_skill_12_failed,        // constant 0x6A3
        itm_ningen_osyare_fits,      // constant 0x6A4
        itm_ningen_osyare_twist,         // constant 0x6A5
        equip_yazawa_accessory_042,      // constant 0x6A6
        equip_yazawa_accessory_043,      // constant 0x6A7
        equip_yazawa_accessory_044,      // constant 0x6A8
        equip_yazawa_accessory_045,      // constant 0x6A9
        equip_yazawa_accessory_046,      // constant 0x6AA
        equip_yazawa_accessory_047,      // constant 0x6AB
        equip_yazawa_accessory_048,      // constant 0x6AC
        equip_yazawa_accessory_049,      // constant 0x6AD
        equip_yazawa_accessory_050,      // constant 0x6AE
        equip_yazawa_accessory_051,      // constant 0x6AF
        equip_yazawa_accessory_052,      // constant 0x6B0
        equip_yazawa_accessory_053,      // constant 0x6B1
        equip_yazawa_accessory_055,      // constant 0x6B2
        equip_yazawa_accessory_056,      // constant 0x6B3
        equip_yazawa_accessory_082,      // constant 0x6B4
        equip_yazawa_accessory_083,      // constant 0x6B5
        equip_yazawa_accessory_086,      // constant 0x6B6
        equip_yazawa_accessory_089,      // constant 0x6B7
        equip_kuroobi,       // constant 0x6B8
        equip_yazawa_accessory_034,      // constant 0x6B9
        equip_yazawa_accessory_035,      // constant 0x6BA
        boss_arakawa_pvk_a_en,       // constant 0x6BB
        equip_waitshort_large,       // constant 0x6BC
        equip_anego_001,         // constant 0x6BD
        equip_devil_001,         // constant 0x6BE
        equip_ono_head_027,      // constant 0x6BF
        equip_ono_body_031,      // constant 0x6C0
        equip_ono_leg_030,       // constant 0x6C1
        boss_sawashiro_x_counter_end,        // constant 0x6C2
        boss_kiryu_legend_skl_counter_end,       // constant 0x6C3
        equip_blow_skill_atk_damage_up,      // constant 0x6C4
        equip_slash_skill_atk_damage_up,         // constant 0x6C5
        equip_shoot_skill_atk_damage_up,         // constant 0x6C6
        equip_fire_skill_atk_damage_up,      // constant 0x6C7
        equip_elec_skill_atk_damage_up,      // constant 0x6C8
        equip_ice_skill_atk_damage_up,       // constant 0x6C9
        equip_myweapon_damege_ryu,       // constant 0x6CA
        equip_weapon_bodyguard_013_slash,        // constant 0x6CB
        equip_weapon_absorb_mp_01_fire,      // constant 0x6CC
        equip_weapon_absorb_mp_01_elec,      // constant 0x6CD
        equip_nightqueen_005_elec,       // constant 0x6CE
        equip_weapon_absorb_mp_01_ice,       // constant 0x6CF
        equip_fireelecice_skill_atk_damage_up,       // constant 0x6D0
        boss_sawashiro_brt_counter_end,      // constant 0x6D1
        boss_DH_014,         // constant 0x6D2
        boss_DH_015,         // constant 0x6D3
        boss_DH_016,         // constant 0x6D4
        itm_exp,         // constant 0x6D5
    };
}
