using System;


namespace DragonEngineLibrary
{
    public enum SceneID : uint
    {
        invalid,		 // constant 0x0
        command_auth_test,		 // constant 0x1
        command_event_preview,		 // constant 0x2
        command_event_talk_test,		 // constant 0x3
        command_first_building,		 // constant 0x4
        command_first_nakamichi,		 // constant 0x5
        command_first_tenkaichi,		 // constant 0x6
        command_test_battle,		 // constant 0x7
        system_selector,		 // constant 0x8
        scenario_selector,		 // constant 0x9
        startup_commandline,		 // constant 0xA
        action_first_tenkaichi,		 // constant 0xB
        action_first_nakamichi,		 // constant 0xC
        action_first_building,		 // constant 0xD
        action_second_test_scenario,		 // constant 0xE
        action_battle_validation,		 // constant 0xF
        action_battle_validation_only_btl,		 // constant 0x10
        auth_preview,		 // constant 0x11
        auth_test,		 // constant 0x12
        test_battle,		 // constant 0x13
        test_battle_no_enemy,		 // constant 0x14
        test_toki01,		 // constant 0x15
        test_toki02,		 // constant 0x16
        test_toki03,		 // constant 0x17
        test_toki04,		 // constant 0x18
        test_toki05,		 // constant 0x19
        test_toki06,		 // constant 0x1A
        test_toki07,		 // constant 0x1B
        test_auth_exit,		 // constant 0x1C
        test_oda01,		 // constant 0x1D
        test_oyama01,		 // constant 0x1E
        test_chara,		 // constant 0x1F
        test_chara_t_pose,		 // constant 0x20
        test_cube_render,		 // constant 0x21
        test_eito01,		 // constant 0x22
        test_eito_examples,		 // constant 0x23
        test_eito_swathe,		 // constant 0x24
        test_atsu01,		 // constant 0x25
        test_waraman01,		 // constant 0x26
        test_waraman02,		 // constant 0x27
        test_waraman03,		 // constant 0x28
        test_effect_glass,		 // constant 0x29
        test_effect_vollight,		 // constant 0x2A
        test_takakie01,		 // constant 0x2B
        test_look_at,		 // constant 0x2C
        test_asset,		 // constant 0x2D
        test_asset_auto_check,		 // constant 0x2E
        test_inaguma_debug01,		 // constant 0x2F
        test_inaguma_debug02,		 // constant 0x30
        test_shoji_k,		 // constant 0x31
        test_shoji_k_save_data,		 // constant 0x32
        test_shoji_k_companion,		 // constant 0x33
        test_talk,		 // constant 0x34
        test_chishow,		 // constant 0x35
        test_ai_mob,		 // constant 0x36
        test_ai_combat,		 // constant 0x37
        test_nakais,		 // constant 0x38
        test_nakais_db,		 // constant 0x39
        test_nakais_puid,		 // constant 0x3A
        test_nakais_ui,		 // constant 0x3B
        test_db_runtime_test,		 // constant 0x3C
        test_particle,		 // constant 0x3D
        test_yhattori_http_server,		 // constant 0x3E
        test_yhattori_movie,		 // constant 0x3F
        test_yhattori_sound,		 // constant 0x40
        test_kato_00,		 // constant 0x41
        test_kato_01,		 // constant 0x42
        test_kato_02,		 // constant 0x43
        test_jack,		 // constant 0x44
        test_google,		 // constant 0x45
        test_stage_st_kamuro_day,		 // constant 0x46
        test_stage_st_kamuro_eve,		 // constant 0x47
        test_stage_st_kamuro_ngt,		 // constant 0x48
        test_stage_st_onomichi_day,		 // constant 0x49
        test_stage_st_onomichi_eve,		 // constant 0x4A
        test_stage_st_onomichi_ngt,		 // constant 0x4B
        test_stage_st_asagao_day,		 // constant 0x4C
        test_stage_st_asagao_eve,		 // constant 0x4D
        test_stage_st_asagao_ngt,		 // constant 0x4E
        test_stage_st_k_asia_ngt,		 // constant 0x4F
        test_stage_st_k_menkai_day,		 // constant 0x50
        test_stage_st_k_tojo_day,		 // constant 0x51
        test_stage_st_k_touto_day,		 // constant 0x52
        test_stage_st_k_touto_eve,		 // constant 0x53
        test_stage_st_k_touto_ngt,		 // constant 0x54
        test_stage_st_h_stadium_day,		 // constant 0x55
        test_stage_st_k_ouka_ngt,		 // constant 0x56
        test_stage_st_k_stardust_day,		 // constant 0x57
        test_stage_te_jimusho_day,		 // constant 0x58
        test_stage_te_jimusho_eve,		 // constant 0x59
        test_stage_te_jimusho_ngt,		 // constant 0x5A
        test_stage_te_0001_day,		 // constant 0x5B
        test_stage_te_0002_day,		 // constant 0x5C
        test_stage_te_0003_day,		 // constant 0x5D
        command_battle_validation,		 // constant 0x5E
        command_stage_id_check01,		 // constant 0x5F
        command_stage_id_check02,		 // constant 0x60
        command_stage_id_check03,		 // constant 0x61
        command_test_scene,		 // constant 0x62
        test_stage_st_kamuro_day_outs,		 // constant 0x63
        test_stage_st_kamuro_eve_outs,		 // constant 0x64
        test_stage_st_kamuro_ngt_outs,		 // constant 0x65
        test_ui_test,		 // constant 0x66
        test_instant_chat,		 // constant 0x67
        test_motion_conv,		 // constant 0x68
        test_spatial_perception,		 // constant 0x69
        test_ohtah_00,		 // constant 0x6A
        test_talk_00,		 // constant 0x6B
        test_asset_auto_check_with_photo,		 // constant 0x6C
        test_stage_st_h_senkouji_day,		 // constant 0x6D
        test_stage_st_h_senkouji_eve,		 // constant 0x6E
        test_stage_st_h_senkouji_ngt,		 // constant 0x6F
        test_event_area,		 // constant 0x70
        test_stroll,		 // constant 0x71
        test_eito_subsequence,		 // constant 0x72
        test_eito_sequel,		 // constant 0x73
        test_car_encount,		 // constant 0x74
        test_encount,		 // constant 0x75
        test_mood_influence,		 // constant 0x76
        test_talk_01,		 // constant 0x77
        test_dynamic_collision,		 // constant 0x78
        test_asset2,		 // constant 0x79
        test_ui_viewer,		 // constant 0x7A
        action_main_scene,		 // constant 0x7B
        test_many_npc,		 // constant 0x7C
        test_toki08,		 // constant 0x7D
        test_stage_st_h_geihinkan_ngt,		 // constant 0x7E
        test_stage_te_0004_day,		 // constant 0x7F
        test_asset3,		 // constant 0x80
        test_stage_st_k_kousoku_day,		 // constant 0x81
        test_stage_st_k_lawroom_day,		 // constant 0x82
        test_stage_st_k_tougen_ngt,		 // constant 0x83
        test_stage_st_k_ginza_ngt,		 // constant 0x84
        test_stage_st_h_island_ngt,		 // constant 0x85
        test_stage_st_k_restaurant_ngt,		 // constant 0x86
        test_stage_st_h_dockyard_ngt,		 // constant 0x87
        test_stage_st_k_daijouji_day,		 // constant 0x88
        test_stage_st_k_daijouji_ngt,		 // constant 0x89
        test_stage_st_k_m_tower_vip_ngt,		 // constant 0x8A
        test_stage_st_h_sagyouba_ngt,		 // constant 0x8B
        test_stage_st_h_sickroom_ngt,		 // constant 0x8C
        test_stage_te_0005_day,		 // constant 0x8D
        test_stage_te_0006_day,		 // constant 0x8E
        test_asset_big,		 // constant 0x8F
        test_stage_te_0007_day,		 // constant 0x90
        test_stage_te_0008_day,		 // constant 0x91
        test_stage_te_asset_day,		 // constant 0x92
        test_stage_st_k_daidouji_day,		 // constant 0x93
        test_stage_st_k_daidouji_ngt,		 // constant 0x94
        test_stage_te_0009_day,		 // constant 0x95
        test_same_player_npc,		 // constant 0x96
        test_instant_mission,		 // constant 0x97
        action_title_scene,		 // constant 0x98
        action_shop,		 // constant 0x99
        test_map_runtime_test,		 // constant 0x9A
        test_ai_layout,		 // constant 0x9B
        test_battle_many_enemy,		 // constant 0x9C
        test_trace_route_path,		 // constant 0x9D
        test_battle_many_enemy_supporter,		 // constant 0x9E
        test_follow_player,		 // constant 0x9F
        test_asset4,		 // constant 0xA0
        test_stroll_city,		 // constant 0xA1
        test_jaunt_stairs,		 // constant 0xA2
        action_continue,		 // constant 0xA3
        test_wanderer,		 // constant 0xA4
        test_asset5,		 // constant 0xA5
        test_asset6,		 // constant 0xA6
        test_encount_city,		 // constant 0xA7
        test_ai_guide,		 // constant 0xA8
        test_stage_te_0010_day,		 // constant 0xA9
        test_battle_hact,		 // constant 0xAA
        action_game_over,		 // constant 0xAB
        action_clan_creator,		 // constant 0xAC
        test_shop_kamuro,		 // constant 0xAD
        test_stage_st_kamuro_day_obj,		 // constant 0xAE
        test_stage_st_kamuro_ngt_obj,		 // constant 0xAF
        test_asset_arms,		 // constant 0xB0
        test_nakais_font,		 // constant 0xB1
        test_ui_runtime_test,		 // constant 0xB2
        test_toki09,		 // constant 0xB3
        test_sound_exec_test,		 // constant 0xB4
        test_stage_st_h_kurusu_room_day,		 // constant 0xB5
        pub_fly_through,		 // constant 0xB6
        pub_fly_through_nakamichi,		 // constant 0xB7
        action_taikenban_announce,		 // constant 0xB8
        test_stage_st_k_hospital_day,		 // constant 0xB9
        test_stage_st_k_hospital_eve,		 // constant 0xBA
        test_stage_st_k_hospital_ngt,		 // constant 0xBB
        test_stage_st_h_tenboudai_day,		 // constant 0xBC
        test_stage_st_h_tenboudai_eve,		 // constant 0xBD
        test_stage_st_h_tenboudai_ngt,		 // constant 0xBE
        test_stage_st_h_hospital_ngt,		 // constant 0xBF
        test_ohtah_01,		 // constant 0xC0
        clean_up_bridge,		 // constant 0xC1
        test_asset_arms2,		 // constant 0xC2
        test_asset7,		 // constant 0xC3
        test_asset8,		 // constant 0xC4
        test_toki10,		 // constant 0xC5
        test_behavior_param,		 // constant 0xC6
        test_hybrid_control_npc,		 // constant 0xC7
        test_waraman_exp,		 // constant 0xC8
        test_instant_mission_pattern,		 // constant 0xC9
        test_stage_te_0011_day,		 // constant 0xCA
        test_stage_te_0012_day,		 // constant 0xCB
        test_ai_chara_generate,		 // constant 0xCC
        test_stage_te_0013_day,		 // constant 0xCD
        test_stage_te_0013_eve,		 // constant 0xCE
        test_stage_te_0013_ngt,		 // constant 0xCF
        test_ai_animal,		 // constant 0xD0
        test_btl_behavior,		 // constant 0xD1
        test_stage_st_k_lawroom_ngt,		 // constant 0xD2
        test_npc_deform,		 // constant 0xD3
        test_stage_st_ferry_day,		 // constant 0xD4
        test_stage_st_prison_day,		 // constant 0xD5
        test_stage_st_h_dockyard_eve,		 // constant 0xD6
        test_yhattori_sound_test,		 // constant 0xD7
        test_inaguma_minigame,		 // constant 0xD8
        test_ai_barker,		 // constant 0xD9
        minigame_batting_center,		 // constant 0xDA
        test_stage_st_h_diving_day,		 // constant 0xDB
        test_stage_st_h_diving_eve,		 // constant 0xDC
        test_stage_st_h_diving_ngt,		 // constant 0xDD
        test_spearfishing,		 // constant 0xDE
        minigame_sandlot_baseball,		 // constant 0xDF
        clan_battle,		 // constant 0xE0
        test_minigame_sports_gym,		 // constant 0xE1
        test_talk_caba,		 // constant 0xE2
        action_alpha_test_area,		 // constant 0xE3
        test_stage_st_k_lawroom_spe,		 // constant 0xE4
        minigame_snack,		 // constant 0xE5
        test_stroll_city_onomichi,		 // constant 0xE6
        minigame_cabaret_solo,		 // constant 0xE7
        minigame_cabaret_escort,		 // constant 0xE8
        test_ai_car,		 // constant 0xE9
        minigame_darts,		 // constant 0xEA
        minigame_sports_gym,		 // constant 0xEB
        test_simple_auth_play,		 // constant 0xEC
        test_stage_st_k_stardust_old_ngt,		 // constant 0xED
        test_stage_st_h_hall_ngt,		 // constant 0xEE
        test_stage_st_k_mtower_ngt,		 // constant 0xEF
        minigame_mahjong,		 // constant 0xF0
        test_stage_mg_mahjong_day,		 // constant 0xF1
        test_ai_param,		 // constant 0xF2
        test_spawn_chair,		 // constant 0xF3
        test_stage_st_k_lawroom_old_day,		 // constant 0xF4
        test_stage_st_k_lawroom_old_ngt,		 // constant 0xF5
        minigame_spearfishing,		 // constant 0xF6
        pass_stage_warp,		 // constant 0xF7
        test_stage_st_h_dockyard_long_ngt,		 // constant 0xF8
        test_nakais_network,		 // constant 0xF9
        sound_check_st_kamuro_test,		 // constant 0xFA
        test_namiki,		 // constant 0xFB
        test_sakaue,		 // constant 0xFC
        minigame_clan_creator,		 // constant 0xFD
        test_instant_mission_dandle,		 // constant 0xFE
        snd_chk_onomichi_apart,		 // constant 0xFF
        snd_chk_onomichi_kiyomi,		 // constant 0x100
        snd_chk_onomichi_moreno,		 // constant 0x101
        snd_chk_onomichi_hirose_ikka,		 // constant 0x102
        snd_chk_onomichi_mng_snack,		 // constant 0x103
        snd_chk_onomichi_railway_bridge,		 // constant 0x104
        snd_chk_onomichi_ropeway,		 // constant 0x105
        snd_chk_onomichi_arcade,		 // constant 0x106
        snd_chk_onomichi_shrine,		 // constant 0x107
        snd_chk_onomichi_ferry,		 // constant 0x108
        test_stage_st_livestage_day,		 // constant 0x109
        test_minigame_pitch_ball,		 // constant 0x10A
        minigame_karaoke,		 // constant 0x10B
        test_chara_attach,		 // constant 0x10C
        minigame_clan_creator_menu,		 // constant 0x10D
        test_character_base,		 // constant 0x10E
        minigame_sandlot_baseball_menu,		 // constant 0x10F
        test_toki11,		 // constant 0x110
        snd_chk_onomichi_senkouji,		 // constant 0x111
        snd_chk_kamuro_out_tenkaichi,		 // constant 0x112
        snd_chk_kamuro_out_gekizyo,		 // constant 0x113
        snd_chk_kamuro_out_mtower,		 // constant 0x114
        snd_chk_kamuro_out_batting,		 // constant 0x115
        snd_chk_kamuro_out_parking,		 // constant 0x116
        snd_chk_kamuro_out_ajiagai,		 // constant 0x117
        snd_chk_kamuro_out_senryo_st,		 // constant 0x118
        snd_chk_kamuro_out_pink_st,		 // constant 0x119
        snd_chk_kamuro_out_nakamichi_st,		 // constant 0x11A
        snd_chk_kamuro_in_mtower_low,		 // constant 0x11B
        snd_chk_kamuro_in_shine,		 // constant 0x11C
        snd_chk_kamuro_in_apahotel_lobby,		 // constant 0x11D
        snd_chk_kamuro_in_apahotel_room,		 // constant 0x11E
        snd_chk_kamuro_in_gesui01,		 // constant 0x11F
        snd_chk_kamuro_in_gesui02,		 // constant 0x120
        snd_chk_kamuro_out_lovehotel_st,		 // constant 0x121
        snd_chk_kamuro_in_hanrai,		 // constant 0x122
        snd_chk_kamuro_in_senryo_bldg_01,		 // constant 0x123
        snd_chk_kamuro_in_nakamichi_bldg_01,		 // constant 0x124
        snd_chk_kamuro_in_emoto_bldg_01,		 // constant 0x125
        snd_chk_kamuro_in_tenkaichi_bldg_01,		 // constant 0x126
        snd_chk_kamuro_in_rizap,		 // constant 0x127
        test_yoshimitsu,		 // constant 0x128
        test_stage_st_dream_day,		 // constant 0x129
        test_stage_st_amon_day,		 // constant 0x12A
        test_ai_cat_cafe,		 // constant 0x12B
        minigame_sports_gym_result,		 // constant 0x12C
        test_ai_div_ai,		 // constant 0x12D
        empty,		 // constant 0x12E
        snd_chk_onomichi_tenboudai,		 // constant 0x12F
        snd_chk_kamuro_in_serena,		 // constant 0x130
        minigame_dandle_baby,		 // constant 0x131
        snd_chk_onomichi_senkouji_day,		 // constant 0x132
        snd_chk_onomichi_senkouji_eve,		 // constant 0x133
        snd_chk_onomichi_senkouji_ngt,		 // constant 0x134
        snd_chk_onomichi_tenboudai_day,		 // constant 0x135
        snd_chk_onomichi_tenboudai_eve,		 // constant 0x136
        snd_chk_onomichi_tenboudai_ngt,		 // constant 0x137
        minigame_offertory_box,		 // constant 0x138
        test_instant_mission_cat_capture,		 // constant 0x139
        minigame_vf5fs,		 // constant 0x13A
        minigame_batting_center_challenge,		 // constant 0x13B
        minigame_batting_center_homerun,		 // constant 0x13C
        test_talk_02,		 // constant 0x13D
        minigame_live_chat,		 // constant 0x13E
        test_cat_cafe,		 // constant 0x13F
        test_instant_mission_dandle_access,		 // constant 0x140
        test_ai_mob_avoid,		 // constant 0x141
        test_stage,		 // constant 0x142
        test_ai_layout_cheer,		 // constant 0x143
        minigame_puyo,		 // constant 0x144
        test_stage_st_title_day,		 // constant 0x145
        test_stage_st_jimu0001_day,		 // constant 0x146
        minigame_karaoke_kamuro,		 // constant 0x147
        minigame_sagaages_fzn,		 // constant 0x148
        minigame_sagaages_hng,		 // constant 0x149
        minigame_sagaages_otr,		 // constant 0x14A
        minigame_sagaages_sph,		 // constant 0x14B
        minigame_segaages_fzn,		 // constant 0x14C
        minigame_segaages_hng,		 // constant 0x14D
        minigame_segaages_otr,		 // constant 0x14E
        minigame_segaages_sph,		 // constant 0x14F
        test_cat_cafe_kamuro,		 // constant 0x150
        cache_restore,		 // constant 0x151
        test_minigame_offerings,		 // constant 0x152
        test_stage_st_onomichi_spe,		 // constant 0x153
        test_stage_st_h_stadium_eve,		 // constant 0x154
        test_stage_st_jimu0001_eve,		 // constant 0x155
        test_stage_st_jimu0001_ngt,		 // constant 0x156
        test_random_point,		 // constant 0x157
        clan_story,		 // constant 0x158
        test_adv,		 // constant 0x159
        test_battle_saka,		 // constant 0x15A
        test_adv_saka,		 // constant 0x15B
        snd_chk_kamuro_coma_rooftop,		 // constant 0x15C
        taiken_last_info,		 // constant 0x15D
        uniq_manager_reset,		 // constant 0x15E
        timer_setting,		 // constant 0x15F
        game_reset,		 // constant 0x160
        test_instant_mission_random_select,		 // constant 0x161
        minigame_karaoke_denmoku,		 // constant 0x162
        test_stage_st_osaka_day,		 // constant 0x163
        test_stage_st_osaka_ngt,		 // constant 0x164
        test_stage_st_o_grand_day,		 // constant 0x165
        test_stage_st_k_shine_day,		 // constant 0x166
        test_stage_st_k_disco_ngt,		 // constant 0x167
        test_stage_st_old_buil_ngt,		 // constant 0x168
        test_stage_st_k_doujima_ngt,		 // constant 0x169
        test_stage_st_o_kazabori_day,		 // constant 0x16A
        test_stage_st_kawara_rm_a_day,		 // constant 0x16B
        test_stage_st_kawara_rm_b_day,		 // constant 0x16C
        test_stage_st_k_police_meet_day,		 // constant 0x16D
        test_stage_st_k_shiryou_rm_day,		 // constant 0x16E
        test_stage_st_k_sudou_rm_ngt,		 // constant 0x16F
        test_stage_st_k_police_rouka_day,		 // constant 0x170
        test_stage_st_o_geinou_day,		 // constant 0x171
        test_stage_st_kousoku_ngt,		 // constant 0x172
        test_stage_st_kousoku_fuji_ngt,		 // constant 0x173
        test_stage_st_kiryu_apart_day,		 // constant 0x174
        test_stage_st_o_police_day,		 // constant 0x175
        test_stage_st_o_torishirabe_eve,		 // constant 0x176
        test_stage_st_o_torishirabe_ngt,		 // constant 0x177
        test_stage_st_o_kouno_day,		 // constant 0x178
        test_stage_st_k_takashima_day,		 // constant 0x179
        test_stage_st_o_tamiyo_rm_day,		 // constant 0x17A
        test_stage_st_sai_day,		 // constant 0x17B
        test_stage_st_sai_majima_rm_day,		 // constant 0x17C
        test_stage_st_sai_tougi_day,		 // constant 0x17D
        test_stage_st_k_tougenkyo_ngt,		 // constant 0x17E
        test_stage_st_kill_elv_ngt,		 // constant 0x17F
        test_stage_st_kill_road_a_ngt,		 // constant 0x180
        test_stage_st_kill_road_b_ngt,		 // constant 0x181
        test_stage_st_bochi_day,		 // constant 0x182
        test_stage_st_ambulance_day,		 // constant 0x183
        test_stage_st_k_m_transform_day,		 // constant 0x184
        test_stage_st_k_m_kazama_ngt,		 // constant 0x185
        test_stage_st_k_m_monitor_day,		 // constant 0x186
        test_stage_st_o_sogeki_day,		 // constant 0x187
        test_stage_st_k_hotel_bar_day,		 // constant 0x188
        test_stage_st_k_kidsroom_day,		 // constant 0x189
        test_mind_control,		 // constant 0x18A
        test_ai_script_and_node,		 // constant 0x18B
        test_stage_st_k_amano_buil_ngt,		 // constant 0x18C
        test_stage_st_k_amano_roof_ngt,		 // constant 0x18D
        test_stage_st_o_shiro_ngt,		 // constant 0x18E
        test_stage_st_osaka_day_outs,		 // constant 0x18F
        test_stage_st_osaka_eve_outs,		 // constant 0x190
        test_ui_spy,		 // constant 0x191
        test_toki12,		 // constant 0x192
        test_stage_st_kamuro_day_judge,		 // constant 0x193
        test_stage_st_kamuro_ngt_judge,		 // constant 0x194
        test_stage_st_osaka_day_judge,		 // constant 0x195
        test_stage_st_osaka_ngt_judge,		 // constant 0x196
        test_stage_st_k_tojo_day_judge,		 // constant 0x197
        test_stage_st_o_grand_day_judge,		 // constant 0x198
        test_stage_st_k_shine_day_judge,		 // constant 0x199
        test_stage_st_k_disco_ngt_judge,		 // constant 0x19A
        test_stage_st_old_buil_ngt_judge,		 // constant 0x19B
        test_stage_st_k_doujima_ngt_judge,		 // constant 0x19C
        test_stage_st_o_kazabori_day_judge,		 // constant 0x19D
        test_stage_st_kawara_rm_a_day_judge,		 // constant 0x19E
        test_stage_st_kawara_rm_b_day_judge,		 // constant 0x19F
        test_stage_st_k_police_meet_day_judge,		 // constant 0x1A0
        test_stage_st_k_shiryou_rm_day_judge,		 // constant 0x1A1
        test_stage_st_k_sudou_rm_ngt_judge,		 // constant 0x1A2
        test_stage_st_k_police_rouka_day_judge,		 // constant 0x1A3
        test_stage_st_o_geinou_day_judge,		 // constant 0x1A4
        test_stage_st_kousoku_ngt_judge,		 // constant 0x1A5
        test_stage_st_kousoku_fuji_ngt_judge,		 // constant 0x1A6
        test_stage_st_kiryu_apart_day_judge,		 // constant 0x1A7
        test_stage_st_o_police_day_judge,		 // constant 0x1A8
        test_stage_st_o_torishirabe_eve_judge,		 // constant 0x1A9
        test_stage_st_o_torishirabe_ngt_judge,		 // constant 0x1AA
        test_stage_st_o_kouno_day_judge,		 // constant 0x1AB
        test_stage_st_k_takashima_day_judge,		 // constant 0x1AC
        test_stage_st_o_tamiyo_rm_day_judge,		 // constant 0x1AD
        test_stage_st_sai_day_judge,		 // constant 0x1AE
        test_stage_st_sai_majima_rm_day_judge,		 // constant 0x1AF
        test_stage_st_sai_tougi_day_judge,		 // constant 0x1B0
        test_stage_st_k_tougenkyo_ngt_judge,		 // constant 0x1B1
        test_stage_st_kill_elv_ngt_judge,		 // constant 0x1B2
        test_stage_st_kill_road_a_ngt_judge,		 // constant 0x1B3
        test_stage_st_kill_road_b_ngt_judge,		 // constant 0x1B4
        test_stage_st_bochi_day_judge,		 // constant 0x1B5
        test_stage_st_ambulance_day_judge,		 // constant 0x1B6
        test_stage_st_k_m_transform_day_judge,		 // constant 0x1B7
        test_stage_st_k_m_kazama_ngt_judge,		 // constant 0x1B8
        test_stage_st_k_m_monitor_day_judge,		 // constant 0x1B9
        test_stage_st_o_sogeki_day_judge,		 // constant 0x1BA
        test_stage_st_k_stardust_day_judge,		 // constant 0x1BB
        test_stage_st_k_hotel_bar_day_judge,		 // constant 0x1BC
        test_stage_st_k_kidsroom_day_judge,		 // constant 0x1BD
        test_stage_st_k_amano_buil_ngt_judge,		 // constant 0x1BE
        test_stage_st_k_amano_roof_ngt_judge,		 // constant 0x1BF
        test_stage_st_o_shiro_ngt_judge,		 // constant 0x1C0
        test_stage_mg_mahjong_day_judge,		 // constant 0x1C1
        test_stage_te_0001_day_judge,		 // constant 0x1C2
        test_stage_te_0002_day_judge,		 // constant 0x1C3
        test_stage_te_0004_day_judge,		 // constant 0x1C4
        test_stage_te_asset_day_judge,		 // constant 0x1C5
        minigame_cabaret_island,		 // constant 0x1C6
        test_stage_st_kamuro_eve_judge,		 // constant 0x1C7
        minigame_chinchiro,		 // constant 0x1C8
        minigame_blackjack,		 // constant 0x1C9
        test_street_sampler,		 // constant 0x1CA
        test_stage_te_0007_eve,		 // constant 0x1CB
        test_stage_te_0007_ngt,		 // constant 0x1CC
        test_shibayama_cmm,		 // constant 0x1CD
        test_waraman_exp2,		 // constant 0x1CE
        test_shibayama,		 // constant 0x1CF
        stalking,		 // constant 0x1D0
        test_stage_st_kamuro_day_judge_kari,		 // constant 0x1D1
        test_stage_st_kamuro_eve_judge_kari,		 // constant 0x1D2
        test_stage_st_kamuro_ngt_judge_kari,		 // constant 0x1D3
        test_stage_te_0001_day_judge_kari,		 // constant 0x1D4
        test_stage_te_0002_day_judge_kari,		 // constant 0x1D5
        test_stage_te_0004_day_judge_kari,		 // constant 0x1D6
        test_stage_te_asset_day_judge_kari,		 // constant 0x1D7
        test_stage_st_kamuro_judge_day,		 // constant 0x1D8
        test_stage_st_kamuro_judge_eve,		 // constant 0x1D9
        test_stage_st_kamuro_judge_ngt,		 // constant 0x1DA
        test_stage_te_0001_judge_day,		 // constant 0x1DB
        test_stage_te_0002_judge_day,		 // constant 0x1DC
        test_stage_te_0004_judge_day,		 // constant 0x1DD
        test_stage_te_asset_judge_day,		 // constant 0x1DE
        minigame_batting_center_competition,		 // constant 0x1DF
        test_stage_mg_mahjong_judge_day,		 // constant 0x1E0
        test_toki13,		 // constant 0x1E1
        test_stage_st_o_oumi_day,		 // constant 0x1E2
        test_stage_st_k_hills_ngt,		 // constant 0x1E3
        test_stage_st_o_syougi_day,		 // constant 0x1E4
        test_stage_st_shinkansen_ngt,		 // constant 0x1E5
        test_stage_st_o_sengoku_ngt,		 // constant 0x1E6
        test_stage_st_o_roof_date_ngt,		 // constant 0x1E7
        test_stage_st_o_caba_day,		 // constant 0x1E8
        test_stage_mg_karaoke_sp_day,		 // constant 0x1E9
        minigame_batting_center_challenge_lexus2,		 // constant 0x1EA
        minigame_batting_center_homerun_lexus2,		 // constant 0x1EB
        minigame_batting_center_challenge_judge,		 // constant 0x1EC
        minigame_batting_center_homerun_judge,		 // constant 0x1ED
        test_satohk,		 // constant 0x1EE
        test_stage_st_kamuro_judge_spe,		 // constant 0x1EF
        test_stage_st_menkaijo_judge_day,		 // constant 0x1F0
        test_stage_st_saibansyo_judge_day,		 // constant 0x1F1
        test_stage_st_souyakucenter_judge_day,		 // constant 0x1F2
        test_stage_st_souyakucenter_judge_eve,		 // constant 0x1F3
        test_stage_st_souyakucenter_judge_ngt,		 // constant 0x1F4
        test_stage_st_souyakucenter_judge_spe,		 // constant 0x1F5
        test_stage_st_kensatsuchou_judge_day,		 // constant 0x1F6
        test_stage_st_kikunoya_judge_ngt,		 // constant 0x1F7
        test_stage_st_toba_judge_ngt,		 // constant 0x1F8
        test_stage_st_honmaruden_judge_ngt,		 // constant 0x1F9
        test_stage_st_torishirabe_judge_day,		 // constant 0x1FA
        test_stage_st_apartment_judge_ngt,		 // constant 0x1FB
        test_stage_st_soreiyu_judge_ngt,		 // constant 0x1FC
        test_stage_st_for_casino_ngt,		 // constant 0x1FD
        test_stage_st_for_casino_day,		 // constant 0x1FE
        minigame_shogi,		 // constant 0x1FF
        test_stage_st_k_tojo_ngt,		 // constant 0x200
        test_ote_stage,		 // constant 0x201
        minigame_poker,		 // constant 0x202
        test_stage_st_k_m_monitor_ngt,		 // constant 0x203
        test_shoji_k_webapi,		 // constant 0x204
        minigame_drone_race,		 // constant 0x205
        test_character_preview,		 // constant 0x206
        test_connect_hand,		 // constant 0x207
        test_waraman_exp3,		 // constant 0x208
        minigame_hanafuda,		 // constant 0x209
        test_stage_st_title_judge_day,		 // constant 0x20A
        minigame_lock_picking,		 // constant 0x20B
        test_yanagisako,		 // constant 0x20C
        test_battle_saka_judge,		 // constant 0x20D
        test_stage_st_old_buil_fire_ngt,		 // constant 0x20E
        test_stage_st_for_hanahuda_day,		 // constant 0x20F
        test_stage_st_for_casino_judge_day,		 // constant 0x210
        chase,		 // constant 0x211
        test_stage_st_mg_golf_day,		 // constant 0x212
        test_stage_st_mg_golf_ngt,		 // constant 0x213
        test_stage_st_mg_video_day,		 // constant 0x214
        test_stage_st_sai_fukumaden_day,		 // constant 0x215
        minigame_ufo_catcher,		 // constant 0x216
        test_stage_st_for_shogi_day,		 // constant 0x217
        test_stage_st_for_hanahuda_judge_day,		 // constant 0x218
        test_stage_st_for_shogi_judge_day,		 // constant 0x219
        test_stage_te_0005_judge_day,		 // constant 0x21A
        test_stage_te_0006_judge_day,		 // constant 0x21B
        minigame_toylets_k,		 // constant 0x21C
        minigame_toylets_o,		 // constant 0x21D
        test_stage_st_o_shiro_soto_ngt,		 // constant 0x21E
        test_effect_chara,		 // constant 0x21F
        test_stage_st_k_tougenkyo_b_ngt,		 // constant 0x220
        test_stage_st_honmaruen_judge_ngt,		 // constant 0x221
        minigame_golf_driving_range,		 // constant 0x222
        test_stage_st_toilet_ngt,		 // constant 0x223
        test_stage_st_toilet_day,		 // constant 0x224
        test_stage_st_k_hills_elv_ngt,		 // constant 0x225
        test_stage_st_kousoku_day,		 // constant 0x226
        test_takahashit3,		 // constant 0x227
        test_dynamic_collision_battle,		 // constant 0x228
        test_stage_st_mg_nozoki_day,		 // constant 0x229
        test_stage_st_clan_nishikouen_day,		 // constant 0x22A
        test_stage_st_clan_nishikouen_ngt,		 // constant 0x22B
        minigame_darts_judge,		 // constant 0x22C
        test_nakais_ui_3d,		 // constant 0x22D
        test_stage_st_o_grand_eve,		 // constant 0x22E
        test_stage_st_o_grand_ngt,		 // constant 0x22F
        test_stage_st_o_grand_spe,		 // constant 0x230
        test_stage_st_k_shine_eve,		 // constant 0x231
        test_stage_st_k_shine_ngt,		 // constant 0x232
        test_stage_st_k_shine_spe,		 // constant 0x233
        test_stage_st_o_kazabori_eve,		 // constant 0x234
        test_stage_st_o_kazabori_ngt,		 // constant 0x235
        test_stage_st_o_kazabori_spe,		 // constant 0x236
        test_stage_st_kawara_rm_a_eve,		 // constant 0x237
        test_stage_st_kawara_rm_a_ngt,		 // constant 0x238
        test_stage_st_kawara_rm_a_spe,		 // constant 0x239
        test_stage_st_kawara_rm_b_eve,		 // constant 0x23A
        test_stage_st_kawara_rm_b_ngt,		 // constant 0x23B
        test_stage_st_kawara_rm_b_spe,		 // constant 0x23C
        test_stage_st_k_police_meet_eve,		 // constant 0x23D
        test_stage_st_k_police_meet_ngt,		 // constant 0x23E
        test_stage_st_k_police_meet_spe,		 // constant 0x23F
        test_stage_st_k_shiryou_rm_eve,		 // constant 0x240
        test_stage_st_k_shiryou_rm_ngt,		 // constant 0x241
        test_stage_st_k_shiryou_rm_spe,		 // constant 0x242
        test_stage_st_k_police_rouka_eve,		 // constant 0x243
        test_stage_st_k_police_rouka_ngt,		 // constant 0x244
        test_stage_st_k_police_rouka_spe,		 // constant 0x245
        test_stage_st_o_geinou_eve,		 // constant 0x246
        test_stage_st_o_geinou_ngt,		 // constant 0x247
        test_stage_st_o_geinou_spe,		 // constant 0x248
        test_stage_st_kousoku_btl_ngt,		 // constant 0x249
        test_stage_st_sai_eve,		 // constant 0x24A
        test_stage_st_sai_ngt,		 // constant 0x24B
        test_stage_st_sai_spe,		 // constant 0x24C
        test_stage_st_sai_majima_rm_eve,		 // constant 0x24D
        test_stage_st_sai_majima_rm_ngt,		 // constant 0x24E
        test_stage_st_sai_majima_rm_spe,		 // constant 0x24F
        test_stage_st_sai_tougi_eve,		 // constant 0x250
        test_stage_st_sai_tougi_ngt,		 // constant 0x251
        test_stage_st_sai_tougi_spe,		 // constant 0x252
        test_stage_st_k_m_transform_eve,		 // constant 0x253
        test_stage_st_k_m_transform_ngt,		 // constant 0x254
        test_stage_st_k_m_transform_spe,		 // constant 0x255
        test_stage_st_k_stardust_eve,		 // constant 0x256
        test_stage_st_k_stardust_ngt,		 // constant 0x257
        test_stage_st_k_stardust_spe,		 // constant 0x258
        test_stage_st_k_hotel_bar_eve,		 // constant 0x259
        test_stage_st_k_hotel_bar_ngt,		 // constant 0x25A
        test_stage_st_k_hotel_bar_spe,		 // constant 0x25B
        test_stage_st_k_kidsroom_eve,		 // constant 0x25C
        test_stage_st_k_kidsroom_ngt,		 // constant 0x25D
        test_stage_st_k_kidsroom_spe,		 // constant 0x25E
        test_stage_st_o_syougi_eve,		 // constant 0x25F
        test_stage_st_o_syougi_ngt,		 // constant 0x260
        test_stage_st_o_syougi_spe,		 // constant 0x261
        test_stage_st_o_caba_eve,		 // constant 0x262
        test_stage_st_o_caba_ngt,		 // constant 0x263
        test_stage_st_o_caba_spe,		 // constant 0x264
        test_stage_st_for_casino_eve,		 // constant 0x265
        test_stage_st_for_casino_spe,		 // constant 0x266
        test_stage_st_for_hanahuda_eve,		 // constant 0x267
        test_stage_st_for_hanahuda_ngt,		 // constant 0x268
        test_stage_st_for_hanahuda_spe,		 // constant 0x269
        test_stage_st_mg_video_eve,		 // constant 0x26A
        test_stage_st_mg_video_ngt,		 // constant 0x26B
        test_stage_st_mg_video_spe,		 // constant 0x26C
        test_stage_st_sai_fukumaden_eve,		 // constant 0x26D
        test_stage_st_sai_fukumaden_ngt,		 // constant 0x26E
        test_stage_st_sai_fukumaden_spe,		 // constant 0x26F
        test_stage_st_for_shogi_eve,		 // constant 0x270
        test_stage_st_for_shogi_ngt,		 // constant 0x271
        test_stage_st_for_shogi_spe,		 // constant 0x272
        test_stage_st_toilet_eve,		 // constant 0x273
        test_stage_st_toilet_spe,		 // constant 0x274
        test_stage_st_mg_nozoki_eve,		 // constant 0x275
        test_stage_st_mg_nozoki_ngt,		 // constant 0x276
        test_stage_st_mg_nozoki_spe,		 // constant 0x277
        test_stage_mg_karaoke_sp_eve,		 // constant 0x278
        test_stage_mg_karaoke_sp_ngt,		 // constant 0x279
        test_stage_mg_karaoke_sp_spe,		 // constant 0x27A
        test_stage_mg_mahjong_eve,		 // constant 0x27B
        test_stage_mg_mahjong_ngt,		 // constant 0x27C
        test_stage_mg_mahjong_spe,		 // constant 0x27D
        test_stage_te_dynamic_collision_day,		 // constant 0x27E
        test_stage_st_menkaijo_judge_eve,		 // constant 0x27F
        test_stage_st_menkaijo_judge_ngt,		 // constant 0x280
        test_stage_st_menkaijo_judge_spe,		 // constant 0x281
        test_stage_st_saibansyo_judge_eve,		 // constant 0x282
        test_stage_st_saibansyo_judge_ngt,		 // constant 0x283
        test_stage_st_saibansyo_judge_spe,		 // constant 0x284
        test_stage_st_kensatsuchou_judge_eve,		 // constant 0x285
        test_stage_st_kensatsuchou_judge_ngt,		 // constant 0x286
        test_stage_st_kensatsuchou_judge_spe,		 // constant 0x287
        test_stage_st_torishirabe_judge_eve,		 // constant 0x288
        test_stage_st_torishirabe_judge_ngt,		 // constant 0x289
        test_stage_st_torishirabe_judge_spe,		 // constant 0x28A
        test_stage_st_title_judge_eve,		 // constant 0x28B
        test_stage_st_title_judge_ngt,		 // constant 0x28C
        test_stage_st_title_judge_spe,		 // constant 0x28D
        test_stage_st_for_casino_judge_eve,		 // constant 0x28E
        test_stage_st_for_casino_judge_ngt,		 // constant 0x28F
        test_stage_st_for_casino_judge_spe,		 // constant 0x290
        test_stage_st_for_hanahuda_judge_eve,		 // constant 0x291
        test_stage_st_for_hanahuda_judge_ngt,		 // constant 0x292
        test_stage_st_for_hanahuda_judge_spe,		 // constant 0x293
        test_stage_st_for_shogi_judge_eve,		 // constant 0x294
        test_stage_st_for_shogi_judge_ngt,		 // constant 0x295
        test_stage_st_for_shogi_judge_spe,		 // constant 0x296
        test_stage_mg_mahjong_judge_eve,		 // constant 0x297
        test_stage_mg_mahjong_judge_ngt,		 // constant 0x298
        test_stage_mg_mahjong_judge_spe,		 // constant 0x299
        test_stage_te_dynamic_collision_judge_day,		 // constant 0x29A
        test_majima,		 // constant 0x29B
        test_stage_st_studio_day,		 // constant 0x29C
        test_stage_st_studio_eve,		 // constant 0x29D
        test_stage_st_studio_ngt,		 // constant 0x29E
        test_stage_st_studio_spe,		 // constant 0x29F
        minigame_m2ftg,		 // constant 0x2A0
        test_map_navi,		 // constant 0x2A1
        test_nakais_map_navi,		 // constant 0x2A2
        test_stage_st_yagami_day,		 // constant 0x2A3
        test_stage_st_laboratory_ngt,		 // constant 0x2A4
        test_unlocking,		 // constant 0x2A5
        action_majima_scene,		 // constant 0x2A6
        minigame_bouncer_menu,		 // constant 0x2A7
        minigame_oichokabu,		 // constant 0x2A8
        test_ui_test_3d,		 // constant 0x2A9
        test_sugoroku_default,		 // constant 0x2AA
        test_npc_step,		 // constant 0x2AB
        test_sugoroku_kamuro,		 // constant 0x2AC
        test_ai_chara_generate_group,		 // constant 0x2AD
        test_namiki_00,		 // constant 0x2AE
        test_namiki_01,		 // constant 0x2AF
        minigame_peeping,		 // constant 0x2B0
        test_stage_st_mountain_road_day,		 // constant 0x2B1
        test_stage_st_interviewhall_day,		 // constant 0x2B2
        test_stage_st_interviewhall_eve,		 // constant 0x2B3
        test_stage_st_interviewhall_ngt,		 // constant 0x2B4
        test_stage_st_interviewhall_spe,		 // constant 0x2B5
        minigame_tougijyo,		 // constant 0x2B6
        minigame_tougijyo_menu,		 // constant 0x2B7
        minigame_karaoke_osaka,		 // constant 0x2B8
        test_stage_st_honmaruen_judge_spe,		 // constant 0x2B9
        minigame_bouncer,		 // constant 0x2BA
        minigame_darts_souten,		 // constant 0x2BB
        test_stage_st_bochi_spe,		 // constant 0x2BC
        minigame_gravure_shooting_studio,		 // constant 0x2BD
        minigame_rail_shooter,		 // constant 0x2BE
        minigame_sugoroku,		 // constant 0x2BF
        test_stage_st_hikouki_day,		 // constant 0x2C0
        test_stage_st_hikouki_ngt,		 // constant 0x2C1
        test_stage_st_k_uematsu_day,		 // constant 0x2C2
        minigame_sugoroku_battle,		 // constant 0x2C3
        kaisou_dummy_ss_creater,		 // constant 0x2C4
        test_stage_st_tojo_judge_day,		 // constant 0x2C5
        test_stage_st_common_office_judge_day,		 // constant 0x2C6
        test_stage_st_common_office_judge_eve,		 // constant 0x2C7
        test_stage_st_common_office_judge_ngt,		 // constant 0x2C8
        minigame_drone_race_reverse,		 // constant 0x2C9
        minigame_gravure_shooting_studio_meomry,		 // constant 0x2CA
        minigame_gravure_shooting_studio_memory,		 // constant 0x2CB
        minigame_drone_vs,		 // constant 0x2CC
        test_asset_auto_check_with_pickup_photo,		 // constant 0x2CD
        test_stage_st_k_clan_bar_day,		 // constant 0x2CE
        test_stage_st_k_clan_bar_eve,		 // constant 0x2CF
        test_stage_st_k_clan_bar_ngt,		 // constant 0x2D0
        test_stage_st_k_clan_bar_spe,		 // constant 0x2D1
        minigame_drone_vs2,		 // constant 0x2D2
        test_stage_st_toba_judge_spe,		 // constant 0x2D3
        test_stage_st_apartment_judge_spe,		 // constant 0x2D4
        game_over_tips_default,		 // constant 0x2D5
        kaisou_list_creater,		 // constant 0x2D6
        test_stage_te_0007_judge_day,		 // constant 0x2D7
        test_stage_te_0007_judge_eve,		 // constant 0x2D8
        minigame_decorate_office,		 // constant 0x2D9
        minigame_photo_shooting,		 // constant 0x2DA
        test_toki14,		 // constant 0x2DB
        continue_to_load_clear_finish,		 // constant 0x2DC
        test_stage_st_sai_tougi_judge_day,		 // constant 0x2DD
        test_stage_st_sai_tougi_judge_eve,		 // constant 0x2DE
        test_stage_st_sai_tougi_judge_ngt,		 // constant 0x2DF
        test_stage_st_sai_tougi_judge_spe,		 // constant 0x2E0
        minigame_pinball,		 // constant 0x2E1
        test_stage_st_dress_up_judge_day,		 // constant 0x2E2
        test_stage_st_dress_up_judge_eve,		 // constant 0x2E3
        test_stage_st_dress_up_judge_ngt,		 // constant 0x2E4
        test_stage_st_dress_up_judge_spe,		 // constant 0x2E5
        test_player_control,		 // constant 0x2E6
        test_db_unittest,		 // constant 0x2E7
        minigame_fv,		 // constant 0x2E8
        minigame_mr,		 // constant 0x2E9
        test_map_unittest,		 // constant 0x2EA
        test_ui_unittest,		 // constant 0x2EB
        test_libpuid_unittest,		 // constant 0x2EC
        minigame_tsume_shogi,		 // constant 0x2ED
        test_particle_capture,		 // constant 0x2EE
        test_inaguma_picking_job,		 // constant 0x2EF
        test_stage_te_0008_judge_day,		 // constant 0x2F0
        test_stage_te_0009_judge_day,		 // constant 0x2F1
        test_stage_st_yokohama_day,		 // constant 0x2F2
        test_stage_st_yokohama_eve,		 // constant 0x2F3
        test_stage_st_yokohama_ngt,		 // constant 0x2F4
        test_study,		 // constant 0x2F5
        test_kuwabara,		 // constant 0x2F6
        test_kurimoto01,		 // constant 0x2F7
        test_stage_te_asset_eve,		 // constant 0x2F8
        test_stage_te_asset_ngt,		 // constant 0x2F9
        test_stage_te_asset_spe,		 // constant 0x2FA
        test_stage_te_dynamic_collision_eve,		 // constant 0x2FB
        test_stage_te_dynamic_collision_ngt,		 // constant 0x2FC
        test_stage_te_dynamic_collision_spe,		 // constant 0x2FD
        test_stage_te_0010_eve,		 // constant 0x2FE
        test_stage_te_0010_ngt,		 // constant 0x2FF
        test_stage_te_0011_eve,		 // constant 0x300
        test_stage_te_0011_ngt,		 // constant 0x301
        test_kurimoto02,		 // constant 0x302
        scene_debug_boot,		 // constant 0x303
        test_stage_st_endroll_judge_day,		 // constant 0x304
        test_stage_st_endroll_judge_eve,		 // constant 0x305
        test_stage_st_endroll_judge_ngt,		 // constant 0x306
        test_stage_st_endroll_judge_spe,		 // constant 0x307
        scene_debug_load,		 // constant 0x308
        minigame_drone_select_tgs,		 // constant 0x309
        minigame_yazawa_dragon_cart,		 // constant 0x30A
        test_dragon_cart,		 // constant 0x30B
        test_stage_st_kamuro_yazawa_now_day,		 // constant 0x30C
        test_stage_st_kamuro_yazawa_now_eve,		 // constant 0x30D
        test_stage_st_kamuro_yazawa_now_ngt,		 // constant 0x30E
        test_stage_st_kamuro_yazawa_past_day,		 // constant 0x30F
        test_stage_st_kamuro_yazawa_past_ngt,		 // constant 0x310
        test_stage_st_butai_ngt,		 // constant 0x311
        test_stage_st_gakuya_ngt,		 // constant 0x312
        test_stage_st_caba_nakai_ngt,		 // constant 0x313
        test_stage_st_jim_nonomura_eve,		 // constant 0x314
        test_stage_st_jim_nonomura_ngt,		 // constant 0x315
        test_stage_st_kamuro_police_day,		 // constant 0x316
        test_stage_st_tougen_birth_day,		 // constant 0x317
        test_stage_st_heianrou_auth_ngt,		 // constant 0x318
        test_stage_st_jim_arakawa_day,		 // constant 0x319
        test_stage_st_jim_arakawa_ngt,		 // constant 0x31A
        test_stage_st_imekura_day,		 // constant 0x31B
        test_stage_st_imekura_ngt,		 // constant 0x31C
        test_stage_st_prison_sagyou_day,		 // constant 0x31D
        test_stage_st_prison_souko_day,		 // constant 0x31E
        test_stage_st_prison_dokkyo_ngt,		 // constant 0x31F
        test_stage_st_prison_zakkyo_ngt,		 // constant 0x320
        test_stage_st_prison_exit_day,		 // constant 0x321
        test_stage_st_salon_day,		 // constant 0x322
        test_stage_st_mg_golf_eve,		 // constant 0x323
        test_stage_st_ron_pv_ngt,		 // constant 0x324
        test_meigaza,		 // constant 0x325
        minigame_yazawa_meigaza,		 // constant 0x326
        test_grass,		 // constant 0x327
        test_stage_mg_cinema_yokohama_day,		 // constant 0x328
        test_stage_mg_cinema_yokohama_ngt,		 // constant 0x329
        test_stage_te_0012_ngt,		 // constant 0x32A
        test_itotsyk_01,		 // constant 0x32B
        test_stage_st_hospital_roka_day,		 // constant 0x32C
        test_stage_st_hospital_roka_ngt,		 // constant 0x32D
        minigame_yazawa_homeless,		 // constant 0x32E
        test_stage_st_tower_mansion_ngt,		 // constant 0x32F
        test_stage_st_caba_luxury_out_ngt,		 // constant 0x330
        test_stage_st_caba_luxury_ngt,		 // constant 0x331
        test_stage_st_k_heianrou_roof_ngt,		 // constant 0x332
        test_stage_st_k_heianrou_vip_ngt,		 // constant 0x333
        test_waraman_exp4,		 // constant 0x334
        minigame_yazawa_dragon_cart_menu,		 // constant 0x335
        test_ui_example,		 // constant 0x336
        test_ui_sample,		 // constant 0x337
        test_physics01,		 // constant 0x338
        test_physics02,		 // constant 0x339
        test_physics03,		 // constant 0x33A
        test_stage_st_dark_room_ngt,		 // constant 0x33B
        test_stage_st_dgn_k_a_day,		 // constant 0x33C
        test_stage_st_dgn_k_a_eve,		 // constant 0x33D
        test_stage_st_dgn_k_a_ngt,		 // constant 0x33E
        test_stage_st_dgn_k_a_spe,		 // constant 0x33F
        test_stage_st_dgn_k_b_day,		 // constant 0x340
        test_stage_st_dgn_k_b_eve,		 // constant 0x341
        test_stage_st_dgn_k_b_ngt,		 // constant 0x342
        test_stage_st_dgn_k_b_spe,		 // constant 0x343
        test_stage_st_dgn_k_c_day,		 // constant 0x344
        test_stage_st_dgn_k_c_eve,		 // constant 0x345
        test_stage_st_dgn_k_c_ngt,		 // constant 0x346
        test_stage_st_dgn_k_c_spe,		 // constant 0x347
        test_stage_st_dgn_y_a_day,		 // constant 0x348
        test_stage_st_dgn_y_a_eve,		 // constant 0x349
        test_stage_st_dgn_y_a_ngt,		 // constant 0x34A
        test_stage_st_dgn_y_a_spe,		 // constant 0x34B
        test_stage_st_dgn_y_b_day,		 // constant 0x34C
        test_stage_st_dgn_y_b_eve,		 // constant 0x34D
        test_stage_st_dgn_y_b_ngt,		 // constant 0x34E
        test_stage_st_dgn_y_b_spe,		 // constant 0x34F
        test_stage_st_dgn_y_c_day,		 // constant 0x350
        test_stage_st_dgn_y_c_eve,		 // constant 0x351
        test_stage_st_dgn_y_c_ngt,		 // constant 0x352
        test_stage_st_dgn_y_c_spe,		 // constant 0x353
        test_party_talk,		 // constant 0x354
        minigame_batting_center_yokohama_challenge,		 // constant 0x355
        minigame_batting_center_yokohama_homerun,		 // constant 0x356
        minigame_batting_center_yokohama_competition,		 // constant 0x357
        test_json_unittest,		 // constant 0x358
        test_rpc_unittest,		 // constant 0x359
        minigame_batting_center_kamuro_challenge,		 // constant 0x35A
        minigame_batting_center_kamuro_homerun,		 // constant 0x35B
        minigame_batting_center_kamuro_competition,		 // constant 0x35C
        test_stage_st_tojo_day,		 // constant 0x35D
        test_stage_mg_shogi_day,		 // constant 0x35E
        test_stage_mg_shogi_ngt,		 // constant 0x35F
        test_upstart_battle,		 // constant 0x360
        test_upstart_management,		 // constant 0x361
        minigame_rail_shooter_yazawa,		 // constant 0x362
        test_stage_st_yokohama_soko_day,		 // constant 0x363
        test_stage_st_yokohama_soko_ngt,		 // constant 0x364
        test_stage_st_rojin_home_day,		 // constant 0x365
        test_stage_st_rojin_home_ngt,		 // constant 0x366
        test_stage_st_seiryu_day,		 // constant 0x367
        test_stage_st_hanafuda_day,		 // constant 0x368
        test_stage_st_hanafuda_eve,		 // constant 0x369
        test_stage_st_hanafuda_ngt,		 // constant 0x36A
        test_stage_st_hanafuda_spe,		 // constant 0x36B
        test_stage_st_chikarou_ngt,		 // constant 0x36C
        test_stage_st_geomijul_day,		 // constant 0x36D
        test_stage_st_geomijul_ngt,		 // constant 0x36E
        minigame_upstart_battle,		 // constant 0x36F
        minigame_upstart_management,		 // constant 0x370
        test_stage_st_dgn_k_a2_spe,		 // constant 0x371
        test_stage_st_dgn_k_a3_spe,		 // constant 0x372
        test_stage_st_dgn_k_b2_spe,		 // constant 0x373
        test_stage_st_dgn_k_b3_spe,		 // constant 0x374
        test_stage_st_dgn_k_c2_spe,		 // constant 0x375
        test_stage_st_dgn_k_c3_spe,		 // constant 0x376
        test_stage_st_dgn_y_a2_spe,		 // constant 0x377
        test_stage_st_dgn_y_a3_spe,		 // constant 0x378
        test_stage_st_dgn_y_b2_spe,		 // constant 0x379
        test_stage_st_dgn_y_b3_spe,		 // constant 0x37A
        test_stage_st_dgn_y_c2_spe,		 // constant 0x37B
        test_stage_st_dgn_y_c3_spe,		 // constant 0x37C
        scenario_jump,		 // constant 0x37D
        debug_jump,		 // constant 0x37E
        debug_scenario_jump,		 // constant 0x37F
        test_stage_st_tochiji_buil_ngt,		 // constant 0x380
        test_stage_st_seiryu_ngt,		 // constant 0x381
        test_stage_st_keikin_ngt,		 // constant 0x382
        test_stage_st_kisya_kaiken_day,		 // constant 0x383
        test_stage_st_hospital_ngt,		 // constant 0x384
        test_stage_st_sougi_day,		 // constant 0x385
        test_stage_st_chikachu_day,		 // constant 0x386
        test_stage_st_souri_ngt,		 // constant 0x387
        minigame_hades,		 // constant 0x388
        test_stage_st_grand_ngt,		 // constant 0x389
        test_stage_st_oumi_day,		 // constant 0x38A
        test_stage_st_oumi_ngt,		 // constant 0x38B
        test_stage_st_chinese_rest_day,		 // constant 0x38C
        test_stage_mg_keiei_day,		 // constant 0x38D
        test_stage_mg_keiei_ngt,		 // constant 0x38E
        test_stage_st_coin_locker_ngt,		 // constant 0x38F
        test_excavator_continuous_track,		 // constant 0x390
        test_animal_ik,		 // constant 0x391
        test_stage_st_jim_arakawa_spe,		 // constant 0x392
        test_stage_st_geomijul_burned_ngt,		 // constant 0x393
        test_stage_st_ishioda_ngt,		 // constant 0x394
        test_stage_st_senkyo_hall_day,		 // constant 0x395
        test_stage_st_m_tower_ngt,		 // constant 0x396
        test_stage_st_last_battle_ngt,		 // constant 0x397
        test_stage_st_coin_locker_now_ngt,		 // constant 0x398
        test_stage_st_menkai_day,		 // constant 0x399
        test_stage_st_police_roof_day,		 // constant 0x39A
        test_crowd,		 // constant 0x39B
        test_stage_st_heianrou_auth_day,		 // constant 0x39C
        test_stage_st_heianrou_auth_spe,		 // constant 0x39D
        test_stage_mg_karaoke_mgk_day,		 // constant 0x39E
        test_stage_mg_karaoke_mgk_ngt,		 // constant 0x39F
        test_stage_mg_karaoke_lab_day,		 // constant 0x3A0
        test_stage_mg_karaoke_lab_ngt,		 // constant 0x3A1
        test_stage_mg_karaoke_bkm_day,		 // constant 0x3A2
        test_stage_mg_karaoke_bkm_ngt,		 // constant 0x3A3
        test_stage_st_k_heianrou_vip_spe,		 // constant 0x3A4
        test_stage_mg_karaoke_kym_day,		 // constant 0x3A5
        test_stage_mg_karaoke_kym_ngt,		 // constant 0x3A6
        test_stage_mg_karaoke_ak_jn_day,		 // constant 0x3A7
        test_stage_mg_karaoke_ak_jn_ngt,		 // constant 0x3A8
        minigame_milligod,		 // constant 0x3A9
        minigame_souten,		 // constant 0x3AA
        minigame_beast,		 // constant 0x3AB
        minigame_darts_yazawa,		 // constant 0x3AC
        minigame_darts_yokohama,		 // constant 0x3AD
        minigame_karaoke_yokohama,		 // constant 0x3AE
        test_stage_st_tv_studio_day,		 // constant 0x3AF
        test_stage_st_osaka_police_day,		 // constant 0x3B0
        minigame_yazawa_dragon_cart_rival_story,		 // constant 0x3B1
        minigame_pachisolt,		 // constant 0x3B2
        minigame_pachislot,		 // constant 0x3B3
        test_stage_st_ryuchijo_day,		 // constant 0x3B4
        test_xu,		 // constant 0x3B5
        test_horie,		 // constant 0x3B6
        test_oto,		 // constant 0x3B7
        test_ishii,		 // constant 0x3B8
        test_yonezawa,		 // constant 0x3B9
        minigame_shikaku,		 // constant 0x3BA
        minigame_shikaku_main,		 // constant 0x3BB
        test_teacher,		 // constant 0x3BC
        test_stage_st_dgn_y_a3_boss_spe,		 // constant 0x3BD
        test_stage_st_dungeon_souten_day,		 // constant 0x3BE
        test_stage_st_dungeon_souten_ngt,		 // constant 0x3BF
        test_stage_te_0013_rontgs_day,		 // constant 0x3C0
        test_stage_st_black_ngt,		 // constant 0x3C1
        test_stage_st_mg_golf_yoko_day,		 // constant 0x3C2
        test_stage_st_mg_golf_yoko_ngt,		 // constant 0x3C3
        action_arena_scene,		 // constant 0x3C4
        reboot_elf,		 // constant 0x3C5
        minigame_pachislot_dll,		 // constant 0x3C6
        playing_to_load,		 // constant 0x3C7
        num,		 // constant 0x3C8
    };
}
