using System;

namespace DragonEngineLibrary
{

    public enum SceneEntity : uint
    {
        scene,       // constant 0x0
        artisan_host,        // constant 0x1
        collision,       // constant 0x2
        motion_manager,      // constant 0x3
        navimesh_collision_manager,      // constant 0x4
        navimesh_manager,        // constant 0x5
        auth_manager,        // constant 0x6
        human_player,        // constant 0x7
        ui_fade_manager,         // constant 0x8
        camera_free,         // constant 0x9
        camera_fps,      // constant 0xA
        camera_photo,        // constant 0xB
        camera_selfie,       // constant 0xC
        camera_gatling_gun,      // constant 0xD
        camera_drone_adv,        // constant 0xE
        camera_fps_drone_adv,        // constant 0xF
        camera_mg_clc,       // constant 0x10
        camera_ufo_catcher,      // constant 0x11
        camera_verification_fps,         // constant 0x12
        camera_rpg_battle,       // constant 0x13
        auth_player_preview,         // constant 0x14
        asset_manager,       // constant 0x15
        stage,       // constant 0x16
        light_manager,       // constant 0x17
        effect_manager,      // constant 0x18
        character_manager,       // constant 0x19
        particle_manager,        // constant 0x1A
        physics_manager,         // constant 0x1B
        street_map,      // constant 0x1C
        street_map_area_manager,         // constant 0x1D
        movie_tex_manager,       // constant 0x1E
        team_manager,        // constant 0x1F
        battle_manager,      // constant 0x20
        pause_manager,       // constant 0x21
        post_effect_manager,         // constant 0x22
        ccc_manager,         // constant 0x23
        sound_manager,       // constant 0x24
        behavior_property_manager,       // constant 0x25
        instant_chat_manager,        // constant 0x26
        ui_manager,      // constant 0x27
        ui_entity_player_gauge,      // constant 0x28
        player_battle_buff_entity,       // constant 0x29
        encount_unsafe_area_entity,      // constant 0x2A
        map_manager_entity,      // constant 0x2B
        curtain_range_manager,       // constant 0x2C
        dont_use_xxx______________game_var_manager,      // constant 0x2D
        fade_manager,        // constant 0x2E
        range_manager,       // constant 0x2F
        puid_manager_entity,         // constant 0x30
        db_manager_entity,       // constant 0x31
        character_dispose_manager,       // constant 0x32
        hact_manager,        // constant 0x33
        effect_draw_manager,         // constant 0x34
        wind,        // constant 0x35
        route_path_manager,      // constant 0x36
        rumble_manager,      // constant 0x37
        auth_light_light_reference,      // constant 0x38
        save_data_manager,       // constant 0x39
        door_range_manager,      // constant 0x3A
        street_obstacle_manager,         // constant 0x3B
        encount_manager,         // constant 0x3C
        color_correction_range_manager,      // constant 0x3D
        inhibition_updater,      // constant 0x3E
        map_minimap_entity,      // constant 0x3F
        map_stage_entity,        // constant 0x40
        scene_info_handover,         // constant 0x41
        dispose_manager,         // constant 0x42
        uniq_dispose_manager,        // constant 0x43
        lod_manager,         // constant 0x44
        objective_entity,        // constant 0x45
        objective_manager_entity,        // constant 0x46
        navi_edge_manager_entity,        // constant 0x47
        navi_manager_entity,         // constant 0x48
        navi_node_manager_entity,        // constant 0x49
        tww_manager_entity,      // constant 0x4A
        player_photo_mode_scene_entity,      // constant 0x4B
        tww_notify_entity,       // constant 0x4C
        player_pause_entity,         // constant 0x4D
        player_activity_entity,      // constant 0x4E
        mg_bouncer_manager,      // constant 0x4F
        mg_bouncer_menu_manager,         // constant 0x50
        popup_manager_entity,        // constant 0x51
        player_action_entity,        // constant 0x52
        effect_event_manager,        // constant 0x53
        effect_mirror_manager,       // constant 0x54
        effect_draw_pip,         // constant 0x55
        effect_draw_mask_manager,        // constant 0x56
        effect_lens_flare,       // constant 0x57
        effect_character_halo,       // constant 0x58
        effect_track_draw_manager,       // constant 0x59
        door_auto_lock_manager,      // constant 0x5A
        scene_fade_ctrl,         // constant 0x5B
        chara_generate_manager,      // constant 0x5C
        chara_generate_clan_manager,         // constant 0x5D
        fish_generate_manager,       // constant 0x5E
        ai_manager,      // constant 0x5F
        mind_control_manager,        // constant 0x60
        sub_story_manager,       // constant 0x61
        msg_window_manager,      // constant 0x62
        live_chase_manager,      // constant 0x63
        ui_entity_enemy_gauge_manager,       // constant 0x64
        main_story_info,         // constant 0x65
        scene_ex_status_callback_ctrl,       // constant 0x66
        entity_sweeper,      // constant 0x67
        tutorial_show,       // constant 0x68
        navi_mesh_loader,        // constant 0x69
        tips_manager_entity,         // constant 0x6A
        player_ability_entity,       // constant 0x6B
        player_carry_item_entity,        // constant 0x6C
        player_carry_item_launcher_entity,       // constant 0x6D
        player_po_entity,         // constant 0x6E
        pause_sns_manager_entity,        // constant 0x6F
        pause_mail_manager_entity,       // constant 0x70
        pause_message_manager_entity,        // constant 0x71
        item_get_manager_entity,         // constant 0x72
        shop_manager_entity,         // constant 0x73
        mission_area_manager,        // constant 0x74
        network_manager,         // constant 0x75
        timeline_manager,        // constant 0x76
        mission_manager,         // constant 0x77
        random_po_manager,        // constant 0x78
        callback_db_holder,      // constant 0x79
        traffic_signal_manager,      // constant 0x7A
        clock_pkg_holder,        // constant 0x7B
        npc_tag_manager,         // constant 0x7C
        general_car_manager,         // constant 0x7D
        general_car_ersection_manager,        // constant 0x7E
        train_manager,       // constant 0x7F
        vehicle_special_manager,         // constant 0x80
        ladder_manager,      // constant 0x81
        wall_manager,        // constant 0x82
        mg_snack_manager,        // constant 0x83
        mg_toylets_manager,      // constant 0x84
        mg_golf_driving_range,       // constant 0x85
        npc_control_manager,         // constant 0x86
        foreground_ui_texture_que,       // constant 0x87
        shop_destory_manager,        // constant 0x88
        load_position_entity,        // constant 0x89
        pause_id_manager,        // constant 0x8A
        player_control_manager,      // constant 0x8B
        time_updater,        // constant 0x8C
        exclusion_control_checker,       // constant 0x8D
        stalking_manager,        // constant 0x8E
        cover_po_manager,         // constant 0x8F
        link_any,        // constant 0x90
        wrapping_collision_manager,      // constant 0x91
        police_manager,      // constant 0x92
        police_area_manager,         // constant 0x93
        chase_manager,       // constant 0x94
        run_trick_po_manager,         // constant 0x95
        ufo_catcher_manager,         // constant 0x96
        drone_manager,       // constant 0x97
        drone_online_manager,        // constant 0x98
        onedari_manager,         // constant 0x99
        player_equip_entity,         // constant 0x9A
        player_equip_item_drop_entity,       // constant 0x9B
        sugoroku_masu_manager,       // constant 0x9C
        tougijyo_manager,        // constant 0x9D
        sugoroku_manager_entity,         // constant 0x9E
        sugoroku_effect_manager,         // constant 0x9F
        sugoroku_dispose_po_manager,      // constant 0xA0
        sugoroku_break_asset_manager,        // constant 0xA1
        coin_locker_key_manager,         // constant 0xA2
        qrcord_manager,      // constant 0xA3
        pickup_dispose_manager,      // constant 0xA4
        escalator_manager,       // constant 0xA5
        pause_crowdfunding_entity,       // constant 0xA6
        dragon_cart_race_manager,        // constant 0xA7
        party_equip_entity,      // constant 0xA8
        party_carry_item_entity,         // constant 0xA9
        camera_filter_range_manager,         // constant 0xAA
        mg_meigaza_manager,      // constant 0xAB
        talk_party_chat_manager,         // constant 0xAC
        mg_homeless_manager,         // constant 0xAD
        talk_party_talk_manager,         // constant 0xAE
        upstart_manager,         // constant 0xAF
        score_ranking_manager,       // constant 0xB0
        planter_man,         // constant 0xB1
        talk_notice_gauge_manager,       // constant 0xB2
        pause_auth_renderer_entity,      // constant 0xB3
        talk_trust_param_manager,        // constant 0xB4
        crowd_tile_manager,      // constant 0xB5
        planting_collision_manager,      // constant 0xB6
        talk_adv_hp_gauge_manager,       // constant 0xB7
        adv_battle_gauge_manager,        // constant 0xB8
        human_player_dummy,      // constant 0xB9
        water_manager,       // constant 0xBA
        effect_only_one_manager,         // constant 0xBB
        mg_clan_creator_online_rival_manager,        // constant 0xBC
        mg_baseball_picture_holder,      // constant 0xBD
        minigame_sandlot_baseball_manager,       // constant 0xBE
        mg_offertory_box_entity,         // constant 0xBF
        reward_manager,      // constant 0xC0
        taiken_timer,        // constant 0xC1
        file_port_manager,       // constant 0xC2
        talk_text_man,       // constant 0xC3
        uniq_auth_manager,       // constant 0xC4
        friend_gauge_man,        // constant 0xC5
        unlocking_adv_man,       // constant 0xC6
        tss_manager,         // constant 0xC7
        player_personality,      // constant 0xC8
        uniq_replace_start,      // constant 0xC9
        uniq_replace_nakama0,        // constant 0xCA
        uniq_replace_nakama1,        // constant 0xCB
        uniq_replace_nakama2,        // constant 0xCC
        uniq_replace_nakama3,        // constant 0xCD
        uniq_replace_nakama_adachi,      // constant 0xCE
        uniq_replace_nakama_saeko,       // constant 0xCF
        uniq_replace_nakama_nanba,       // constant 0xD0
        uniq_replace_nakama_ayaka,       // constant 0xD1
        uniq_replace_nakama_chou,        // constant 0xD2
        uniq_replace_nakama_jyungi,      // constant 0xD3
        uniq_replace_nakama_woman_a,         // constant 0xD4
        uniq_replace_end,        // constant 0xD5
        speech_subtitle_manager,         // constant 0xD6
        dlc_manager,         // constant 0xD7
        post_effect_dof,         // constant 0xD8
        post_effect_glare,       // constant 0xD9
        post_effect_tonemap,         // constant 0xDA
        post_effect_filmgrain,       // constant 0xDB
        post_effect_color_correction,        // constant 0xDC
        post_effect_antialias,       // constant 0xDD
        post_effect_motion_blur,         // constant 0xDE
        post_effect_feedback,        // constant 0xDF
        post_effect_chromatic_aberration,        // constant 0xE0
        post_effect_vignette,        // constant 0xE1
        post_effect_ssao,        // constant 0xE2
        entity_FullBodyIKDbgMngr,        // constant 0xE3
        auth_play,       // constant 0xE4
        light_reference,         // constant 0xE5
        hoge_entity,         // constant 0xE6
        ui_nowloading,       // constant 0xE7
        npc_bypass_manager,      // constant 0xE8
        stage_area_monitoring,       // constant 0xE9
        title_entity,        // constant 0xEA
        battle_tutorial,         // constant 0xEB
        auth_skip_manager,       // constant 0xEC
        qsearch_manager,         // constant 0xED
        video_call,      // constant 0xEE
        side_case_manager,       // constant 0xEF
        verification_manager,        // constant 0xF0
        continue_ui_flow_holder,         // constant 0xF1
        photo_mission_dispose_manager,       // constant 0xF2
        decorating_office_dispose_manager,       // constant 0xF3
        dialog_information_manager,      // constant 0xF4
        sp_provider,         // constant 0xF5
        ui_popup_number_manager,         // constant 0xF6
        part_time_job_quest_entity,      // constant 0xF7
        checkpo_entity,       // constant 0xF8
        grass_draw_manager,      // constant 0xF9
        mission_objective_manager_entity,        // constant 0xFA
        num,         // constant 0xFB
        invalid,         // constant 0xFC
    }
}
