#if IW || GAIDEN || Y6 || YLAD || YK2 || LJ
#define SERVICE_ID
#endif

namespace DragonEngineLibrary
{
#if IW || GAIDEN || !SERVICE_ID
public enum ServiceID
{
    unknown,
    sound = 1,
    save = 2,
    play_go = 3,
    file = 4,
    screenshot = 5,
    flood = 6,
    habitus = 7,
    resource = 8,
    startup = 9,
    system_utility = 10,
    trophy = 11,
    network = 12,
    puid = 13,
    db = 14,
    ui = 15,
    fade = 16,
    input = 17,
    lua = 18,
    entity = 19,
    camera = 20,
    shadow = 21,
    light = 22,
    physics = 23,
    scene = 24,
    post_process = 25,
    vollight = 26,
    rich_presence = 27,
    motion = 28,
    effect_resource = 29,
    effect_draw = 30,
    blackboard = 31,
    artisan = 32,
    grass = 33,
    num = 34
};
#endif

#if YK2
public enum ServiceID
{
    unknown,
    sound,
    steam,
    prism,
    amd_ags,
    file,
    screenshot,
    flood,
    habitus,
    resource,
    startup,
    system_utility,
    play_go,
    save_data,
    trophy,
    network,
    db,
    puid,
    ui,
    fade,
    input,
    font,
    lua,
    entity,
    camera,
    shadow,
    light,
    physics,
    scene,
    post_process,
    vollight,
    motion,
    effect_resource,
    blackboard,
    cmm,
    artisan,
    mouse,
    num,

};
#endif

#if YLAD
    public enum ServiceID
    {
        unknown = 0,
        sound = 1,
        save_data = 2,
        play_go = 3,
        file = 4,
        screenshot = 5,
        flood = 6,
        habitus = 7,
        resource = 8,
        startup = 9,
        system_utility = 10,
        trophy = 11,
        network = 12,
        puid = 13,
        db = 14,
        ui = 15,
        fade = 16,
        input = 17,
        font = 18,
        lua = 19,
        entity = 20,
        camera = 21,
        shadow = 22,
        light = 23,
        physics = 24,
        scene = 25,
        post_process = 26,
        vollight = 27,
        rich_presence = 28,
        motion = 29,
        effect_resource = 30,
        blackboard = 31,
        artisan = 32,
        grass = 33,
        num = 34
    };
#endif

#if LJ
public enum ServiceID
{
    unknown = 0x0,
    sound = 0x1,
    play_go = 0x2,
    save_data = 0x3,
    file = 0x4,
    screenshot = 0x5,
    flood = 0x6,
    habitus = 0x7,
    resource = 0x8,
    startup = 0x9,
    system_utility = 0xA,
    trophy = 0xB,
    network = 0xC,
    puid = 0xD,
    db = 0xE,
    ui = 0xF,
    fade = 0x10,
    input = 0x11,
    lua = 0x12,
    entity = 0x13,
    camera = 0x14,
    shadow = 0x15,
    light = 0x16,
    physics = 0x17,
    scene = 0x18,
    post_process = 0x19,
    vollight = 0x1A,
    rich_presence = 0x1B,
    http_server = 0x1C,
    tool_http = 0x1D,
    http_debug = 0x1E,
    motion = 0x1F,
    effect_resource = 0x20,
    blackboard = 0x21,
    artisan = 0x22,
    grass = 0x23,
    perf = 0x24,
    mouse = 0x25,
    gwin = 0x26,
    vram_info = 0x27,
    tool_com = 0x28,
    log_analysis = 0x29,
    auto_input = 0x2A,
    num = 0x2B,
};
#endif

#if Y6
public enum ServiceID
{
    unknown,
    sound,
   // steam,
    save_data,
    file,
    screenshot,
    flood,
    habitus,
    resource,
    startup,
    system_utility,
    play_go,
    save_dataa,
    trophy,
    network,
    db,
    puid,
    ui,
    fade,
    input,
    font,
    lua,
    entity,
    camera,
    shadow,
    light,
    physics,
    scene,
    post_process,
    vollight,
    motion,
    effect_resource,
    num,
};
#endif
}
