using System;

namespace DragonEngineLibrary
{
    public enum SoundCategoryLabelGVTalkID : uint
    {
        invalid,         // constant 0x0
        nod_casual_joy,      // constant 0x1
        nod_casual_ang,      // constant 0x2
        nod_casual_sad,      // constant 0x3
        nod_casual_nrm1,         // constant 0x4
        nod_casual_nrm2,         // constant 0x5
        nod_polite_joy,      // constant 0x6
        nod_polite_ang,      // constant 0x7
        nod_polite_sad,      // constant 0x8
        nod_polite_nrm1,         // constant 0x9
        agree_joy,       // constant 0xA
        agree_ang,       // constant 0xB
        agree_sad,       // constant 0xC
        agree_nrm1,      // constant 0xD
        agree_nrm2,      // constant 0xE
        negat_casual_joy,        // constant 0xF
        negat_casual_ang,        // constant 0x10
        negat_casual_sad,        // constant 0x11
        negat_casual_nrm1,       // constant 0x12
        negat_casual_nrm2,       // constant 0x13
        negat_polite_joy,        // constant 0x14
        negat_polite_ang,        // constant 0x15
        negat_polite_sad,        // constant 0x16
        negat_polite_nrm1,       // constant 0x17
        reject_joy,      // constant 0x18
        reject_ang,      // constant 0x19
        reject_sad,      // constant 0x1A
        reject_nrm1,         // constant 0x1B
        call_joy,        // constant 0x1C
        call_ang,        // constant 0x1D
        call_sad,        // constant 0x1E
        call_casual1,        // constant 0x1F
        call_casual2,        // constant 0x20
        call_casual3,        // constant 0x21
        call_polite1,        // constant 0x22
        wait_joy,        // constant 0x23
        wait_ang,        // constant 0x24
        wait_sad,        // constant 0x25
        wait_nrm1,       // constant 0x26
        wait_far,        // constant 0x27
        bye1,        // constant 0x28
        bye2,        // constant 0x29
        bye3,        // constant 0x2A
        surprised1,      // constant 0x2B
        surprised2,      // constant 0x2C
        surprised3,      // constant 0x2D
        disappoed1,      // constant 0x2E
        disappoed2,      // constant 0x2F
        irritated1,      // constant 0x30
        irritated2,      // constant 0x31
        question1,       // constant 0x32
        question2,       // constant 0x33
        angry1,      // constant 0x34
        angry2,      // constant 0x35
        angry3,      // constant 0x36
        notice1,         // constant 0x37
        laugh1,      // constant 0x38
        laugh2,      // constant 0x39
        laugh3,      // constant 0x3A
        suffer1,         // constant 0x3B
        suffer2,         // constant 0x3C
        thinking1,       // constant 0x3D
        thinking2,       // constant 0x3E
        understand1,         // constant 0x3F
        understand2,         // constant 0x40
        understand3,         // constant 0x41
        say_ok1,         // constant 0x42
        say_ok2,         // constant 0x43
        say_ok3,         // constant 0x44
        say_ok_polite,       // constant 0x45
        say_sorry_nrm,       // constant 0x46
        say_sorry_low,       // constant 0x47
        say_sorry_polite,        // constant 0x48
        say_thank_nrm,       // constant 0x49
        say_thank_polite,        // constant 0x4A
        eat_start,       // constant 0x4B
        eat_end,         // constant 0x4C
        eat_imp_best,        // constant 0x4D
        eat_call_best,       // constant 0x4E
        eat_imp_better,      // constant 0x4F
        eat_call_better,         // constant 0x50
        eat_imp_good,        // constant 0x51
        eat_call_good,       // constant 0x52
        eat_imp_nrm,         // constant 0x53
        eat_call_nrm,        // constant 0x54
        eat_imp_bad,         // constant 0x55
        eat_call_bad,        // constant 0x56
        eat_imp_worse,       // constant 0x57
        eat_call_worse,      // constant 0x58
        eat_imp_worst,       // constant 0x59
        eat_call_worst,      // constant 0x5A
        eat_cmt1,        // constant 0x5B
        eat_cmt2,        // constant 0x5C
        eat_cmt3,        // constant 0x5D
        eat_cmt4,        // constant 0x5E
        eat_cmt5,        // constant 0x5F
        drink_cmt1,      // constant 0x60
        drink_cmt2,      // constant 0x61
        drink_cmt3,      // constant 0x62
        drink_cmt4,      // constant 0x63
        drink_cmt5,      // constant 0x64
        party_talk1,         // constant 0x65
        party_talk2,         // constant 0x66
        party_talk3,         // constant 0x67
        party_talk4,         // constant 0x68
        party_talk5,         // constant 0x69
        party_talk6,         // constant 0x6A
        party_talk7,         // constant 0x6B
        party_talk8,         // constant 0x6C
        party_talk9,         // constant 0x6D
        party_talk10,        // constant 0x6E
        call_baddy_nanba1,       // constant 0x6F
        call_baddy_nanba2,       // constant 0x70
        call_baddy_adachi1,      // constant 0x71
        call_baddy_adachi2,      // constant 0x72
        call_baddy_ayaka1,       // constant 0x73
        call_baddy_ayaka2,       // constant 0x74
        call_baddy_sachi1,       // constant 0x75
        call_baddy_sachi2,       // constant 0x76
        call_baddy_han1,         // constant 0x77
        call_baddy_han2,         // constant 0x78
        call_baddy_chou1,        // constant 0x79
        call_baddy_chou2,        // constant 0x7A
        call_baddy_uk1,      // constant 0x7B
        call_baddy_uk2,      // constant 0x7C
        shop_start,      // constant 0x7D
        shop_end,        // constant 0x7E
        shop_agree,      // constant 0x7F
        shop_cancel1,        // constant 0x80
        shop_cancel2,        // constant 0x81
        shop_serve,      // constant 0x82
        mob_disgusto1,       // constant 0x83
        mob_disgusto2,       // constant 0x84
        mob_disgusto3,       // constant 0x85
        mob_trouble1,        // constant 0x86
        mob_trouble2,        // constant 0x87
        mob_disapo,      // constant 0x88
        mob_tangle1,         // constant 0x89
        mob_tangle2,         // constant 0x8A
        special01,       // constant 0x8B
        special02,       // constant 0x8C
        special03,       // constant 0x8D
        special04,       // constant 0x8E
        special05,       // constant 0x8F
        special06,       // constant 0x90
        special07,       // constant 0x91
        special08,       // constant 0x92
        special09,       // constant 0x93
        special10,       // constant 0x94
        special11,       // constant 0x95
        special12,       // constant 0x96
        special13,       // constant 0x97
        special14,       // constant 0x98
        special15,       // constant 0x99
        special16,       // constant 0x9A
        special17,       // constant 0x9B
        special18,       // constant 0x9C
        special19,       // constant 0x9D
        special20,       // constant 0x9E
        mng_other01,         // constant 0x9F
        mng_other02,         // constant 0xA0
        mng_other03,         // constant 0xA1
        greet_gf_lv1,        // constant 0xA2
        greet_gf_lv2,        // constant 0xA3
        greet_gf_lv3,        // constant 0xA4
        greet_gf_lv4,        // constant 0xA5
        greet_gf_lv5,        // constant 0xA6
        jobhunt_talk_start,      // constant 0xA7
        jobhunt_talk_end,        // constant 0xA8
        jobhunt_new_job,         // constant 0xA9
        jobhunt_ng_job,      // constant 0xAA
        jobhunt_gaya,        // constant 0xAB
        smith_working,       // constant 0xAC
        smith_finish,        // constant 0xAD
        smith_pause,         // constant 0xAE
        smith_rslt_make_suc,         // constant 0xAF
        smith_rslt_make_cmn,         // constant 0xB0
        smith_rslt_make_miss,        // constant 0xB1
        smith_rslt_powup_suc,        // constant 0xB2
        smith_rslt_powup_cmn,        // constant 0xB3
        smith_rslt_powup_miss,       // constant 0xB4
        levelup,         // constant 0xB5
        eat_imp_cmn,         // constant 0xB6
        smith_buildup,       // constant 0xB7
        call_baddy_saeko1,       // constant 0xB8
        call_baddy_saeko2,       // constant 0xB9
        call_baddy_eri1,         // constant 0xBA
        call_baddy_eri2,         // constant 0xBB
        num,		 // constant 0xBC
    }
}
