using System;
namespace DragonEngineLibrary
{
    public enum StageID : uint
    {
        invalid,		 // constant 0x0
        st_kamuro,		 // constant 0x1
        te_0006,		 // constant 0x2
        te_0007,		 // constant 0x3
        st_kamuro_judge,		 // constant 0x4
        te_0001_judge,		 // constant 0x5
        st_k_tojo,		 // constant 0x6
        te_0002_judge,		 // constant 0x7
        te_0004_judge,		 // constant 0x8
        te_asset_judge,		 // constant 0x9
        mg_mahjong_judge,		 // constant 0xA
        st_o_oumi,		 // constant 0xB
        te_0001,		 // constant 0xC
        te_0002,		 // constant 0xD
        st_k_hills,		 // constant 0xE
        st_o_syougi,		 // constant 0xF
        st_shinkansen,		 // constant 0x10
        te_0004,		 // constant 0x11
        st_o_sengoku,		 // constant 0x12
        st_o_roof_date,		 // constant 0x13
        st_o_caba,		 // constant 0x14
        mg_karaoke_sp,		 // constant 0x15
        st_menkaijo_judge,		 // constant 0x16
        st_saibansyo_judge,		 // constant 0x17
        st_souyakucenter_judge,		 // constant 0x18
        st_kensatsuchou_judge,		 // constant 0x19
        st_kikunoya_judge,		 // constant 0x1A
        st_toba_judge,		 // constant 0x1B
        st_honmaruden_judge,		 // constant 0x1C
        st_torishirabe_judge,		 // constant 0x1D
        st_apartment_judge,		 // constant 0x1E
        st_soreiyu_judge,		 // constant 0x1F
        st_for_casino,		 // constant 0x20
        st_title_judge,		 // constant 0x21
        st_kousoku_btl,		 // constant 0x22
        st_studio,		 // constant 0x23
        all,		 // constant 0x24
        st_old_buil_fire,		 // constant 0x25
        st_for_hanahuda,		 // constant 0x26
        st_for_casino_judge,		 // constant 0x27
        st_mg_golf,		 // constant 0x28
        st_mg_video,		 // constant 0x29
        st_sai_fukumaden,		 // constant 0x2A
        st_for_shogi,		 // constant 0x2B
        st_for_hanahuda_judge,		 // constant 0x2C
        st_for_shogi_judge,		 // constant 0x2D
        te_0005_judge,		 // constant 0x2E
        te_0006_judge,		 // constant 0x2F
        st_o_shiro_soto,		 // constant 0x30
        st_k_tougenkyo_b,		 // constant 0x31
        mg_mahjong,		 // constant 0x32
        st_honmaruen_judge,		 // constant 0x33
        te_dynamic_collision,		 // constant 0x34
        st_toilet,		 // constant 0x35
        st_k_hills_elv,		 // constant 0x36
        te_dynamic_collision_judge,		 // constant 0x37
        st_mg_nozoki,		 // constant 0x38
        st_clan_nishikouen,		 // constant 0x39
        st_osaka,		 // constant 0x3A
        st_o_grand,		 // constant 0x3B
        st_k_shine,		 // constant 0x3C
        st_k_disco,		 // constant 0x3D
        st_old_buil,		 // constant 0x3E
        st_k_doujima,		 // constant 0x3F
        st_o_kazabori,		 // constant 0x40
        st_kawara_rm_a,		 // constant 0x41
        st_kawara_rm_b,		 // constant 0x42
        st_k_police_meet,		 // constant 0x43
        st_k_shiryou_rm,		 // constant 0x44
        st_k_sudou_rm,		 // constant 0x45
        st_k_police_rouka,		 // constant 0x46
        st_o_geinou,		 // constant 0x47
        st_kousoku,		 // constant 0x48
        st_kousoku_fuji,		 // constant 0x49
        st_kiryu_apart,		 // constant 0x4A
        st_o_police,		 // constant 0x4B
        st_o_torishirabe,		 // constant 0x4C
        st_o_kouno,		 // constant 0x4D
        st_k_takashima,		 // constant 0x4E
        st_o_tamiyo_rm,		 // constant 0x4F
        st_sai,		 // constant 0x50
        st_sai_majima_rm,		 // constant 0x51
        st_sai_tougi,		 // constant 0x52
        st_k_tougenkyo,		 // constant 0x53
        st_kill_elv,		 // constant 0x54
        st_kill_road_a,		 // constant 0x55
        st_kill_road_b,		 // constant 0x56
        st_bochi,		 // constant 0x57
        st_ambulance,		 // constant 0x58
        st_k_m_transform,		 // constant 0x59
        st_k_m_kazama,		 // constant 0x5A
        st_k_m_monitor,		 // constant 0x5B
        st_o_sogeki,		 // constant 0x5C
        st_k_stardust,		 // constant 0x5D
        st_k_hotel_bar,		 // constant 0x5E
        st_k_kidsroom,		 // constant 0x5F
        st_k_amano_buil,		 // constant 0x60
        st_k_amano_roof,		 // constant 0x61
        st_o_shiro,		 // constant 0x62
        te_asset,		 // constant 0x63
        st_yagami,		 // constant 0x64
        st_laboratory,		 // constant 0x65
        st_livestage,		 // constant 0x66
        st_mountain_road,		 // constant 0x67
        st_interviewhall,		 // constant 0x68
        st_hikouki,		 // constant 0x69
        st_k_uematsu,		 // constant 0x6A
        st_tojo_judge,		 // constant 0x6B
        st_common_office_judge,		 // constant 0x6C
        none_resource,		 // constant 0x6D
        st_k_clan_bar,		 // constant 0x6E
        te_0007_judge,		 // constant 0x6F
        st_sai_tougi_judge,		 // constant 0x70
        st_dress_up_judge,		 // constant 0x71
        st_yokohama,		 // constant 0x72
        te_0008_judge,		 // constant 0x73
        te_0009_judge,		 // constant 0x74
        te_0005,		 // constant 0x75
        te_0008,		 // constant 0x76
        te_0009,		 // constant 0x77
        te_0010,		 // constant 0x78
        te_0011,		 // constant 0x79
        st_butai,		 // constant 0x7A
        st_gakuya,		 // constant 0x7B
        st_caba_nakai,		 // constant 0x7C
        st_jim_nonomura,		 // constant 0x7D
        st_kamuro_police,		 // constant 0x7E
        st_ron_pv,		 // constant 0x7F
        st_tougen_birth,		 // constant 0x80
        st_heianrou_auth,		 // constant 0x81
        st_jim_arakawa,		 // constant 0x82
        st_kamuro_yazawa_now,		 // constant 0x83
        st_kamuro_yazawa_past,		 // constant 0x84
        st_imekura,		 // constant 0x85
        st_prison_sagyou,		 // constant 0x86
        st_prison_souko,		 // constant 0x87
        st_prison_dokkyo,		 // constant 0x88
        st_prison_zakkyo,		 // constant 0x89
        st_prizon_exit,		 // constant 0x8A
        st_salon,		 // constant 0x8B
        st_prison_exit,		 // constant 0x8C
        mg_cinema_yokohama,		 // constant 0x8D
        te_0012,		 // constant 0x8E
        st_hospital_roka,		 // constant 0x8F
        st_tower_mansion,		 // constant 0x90
        st_caba_luxury_out,		 // constant 0x91
        st_caba_luxury,		 // constant 0x92
        st_k_heianrou_roof,		 // constant 0x93
        st_k_heianrou_vip,		 // constant 0x94
        st_dark_room,		 // constant 0x95
        st_dgn_k_a,		 // constant 0x96
        st_dgn_k_b,		 // constant 0x97
        st_dgn_k_c,		 // constant 0x98
        st_dgn_y_a,		 // constant 0x99
        st_dgn_y_b,		 // constant 0x9A
        st_dgn_y_c,		 // constant 0x9B
        st_tojo,		 // constant 0x9C
        mg_shogi,		 // constant 0x9D
        st_yokohama_soko,		 // constant 0x9E
        st_rojin_home,		 // constant 0x9F
        st_seiryu,		 // constant 0xA0
        st_hanafuda,		 // constant 0xA1
        st_chikarou,		 // constant 0xA2
        st_geomijul,		 // constant 0xA3
        st_dgn_k_a2,		 // constant 0xA4
        st_dgn_k_a3,		 // constant 0xA5
        st_dgn_k_b2,		 // constant 0xA6
        st_dgn_k_b3,		 // constant 0xA7
        st_dgn_k_c2,		 // constant 0xA8
        st_dgn_k_c3,		 // constant 0xA9
        st_dgn_y_a2,		 // constant 0xAA
        st_dgn_y_a3,		 // constant 0xAB
        st_dgn_y_b2,		 // constant 0xAC
        st_dgn_y_b3,		 // constant 0xAD
        st_dgn_y_c2,		 // constant 0xAE
        st_dgn_y_c3,		 // constant 0xAF
        st_tochiji_buil,		 // constant 0xB0
        st_keikin,		 // constant 0xB1
        st_kisya_kaiken,		 // constant 0xB2
        st_hospital,		 // constant 0xB3
        st_sougi,		 // constant 0xB4
        st_chikachu,		 // constant 0xB5
        st_souri,		 // constant 0xB6
        st_grand,		 // constant 0xB7
        st_oumi,		 // constant 0xB8
        st_chinese_rest,		 // constant 0xB9
        mg_keiei,		 // constant 0xBA
        st_coin_locker,		 // constant 0xBB
        st_geomijul_burned,		 // constant 0xBC
        st_ishioda,		 // constant 0xBD
        st_senkyo_hall,		 // constant 0xBE
        st_m_tower,		 // constant 0xBF
        st_last_battle,		 // constant 0xC0
        st_coin_locker_now,		 // constant 0xC1
        st_menkai,		 // constant 0xC2
        st_police_roof,		 // constant 0xC3
        mg_karaoke_mgk,		 // constant 0xC4
        mg_karaoke_lab,		 // constant 0xC5
        mg_karaoke_bkm,		 // constant 0xC6
        mg_karaoke_kym,		 // constant 0xC7
        mg_karaoke_ak_jn,		 // constant 0xC8
        st_tv_studio,		 // constant 0xC9
        st_osaka_police,		 // constant 0xCA
        st_ryuchijo,		 // constant 0xCB
        st_dgn_y_a3_boss,		 // constant 0xCC
        st_dungeon_souten,		 // constant 0xCD
        te_0013_rontgs,		 // constant 0xCE
        st_black,		 // constant 0xCF
        st_mg_golf_yoko,		 // constant 0xD0
        num,		 // constant 0xD1
    };
}

