using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DragonEngineLibrary
{
    public enum UIControlID : uint
    {
        gauge = 1,
        counter = 2,
        button = 3,
        dialog = 4,
        list = 5,
        picker = 6,
        scrollbar = 7,
        panel = 8,
        guide = 9,
        tab = 10,
        list_item = 11,
        slider = 12,
        pattern = 13,
        segment = 14,
        scroller = 15,
        npc_gauge = 16,
        offscreen = 17,
        filter = 18,
        edit_list = 19,
        segment_base = 20,
        list_item_checked = 21,
        resizable_gauge = 22,
        player_point = 23,
        tab_item = 24,
        life_gauge = 25,
        guide_item = 26,
        chart = 27,
        navigation = 28,
        hint_can_move_to_left = 29,
        hint_can_move_to_right = 30,
        hint_can_move_to_up = 31,
        hint_can_move_to_down = 32,
        hint_can_move_to_prev = 33,
        hint_can_move_to_next = 34,
        pattern_index = 35,
        scrollbar_thumb = 36,
        scrollable_gauge = 37,
        scrollable_gauge_bar = 38,
        loop_list = 39,
        scrollable_text = 40,
        complex_list = 41,
        label = 42,
        fixed_list = 43,
        hint_can_scroll_to_prev = 44,
        hint_can_scroll_to_next = 45,
        hint_can_scroll_to_left = 46,
        hint_can_scroll_to_right = 47,
        hint_can_scroll_to_up = 48,
        hint_can_scroll_to_down = 49,
        guide_item_button = 50,
        heavy_list = 51,
        select_point = 52,
        picture = 53,
        stick_choice_list = 54,
        four_button_list = 55,
        icon = 56,
        world = 57,
        slider_thumb = 58,
        offscreen_marker = 59,
        pager = 60,
        pager_page = 61,
        page_indicator = 62,
        page_indicator_item = 63,
        offscreen_arrow = 64,
        switcher = 65,
        scroll_list = 66,
        tab_prev_page_button = 67,
        tab_next_page_button = 68,
        popup_tail_start = 69,
        popup_tail_end = 70,
        char_list = 71,
        char_list_item = 72,
        roll_char_list = 73,
        roll_char_list_item = 74,
        old_pattern = 75,
        old_pattern_index = 76,
        button_list = 77,
        switcher_reversed = 78,
        platform = 79
    }
}
