using System;
using System.Runtime.InteropServices;

namespace DragonEngineLibrary
{
    public static class PlayerPoint
    {

        [DllImport("Y7Internal.dll", EntryPoint = "LIB_SDCHUNK_PLAYER_GET_PLAYER_POINT", CallingConvention = CallingConvention.Cdecl)]
        public static extern long GetPoint(ID playerPoint);

        [DllImport("Y7Internal.dll", EntryPoint = "LIB_SDCHUNK_PLAYER_SET_PLAYER_POINT", CallingConvention = CallingConvention.Cdecl)]
        public static extern void SetPoint(ID playerPoint, long value);


        public enum ID : uint
        {

            money = 0x1,       // constant 0x1
            exp_muscle,      // constant 0x2
            exp_quickness,       // constant 0x3
            exp_guts,        // constant 0x4
            exp_technique,       // constant 0x5
            exp_charm,       // constant 0x6
            stomach,         // constant 0x7
            ten_mahjong,         // constant 0x8
            ability_hit_point,       // constant 0x9
            ability_attack,      // constant 0xA
            ability_defense,         // constant 0xB
            ability_agility,         // constant 0xC
            ability_heat_gauge,      // constant 0xD
            ability_resist_sword,        // constant 0xE
            ability_resist_gun,      // constant 0xF
            ability_stamina,         // constant 0x10
            activity_talk_count,         // constant 0x11
            activity_drink_count,        // constant 0x12
            activity_eat_food_item_count,        // constant 0x13
            activity_use_medicine_count,         // constant 0x14
            activity_use_taxi_count,         // constant 0x15
            activity_make_money,         // constant 0x16
            activity_use_money,      // constant 0x17
            activity_take_picture_count,         // constant 0x18
            activity_email_friend_count,         // constant 0x19
            activity_use_toilet_count,       // constant 0x1A
            activity_open_safe,      // constant 0x1B
            activity_eat_food_at_restaurant_count,       // constant 0x1C
            activity_bonus_at_restaurant_count,      // constant 0x1D
            activity_clear_instant_mission_count,        // constant 0x1E
            activity_kill_enemy_count,       // constant 0x1F
            activity_kill_enemy_by_heat_mode_count,      // constant 0x20
            activity_break_object_count,         // constant 0x21
            activity_kill_enemy_by_weapon_count,         // constant 0x22
            activity_help_people_count,      // constant 0x23
            activity_kill_enemy_narikin_count,       // constant 0x24
            activity_kill_enemy_justis_count,        // constant 0x25
            activity_kill_enemy_sega_count,      // constant 0x26
            activity_use_hact_count,         // constant 0x27
            activity_playspot_play_count,        // constant 0x28
            activity_walk_km,        // constant 0x29
            activity_dash_km,        // constant 0x2A
            donation,        // constant 0x2B
            training_ticket,         // constant 0x2C
            rarabai_play_point,      // constant 0x2D
            rarabai_free_top_count,      // constant 0x2E
            kindai_play_point,       // constant 0x2F
            kindai_free_top_count,       // constant 0x30
            trophy_escape_encount_btl_count,         // constant 0x31
            activity_move_m,         // constant 0x32
            activity_dash_m,         // constant 0x33
            clan_creator_win,        // constant 0x34
            activity_kill_encounter_count,       // constant 0x35
            trophy_dragon_boost_use_count,       // constant 0x36
            live_chat_input_success_count,       // constant 0x37
            darts_hattrick_count,        // constant 0x38
            darts_win_count,         // constant 0x39
            batting_homerun_count,       // constant 0x3A
            batting_clear_mission_count,         // constant 0x3B
            sandlot_baseball_win_by_warriors,        // constant 0x3C
            sports_gym_get_challenge_rank_a_count,       // constant 0x3D
            spearfishing_get_fish_count,         // constant 0x3E
            clan_creator_kill_enemy_count,       // constant 0x3F
            caba_very_good_count,        // constant 0x40
            snack_enter_count,       // constant 0x41
            mahjong_ron_or_tsumo_count,      // constant 0x42
            cat_cafe_give_food_count,        // constant 0x43
            temple_omikuji_count,        // constant 0x44
            temple_osonae_count,         // constant 0x45
            dandling_child_success_count,        // constant 0x46
            vf5fs_win_count,         // constant 0x47
            puyo_win_count,      // constant 0x48
            temple_saisen_money,         // constant 0x49
            batting_challenge_play_count,        // constant 0x4A
            batting_homerun_play_count,      // constant 0x4B
            activity_open_safe_count,        // constant 0x4C
            darts_rookie_win_count,      // constant 0x4D
            darts_intermediate_win_count,        // constant 0x4E
            darts_veteran_win_count,         // constant 0x4F
            capture_same,        // constant 0x50
            capture_kajiki,      // constant 0x51
            capture_maguro,      // constant 0x52
            capture_madai,       // constant 0x53
            capture_salmon,      // constant 0x54
            capture_onikasago,       // constant 0x55
            capture_kawahagi,        // constant 0x56
            capture_haze,        // constant 0x57
            capture_torafugu,        // constant 0x58
            capture_harisen,         // constant 0x59
            capture_karei,       // constant 0x5A
            capture_anago,       // constant 0x5B
            capture_ryuguu,      // constant 0x5C
            capture_octopus,         // constant 0x5D
            capture_ika,         // constant 0x5E
            capture_takaashigani,        // constant 0x5F
            capture_siirakansu,      // constant 0x60
            capture_ebi,         // constant 0x61
            capture_sirasu,      // constant 0x62
            capture_jellyfish,       // constant 0x63
            capture_ufo,         // constant 0x64
            clan_play_count,         // constant 0x65
            main_story_round,        // constant 0x66
            total_exp,       // constant 0x67
            sub_b02_count,       // constant 0x68
            spearfishing_level1_1_clear,         // constant 0x69
            spearfishing_level1_2_clear,         // constant 0x6A
            spearfishing_level1_3_clear,         // constant 0x6B
            cabaret_island_money,        // constant 0x6C
            cabaret_island_total_fan_division1,      // constant 0x6D
            cabaret_island_total_fan_division2,      // constant 0x6E
            cabaret_island_total_fan_division3,      // constant 0x6F
            cabaret_island_total_fan_division4,      // constant 0x70
            cabaret_island_total_fan_division5,      // constant 0x71
            cabaret_island_cp,       // constant 0x72
            skill,       // constant 0x73
            skill_point,         // constant 0x74
            toba_kifuda,         // constant 0x75
            casino_chip,         // constant 0x76
            batting_point,       // constant 0x77
            exp_sp,      // constant 0x78
            cabaret_island_total_fan_hierachy1,      // constant 0x79
            cabaret_island_total_fan_hierachy2,      // constant 0x7A
            cabaret_island_total_fan_hierachy3,      // constant 0x7B
            cabaret_island_total_fan_hierachy4,      // constant 0x7C
            cabaret_island_total_fan_hierachy5,      // constant 0x7D
            cabaret_island_play_count_league_01,         // constant 0x7E
            cabaret_island_play_count_league_02,         // constant 0x7F
            cabaret_island_play_count_league_03,         // constant 0x80
            cabaret_island_play_count_league_04,         // constant 0x81
            activity_kill_enemy_by_equip_count,      // constant 0x82
            onedari_exp,         // constant 0x83
            cabaret_island_talk_event_gauge,         // constant 0x84
            arena_victory_count,         // constant 0x85
            clan_creator_use_tension_up_count,       // constant 0x86
            clan_creator_use_skill_count,        // constant 0x87
            clan_creator_do_gacha_count,         // constant 0x88
            clan_creator_level_up_member_count,      // constant 0x89
            ufo_catcher_get_prize_count,         // constant 0x8A
            mahjong_win_count,       // constant 0x8B
            poker_make_money,        // constant 0x8C
            bj_make_money,       // constant 0x8D
            hanafuda_make_money,         // constant 0x8E
            oichokabu_make_money,        // constant 0x8F
            mahjong_make_money,      // constant 0x90
            omizu_make_money,        // constant 0x91
            omizu_make_visitor,      // constant 0x92
            omizu_recruit_count,         // constant 0x93
            omizu_meal_with_platinum_cast,       // constant 0x94
            kill_encount_boss_count,         // constant 0x95
            sub_a05_count,       // constant 0x96
            shop_destory,        // constant 0x97
            sub_a33_count,       // constant 0x98
            sub_a36_count,       // constant 0x99
            sub_b25_count,       // constant 0x9A
            sub_b26_count,       // constant 0x9B
            trophy_Donation_million,         // constant 0x9C
            shogi_point,         // constant 0x9D
            reach_play_point,        // constant 0x9E
            reach_free_top_count,        // constant 0x9F
            reach_event_top_count,       // constant 0xA0
            kamiyama_total_sell_price,       // constant 0xA1
            sub_a06_count,       // constant 0xA2
            drink_alcoholic_count,       // constant 0xA3
            lock_picking_unlock_count,       // constant 0xA4
            kill_enemy_by_issen_mode,        // constant 0xA5
            kill_enemy_by_enbu_mode,         // constant 0xA6
            kill_enemy_by_kabekeri,      // constant 0xA7
            win_battle_no_damaged,       // constant 0xA8
            mahjong_rarabai_ron_or_tsumo_count,      // constant 0xA9
            mahjong_kindai_ron_or_tsumo_count,       // constant 0xAA
            cooking_move_m,      // constant 0xAB
            darts_god_win_count,         // constant 0xAC
            locker_key_get,      // constant 0xAD
            mahjong_mankan_agari_count,      // constant 0xAE
            mahjong_haneman_agari_count,         // constant 0xAF
            mahjong_sanshokudoujun_agari_count,      // constant 0xB0
            mahjong_riichiippatsu_agari_count,       // constant 0xB1
            bj_make_chip,        // constant 0xB2
            poker_make_chip,         // constant 0xB3
            hanafuda_make_kifuda,        // constant 0xB4
            oichokabu_make_kifuda,       // constant 0xB5
            shogi_win_no_use_matta_count,        // constant 0xB6
            shogi_win_by_first_move_count,       // constant 0xB7
            shogi_win_by_second_move_count,      // constant 0xB8
            shogi_win_count,         // constant 0xB9
            greeting_by_friend_count,        // constant 0xBA
            akaushi_h_count,         // constant 0xBB
            msidecafe_count,         // constant 0xBC
            pop_shichi_east_point,       // constant 0xBD
            pop_shichi_west_point,       // constant 0xBE
            pop_syouwa_point,        // constant 0xBF
            pop_tenkaichi_point,         // constant 0xC0
            sell_shiranui_count_botan,       // constant 0xC1
            sell_shiranui_count_sakura,      // constant 0xC2
            sell_shiranui_count_tsubaki,         // constant 0xC3
            sell_shiranui_count_ume,         // constant 0xC4
            sell_shiranui_count_suzuran,         // constant 0xC5
            friend_001_kizuna_point,         // constant 0xC6
            friend_002_kizuna_point,         // constant 0xC7
            friend_003_kizuna_point,         // constant 0xC8
            friend_004_kizuna_point,         // constant 0xC9
            friend_005_kizuna_point,         // constant 0xCA
            friend_006_kizuna_point,         // constant 0xCB
            friend_007_kizuna_point,         // constant 0xCC
            friend_008_kizuna_point,         // constant 0xCD
            friend_009_kizuna_point,         // constant 0xCE
            friend_010_kizuna_point,         // constant 0xCF
            friend_011_kizuna_point,         // constant 0xD0
            friend_012_kizuna_point,         // constant 0xD1
            friend_013_kizuna_point,         // constant 0xD2
            friend_014_kizuna_point,         // constant 0xD3
            friend_015_kizuna_point,         // constant 0xD4
            friend_016_kizuna_point,         // constant 0xD5
            friend_017_kizuna_point,         // constant 0xD6
            friend_018_kizuna_point,         // constant 0xD7
            friend_019_kizuna_point,         // constant 0xD8
            friend_020_kizuna_point,         // constant 0xD9
            friend_021_kizuna_point,         // constant 0xDA
            friend_022_kizuna_point,         // constant 0xDB
            friend_023_kizuna_point,         // constant 0xDC
            friend_024_kizuna_point,         // constant 0xDD
            friend_025_kizuna_point,         // constant 0xDE
            friend_026_kizuna_point,         // constant 0xDF
            friend_027_kizuna_point,         // constant 0xE0
            friend_028_kizuna_point,         // constant 0xE1
            friend_029_kizuna_point,         // constant 0xE2
            friend_030_kizuna_point,         // constant 0xE3
            friend_031_kizuna_point,         // constant 0xE4
            friend_032_kizuna_point,         // constant 0xE5
            friend_033_kizuna_point,         // constant 0xE6
            friend_034_kizuna_point,         // constant 0xE7
            friend_035_kizuna_point,         // constant 0xE8
            friend_036_kizuna_point,         // constant 0xE9
            friend_037_kizuna_point,         // constant 0xEA
            friend_038_kizuna_point,         // constant 0xEB
            friend_039_kizuna_point,         // constant 0xEC
            friend_040_kizuna_point,         // constant 0xED
            friend_041_kizuna_point,         // constant 0xEE
            friend_042_kizuna_point,         // constant 0xEF
            friend_043_kizuna_point,         // constant 0xF0
            friend_044_kizuna_point,         // constant 0xF1
            friend_045_kizuna_point,         // constant 0xF2
            friend_046_kizuna_point,         // constant 0xF3
            friend_047_kizuna_point,         // constant 0xF4
            friend_048_kizuna_point,         // constant 0xF5
            friend_049_kizuna_point,         // constant 0xF6
            friend_050_kizuna_point,         // constant 0xF7
            machi_hyoban,        // constant 0xF8
            arrest_count,        // constant 0xF9
            smileburger_g_count,         // constant 0xFA
            encount_battle_count,        // constant 0xFB
            drone_race_win_count,        // constant 0xFC
            exp_money,       // constant 0xFD
            girl_001_kizuna_point,       // constant 0xFE
            girl_002_kizuna_point,       // constant 0xFF
            girl_003_kizuna_point,       // constant 0x100
            girl_004_kizuna_point,       // constant 0x101
            sid20_move_m,        // constant 0x102
            smileburger_le_marche,       // constant 0x103
            sell_item_count,         // constant 0x104
            buy_item_count,      // constant 0x105
            sid13_massage01,         // constant 0x106
            sid13_massage02,         // constant 0x107
            sid13_massage03,         // constant 0x108
            done_finish_brow,        // constant 0x109
            done_guard,      // constant 0x10A
            done_kamae,      // constant 0x10B
            done_sway,       // constant 0x10C
            done_grab_or_pickup,         // constant 0x10D
            done_heat_action,        // constant 0x10E
            done_physical_switch,        // constant 0x10F
            done_flying_triangle,        // constant 0x110
            can_growup,      // constant 0x111
            done_ex_boost,       // constant 0x112
            had_fatal_damage,        // constant 0x113
            reach_to_warning,        // constant 0x114
            reach_to_max_danger,         // constant 0x115
            done_elixir,         // constant 0x116
            unused_finish_brow,      // constant 0x117
            unused_guard,        // constant 0x118
            unused_kamae,        // constant 0x119
            unused_sway,         // constant 0x11A
            unused_grab_or_pickup,       // constant 0x11B
            unused_heat_action,      // constant 0x11C
            unused_physical_switch,      // constant 0x11D
            unused_flying_triangle,      // constant 0x11E
            unused_ex_boost,         // constant 0x11F
            unused_elixir,       // constant 0x120
            mahjong_tachibana_ron_or_tsumo_count,        // constant 0x121
            mahjong_tachibana_open_riichi_agari_count,       // constant 0x122
            sugoroku_win_vs_tora_count,      // constant 0x123
            sugoroku_boot_koronyan_mode_count,       // constant 0x124
            sugoroku_throw_dice_count,       // constant 0x125
            sugoroku_dice_plus_count,        // constant 0x126
            use_senyaku_count,       // constant 0x127
            le_marche_count,         // constant 0x128
            wildjackson_t_count,         // constant 0x129
            wettekitchen_tw_count,       // constant 0x12A
            friend_051_kizuna_point,         // constant 0x12B
            friend_052_kizuna_point,         // constant 0x12C
            friend_053_kizuna_point,         // constant 0x12D
            friend_054_kizuna_point,         // constant 0x12E
            ikinari_steak_count,         // constant 0x12F
            can_growup_after_battle,         // constant 0x130
            pinball_play_count,      // constant 0x131
            frd_g02_move_m,      // constant 0x132
            frd_g03_move_m,      // constant 0x133
            main_m10_00800_move_m,       // constant 0x134
            frd_g04_move_m,      // constant 0x135
            honda_kd_stock,      // constant 0x136
            kasai_kd_stock,      // constant 0x137
            sakakiba_kd_stock,       // constant 0x138
            koga_kd_stock,       // constant 0x139
            akaushi_alps,        // constant 0x13A
            smileburger_count,       // constant 0x13B
            akaushi_t_count,         // constant 0x13C
            shopping_at_store,       // constant 0x13D
            guarded_by_boss_during_enbu,         // constant 0x13E
            guarded_by_enemy,        // constant 0x13F
            after_battle_for_recipe,         // constant 0x140
            girl_001_love_level,         // constant 0x141
            girl_002_love_level,         // constant 0x142
            girl_003_love_level,         // constant 0x143
            girl_004_love_level,         // constant 0x144
            frd_g01_move_m,      // constant 0x145
            frd_g01_date_02,         // constant 0x146
            kanrai_count,        // constant 0x147
            ichiban_count,       // constant 0x148
            dragon_cart_ring,        // constant 0x149
            upstart_money,       // constant 0x14A
            personality_passion,         // constant 0x14B
            personality_mantal,      // constant 0x14C
            personality_heart,       // constant 0x14D
            personality_cheerful,        // constant 0x14E
            personality_sociability,         // constant 0x14F
            personality_intelligence,        // constant 0x150
            personality_trivia,      // constant 0x151
            personality_fashion,         // constant 0x152
            worker_point,        // constant 0x153
            eco_point,       // constant 0x154
            arms_shop_lv01,      // constant 0x155
            arms_shop_lv02,      // constant 0x156
            arms_shop_lv03,      // constant 0x157
            arms_shop_lv04,      // constant 0x158
            trust_param_00,      // constant 0x159
            trust_param_01,      // constant 0x15A
            trust_param_02,      // constant 0x15B
            trust_param_03,      // constant 0x15C
            trust_param_04,      // constant 0x15D
            trust_param_05,      // constant 0x15E
            trust_param_06,      // constant 0x15F
            trust_param_07,      // constant 0x160
            toushi_sub40,        // constant 0x161
            _0075007000730074006100720074005f00730068006100720065002000700072006900630065,       // constant 0x162
            upstart_stock_price,         // constant 0x163
            bank_money,      // constant 0x164
            mahjong_lowerclass_playpoint,        // constant 0x165
            mahjong_lowerclass_top_count,        // constant 0x166
            mahjong_upperclass_playpoint,        // constant 0x167
            mahjong_upperclass_top_count,        // constant 0x168
            pachislot_medal,         // constant 0x169
            do_m_and_a,      // constant 0x16A
            arms_powerup_count,      // constant 0x16B
            iimono_search_get_money,         // constant 0x16C
            open_chest_count,        // constant 0x16D
            grow_vegetables_count,       // constant 0x16E
            order_survivor_bento_count,      // constant 0x16F
            make_herbal_medicine_count,      // constant 0x170
            arms_make_count,         // constant 0x171
            defeat_enemy_in_yokohama_count,      // constant 0x172
            defeat_enemy_in_osaka_count,         // constant 0x173
            defeat_enemy_in_kamuro_count,        // constant 0x174
            battle_skill_exercise_count,         // constant 0x175
            delivery_help_use_count,         // constant 0x176
            attack_item_use_count,       // constant 0x177
            defeat_enemy_as_freeter_count,       // constant 0x178
            defeat_enemy_as_hero_count,      // constant 0x179
            defeat_enemy_as_bouncer_count,       // constant 0x17A
            defeat_enemy_as_host_count,      // constant 0x17B
            defeat_enemy_as_breaker_count,       // constant 0x17C
            defeat_enemy_as_musician_count,      // constant 0x17D
            defeat_enemy_as_dancer_count,        // constant 0x17E
            defeat_enemy_as_task_force_count,        // constant 0x17F
            defeat_enemy_as_cook_count,      // constant 0x180
            defeat_enemy_as_fortuneteller_count,         // constant 0x181
            scount_on_the_street_count,      // constant 0x182
            management_mode_pay,         // constant 0x183
            persuasion_stockholder_count,        // constant 0x184
            kind_of_food_drink_talk_count,       // constant 0x185
            kind_of_party_chat_play_count,       // constant 0x186
            upstart_stock_price_rank,        // constant 0x187
            karaoke_singing_count,       // constant 0x188
            golf_play_count,         // constant 0x189
            shogi_taikyoku_count,        // constant 0x18A
            homeless_pick_up_cans_count,         // constant 0x18B
            homeless_defeat_count,       // constant 0x18C
            dragon_cart_time_attack_finish_count,        // constant 0x18D
            meigaza_try_to_keep_awake_count,         // constant 0x18E
            pachislot_hades_get_medal_count,         // constant 0x18F
            pachislot_milligod_get_medal_count,      // constant 0x190
            pachislot_souten_get_medal_count,        // constant 0x191
            pachislot_beast_get_medal_count,         // constant 0x192
            sujimon_complete_count,      // constant 0x193
            niwatori_talk_count,         // constant 0x194
            spring_na_hougeki,       // constant 0x195
            daimon,      // constant 0x196
            upstart_stock_price_point,       // constant 0x197
            dragon_cart_first_place_count,       // constant 0x198
            cabaret_yoasobi_visit_ct_rb,         // constant 0x199
            cabaret_yoasobi_visit_ct_rin,        // constant 0x19A
            a81_lau_shop_count,      // constant 0x19B
        };

    }
}
